### ISSUE TITLE
Example with remote peers

### ISSUE THREAD

**Issue by rdjanati** [paullouisageneau/libdatachannel#1]
Hi,

I wonder is there an example with remote peers? Peers that are running on different machines.

Thank you,
Rabah

**Comment by paullouisageneau** [comment]
Yes, I'm finishing an example with proper signaling, I'll push it soon.

**Comment by paullouisageneau** [comment]
Sorry, I didn't have much time to spent on this. However, @murat-dogan recently merged an example with 2 peers: https://github.com/paullouisageneau/libdatachannel/pull/23

**Comment by paullouisageneau** [comment]
A complete example has been added in https://github.com/paullouisageneau/libdatachannel/pull/82
