### ISSUE TITLE
Unable to Connect to TLS when Using MbedTLS

### ISSUE THREAD

**Issue by melpon** [paullouisageneau/libdatachannel#1007]
When using MbedTLS, I cannot establish a TLS connection to servers that use CA certificates issued by Let's Encrypt. I suspect this is because MbedTLS does not load the root CA.

As a result, I'm seeking a feature that allows loading a specific CA certificate.

In OpenSSL, the paths retrieved via `X509_get_default_cert_file()` or `X509_get_default_cert_dir()` serve as the default root CA, enabling the avoidance of this issue.

In MbedTLS, by adding the following code to `src/impl/tlstransport.cpp`, I confirmed that TLS connections work on Ubuntu:

```cpp
mbedtls_x509_crt_init(&mCacert); // Defined as mbedtls_x509_crt mCacert; in tlstransport.h
mbedtls::check(mbedtls_x509_crt_parse_file(&mCacert, "/etc/ssl/certs/ca-certificates.crt"));
mbedtls_ssl_conf_ca_chain(&mConf, &mCacert, NULL);
```

I'm considering submitting a Pull Request to address this issue. In this context, I'd like to know whether the CA certificate should be passed as a file path or in PEM string format. Furthermore, I'm curious if there's a need to add the capability to load specific CA certificates for OpenSSL and GnuTLS as well.

**Comment by paullouisageneau** [comment]
Such a pull request would be very welcome!

The [websocket server API](https://github.com/paullouisageneau/libdatachannel/blob/master/DOC.md#rtccreatewebsocketserver) has a field to pass a certificate, and it allows both a PEM certificate as string or a path. Internally it is done by looking for the string `-----BEGIN CERTIFICATE-----`. I think the capability would be useful for OpenSSL and GnuTLS too, but you can start with only MbedTLS.

**Comment by melpon** [comment]
Thank you for the guidance!

I've created a pull request #1009. The method of detecting the "-----BEGIN CERTIFICATE-----" string was especially helpful. For now, I've implemented it for MbedTLS, and I've not yet extended it to OpenSSL and GnuTLS.

Thank you for creating and maintaining the libdatachannel library. I truly appreciate it!

**Comment by paullouisageneau** [comment]
> Thank you for creating and maintaining the libdatachannel library. I truly appreciate it!

I'm glad the library has been useful to you!
