### ISSUE TITLE
MediaHandler does not have a virtual destructor

### ISSUE THREAD

**Issue by cyanidle** [paullouisageneau/libdatachannel#1024]
As MediaHandler is an abstract class it should have 
`virtual ~MediaHandler() = default;`
to prevent possible incorrect deletion in base-class form

**Comment by paullouisageneau** [comment]
Indeed, I opened https://github.com/paullouisageneau/libdatachannel/pull/1025 to add the virtual destructor on `v0.19` branch.

Note `MediaHandler` does have a virtual destructor on `master` branch: https://github.com/paullouisageneau/libdatachannel/blob/60da36e0081d4c3f9741a0d107900f31f33cf7a6/include/rtc/mediahandler.hpp#L22

**Comment by cyanidle** [comment]
Thank you
