### ISSUE TITLE
Strange binary data received by PeerConnection.video.onMessage

### ISSUE THREAD

**Issue by dmllr** [paullouisageneau/libdatachannel#1033]
I have 2 Linux applications based on `libdatachannel`: Sender and Receiver.

The Sender captures frames from the camera, encodes them into h264 format, and sends the encoded buffers using `PeerConnection`. I made a simple website that received this video stream and was able to receive and decode the video successfully, so I believe the Sender part is fine there.

The Receiver is intended to receive the Sender's video stream, decode using `ffmpeg`, and then play it using `opencv`. But there's a problem: `ffmpeg` fails to decode the received buffers. Moreover, the amount of data received is far less than the amount of data sent.

I confirm that the Sender and Receiver apps can connect to each other, and send and receive some data. Data channel works fine. The Receiver's `PeerConnection.video.onMessage` handler receives something, but I cannot recognize the format, `ffmpeg` fails either. Messages received has neither h264 separators nor headers and seem like a random bytes. The sizes of buffers submitted by the Sender and accepted by the Receiver are different.

I know that I may misunderstood something, but would appreciate any advice.

Below are some codes I use in the Receiver app:

```c++
    static std::shared_ptr<Peer::Track> addVideo(
            const std::shared_ptr<rtc::PeerConnection>& pc,
            const rtc::Description::Direction direction,
            const uint8_t payloadType, const uint32_t ssrc, const std::string& cname, const std::string& msid,
            const std::function<void (void)>& onOpen,
            const std::function<void (rtc::binary message)>& onMessage) {
        auto video = rtc::Description::Video(cname, direction);
        video.addH264Codec(payloadType);

        auto track = pc->addTrack(video);
        auto session = std::make_shared<rtc::RtcpReceivingSession>();
        track->setMediaHandler(session);
        track->onOpen(onOpen);
        track->onMessage(onMessage, nullptr);

        return std::make_shared<Peer::Track>(track, session);
    }
```

```c++
    std::shared_ptr<Peer> createPeerConnection(const std::string& id) {
		auto pc = createDefaultPeerConnection(id);

		std::shared_ptr<Peer> peer(new Peer(pc));
        peer->video = addVideo(
            pc, rtc::Description::Direction::RecvOnly,
            102, 10001, "video-stream", "cam-stream-1",
            [this, id, wc = make_weak_ptr(peer)]() {
                MainThread.dispatch([this, wc]() {
                    if (auto c = wc.lock()) {
                        addToStream(c, true);
                    }
                });
                LOGI << "Video from " << id << " opened";
            },
            [this](const rtc::binary& buffer) {
                if (likely(hasReceiver())) {
                    (*this->receiver)(buffer); // here I try to send the data to the decoder which fails
                }
            }
        );

        peer->audio = addAudio(...);
        peer->dataChannel = createDefaultDataChannel(pc, id);
	peer->setState(Peer::State::Ready);

	return peer;
    }
```

onMessage:
```c++
    rtc.setReceiver([&](rtc::binary message) {
        std::ofstream fw("samplein.h264", std::ios::out | std::ios::binary | std::ios_base::app);
        fw.write(reinterpret_cast<const char*>(message.data()), message.size());
    });
```

Thanks!

**Comment by chobie** [comment]
for your reference : https://github.com/paullouisageneau/libdatachannel/discussions/815#discussioncomment-6924934

currently, the Implementation is work in progress for depacketizing and decoding in reception using h264 codec.

If the Sender implementation is correct in terms of WebRTC spec, then RTP Packet data will be received. 
and it can be decoded by realigning it in the correct order through mechanisms like jitter buffers.

**Comment by dmllr** [comment]
Closed in favor of https://github.com/paullouisageneau/libdatachannel/discussions/815
