### ISSUE TITLE
media-receiver 

### ISSUE THREAD

**Issue by foxnight2** [paullouisageneau/libdatachannel#1044]
https://github.com/paullouisageneau/libdatachannel/tree/master/examples/media-receiver

I follow the step to build media-receiver.   `.\media-receiver.exe`  show the  `State: connected`
My 127.0.0.1:5000 can not see anything. But the gstreamer show the window when I wave my hand in front of camera.

Is it the normal for 127.0.0.1:5000 doesnt show the image, but the gstreamer show the image? 

[Download and install GStreamer binaries](https://gstreamer.freedesktop.org/documentation/installing/on-windows.html?gi-language=c)

Here is the command and  log
`gst-launch-1.0 udpsrc address=127.0.0.1 port=5000 caps="application/x-rtp" ! queue ! rtph264depay ! video/x-h264,stream-format=byte-stream ! queue ! avdec_h264 ! queue ! autovideosink`

log
```
Use Windows high-resolution clock, precision: 1 ms
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'autovideosink0': gst.d3d11.device.handle=context, device=(GstD3D11Device)"\(GstD3D11Device\)\ d3d11device2", adapter=(uint)0, adapter-luid=(gint64)81067, device-id=(uint)39497, vendor-id=(uint)32902, hardware=(boolean)true, description=(string)"Intel\(R\)\ Iris\(R\)\ Xe\ Graphics";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
Redistribute latency...
0:01:44.5 / 99:99:99.
```

<img width="662" alt="image" src="https://github.com/paullouisageneau/libdatachannel/assets/142980812/b18f8534-7552-400f-9017-63c7545f17c7">

**Comment by paullouisageneau** [comment]
> My 127.0.0.1:5000 can not see anything. But the gstreamer show the window when I wave my hand in front of camera.
> Is it the normal for 127.0.0.1:5000 doesnt show the image, but the gstreamer show the image?

What do you mean? 127.0.0.1:5000 is not a HTTP server showing the video, it's the address at which the media-receiver example forwards the video stream from the browser (see the example code [here](https://github.com/paullouisageneau/libdatachannel/blob/f434804c94841ed801cb96b5a7770f1f1f894276/examples/media-receiver/main.cpp#L69)). You need to start gstreamer listening at the address to receive and decode the video stream.
