### ISSUE TITLE
build with mbedtls

### ISSUE THREAD

**Issue by azc5OQ** [paullouisageneau/libdatachannel#1058]
What I am trying to achieve is, to build libdatachannel as a static library with mbedtls. 

my steps:
* I downloaded mbedtls from their github repostiroy,
* added it into deps directory and run build in clion.

```
-- Performing Test has_wno_deprecated_declarations
-- Performing Test has_wno_deprecated_declarations - Success
-- link library: ws2_32
CMake Warning (dev) at cmake/Modules/FindMbedTLS.cmake:117 (message):
  Failed to find MbedTLS version.
Call Stack (most recent call first):
  CMakeLists.txt:360 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Program Files/JetBrains/CLion 2022.2/bin/cmake/win/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MbedTLS: Found unsuitable version "0.0.0", but required is
  at least "3" (found MbedTLS_LIBRARY-NOTFOUND)

      Reason given by package: Ensure that an MbedTLS distribution is provided as part of CMAKE_PREFIX_PATH.
```

"Ensure that an MbedTLS distribution is provided as part of CMAKE_PREFIX_PATH." 
this gives me a hint so I edited CMakeLists.txt , and added this:

```
	if (NOT DEFINED CMAKE_PREFIX_PATH)
		set(CMAKE_PREFIX_PATH ${CMAKE_SOURCE_DIR}\\deps\\mbedtls)
	else()
		set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${CMAKE_SOURCE_DIR}\\deps\\mbedtls")
	endif()
```

Still same problem, only diffent message.

```
-- Performing Test has_wno_address_of_packed_member - Success
-- Performing Test has_wno_deprecated_declarations
-- Performing Test has_wno_deprecated_declarations - Success
-- link library: ws2_32
CMake Error at C:/Program Files/JetBrains/CLion 2022.2/bin/cmake/win/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MbedTLS (missing: MbedTLS_LIBRARY MbedCrypto_LIBRARY
  MbedX509_LIBRARY) (found suitable version "3.5.1", minimum required is "3")

      Reason given by package: Ensure that an MbedTLS distribution is provided as part of CMAKE_PREFIX_PATH.

Call Stack (most recent call first):
  C:/Program Files/JetBrains/CLion 2022.2/bin/cmake/win/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMbedTLS.cmake:169 (find_package_handle_standard_args)
  CMakeLists.txt:368 (find_package)
```

Before anyone says that you are supposed to build MbedTLS first, I tried to build static targets from MbedTLS  source that had names similar to what CmakeLists complains about: MbedTLS_LIBRARY MbedCrypto_LIBRARY and MbedX509_LIBRARY . The build process produced some static libraries (.a) , but it did not solve the problem.

So my question is, what exactly needs to be done to build libdatachannel with MbedTLS

**Comment by chobie** [comment]
I have not performed it works, but these are the build instructions for Windows 11.
Please refer to them.

```
# on Developer Command Prompt For vs2022
# C:\Users\USERNAME\github. please replace USERNAME to your account.

git clone https://github.com/Mbed-TLS/mbedtls.git
cd mbedtls
git checkout v3.5.1

# IMPORTANT: 
# You have to edit `include/mbedtls/mbedtls_config.h` to enable `#define MBEDTLS_SSL_DTLS_SRTP` constant (just uncomment that line).
# otherwise `mbedtls_dtls_srtp_info` cannnot find.

cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX="C:\\Users\\USERNAME\\github\\libdatachannel\\deps\\mbedtls" -DUSE_SHARED_MBEDTLS_LIBRARY=On -B build
cd build
nmake
nmake install
# then, result files will install `libdatachannel\deps\mbedtls` directories.


# after compile mbedtls, move to libdatachannel root directory
cd ..\..\

# use cmake command. the point is to specify mbedtls repository path. not library directory.
cmake -B build -G "NMake Makefiles" -DUSE_MBEDTLS=1 -DCMAKE_PREFIX_PATH="C:\\Users\\USERNAME\\github\\libdatachannel\\deps\\mbedtls" 
```

A key point is that building MbedTLS alone does not result in the directory structure expected by `FindMbedTLS`.
Therefore, I first configured the build of MbedTLS to install to the destination specified by `DCMAKE_INSTALL_PREFIX`. Then, by specifying `DCMAKE_CXX_FLAGS` and `DCMAKE_PREFIX_PATH` in libdatachannel, I was able to resolve the references.

For the purpose of explanation, I specified the installation destination as the `libdatachannel\deps` directory, but you can choose any location you prefer. (I believe I have corrected the path in the explanation, but I apologize if there was any mistake during the process of trial and error.)


@paullouisageneau regarding `MBEDTLS_SSL_DTLS_SRTP`, is this understanding correct?

**Comment by chobie** [comment]
I think that it's probably easier to use something like `vcpkg` rather than building mbedtls yourself.

**Comment by azc5OQ** [comment]
problem solved for me

I had to keep this manually added lines of code in libdatachannel's CMakeLists

```
	if (NOT DEFINED CMAKE_PREFIX_PATH)
		set(CMAKE_PREFIX_PATH ${CMAKE_SOURCE_DIR}\\deps\\mbedtls)
	else()
		set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${CMAKE_SOURCE_DIR}\\deps\\mbedtls")
	endif()
```

steps 
- open mbedtls with Clion
- select mbedtls | Release configuration (there are many configurations)
- build

```
[112/116] Building C object library/CMakeFiles/mbedtls.dir/net_sockets.c.obj
[113/116] Building C object library/CMakeFiles/mbedtls.dir/ssl_tls.c.obj
[114/116] Building C object library/CMakeFiles/mbedtls.dir/ssl_tls12_server.c.obj
[115/116] Building C object library/CMakeFiles/mbedtls.dir/ssl_tls12_client.c.obj
[116/116] Linking C static library library\libmbedtls.a
```

- after build go to directory "cmake-build-release" and from there copy move "library" and "include" directories into \\deps\\mbedtls
- rename "library"  to  "lib"

- open libdatachannel in clion, now when cmake is configuring project instead of errors there should be this

```
-- Performing Test has_wno_address_of_packed_member - Success
-- Performing Test has_wno_deprecated_declarations
-- Performing Test has_wno_deprecated_declarations - Success
-- link library: ws2_32
-- Found MbedTLS: C:/Users/user/Desktop/libdatachannel/deps/mbedtls/lib/libmbedtls.a (found suitable version "3.5.1", minimum required is "3") 
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success

```



note both projects libdatachannel and mbedtls have to be build with same toolchain or linker wont be able to glue them together

suggestion: add mbedtls into libdatachannel by default (easiest to built)

**Comment by paullouisageneau** [comment]
> @paullouisageneau regarding `MBEDTLS_SSL_DTLS_SRTP`, is this understanding correct?

@chobie Yes you are right, MbedTLS needs to be compiled with DTLS SRTP support. It's often the case for packaged builds, but if you compile by yourself, you have to make sure it's enabled.

> I had to keep this manually added lines of code in libdatachannel's CMakeLists
> 
> ```
> 	if (NOT DEFINED CMAKE_PREFIX_PATH)
> 		set(CMAKE_PREFIX_PATH ${CMAKE_SOURCE_DIR}\\deps\\mbedtls)
> 	else()
> 		set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${CMAKE_SOURCE_DIR}\\deps\\mbedtls")
> 	endif()
> ```

When building outside of an IDE, you can simply pass `-DCMAKE_PREFIX_PATH=YOURPREFIX` for libdatachannel. I guess there may be a similar option in CLion.

> * after build go to directory "cmake-build-release" and from there copy move "library" and "include" directories into \deps\mbedtls
> 
> * rename "library"  to  "lib"
> 
> * open libdatachannel in clion, now when cmake is configuring project instead of errors there should be this

Same you shouldn't need to do this manually, outside of an IDE you simply pass `-DCMAKE_INSTALL_PREFIX=YOURPREFIX` for MbedTLS, then you install it after the build, typically with `make install`, and CMake will copy everything under the prefix in the right directories.
