### ISSUE TITLE
Websocket remoteAddress() interface return value

### ISSUE THREAD

**Issue by reischen80** [paullouisageneau/libdatachannel#1059]
Hi, Paul
     I setup a Websocket server via libDatachannel WebsocketServer interface.  And I use websocket::RemoteAddress() to accuqire client ip address :

      `WebSocketServer *wss = new WebSocketServer(conf);
        wss->onClient([](shared_ptr<WebSocket> ws) {
               printf("%s", ws->remoteAddress().value().c_str());
       });`

     I got something like  : ::ffff:105.11.31.26:9204
     What does such string the exactly mean? and  Is there more efficient way to seperate IP and Port and other stuff from it?

Thanks and Regards
Reis

**Comment by chobie** [comment]
The following is a document for CAPI, but it internally uses `remoteAddress`.  
https://github.com/paullouisageneau/libdatachannel/blob/master/DOC.md#rtcgetremoteaddress

I think it would be good to search for ':' from the end and then split (like `std::string::rfind`).

It doesn't seem like there was a single API that returns the hostname or port number.
If necessary, wouldn't it be better to consider adding one?

**Comment by reischen80** [comment]
Following C++ WebSocket Class use the same implementation as CAPI
`optional<string> remoteAddress() const;`

I'd just like to know, why the result string have a strange form of "::ffff:105.11.31.26:9204",   expected to be "105.11.31.26:9204".  The last one will be easily to split and interpret. 
It is a bug inside?

**Comment by chobie** [comment]
The format `::ffff:x.x.x.x` is used to maintain compatibility between IPv6 and IPv4, as far as I remember. For more details, I suggest referring to RFC 4291.

**Comment by reischen80** [comment]
Got it! Thanks!
