### ISSUE TITLE
Building on windows fails 

### ISSUE THREAD

**Issue by gamedolphin** [paullouisageneau/libdatachannel#106]
I am using Visual Studio Developer shell to run the commands listed to build, but the build fails with the following error - 

`agent.c : 202 - error C2440: 'function': cannot convert from 'thread_return_t (__cdecl *)(void *)' to 'LPTHREAD_START_ROUTINE'`

**Comment by paullouisageneau** [comment]
It seems the calling convention needs to be specified, maybe this depends on MSVC version. This should be fixed by https://github.com/paullouisageneau/libjuice/pull/23. Could you try to compile with `deps/libjuice` set on the branch `fix-win32-thread-call`?

**Comment by gamedolphin** [comment]
Yes that works! Thank you!

I'd like to add that if anybody is using precompiled binaries for openssl on windows, then https://slproweb.com/download/Win32OpenSSL-1_1_1g.exe -> this installer is the one that I got working finally. Had to add path to the install as OPENSSL_ROOT_DIR to the system environment variables as well.
