### ISSUE TITLE
Does libdatachannel have any examples of integration with GStreamer’s appsrc/appsink

### ISSUE THREAD

**Issue by plume-cat** [paullouisageneau/libdatachannel#1064]
The GStreamer command is as follows:

![image](https://github.com/paullouisageneau/libdatachannel/assets/28625121/f832103c-6658-4fe3-8565-5aeb2b2f8bb8)

My goal is to obtain the video stream from the GStreamer callback and then use libdatachannel to transmit the video stream data to the web by WebRTC.

How should I go about this

**Comment by chobie** [comment]
No, `libdatachannel` does not have an introductory sample that utilizes GStreamer's `appsrc` and `appsink`.

It seems like your question is about how to use GStreamer.
Have you read the GStreamer manual or tutorials? If not, I highly recommend you to read them.
https://gstreamer.freedesktop.org/documentation/tutorials/basic/index.html?gi-language=c

First, it would be good to program until you can generate rtp packet data using `appsrc`.
Once you can do that, it will be easier to explain how to integrate it with `libdatachannel`.

By the way, there are examples of sending and receiving using GStreamer as an external program at the following location.
https://github.com/paullouisageneau/libdatachannel/tree/master/examples/media-sender
https://github.com/paullouisageneau/libdatachannel/tree/master/examples/media-receiver

If you can do what was mentioned earlier, I think you will be able to send and receive media data in these samples with little modification.

**Comment by plume-cat** [comment]
thx, I have successfully obtained the video stream data through the GStreamer interface, but I am not sure how to pass the video data from the GStreamer callback to libdatachannel.
Do I need to modify libdatachannel?

**Comment by plume-cat** [comment]
@chobie 
thx, I have successfully obtained the video stream data through the GStreamer interface, but I am not sure how to pass the video data from the GStreamer callback to libdatachannel.
Do I need to modify libdatachannel?

**Comment by plume-cat** [comment]
@chobie  I do not want to forward the data to libdatachannel using udpsink because it is too inefficient. I would like to directly pass the data to libdatachannel through the GStreamer interface callback

**Comment by paullouisageneau** [comment]
@plume-cat If GStreamer outputs RTP packets, you just need to send them in a track like in the [media sender example](https://github.com/paullouisageneau/libdatachannel/blob/a721f3a298c417941a090b501093d78b43653cf3/examples/media-sender/main.cpp#L93) (You need to ensure SSRC is consistent with the one you set in the track description). If it outputs raw encoded h264 frames, you need to first add a packetizer on the track, then on each frame, update the timestamp and send the raw frame in the track, like [in the streamer example](https://github.com/paullouisageneau/libdatachannel/blob/a721f3a298c417941a090b501093d78b43653cf3/examples/streamer/main.cpp#L351).

**Comment by chobie** [comment]
@paullouisageneau thanks!

@plume-cat As Paul supplemented, that's how it is.
If it's just for as an experiment, up to line 81 of `media-sender` could remain the same, and then setting up the GStreamer callback and loop should make it work, I think. 

```
    // same as media-sender#81
    pc->setRemoteDescription(answer);    
    
    //  I'm not sure about exactly setup gstreamer and set callback. so, this is pseudo function name.
    // `callback` receives gstreamer buffer and send it with `track->send` function
    setup_gstreamer_callback(callback);

    // setup_gstreamer_loop() is a function that execute gstreamer loop and wait it.
    start_gstreamer_loop();
```

I think it would be better to actually use something like a queue to properly manage the data.

**Comment by plume-cat** [comment]
@paullouisageneau  
This is my command：
**ximagesrc use-damage=0 ! video/x-raw,framerate=30/1 ! videoconvert ! videoscale ! video/x-raw,width=1280,height=720 ! x264enc ! appsink name=sink**  

Thank you, I am not very familiar with WebRTC and audio/video processing. I am using GStreamer to capture the screen, but I want to use the **appsink** method in GStreamer to transmit the stream. I have completed the GStreamer code and can obtain the H.264 video stream, but I do not know how to pass this stream to libdatachannel and then have libdatachannel send it to the web via WebRTC

**Comment by plume-cat** [comment]
@chobie @paullouisageneau  

Thank you very much for the guidance from both of you. I will first take a look at the [media sender example](https://github.com/paullouisageneau/libdatachannel/blob/a721f3a298c417941a090b501093d78b43653cf3/examples/media-sender/main.cpp#L93) code and then conduct some tests

**Comment by H4k4nn** [comment]
if ( GStreamer.LaunchSimlpePipelineAndWaitEos( 'filesrc location=C:/Users/HakaN/Desktop/test.opus ! decodebin ! audioresample ! audio/x-raw,channels=2,rate=48000 !  audioconvert ! opusenc ! rtpopuspay  pt=96 ! udpsink host=127.0.0.1 port=6000' ) )

 if ( GStreamer.LaunchSimlpePipelineAndWaitEos( 'filesrc location=C:/Users/HakaN/Desktop/deneme.mp4 ! decodebin ! videoconvert ! x264enc tune=4 bitrate=1000 key-int-max=30 ! rtph264pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=6000' ) ) 

My sender app with appsrc or filesrc

**Comment by plume-cat** [comment]
> if ( GStreamer.LaunchSimlpePipelineAndWaitEos( 'filesrc location=C:/Users/HakaN/Desktop/test.opus ! decodebin ! audioresample ! audio/x-raw,channels=2,rate=48000 ! audioconvert ! opusenc ! rtpopuspay pt=96 ! udpsink host=127.0.0.1 port=6000' ) )
> 
> if ( GStreamer.LaunchSimlpePipelineAndWaitEos( 'filesrc location=C:/Users/HakaN/Desktop/deneme.mp4 ! decodebin ! videoconvert ! x264enc tune=4 bitrate=1000 key-int-max=30 ! rtph264pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=6000' ) )
> 
> if ( GStreamer.LaunchSimlpePipelineAndWaitEos( 'appsrc stream-type=0 format=1 ! decodebin! videoconvert ! x264enc tune=4 bitrate=1000 key-int-max=30 ! rtph264pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=6000' ) ) then
> 
> My sender app with appsrc or filesrc

tks  Our implementation methods differ,you are using the **udksink** approach, while I plan to use **applink**

**Comment by plume-cat** [comment]
**/cpp_gs 
2023-12-11 17:28:03.841 DEBUG [4151] [rtc::impl::Init::doInit@113] Global initialization
2023-12-11 17:28:03.841 DEBUG [4151] [rtc::impl::Init::doInit@123] Spawning 4 threads
2023-12-11 17:28:03.842 DEBUG [4156] [rtc::impl::PollService::runLoop@164] Poll service started
2023-12-11 17:28:03.850 DEBUG [4152] [rtc::impl::Certificate::Generate@380] Generating certificate (OpenSSL)
2023-12-11 17:28:03.850 DEBUG [4151] [rtc::impl::IceTransport::IceTransport@57] Initializing ICE transport (libjuice)
2023-12-11 17:28:03.851 DEBUG [4151] [rtc::impl::PeerConnection::processLocalDescription@956] Adding application to local description, mid="0"
2023-12-11 17:28:03.854 INFO  [4151] [rtc::impl::PeerConnection::changeSignalingState@1228] Changed signaling state to have-local-offer
2023-12-11 17:28:03.854 INFO  [4151] [rtc::impl::PeerConnection::changeGatheringState@1215] Changed gathering state to in-progress
2023-12-11 17:28:03.854 INFO  [4151] [rtc::impl::IceTransport::LogCallback@362] juice: agent.c:1067: Changing state to gathering
2023-12-11 17:28:03.855 INFO  [4151] [rtc::impl::IceTransport::LogCallback@362] juice: agent.c:1067: Changing state to connecting
2023-12-11 17:28:03.855 INFO  [4151] [rtc::impl::PeerConnection::changeIceState@1197] Changed ICE state to checking
2023-12-11 17:28:03.855 INFO  [4151] [rtc::impl::PeerConnection::changeState@1179] Changed state to connecting
2023-12-11 17:28:03.855 INFO  [4151] [rtc::impl::IceTransport::LogCallback@362] juice: agent.c:2395: Candidate gathering done
2023-12-11 17:28:03.855 INFO  [4151] [rtc::impl::PeerConnection::changeGatheringState@1215] Changed gathering state to complete
2023-12-11 17:28:03.856 WARN  [4151] [rtc::PeerConnection::setLocalDescription@134] Unexpected local description in signaling state have-local-offer, ignoring
Please copy/paste the answer provided by the browser:** 


@paullouisageneau @chobie 

Hello two experts, I have successfully integrated GStreamer with libdatachannel using the example from [media sender example](https://github.com/paullouisageneau/libdatachannel/blob/a721f3a298c417941a090b501093d78b43653cf3/examples/media-sender/main.cpp#L93), and I can now display the video stream. However, when I add a data channel, I get the warning log mentioned above. How should I resolve this issue?

**Comment by paullouisageneau** [comment]
By default, `createDataChannel()` calls `setLocalDescription()` automatically to simplify the API when creating only data channels. This create an issue if you add tracks afterwards, as the local offer has already been set and it's now waiting for an answer or rollback before being able to create a new offer.

In your case, you can simply set `disableAutoNegotiation = true` in the configuration to prevent the implicit call, an offer with data channels and tracks will be set on the final `setLocalDescription()`.

Note that when you set `disableAutoNegotiation = true` on answerer side, you need to call `setLocalDescription()` after `setRemoteDescription()`, as the implicit call is disabled there too.

**Comment by plume-cat** [comment]
> By default, `createDataChannel()` calls `setLocalDescription()` automatically to simplify the API when creating only data channels. This create an issue if you add tracks afterwards, as the local offer has already been set and it's now waiting for an answer or rollback before being able to create a new offer.
> 
> In your case, you can simply set `disableAutoNegotiation = true` in the configuration to prevent the implicit call, an offer with data channels and tracks will be set on the final `setLocalDescription()`.
> 
> Note that when you set `disableAutoNegotiation = true` on answerer side, you need to call `setLocalDescription()` after `setRemoteDescription()`, as the implicit call is disabled there too.

thx, I have resolved the issue based on your suggestions~

**Comment by plume-cat** [comment]
@paullouisageneau   
The offer generated by my browser cannot be correctly parsed by libdatachannel，i use [answer example](https://github.com/paullouisageneau/libdatachannel/tree/master/examples/copy-paste) . but it not working.

![image](https://github.com/paullouisageneau/libdatachannel/assets/28625121/b81e9e82-a6a2-4807-862d-7af1d09ef9f3)

this is the web code:

![image](https://github.com/paullouisageneau/libdatachannel/assets/28625121/0fc7b378-e46c-462f-8ffb-649386227356)

**Comment by plume-cat** [comment]
> @plume-cat Can you tell me what version of libdatachannel you are using and what browser type and version you are using?
> 
> This error could be because ice-ufrag is only in "m=".
> 
> This may be a problem that has been fixed in the following Pull-Request #983

**systemos**:   win11
**libdatachannel**:  v0.19.4 
**edge**:   120.0.2210.61
**chrome**:   120.0.6099.71

**Comment by paullouisageneau** [comment]
> This error could be because ice-ufrag is only in "m=". 
>
> This may be a problem that has been fixed in the following Pull-Request https://github.com/paullouisageneau/libdatachannel/pull/983

@voluntas No, #983 fixes the specific situation where the remote agent sends a different ice-ufrag per m-line (I've only seen the issue when opening multiple tracks with aiortc). An ice-ufrag at media-level has always been fine.

@plume-cat The copy-paste example does not accept the JSON format you generate, it is very basic and needs the raw description and candidates. Besides, the copy-paste example handles datachannels only, why your description has media only and no datachannels.

**Comment by paullouisageneau** [comment]
> This error could be because ice-ufrag is only in "m=". 
>
> This may be a problem that has been fixed in the following Pull-Request https://github.com/paullouisageneau/libdatachannel/pull/983

@voluntas No, #983 fixes the specific situation where the remote agent sends a different ice-ufrag per m-line (I've only seen the issue when opening multiple tracks with aiortc). An ice-ufrag at media-level has always been fine.

@plume-cat The copy-paste example does not accept the JSON format you generate, it is very basic and needs the raw description and candidates. Besides, the copy-paste example handles datachannels only, while your description has media only and no datachannels.

You need to write your own sender, a bit like the media-sender example but a bit more complex as you chose to offer to receive on browser side, meaning the sender needs to look into the offered media description to know what to send (codec and payload type). It is simpler to offer on sender side, like the media-sender example does.

**Comment by plume-cat** [comment]
> > This error could be because ice-ufrag is only in "m=".
> > This may be a problem that has been fixed in the following Pull-Request #983
> 
> @voluntas No, #983 fixes the specific situation where the remote agent sends a different ice-ufrag per m-line (I've only seen the issue when opening multiple tracks with aiortc). An ice-ufrag at media-level has always been fine.
> 
> @plume-cat The copy-paste example does not accept the JSON format you generate, it is very basic and needs the raw description and candidates. Besides, the copy-paste example handles datachannels only, while your description has media only and no datachannels.
> 
> You need to write your own sender, a bit like the media-sender example but a bit more complex as you chose to offer to receive on browser side, meaning the sender needs to look into the offered media description to know what to send (codec and payload type). It is simpler to offer on sender side, like the media-sender example does.

@paullouisageneau 
thx  I have successfully tested using libdatachannel as the offerer with media-sender. However, now I want to make the web browser the offerer. Which example should I refer to? I am developing a cloud desktop application, and I am unsure whether it is better to initiate the offer from the web browser or from within libdatachannel

**Comment by paullouisageneau** [comment]
There is no example for that, what you need to do is getting the track media description in `onTrack`, then iterating the RTP map with `payloadTypes()` and `rtpMap()` to find the codec you want to send. You must then use the corresponding payload type for the RTP flow. If the right codec is not here, you have to handle the failure. Optionally, you can remove the other entries from the RTP map as you won't use them. Don't forget to also add the sent SSRC and set the modified description on the track.

It is better to offer from the sender here as your media pipeline is static, so you don't want to negotiate, you already know exactly what you are going to send.

**Comment by plume-cat** [comment]
> There is no example for that, what you need to do is getting the track media description in `onTrack`, then iterating the RTP map with `payloadTypes()` and `rtpMap()` to find the codec you want to send. You must then use the corresponding payload type for the RTP flow. If the right codec is not here, you have to handle the failure. Optionally, you can remove the other entries from the RTP map as you won't use them. Don't forget to also add the sent SSRC and set the modified description on the track.
> 
> It is better to offer from the sender here as your media pipeline is static, so you don't want to negotiate, you already know exactly what you are going to send.

thx 

> There is no example for that, what you need to do is getting the track media description in `onTrack`, then iterating the RTP map with `payloadTypes()` and `rtpMap()` to find the codec you want to send. You must then use the corresponding payload type for the RTP flow. If the right codec is not here, you have to handle the failure. Optionally, you can remove the other entries from the RTP map as you won't use them. Don't forget to also add the sent SSRC and set the modified description on the track.
> 
> It is better to offer from the sender here as your media pipeline is static, so you don't want to negotiate, you already know exactly what you are going to send.

thx, This seems quite complicated, I chose create the offer  with libdatachannal
