### ISSUE TITLE
RtpHeader/Ssrc is not a member of 'rtc'

### ISSUE THREAD

**Issue by franco-jyq** [paullouisageneau/libdatachannel#1085]
Hello, I'm trying out the media-send example, and it seems like the compiler doesn't recognize RtpHeader and SSrc as members of the RTP library. I tried out the copy-paste example, and it worked fine. I used vcpkg to handle the installation.

Also, where do you recommend looking for documentation that helps to understand the API, specifically for media transmission?

![rtpheader](https://github.com/paullouisageneau/libdatachannel/assets/66432427/b665a173-9df1-429d-af8a-2cd101617434)
![ssrc](https://github.com/paullouisageneau/libdatachannel/assets/66432427/95886189-886e-474c-a392-e1eade659911)

**Comment by paullouisageneau** [comment]
You are trying to use the media-sender example with a build of libdatachannel without media support. For some reason, the vcpkg port requires you to add the feature `srtp` to get the full build with media support.

There is a proper reference for the C API only for now, the C++ one should be close enough to the WebRTC Javascript API so you should be able to find your way looking at examples.

**Comment by franco-jyq** [comment]
Thanks! It worked with this configuration in the vcpkg.json file.
`{
  "dependencies": [
    {
      "name": "libdatachannel",
      "features": [
        "srtp"
      ]
    }
  ]
}`
