### ISSUE TITLE
class "rtc::H264RtpPacketizer" has no member "DefaultClockRate"		

### ISSUE THREAD

**Issue by franco-jyq** [paullouisageneau/libdatachannel#1090]
Hello, I'm trying to use the h264 packetizer used in the streamer example and it seems like I have some issues with the library's. I'm using vcpkg with the srtp feature to handle the installation.  

![image](https://github.com/paullouisageneau/libdatachannel/assets/66432427/8ffc4973-8e9c-42ab-8a9b-cfdcf4c25bae)
![image](https://github.com/paullouisageneau/libdatachannel/assets/66432427/4803b719-c2a2-4b2d-857d-3eef4679101f)

**Comment by paullouisageneau** [comment]
The streamer exemple on `master` branch uses a new API that isn't available in `v0.19` branch, so you need to checkout the exemple on `v0.19` branch if you want to link it against the version on vcpkg. Note however that the new API is mostly backward compatible with existing code.
