### ISSUE TITLE
Compile with static msvcrt on windows 

### ISSUE THREAD

**Issue by StillWaters77** [paullouisageneau/libdatachannel#1104]
Hello, i need to compile the static version of the libdatachannel library. However it is always linked against the dynamic msvcrt. Since my application, from which i want to link against libdatachannel, is linked with the static runtime, i need libdatachannel to also be linked against the static runtime.
I followed the instructions:

```
cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=${CMAKE_BINARY_DIR}/...
cd build
nmake datachannel-static
```

This builds a static library, however it is compiled with the dynamic msvcrt (/MD)
```
...
/FAILIFMISMATCH:RuntimeLibrary=MD_DynamicRelease
...
```

I then tried to provide the cmake with the MSVC_RUNTIME_LIBRARY variable:

```
cmake -B build -G "NMake Makefiles" -DMSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=${CMAKE_BINARY_DIR}/...
cd build
nmake datachannel-static
```

Without any changes.
I also ran cmake without setting the generator to nmake files. This generates visual studio solution. In these solution for ever project the runtime library is set to "MultiThreaded-DLL (/MD)".
Am i missing some option or is there a different way to link against the msvcrt statically?

Thanks in advance!

**Comment by paullouisageneau** [comment]
This is actually a generic CMake issue, as the MSVC runtime linkage is unrelated to libdatachannel. The CMake variable is actually named [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/v3.28/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html), so your command should be:
```
cmake -B build -G "NMake Makefiles" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded [...]
```

**Comment by StillWaters77** [comment]
Indeed, i used the wrong parameter name. Thank you
