### ISSUE TITLE
How to add tracks during negotiation

### ISSUE THREAD

**Issue by fusionfoxy** [paullouisageneau/libdatachannel#1110]
Hi,
It seems like adding tracks to a PeerConnection while another negotiation is in progress simply discards the added tracks silently. I experience this in 2 scenarios.

**Scenario 1**
Suppose some external event is triggering a new track to be added to a connection, I would then call `pc->addTrack()` followed by `pc->setLocalDescription()`. This will trigger the `onLocalDescription` event and an offer is sent to the other peer.

If 2 such events occurs at the same time, the second track seems to be lost and never negotiated. We can simulate this case in your Streamer example by adding `pc->setLocalDescription()` between adding video and audio tracks [here](https://github.com/paullouisageneau/libdatachannel/blob/master/examples/streamer/main.cpp#L295). In this case, the audio track is discarded silently.

When the external event occurs, I could check the signaling state and queue the event if the signaling state is not Stable which would solve this scenario. However, if it is simply a matter of `addTrack()` is only allowed in the Stable state, I would expect the `addTrack()` function to fail in this case instead of me having to check the state manually. When `addTrack()` is called successfully, I would expect the added track to be negotiated in a second `onLocalDescription` event after the first track negotiation has completed.

**Scenario 2**
Again, an external event triggers a track to be added. This time, the second event occurs in the other peer causing both peers to send an offer simultaneously. In this case, [this article](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation) states that one of the peer must be "polite" and accept the offer from the other peer. In polite browsers, this causes the `onNegotiationNeeded` event to be triggered a second time after the first negotiation has completed. In libdatachannel, accepting the other peer's offer seems to just remove its own track completely without any notice.
 
This time, I cannot know this when invoking `addTrack()`, so my queuing fix from Scenario 1 would not work. Unless I am missing something, my only option here is to queue the track, invoke `addTrack()`, detect the offer collision, detect when the first negotiation has completed, then call `addTrack()` again based on my queue, detect the second negotiation does not have a collision, and finally pop the track from the queue.

In this case, what happens to the `rtc::Track` pointer returned by the first `addTrack()`? Will this track never be opened, and should just be destroyed?

Is my understanding of libdatachannel accurate here, or am I missing some feature which lets me know when I can trust a successful `addTrack()` will also trigger a negotiation?
If I am not missing something, is this a bug in libdatachannel or is it working as intended?

**Comment by paullouisageneau** [comment]
This is indeed an incorrect implementation in libdatachannel. The issue is with tracking the negotiation needed state: currently, it is too simplistic, the library sets a flag when adding a track and clears it when `setLocalDescription()` is called. As a result, when concurrent events happen, a track may be left non-negotiated, but the library forgets negotiation is needed. I'm looking into it.

**Comment by daweifeng** [comment]
How about invoking `addTrack()` when peer B receives an offer from peer A? Should we adding track after calling `setRemoteDescription()` and before `setLocalDescription()` ?

**Comment by paullouisageneau** [comment]
@daweifeng The specification forbids adding new tracks in answers, you can only add new tracks in offers. You may however modify offered tracks in the `onTrack()` callback before answering.
