### ISSUE TITLE
Implementation in Codeblocks C++

### ISSUE THREAD

**Issue by carl0529** [paullouisageneau/libdatachannel#1114]
I would like to use the library in Codeblocks. I had follow build instruction successfully, and added "/usr/local/include" to Project build options > Search directories > Compiler. The compiler can link to the library and get some declared variables. But I cannot even run the sample codes due to "undefined reference". Is there any additional set-up required for using in Codeblocks?

```
#include <iostream>
#include <stdio.h>
#include <string>
using namespace std;

#include <rtc/rtc.hpp>
using namespace rtc;
#include "include/json.hpp"
using nlohmann::json;

int main(){
    rtc::Configuration config;
    config.iceServers.emplace_back("stun:stun.l.google.com:19302");

    rtc::PeerConnection pc(config);
    pc.onLocalDescription([](rtc::Description sdp) {
        // Send the SDP to the remote peer
        cout << "send SDP: "<< std::string(sdp) << endl;
        // MY_SEND_DESCRIPTION_TO_REMOTE(std::string(sdp));
    });

    pc.onLocalCandidate([](rtc::Candidate candidate) {
        // Send the candidate to the remote peer
        cout << "send candidate: "
            << candidate.candidate() << ", "
            << candidate.mid()
            << endl;
        // MY_SEND_CANDIDATE_TO_REMOTE(candidate.candidate(), candidate.mid());
    });

    pc.onStateChange([](rtc::PeerConnection::State state) {
    std::cout << "State: " << state << std::endl; });

    pc.onGatheringStateChange([pc](rtc::PeerConnection::GatheringState state) {
        std::cout << "Gathering State: " << state << std::endl;
    });
    pc.setLocalDescription();

    return 0;
}
```
<img width="962" alt="error" src="https://github.com/paullouisageneau/libdatachannel/assets/47996588/97affc04-8dbc-4bc4-8304-41f8eee2cdee">

**Comment by carl0529** [comment]
Yet, putting library path in  Project build options > Search directories > Compiler is standard procedure. I have no problem setting-up in this way when using OpenCV libarary. In addition, it still fail to link even if I also add the path to Search directories > Linker.

Is there any flag required when using the library, such as -pthread, -lX11, `pkg-config --flags --libs opencv4`  placed after g++?

**Comment by paullouisageneau** [comment]
> Is there any flag required when using the library, such as -pthread, -lX11, `pkg-config --flags --libs opencv4` placed after g++?

Yes you do, that's what I meant by adding the library, you need to add `datachannel` (the g++ argument is `-ldatachannel`).

**Comment by paullouisageneau** [comment]
> Is there any flag required when using the library, such as -pthread, -lX11, `pkg-config --flags --libs opencv4` placed after g++?

Yes, that's what I meant by adding the library, you need to add `datachannel` (the g++ argument is `-ldatachannel`).

**Comment by carl0529** [comment]
Thanks, it work now. I thought the flag was -libdatachannel and kept getting it wrong.
