### ISSUE TITLE
Issue of RtcpNackResponder nack data

### ISSUE THREAD

**Issue by hqs1** [paullouisageneau/libdatachannel#1117]
Hello, I am using libchannel and the nack data seems to be inconsistent with the media source data. The data sent by the same sequenceNumber and nack seems to use the same message_ptr. It seems that the data sent by nack has secondary encryption.

The storage media data here appears to be weakly referenced
https://github.com/paullouisageneau/libdatachannel/blob/b7f1f03a525e78be08f77e2f23a6077400393c80/src/rtcpnackresponder.cpp#L61

thank you !

**Comment by paullouisageneau** [comment]
Ow, indeed, this is due to SRTP encryption happening in-place so messages referenced by `RtcpNackResponder` end up corrupted. I'm pushing a fix.

**Comment by paullouisageneau** [comment]
Thank you for reporting, it should be fixed by https://github.com/paullouisageneau/libdatachannel/pull/1118

**Comment by hqs1** [comment]
Ok, thanks. I'll test it and give feedback.

**Comment by hqs1** [comment]
After testing, it can be retransmitted normally.
