### ISSUE TITLE
Thread management

### ISSUE THREAD

**Issue by X-Kent** [paullouisageneau/libdatachannel#112]
It may not be a bug but a feature but I would like to make sure which one it is.
From my observations, I see the following behavior:
when I "rtcSetRemoteDescription" or "rtcAddRemoteCandidate" from thread T1 I sometimes (very rare) get the callbacks that are set by "rtcSetLocalDescriptionCallback" and "rtcSetLocalCandidateCallback" called on the same thread T1.

Due to being unable to reproduce it constantly I am not sure if it happens when calling rtcSetRemoteDescription or rtcAddRemoteCandidate but I would like to make sure it's an expected behavior or not.

Usually, when you register for callbacks and then call functions of the library you do not expect the callbacks to be called during your call to the library and using your thread. They usually arrive from some external thread created by the library.

Is it something that is supposed to happen or not ?

**Comment by paullouisageneau** [comment]
Yes, this is supposed to happen in situations where the event is immediate, for instance host candidates are available immediately.

I admit the behavior can be suprising, I'm actually thinking of introducing a thread pool which would prevent those situations.

**Comment by X-Kent** [comment]
Ok, not a bug then.
Just was surprised by the results so wanted to make sure.

Thank you for a quick reply.

**Comment by paullouisageneau** [comment]
The behavior is now changed by https://github.com/paullouisageneau/libdatachannel/pull/118
