### ISSUE TITLE
How to properly release resources in libdatachannel

### ISSUE THREAD

**Issue by bestxpp** [paullouisageneau/libdatachannel#1120]
version:  v0.20.1

this is my code for clean up:

![image](https://github.com/paullouisageneau/libdatachannel/assets/28625121/5e05d483-cdce-424a-9b5f-e89e4b858bca)

When I was testing, the threads in libdatachannel were not being properly released
![image](https://github.com/paullouisageneau/libdatachannel/assets/28625121/61660cae-4a4b-4c06-8004-49c8ad79c9e4)

the test code like [media-sender](https://github.com/paullouisageneau/libdatachannel/tree/v0.20.1/examples/media-sender)

**Comment by paullouisageneau** [comment]
In addition to destroying objects, you have to call `rtc::Cleanup()` to stop threads and free resources.

**Comment by bestxpp** [comment]
thx
