### ISSUE TITLE
Sending h264 message causes assertion in std vector

### ISSUE THREAD

**Issue by Dakror** [paullouisageneau/libdatachannel#1125]
In line https://github.com/paullouisageneau/libdatachannel/blame/437a758ae89e5342940c139b8a647bf1bb1c0ee5/src/message.cpp#L34 i get a "Expression: cannot seek vector iterator after end"

**Comment by paullouisageneau** [comment]
This is a zealous check but it's right, I'll push a fix, thank you for reporting.

**Comment by Dakror** [comment]
Awesome, thanks for the rapid fix 👍
