### ISSUE TITLE
Libnice on Windows

### ISSUE THREAD

**Issue by H4k4nn** [paullouisageneau/libdatachannel#1133]
I wanna use TCP connection for RTP transfer.

I think I have all dependings. I have set USE_NICE in CMakeSettings. What I need to change else or add? I am encountering following error
```
Error LNK2019	Unresolved external symbol nice_agent_new_full için "public: __cdecl rtc::impl::IceTransport::IceTransport(struct rtc::Configuration const &,class std::function<void __cdecl(class rtc::Candidate const &)>,class std::function<void __cdecl(enum rtc::impl::Transport::State)>,class std::function<void __cdecl(enum rtc::impl::IceTransport::GatheringState)>)" (??0IceTransport@impl@rtc@@QEAA@AEBUConfiguration@2@V?$function@$$A6AXAEBVCandidate@rtc@@@Z@std@@V?$function@$$A6AXW4State@Transport@impl@rtc@@@Z@5@V?$function@$$A6AXW4GatheringState@IceTransport@impl@rtc@@@Z@5@@Z) işlevinde başvuruldu	C:\**\libdatachannel2\out\build\x64-Debug\libdatachannel2	C:\**\s\libdatachannel2\out\build\x64-Debug\icetransport.cpp.obj	1		
```

**Comment by H4k4nn** [comment]
what I did. I have downloaded libnice project and build it. After building change the agent.h and agent.c and nice-10.dll with default ones.

For now I can build datachannel project but application gives error 
![error](https://github.com/paullouisageneau/libdatachannel/assets/6388994/160cdef4-2b0f-4b81-bc41-4d3e14ba0bd5)

**Comment by paullouisageneau** [comment]
What do you mean by "I changed agent.h, agent.c and nice-10.dll with default ones."?

**Comment by paullouisageneau** [comment]
> I wanna use TCP connection for RTP transfer.

This is a bad idea in general, I hope you know what you are doing. In addition to using libnice, you need to enable `rtc::Configuration::enableIceTcp` to `true`.

> what I did. I have downloaded libnice project and build it. After building I changed agent.h, agent.c and nice-10.dll with default ones.

What do you mean by "I changed agent.h, agent.c and nice-10.dll with default ones."? From the error it looks like the nice DLL is missing an exported function, but I don't understand Turkish.

**Comment by H4k4nn** [comment]
Problem was I had old version of Gstreamer on my pc. And a few functions deprecated. 

I have changed nice.h and nice-dll but it was shown on image. I changed nice.lib and problem disappeared

**Comment by paullouisageneau** [comment]
I'm closing this issue since it looks like you found the problem.
