### ISSUE TITLE
Crash on closed write (usrstcp)

### ISSUE THREAD

**Issue by X-Kent** [paullouisageneau/libdatachannel#115]
This is not libdatachannel issue but more like usrsctp weird behavior issue but it would be nice if libdatachannel could protect from it.

usrsctp: Send callback is invoked on already closed socket:
https://github.com/sctplab/usrsctp/issues/405

I believe this issue leads to this crashlog I am able to inconsistently reproduce with libdatachannel on Android device:
libc.so - (__fortify_fatal(char const*, ...)+34)
libc.so - (HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)+20)
libc.so - (pthread_mutex_lock+136)
libdatachannel.so - (std::__ndk1::mutex::lock()+4)
libdatachannel.so - (rtc::SctpTransport::handleWrite(std::byte*, unsigned int, unsigned char, unsigned char)+356)
libdatachannel.so - (rtc::SctpTransport::WriteCallback(void*, void*, unsigned int, unsigned char, unsigned char)+24)

It's pretty rare as probably happens if you call close exactly as the packet arrives but can we add some kind of protection against it if my theory is correct ?

**Comment by paullouisageneau** [comment]
I think your assumption is correct. When `usrsctp_close` returns it is assumed the `SctpTransport` instance can be safely destroyed, whereas usrsctp seems to still try to send after that in some specific case.

I'll try to add a workaround by unregistering the calback explicitly before closing it.

**Comment by paullouisageneau** [comment]
Could test if this workaround prevents the issue? https://github.com/paullouisageneau/libdatachannel/pull/116

**Comment by X-Kent** [comment]
Will test it out and report back but it can take a couple of days as it doesn't reproduce that easily.

**Comment by X-Kent** [comment]
It seems to fix it.

**Comment by paullouisageneau** [comment]
Good, I'm merging the PR then.

**Comment by paullouisageneau** [comment]
I introduced a better workaround in https://github.com/paullouisageneau/libdatachannel/pull/120
