### ISSUE TITLE
Invalid pointer casting in H264 packetizer

### ISSUE THREAD

**Issue by ray1422** [paullouisageneau/libdatachannel#1155]
This causes runtime error when sanitizer is enabled since vector<byte> is not aligned to 4, and uint32_t requires 4 bytes alignment.

https://github.com/paullouisageneau/libdatachannel/blob/master/src/h264rtppacketizer.cpp#L36C4-L36C10

**Comment by ray1422** [comment]
## reproduce steps
1. Enable sanitizers
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address -fsanitize=undefined -fsanitize=leak")
```
2. compile with `g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`
3. run `streamer` example

errors:
libdatachannel/examples/streamer/h264fileparser.cpp:32:32: runtime error: load of misaligned address 0x63200000081d for type 'unsigned int', which requires 4 byte alignment

/workspaces/libdatachannel/src/h264rtppacketizer.cpp:36:36
libdatachannel/src/h264rtppacketizer.cpp:36:36: runtime error: load of misaligned address 0x63200006081d for type 'unsigned int', which requires 4 byte alignment

**Comment by ray1422** [comment]
#1157

**Comment by paullouisageneau** [comment]
Thank you for reporting and fixing the issue!
