### ISSUE TITLE
Order of media formats not preserved

### ISSUE THREAD

**Issue by singpolyma** [paullouisageneau/libdatachannel#1158]
When I call:

    description.addOpucCodec(107);
    description.addPCMUCodec(0);

I expect my m-line to contain formats in the order `107 0` so that I express that I prefer to use opus rather than PCMU when both are available.  But https://github.com/paullouisageneau/libdatachannel/blob/fbd8f23d6af2cc3cd3b8bbc5154d3bbbbd0f01b1/src/description.cpp#L908 which generates this list pulls from a `std::map` which orders by key, and the payloadType is the key, so it ends up putting `0` first and PCMU wins.

Using `0` because it is the standard payloadType for PCMU https://en.wikipedia.org/wiki/RTP_payload_formats

**Comment by paullouisageneau** [comment]
Indeed currently order is not preserved. This was already mentioned by @wusspuss in https://github.com/paullouisageneau/libdatachannel/discussions/1142 with a proposed fix in https://github.com/paullouisageneau/libdatachannel/pull/1144, however it's not finished and would break things as it is.

**Comment by paullouisageneau** [comment]
Fixed by https://github.com/paullouisageneau/libdatachannel/pull/1168
