### ISSUE TITLE
v0.21.0 fails to compile due to missing header

### ISSUE THREAD

**Issue by ThePyrotechnic** [paullouisageneau/libdatachannel#1173]
When compiling v0.21.0 on an up-to-date x86 Arch Linux PC, I receive the following error:
(I have also observed this on the master branch as of [919f06e](https://github.com/paullouisageneau/libdatachannel/commit/919f06e9a46e3671c8e042eb61eea9963037d841))
```
[ 50%] Building CXX object CMakeFiles/datachannel.dir/src/nalunit.cpp.o
<truncated>/libdatachannel/src/h264rtpdepacketizer.cpp: In member function ‘virtual void rtc::H264RtpDepacketizer::incoming(rtc::message_vector&, const rtc::message_callback&)’:
<truncated>/libdatachannel/src/h264rtpdepacketizer.cpp:116:29: error: ‘remove_if’ is not a member of ‘std’; did you mean ‘remove_cv’?
  116 |         messages.erase(std::remove_if(messages.begin(), messages.end(),
      |                             ^~~~~~~~~
      |                             remove_cv
make[2]: *** [CMakeFiles/datachannel.dir/build.make:328: CMakeFiles/datachannel.dir/src/h264rtpdepacketizer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:355: CMakeFiles/datachannel.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
From [cppreference](https://en.cppreference.com/w/cpp/algorithm/remove) it seems that `remove_if` requires the `<algorithm>` header to be imported
I've attached the following patch that I used to test (below), but I'm not sure if this is the best place for the include since I am not familiar with the project.
[0001-Include-algorithm-to-use-std-remove_if.patch.txt](https://github.com/paullouisageneau/libdatachannel/files/15280038/0001-Include-algorithm-to-use-std-remove_if.patch.txt)

**Comment by paullouisageneau** [comment]
Thank you for reporting, this is fixed in https://github.com/paullouisageneau/libdatachannel/pull/1176. Your patch is fine but I prefer headers needed only by the implementation to be imported in the .cpp file.
