### ISSUE TITLE
While using rtcSendMessage observed the raise in memory 

### ISSUE THREAD

**Issue by DeepShahEi** [paullouisageneau/libdatachannel#1186]
Version used : v0.18.3
Commit ID: 8a4820223dae00806c4a93dfa182141d15ffbf40

While using rtcSendMessage  observed the raise in memory ? Does rtcSendMessage  creating internal buffer when i used rtcGetBufferedAmount() API always return "ZERO" .
@paullouisageneau

**Comment by paullouisageneau** [comment]
You should update as 0.18.3 was released more than one year ago, there has been 3 releases since then.

Could you please develop? Are you sending in a data channel? Is the receiver local or across a network? What is the memory increase? Code to reproduce the issue would be useful.

**Comment by DeepShahEi** [comment]
@paullouisageneau I have tried to test with the latest version of libdatachannel but facing same issue I am sharing the code code snippet for Sender side: 
```c++
    Peer *peer = (Peer *)malloc(sizeof(Peer));
    if (!peer) {
        return NULL;
        }

    memset(peer, 0, sizeof(Peer));

    // Create peer connection
    peer->pc = rtcCreatePeerConnection(config);
    if (peer->pc < 0) {
        LOG_STRM_ERROR("[ChannelId : %s] PeerConnection creation failed", CHANNEL_X_DEVID.c_str());
        free(peer);
        return NULL;
    }

        peer->mqtt_server = mqtt_server;

    rtcSetUserPointer(peer->pc, peer);
    rtcSetTrackCallback(peer->pc, trackCallback);
    rtcSetLocalDescriptionCallback(peer->pc, descriptionCallback);
    rtcSetLocalCandidateCallback(peer->pc, candidateCallback);
    rtcSetStateChangeCallback(peer->pc, stateChangeCallback);
    rtcSetGatheringStateChangeCallback(peer->pc, gatheringStateCallback);

    peer->tr = -1;
    return peer;

                        // add locking here
                        pthread_mutex_lock(&g_peer_mutex);
                        for(int idx = 0; idx < g_peer_count; idx++) {
                                if(g_peer && g_peer[idx] && g_peer[idx]->connected && g_peer[idx]->state == RTC_CONNECTED) {
                                        // TODO 1st packet must be of I frame
                                        if(mark_bit) {
                                                tempBuffer[1] = (g_peer[idx]->rtc_track.payloadType | 0x80);
                                        } else {
                                                tempBuffer[1] = g_peer[idx]->rtc_track.payloadType;
                                        }
                                                int i = rtcSendMessage(g_peer[idx]->tr, (const char*)tempBuffer, sendLen);
                                                if(i < 0) {
                                                        LOG_STRM_ERROR("[ChannelId : %s] rtcSendMessage is failed return : %d", CHANNEL_X_DEVID.c_str(), i);
                                                } else {
                                                        LOG_GEN_DEBUG("SUCCESS SEND!!!!");
                                                }
                                }
                        }
                        pthread_mutex_unlock(&g_peer_mutex);

```  
Sender side we are dividing the H264 data into 1200 byte chunks and send using rtcSendMessage one by one without any sleep means sender side no flow control .

**Comment by paullouisageneau** [comment]
Thank you for the code. Tracks have no internal buffering, everything is sent synchronously. How to you setup the track itself? 

Also, where do you read the H264 data from and what do you mean exactly by "dividing the H264 data into 1200 byte chunks"?

**Comment by DeepShahEi** [comment]
@paullouisageneau Thank you for the quick reply please find the below snippet : 
```c++
                                                                l_Peer->rtc_track.payloadType = 96;
                                                                l_Peer->rtc_track.direction = RTC_DIRECTION_SENDONLY;
                                                                //NOTE: Only supporting H264 codec in webrtc
                                                                l_Peer->rtc_track.codec = RTC_CODEC_H264;
                                                                l_Peer->rtc_track.ssrc = 42;
                                                                l_Peer->rtc_track.name = "cam_video";
                                                                l_Peer->rtc_track.mid = mid;
                                                                l_Peer->rtc_track.msid = "duclo";

                                                                l_Peer->tr = rtcAddTrackEx(l_Peer->pc, &l_Peer->rtc_track);
                                                                rtcSetOpenCallback(l_Peer->tr, openCallback);
                                                                rtcSetClosedCallback(l_Peer->tr, closedCallback);

``` 
We are using live555 library to pull the H264 buffer from RTSP Server continuously , And we have separate the thread to receive this buffer and internally we chunk the whole H264 frame in 1200 byte and send to webRTC one by one until whole frame processed.

**Comment by DeepShahEi** [comment]
@paullouisageneau Is there any way using libdatachannel API i can know that server is not ready to accept the packet or poll the server availability for acceptance of packet ? Could you please help ?

**Comment by paullouisageneau** [comment]
> And we have separate the thread to receive this buffer and internally we chunk the whole H264 frame in 1200 byte and send to webRTC one by one until whole frame processed.

You must not do that, that's not how you packetize a frame. Don't you get tons of warnings? 

If you have raw h264 frames and not RTP packets, add an H264 packetizer to the track with `rtcSetH264Packetizer()`, then send your frames without chunking them. Before sending each frame, you must set the correct timestamp with `rtcSetTrackRtpTimestamp()`.

> @paullouisageneau Is there any way using libdatachannel API i can know that server is not ready to accept the packet or poll the server availability for acceptance of packet ? Could you please help ?

What do you mean? When the track is open, it means the remote side is ready to receive media.

**Comment by DeepShahEi** [comment]
@paullouisageneau We are not sending raw H264 packet we send RTP using below then send using rtcGetBufferedAmount : 

```c++
extern "C" int createRTPHeader(char *buffer, int len)
{
        if (len < sizeof(rtc::RtpHeader))
                return -1;
        auto rtp = reinterpret_cast<rtc::RtpHeader *>(buffer);
        rtp->setSsrc(42);
        return 0;
}
                        ret = createRTPHeader((char*)(tempBuffer), sendLen);
                        if(-1 == ret) {
                                LOG_STRM_ERROR("[ChannelId : %s] createRTPHeader failed", CHANNEL_X_DEVID.c_str());
                                if(NULL != buffer) {
                                        free(buffer);
                                        buffer = NULL;
                                }
                                if(NULL != tempBuffer) {
                                        free(tempBuffer);
                                        tempBuffer = NULL;
                                }
                                return;
                        }

                        // add locking here
                        pthread_mutex_lock(&g_peer_mutex);
                        for(int idx = 0; idx < g_peer_count; idx++) {
                                if(g_peer && g_peer[idx] && g_peer[idx]->connected && g_peer[idx]->state == RTC_CONNECTED) {
                                        // TODO 1st packet must be of I frame
                                        if(mark_bit) {
                                                tempBuffer[1] = (g_peer[idx]->rtc_track.payloadType | 0x80);
                                        } else {
                                                tempBuffer[1] = g_peer[idx]->rtc_track.payloadType;
                                        }
                                                int i = rtcSendMessage(g_peer[idx]->tr, (const char*)tempBuffer, sendLen);

~        
```

**Comment by DeepShahEi** [comment]
> > And we have separate the thread to receive this buffer and internally we chunk the whole H264 frame in 1200 byte and send to webRTC one by one until whole frame processed.
> 
> You must not do that, that's not how you packetize a frame. Don't you get tons of warnings?
> 
> If you have raw h264 frames and not RTP packets, add an H264 packetizer to the track with `rtcSetH264Packetizer()`, then send your frames without chunking them. Before sending each frame, you must set the correct timestamp with `rtcSetTrackRtpTimestamp()`.
> 
> > @paullouisageneau Is there any way using libdatachannel API i can know that server is not ready to accept the packet or poll the server availability for acceptance of packet ? Could you please help ?
> 
> What do you mean? When the track is open, it means the remote side is ready to receive media.

@paullouisageneau Ohh okay got it.

**Comment by paullouisageneau** [comment]
Even if you write RTP headers to the chunks, that's not how you packetize H264. The process is more complex (it is specified in [RFC 6184](https://www.rfc-editor.org/rfc/rfc6184)). Also, the code is incorrect, even assuming you reserved the header size and zeroed it beforehand, it looks like you don't fill the header correctly (sequence and timestamp are not set, for instance).

It looks like you copy-pasted the code from media sender example completely out of context. The example takes an RTP stream as input, of course it doesn't work if your input is not an RTP stream. If you get raw H264 frames, you should use the H264 packetizer in libdatachannel.

**Comment by paullouisageneau** [comment]
Note that `rtcGetBufferedAmount` will always return 0 for tracks, as there is no applicative buffer.

**Comment by DeepShahEi** [comment]
> Even if you write RTP headers to the chunks, that's not how you packetize H264. The process is more complex (it is specified in [RFC 6184](https://www.rfc-editor.org/rfc/rfc6184)). Also, the code is incorrect, even assuming you reserved the header size and zeroed it beforehand, it looks like you don't fill the header correctly (sequence and timestamp are not set, for instance).
> 
> It looks like you copy-pasted the code from media sender example completely out of context. The example takes an RTP stream as input, of course it doesn't work if your input is not an RTP stream. If you get raw H264 frames, you should use the H264 packetizer in libdatachannel.

@paullouisageneau  It seems like I am not setting the timestamp in the header. Could this cause a memory leak? When I comment out the rtcSendMessage API, I don't observe the leak. Am I missing some prior configuration?

**Comment by paullouisageneau** [comment]
It's not just about the timestamp, the entire way you do the packetization is incorrect. Again, you should use the packetizer in the library.

**Comment by DeepShahEi** [comment]
@paullouisageneau Here is my observation : 
When my application runs for around 12 hours process VmRSS memory is increasing around 400 MB and after that, I have observed the following: 

`2024-06-17 02:16:31.096 WARN  [8192] [rtc::impl::LogCounter::operator++@29] Number of media packets dropped due to a full queue: 130 `

Suddenly process VmRSS memory steady, Could you please confirm is because of the queue implementation internally allocating data? Can we configure the queue size to a minimum to avoid internal buffering? 

However, I can see the live stream effortlessly.
could you please help ?

**Comment by DeepShahEi** [comment]
I have included below code that looks like a queue The RECV_QUEUE_LIMIT is set to 1024 messages. This means each track can queue up to 1024 messages before dropping packets. The size of each message, the default local max message size is quite large (256 KB).
If each message is at the max size (256 KB), the queue could theoretically use up to 256 KB * 1024 ≈ 256 MB.

**As per my observation that RSS memory continues to grow until the queue is full looks like the messages are accumulating in the queue without being processed or cleared fast enough.**

`namespace rtc {

const size_t MAX_NUMERICNODE_LEN = 48; // Max IPv6 string representation length
const size_t MAX_NUMERICSERV_LEN = 6;  // Max port string representation length

const uint16_t DEFAULT_SCTP_PORT = 5000; // SCTP port to use by default

const uint16_t MAX_SCTP_STREAMS_COUNT = 1024; // Max number of negotiated SCTP streams
                                              // RFC 8831 recommends 65535 but usrsctp needs a lot
                                              // of memory, Chromium historically limits to 1024.

const size_t DEFAULT_LOCAL_MAX_MESSAGE_SIZE = 256 * 1024; // Default local max message size
const size_t DEFAULT_REMOTE_MAX_MESSAGE_SIZE = 65536;     // Remote max message size if not in SDP

const size_t DEFAULT_WS_MAX_MESSAGE_SIZE = 256 * 1024;   // Default max message size for WebSockets

const size_t RECV_QUEUE_LIMIT = 1024; // Max per-channel queue size (messages)

const int MIN_THREADPOOL_SIZE = 4; // Minimum number of threads in the global thread pool (>= 2)

const size_t DEFAULT_MTU = RTC_DEFAULT_MTU; // defined in rtc.h

} // namespace rtc`

**Comment by paullouisageneau** [comment]
> Suddenly process VmRSS memory steady, Could you please confirm is because of the queue implementation internally allocating data? Can we configure the queue size to a minimum to avoid internal buffering?

If the queue grows it means there are messages waiting to be received on the track. You need to set an `onMessage()` callback. You should set one also on sender side because the receiver typically sends RTCP messages.

> I have included below code that looks like a queue The RECV_QUEUE_LIMIT is set to 1024 messages. This means each track can queue up to 1024 messages before dropping packets.

`RECV_QUEUE_LIMIT` was set to 1024 in v0.21.1. If you use an older version, it's basically unlimited.

>  The size of each message, the default local max message size is quite large (256 KB). If each message is at the max size (256 KB), the queue could theoretically use up to 256 KB * 1024 ≈ 256 MB

No, the max message size is for datachannels. Media packets are limited by the MTU minus headers, so 1024 * (1280-60) ≈ 1.2 MB. If you use a depacketizer, it depends on the media frame size, for instance for 1Mbps@30fps a frame is around 4200 bytes so 1024 * 4000 ≈ 4.3 MB.

> **As per my observation that RSS memory continues to grow until the queue is full looks like the messages are accumulating in the queue without being processed or cleared fast enough.**

Most probably, messages are not processed because you did not set a `onMessage()` callback. You can safely ignore the messages if you don't need them.

**Comment by DeepShahEi** [comment]
@paullouisageneau I think the issue is the queue size because after some time (approx . 12 hours) I see VmRSS memory steady.
As you suggested, is this issue resolved if we set onMessage() callback sender side? could you please provide the guidelines?

**Comment by paullouisageneau** [comment]
> As you suggested, is this issue resolved if we set onMessage() callback sender side? could you please provide the guidelines?

If you use the C API:
```c
static void RTC_API messageCallback(int id, const char *message, int size, void *ptr) {
    // ignore message
}

[...]

rtcSetMessageCallback(track, messageCallback);
```

**Comment by DeepShahEi** [comment]
@paullouisageneau what should we handle in messageCallback if the server is not ready to accept the packet?

**Comment by DeepShahEi** [comment]
@paullouisageneau What I think if we get RTCP message in a callback that says "waiting to be received on the track ", the sender will not send the message using rtcSendMessage.

**Comment by DeepShahEi** [comment]
@paullouisageneau After registering rtcSetMessageCallback we can reduce our device's memory footprint.

Thank you for your active participation in this issue. It is really appreciated.
