### ISSUE TITLE
WebSocket server only sends the first certificate in a certificate chain

### ISSUE THREAD

**Issue by ptesavol** [paullouisageneau/libdatachannel#1189]
Hi

This bug is preventing us from taking the node-datachannel WebSockets into use at Streamr.  

The WebSocketServer of libdatachannel currently only sends the first certificate in the certificate chain to the client. This usually works in the case of browser clients, but causes the error "Error: unable to verify the first certificate" on nodejs clients, as the intermediate certificates of the chain are not sent.

Looking at the code, it seems that in the case of OpenSSL the reason for the bug is at
https://github.com/paullouisageneau/libdatachannel/blob/17877358c4887cd561c457d9ae713f1c0ad4db18/src/impl/tlstransport.cpp#L604 where only one certificate is loaded into the context. According to the [OpenSSL documentation](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_cert_and_key.html) "The rest of the certificates needed to form the complete certificate chain can be specified using the SSL_CTX_add_extra_chain_cert()"  function.

**Comment by paullouisageneau** [comment]
I added support for loading the chain with OpenSSL in the existing `Certificate` wrapper on #1195, since GnuTLS should support loading the chain out of the box with the existing code.
