### ISSUE TITLE
Update the remote description after SDP negotiation?

### ISSUE THREAD

**Issue by achingbrain** [paullouisageneau/libdatachannel#1203]
This is related to #1166

For libp2p WebRTC-Direct after the DTLS handshake has taken place and the connection becomes ready to use, we open a datachannel and use it to [verify](https://github.com/libp2p/specs/blob/master/webrtc/webrtc-direct.md#connection-security) the local and remote certificate fingerprints and the peer identifier so we can assert that the remote peer is the peer we think they are.

During connection we set the remote certificate fingerprint to a dummy value and disable fingerprint validation, since we are going to do it later.

When we come to do it we need access to the fingerprint of the remote certificate.

The browser `RTCPeerConnection` has a [.currentRemoteDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription) property - this returns:

> an object describing the remote end of the connection as it was most recently successfully negotiated

and includes the fingerprint of the remote connection.

The node.js polyfill [returns the remoteDescription](https://github.com/murat-dogan/node-datachannel/blob/master/polyfill/RTCPeerConnection.js#L168) when this property is accessed, the same as `.remoteDescription` - this is not quite right as the `.remoteDescription` property should return what was passed to [.setRemoteDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription) - this can be different to the currently negotiated state of remote end of the connection.

The Description class [parses the fingerprint](https://github.com/paullouisageneau/libdatachannel/blob/master/src/description.cpp#L108-L144) out of the description passed to `.setRemoteDescription`, later on that fingerprint is [verified or not, depending on config](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L447-L448) - would it be possible to have a copy of the local Description that gets updated with the actual fingerprint the connection uses?

If this is done along with the final ICE candidates etc it would make it possible to implement `.currentRemoteDescription` on the polyfill correctly and also for me to implement the final piece of the WebRTC-Direct connection listener.

I can try to implement this if it's acceptable though it's really stretching my C++!

**Comment by xicilion** [comment]
sure, this is a feature that is needed on the listening side, I tried to make some modifications but may need to change the const attribute of libdatachannel's checkFingerprint function.
Maybe you can have a better implementation.

**Comment by achingbrain** [comment]
> may need to change the const attribute of libdatachannel's checkFingerprint function, which feels bad

I opened  #1204 to implement this and edit up removing the `const` attribute as above.  It works though I'm open to better ideas..

**Comment by xicilion** [comment]
> I opened #1204 to implement this and edit up removing the `const` attribute as above. It works though I'm open to better ideas..

Yes, I noticed that, adding `currentRemoteDescription` is a great idea, I like it.

**Comment by paullouisageneau** [comment]
> The browser `RTCPeerConnection` has a [.currentRemoteDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription) property - this returns:
> 
> > an object describing the remote end of the connection as it was most recently successfully negotiated
> 
> and includes the fingerprint of the remote connection.
> 
> The node.js polyfill [returns the remoteDescription](https://github.com/murat-dogan/node-datachannel/blob/master/polyfill/RTCPeerConnection.js#L168) when this property is accessed, the same as `.remoteDescription` - this is not quite right as the `.remoteDescription` property should return what was passed to [.setRemoteDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription) - this can be different to the currently negotiated state of remote end of the connection.
> 
> The Description class [parses the fingerprint](https://github.com/paullouisageneau/libdatachannel/blob/master/src/description.cpp#L108-L144) out of the description passed to `.setRemoteDescription`, later on that fingerprint is [verified or not, depending on config](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L447-L448) - would it be possible to have a copy of the local Description that gets updated with the actual fingerprint the connection uses?

@achingbrain I think there is a misunderstanding about what `RTCPeerConnection.currentRemoteDescription` is. The difference only matters during renegotiation: the current description corresponds to the last successful negotiation, whereas `pendingRemoteDescription` is the new one being negotiated. `remoteDescription` is the pending description if it exists, otherwise the current one. For more details look at [Pending and current descriptions](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions).

The situation you are discussing here does not happen in the standard because a peer is supposed to reject fingerprints that don't match, but the sure thing is that set descriptions must not be updated according to what happens on the wire. In this case changing the description might even be misleading as users could consider it as the source of truth for what the expected fingerprint was.

I appreciate the effort, however `currentRemoteDescription` is not a proper way to report information about the current connection to the user, I think a `rtc::PeerConnection::remoteFingerprints()` getter would be appropriate for this use case.

**Comment by achingbrain** [comment]
I chose `currentRemoteDescription` precisely because it can change during the lifetime of the connection, though my opinion is not very strong.

https://github.com/paullouisageneau/libdatachannel/pull/1206 adds the suggested `rtc::PeerConnection::remoteFingerprints()` method.

**Comment by paullouisageneau** [comment]
> I chose `currentRemoteDescription` precisely because it can change during the lifetime of the connection, though my opinion is not very strong.

Sure, all descriptions can change, only they have to be changed by signaling, and `currentRemoteDescription` must be the same as `remoteDescription`when there is no pending description. It must not be changed to reflect wire status.

> #1206 adds the suggested `rtc::PeerConnection::remoteFingerprints()` method.

Thank you for adding!
