### ISSUE TITLE
CMake script does not install STATIC library and static dependencies

### ISSUE THREAD

**Issue by pfeatherstone** [paullouisageneau/libdatachannel#1208]
I'm building and installing this library using the following commands:
```
cmake . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --parallel
sudo cmake --build build --target install
```
I was expecting it to build the static library `libdatachannel-static.a` by default and installing it along with its dependencies:
* `libjuice-static.a`
* `libsrtp2.a`
* `libusrsctp.a`
That doesn't seem to be the case. Is this possible?

**Comment by paullouisageneau** [comment]
CMakelists builds the shared library by default. The static library can be built with the target `datachannel-static`, however only the shared library can be installed.

**Comment by pfeatherstone** [comment]
Cheers. It is possible to amend the script to allow for installing the static library along with it dependencies ?

**Comment by mkm85** [comment]
Had the same issue, maybe just remove the static vs dynamic stuff and only provide a single library called LibDataChannel, then it is up to the one who compiles the library to specify if it should be built as static or dynamic. Consumers of the library can then simply link against LibDataChannel::LibDataChannel without having to worry about how it is compiled.
