### ISSUE TITLE
Error in build node-datachannel for webtorrent-cli

### ISSUE THREAD

**Issue by asimovc** [paullouisageneau/libdatachannel#1213]
Recently i having some errors whe i install webtorrent-cli because the installation of node-datachannel. Here the [logs](https://0x0.st/XcF6.log)

## System Info

**OS:** [Kiss Linux](https://kisslinux.github.io/)
**Libc:** Musl
**Core Utils:** Busybox
**Cmake Version:** 3.29.5
**NodeJS Version:** 22.3.0

**Comment by paullouisageneau** [comment]
This is fixed in libdatachannel v0.21.1 by https://github.com/paullouisageneau/libdatachannel/pull/1183. This should be reported to [node-datachannel](https://github.com/murat-dogan/node-datachannel) instead, which still uses v0.21.0.

**Comment by asimovc** [comment]
node-datachannel already get the upstream
