### ISSUE TITLE
setLocalDescription's Init parameter may not work.

### ISSUE THREAD

**Issue by xicilion** [paullouisageneau/libdatachannel#1218]
In the following code snippet:
```JavaScript
const offerSdp = await peerConnection.createOffer();
const mungedOfferSdp = munge(offerSdp, ufrag);
await peerConnection.setLocalDescription(mungedOfferSdp);
```
When `setLocalDescription` internally calls `PeerConnection::setLocalDescription` and passes the Init parameter, it's because of the presence of the following code(https://github.com/paullouisageneau/libdatachannel/blob/master/src/peerconnection.cpp#L101):
```cpp
// Only a local offer resets the negotiation needed flag
if (type == Description::Type::Offer && !impl()->negotiationNeeded.exchange(false)) {
PLOG_DEBUG << "No negotiation needed";
return;
}
```
The method `iceTransport->setIceAttributes` will not be called.

**Comment by xicilion** [comment]
Yes, you are right. The behavior of createOffer here is implemented based on the node-datachannel's polyfill. But it seems that we can't get the correct localDescription without creating a socket.

**Comment by xicilion** [comment]
made a little change, just moved the `iceTransport->setIceAttributes` before checking the `type`, and it seems to work after testing. But I'm not sure if there will be any side effects like this.

**Comment by paullouisageneau** [comment]
> made a little change, just called the `iceTransport->setIceAttributes` before checking the `type`, and it seems to work after testing. But I'm not sure if there will be any side effects like this.

You can't do that, it introduces a side effect when it fails and the description ends-up half applied. The polyfill needs to be fixed.
