### ISSUE TITLE
The push function of the sendQueue in DataChannel will trigger wait and  can not be awaked.

### ISSUE THREAD

**Issue by the-loki** [paullouisageneau/libdatachannel#1219]
The push function of the sendQueue in DataChannel will trigger waiting when the number of elements in the queue reaches its limit under capacity constraints. However, there is no place other than close that wakes up the thread.

![YoloMouse_Zg07sbFcEr](https://github.com/paullouisageneau/libdatachannel/assets/40163921/f367aba4-501b-4d2d-8ab4-06373011ed02)

**Comment by paullouisageneau** [comment]
Good catch, this is fixed by https://github.com/paullouisageneau/libdatachannel/pull/1221

**Comment by paullouisageneau** [comment]
Released in v0.21.2

**Comment by the-loki** [comment]
> Good catch, this is fixed by #1221

thanks!
