### ISSUE TITLE
C API lacking proper closure support

### ISSUE THREAD

**Issue by pschichtel** [paullouisageneau/libdatachannel#1228]
As mentioned in #1227 I'm working in Java bindings for libdatachannel. For that I'm using the C API to keep the JNI-side of the interface as simple as possible. libdatachannel's callbacks have the for of for example:

```c
typedef void(RTC_API *rtcDescriptionCallbackFunc)(int pc, const char *sdp, const char *type,  void *ptr);
int rtcSetLocalDescriptionCallback(int pc, rtcDescriptionCallbackFunc cb);
```

The function pointer's definition is fine, as it already supports passing in arbitrary user defined data (with the exception of `rtcLogCallbackFunc`), however the rtcSet*Callback functions don't accept arbitrary user data. There is only a way to attach data to a peer/channel/track. So to have per-callback custom data, the only way currently is to have a large struct per peer/channel/track that holds a reference to the actual user data per type of callback. This is annoying, because now I need to worry about properly synchronizing access to these structs.

I'd like to propose a new set of `rtcSet*Callback` functions (e.g. `rtcSet*CallbackEx` as you did for other functions):

```c
int rtcSetLocalDescriptionCallbackEx(int pc, rtcDescriptionCallbackFunc cb, void** user_data_ptr);
```

When invoking that function with a non-null function pointer, then it would dereference the user_data_ptr pointer once and store the result a long with the callback on the peer/channel/track.
When invoking it with a null function pointer, then it would remove the callback and write the pointer back to user_data_ptr, so the caller has a chance to cleanup the memory.

So usage-wise it would look something like this:

```c
struct callback_data {
    int some_data;
};

void RTC_API handle_local_description_callback2(int pc, const char* sdp, const char* type, void* ptr) {
    struct callback_data* data = ptr;
    printf("sdp=%s, type=%s data=%d\n", sdp, type, data->some_data);
}

void register_callback(int pc, int some_data) {
    struct callback_data* data = malloc(sizeof(struct callback_data));
    data->some_data = some_data;
    rtcSetLocalDescriptionCallbackEx(pc, handle_local_description_callback, (void**) &data);
}

void deregister_callback(int pc) {
    void* data;
    rtcSetLocalDescriptionCallbackEx(pc, NULL, &data);
    if (data != NULL) {
        free(data);
    }
}
```

Implementation wise, in order to support writing back the user data pointer, libdatachannel would have to store that pointer somewhere, optimally together with the callback function itself on the peer/channel/track.

**Comment by paullouisageneau** [comment]
I don't understand the use case very well here, it seems this is something you can achieve currently with only the user pointer. Besides, I'm not a fan of the design where you write back the pointer to deallocate as it seems error-prone.

> There is only a way to attach data to a peer/channel/track. So to have per-callback custom data, the only way currently is to have a large struct per peer/channel/track that holds a reference to the actual user data per type of callback. This is annoying, because now I need to worry about properly synchronizing access to these structs.

You should not need specific synchronization. What is wrong with simply doing this? It is thread-safe in C11, doesn't use malloc, and looks simpler to me overall:
```cpp
struct callback_data {
    int some_data;
};

struct pc_wrapper {
    int id;
    callback_data local_description_data;
};

// Assume the pc_wrapper instance is set with rtcSetUserPointer(wrapper->id, wrapper) on pc creation

void RTC_API handle_local_description_callback(int pc, const char* sdp, const char* type, void* ptr) {
    struct pc_wrapper* pc = (struct pc_wrapper*)ptr;
    printf("sdp=%s, type=%s data=%d\n", sdp, type, pc->local_description_data->some_data);
}

void register_callback(pc_wrapper *pc, int some_data) {
    rtcSetLocalDescriptionCallback(pc->id, NULL);
    pc->local_description_data = some_data;
    rtcSetLocalDescriptionCallback(pc->id, handle_local_description_callback);
}

// Deregistering is now optional
void deregister_callback(my_pc_wrapper *pc) {
    rtcSetLocalDescriptionCallback(pc->id, NULL);
}
```

**Comment by pschichtel** [comment]
But what if you have a different callback for e.g. rtcSetGatheringStateChangeCallback that requires different callback_data?

What I did now, is to have Java listener per peer and all channels and tracks invoke functions on that. then I can do closures in Java all I want.

**Comment by paullouisageneau** [comment]
> But what if you have a different callback for e.g. rtcSetGatheringStateChangeCallback that requires different callback_data?

By adding callback data to the wrapper:
```cpp
struct callback_data {
    int some_data;
};

struct pc_wrapper {
    int id;
    struct callback_data local_description_data;
    struct callback_data gathering_state_change_data;
};

// Assume the pc_wrapper instance is set with rtcSetUserPointer(wrapper->id, wrapper) on pc creation

void RTC_API handle_local_description_callback(int pc, const char* sdp, const char* type, void* ptr) {
    struct pc_wrapper* pc = (struct pc_wrapper*)ptr;
    printf("sdp=%s, type=%s data=%d\n", sdp, type, pc->local_description_data.some_data);
}

void RTC_API handle_gathering_state_change_callback(int pc, rtcGatheringState state, void* ptr) {
    struct pc_wrapper* pc = (struct pc_wrapper*)ptr;
    printf("state=%d data=%d\n", (int)state, pc->gathering_state_change_data.some_data);
}

void register_local_description_callback(pc_wrapper *pc, int some_data) {
    rtcSetLocalDescriptionCallback(pc->id, NULL); // Needed only if you allow registering without deregistering first
    pc->local_description_data.some_data = some_data;
    rtcSetLocalDescriptionCallback(pc->id, handle_local_description_callback);
}

void register_gathering_state_change_callback(pc_wrapper *pc, int some_data) {
    rtcSetGatheringStateChangeCallback(pc->id, NULL); // Needed only if you allow registering without deregistering first
    pc->gathering_state_change_data.some_data = some_data;
    rtcSetGatheringStateChangeCallback(pc->id, handle_gathering_state_change_callback);
}
```

**Comment by pschichtel** [comment]
Yeah I'm pretty much doing that right now, except that I'm doing it on the Java side of things. It's fine for my use-case. I was mostly just reading up on how closures are usually approached in C and while clicking around in the libdatachannel codebase I noticed the mutex that's required for user data access, which wouldn't be needed if the data was attached to each individual callback.

I might build a small prototype/RFC PR about what I'm thinking, but we can close this for now.
