### ISSUE TITLE
Trouble connecting via TURN server

### ISSUE THREAD

**Issue by singpolyma** [paullouisageneau/libdatachannel#1236]
When I test locally, I have no trouble connecting to local devices, but when I test a session between the same two devices and one is outside such that TURN is needed, it never connects.  One device is using my app on libdatachannel, the other is an app using libwebrtc on android.  I am also in control of one of the two TURN servers.

I have attached the libdatachannel logs here. I'm not 100% sure how to interpret them, but it almost seems like it is able to contact the TURN server to allocate a port for the channel, but then is never able to contact anything over that channel?
[log.txt](https://github.com/user-attachments/files/16364497/log.txt)

**Comment by paullouisageneau** [comment]
> I have attached the libdatachannel logs here. I'm not 100% sure how to interpret them, but it almost seems like it is able to contact the TURN server to allocate a port for the channel, but then is never able to contact anything over that channel?

The first TURN server is unreachable, it never answers. The second TURN server is successful and the client gets a relay candidate, but no packet is ever received on the allocated port. Firewall might be misconfigured on the server.
