### ISSUE TITLE
Does libdatachannel support to compile in pure C Linux system(for some embedded device no support C++17)?

### ISSUE THREAD

**Issue by topworldcoder** [paullouisageneau/libdatachannel#1240]
Dear author of libdatachannel, I found libdatachannel to be a great project for WebRTC SDK. But please forgive me for asking a simple question. libdatachannel provides a pure C interface, so can I use libdatachannel in a compilation chain (compilation environment) that does not support C++ (at least not C++17)? Thanks for attention!

**Comment by paullouisageneau** [comment]
libdatachannel is a C++ project, it needs a C++ compiler to build even if the library also has a C API. If you have a legacy C++ compiler that doesn't support C++17, @Nemirtingas maintains [a C++14 fork](https://github.com/Nemirtingas/libdatachannel/tree/cxx14).

**Comment by topworldcoder** [comment]
> libdatachannel is a C++ project, it needs a C++ compiler to build even if the library also has a C API. If you have a legacy C++ compiler that doesn't support C++17, @Nemirtingas maintains [a C++14 fork](https://github.com/Nemirtingas/libdatachannel/tree/cxx14).

Thank you very much for your reply. I will try my best to learn libdatachannel and then apply webrtc in a lower c++ compilation environment.

**Comment by Sean-Der** [comment]
Hey @topworldcoder for embedded devices https://github.com/sepfy/libpeer might be a better option. It does a lot less, but isn't as demanding.
