### ISSUE TITLE
Unable to retrieve negotiated media details

### ISSUE THREAD

**Issue by mscdex** [paullouisageneau/libdatachannel#1242]
I've been digging around the code and as far as I can tell there is no way to get the codec and other pertinent details that were negotiated.

The scenario I'm dealing with here is where libdatachannel is receiving an offer. In my `onTrack` callback I'm able to see the type (e.g. audio) and direction but nothing about whether I should be expecting opus, PCMU, PCMA, etc., what sampling rate I should be expecting, etc.

I need this information because internally I will be pushing the media into another library that will handle things like decoding, re-encoding, and bridging (pjproject), but it needs to know what resources to allocate first. It's not realistically possible to work around this by lazily allocating on the first RTP packet because of dynamic payload types (e.g. opus).

Am I just missing something or is this functionality not currently available?

Additionally on a tangentially related matter, is there some way to restrict which codecs are offered from the outset (potentially at peer connection creation time) whether in an offer or answer?

**Comment by paullouisageneau** [comment]
This information is available in the track description, available with `track->description()`. It returns a `rtc::Description::Media` object allowing you to enumerate offered codecs by payload type:
```cpp
auto desc = track->description();
for (int pt : desc.payloadTypes()) {
    auto rtpMap = desc.rtpMap(pt);
    // media format is rtpMap->format
    // rate is rtpMap->clockRate
    // etc
}
```
Codecs are listed from most preferred to least preferred. To restrict codecs in the answser, you can edit the description in the `onTrack()` callback and remove codecs with `removeRtpMap()` (or `removeFormat()`), then set the modified description back with `track->setDescription()`. This way, the answer will contain only a subset of codecs.

You have to manually list offered codecs when adding a track with the media description passed to `addTrack()`:
```cpp
int pt = 96;
rtc::SSRC ssrc = 42;
rtc::Description::Video desc("video", rtc::Description::Direction::SendOnly);
desc.addH264Codec(pt);
desc.addSSRC(ssrc, "video-send");
auto track = pc->addTrack(desc);
```

**Comment by mscdex** [comment]
The first solution seemed to do the trick, thanks.
