### ISSUE TITLE
Enable connectivity checks when using libnice

### ISSUE THREAD

**Issue by krystiancha** [paullouisageneau/libdatachannel#1262]
When using libnice broken connection is not being detected. After some discussion on Discord Paulo found out that connectivity checks are disabled by default in libnice.

To reproduce the issue:
1. Complie libdatachannel with libnice instead of libjuice.
2. Launch a WebRTC-compatible web browser.
3. Run examples/media-send and using the instructions, get the webcam feed into the browser.
4. SIGKILL the browser.
5. media-send will stay in the connected state.

**Comment by paullouisageneau** [comment]
The exact feature to enable in libnice is ICE consent freshness (which involves keepalive with connectivity checks).
