### ISSUE TITLE
Compatible with srtp3

### ISSUE THREAD

**Issue by topworldcoder** [paullouisageneau/libdatachannel#1268]
Hi author,

I tried to update libsrtp to the latest trunk(which is srtp3), and then debugged libdatachannel and found several incompatibilities with srtp3 (in the file dtlssrtptransport.cpp). I list them here so that you can quickly get compatibility with srtp3 if you need to update it later.

1. The input parameter of srtp_protect_rtcp/srtp_protect/srtp_unprotect_rtcp/srtp_unprotect is changed to use size_t type (previously used int type)
size_t uses unsigned __int64 in 64-bit compiler. If continue to use the 'int size' defined in the old code to pass into srtp_protect_rtcp, an exception will be thrown when running in 64-bit: Run-Time Check Failure #2 - Stack around the variable 'size' was corrupted.
---------
So the change point is: 'int size' is changed to 'size_t size'

2. According to the official example of srtp3
uint8_t *srtcp in srtp_protect_rtcp needs to be applied as the length of const uint8_t *rtcp plus SRTP_MAX_SRTCP_TRAILER_LEN
uint8_t *srtp in srtp_protect needs to be applied as the length of const uint8_t *rtp plus SRTP_MAX_TRAILER_LEN
---------
So the changes are: 
size_t srtcp_len = size + SRTP_MAX_SRTCP_TRAILER_LEN; message = make_message(srtcp_len, message);
size_t srtp_len = size + SRTP_MAX_TRAILER_LEN; message = make_message(srtp_len, message);

3. The function srtp_add_stream has been deleted, and the timing of using srtp_create needs to be changed

After the above modifications, libdatachannel can be adapted to use srtp3 and work properly.
You can refer to my branch: https://github.com/topworldcoder/libdatachannel.git

The above is for reference only, thank you for your time!

**Comment by paullouisageneau** [comment]
Thank you for taking the time to report the necessary changes!
