### ISSUE TITLE
Robustness in case of connection loss for a host with multiple connections

### ISSUE THREAD

**Issue by alexswerner** [paullouisageneau/libdatachannel#1270]
Hi,

Thanks again for this amazing work! I am wondering what would be the best way to minimize or eliminate the interruption when a network connection goes down. Consider the scenario of a mobile phone connected via Wi-Fi and 5G, one of these will be selected when the WebRTC peerconnection is established from the list of candidates. Now what happens if this connection is lost? Ideally the other connection should take over. As far as I understand the WebRTC spec, this requires first detection the lost connection and then renegotiation the session. Is that correct? How can I minimize the interruption when using libdatachannel?

Thanks!

**Comment by paullouisageneau** [comment]
libdatachannel does not support ICE restart for now as it is missing from libjuice (see https://github.com/paullouisageneau/libjuice/issues/130), which would reduce interruption duration. Therefore, the solution right now is to detect the lost connection and reconnect.

**Comment by alexswerner** [comment]
Thanks for the reply @paullouisageneau ! We'll go this route.
