### ISSUE TITLE
`media_sender` example seems not to work w/ H265

### ISSUE THREAD

**Issue by FreeNachman** [paullouisageneau/libdatachannel#1289]
- Changed `main.cpp` of the `media-sender` sample to use H265 codec
```
-               media.addH264Codec(96);
+               media.addH265Codec(96); 
``` 
- Pasted the native offer into the HTML page, but no response
- Tried this on _both_ chrome and opera

**Comment by paullouisageneau** [comment]
Have you changed the gstreamer pipeline to encode the input media as h265?

**Comment by FreeNachman** [comment]
> Have you changed the gstreamer pipeline to encode the input media as h265?

Thx for your prompt response. The issue is, `ICE` connection failed to be established, _before_ the actual streaming over the datachannel (verified using webrtc internals).  Once, I'm posting the native code offer into the browser, the HTML page does not "posts its response (so one could paste it to the native code)

**Comment by paullouisageneau** [comment]
Have you set the [flags ](https://chromium.googlesource.com/chromium/src/+/8ca090ecf9fcb51daaa549bbce830511b62f00aa) to enable experimental h265 support for WebRTC in Chrome? You device must also have hardware support for h265 decoding. Otherwise it's expected that the browser rejects the offer.

**Comment by FreeNachman** [comment]
> Have you set the [flags ](https://chromium.googlesource.com/chromium/src/+/8ca090ecf9fcb51daaa549bbce830511b62f00aa) to enable experimental h265 support for WebRTC in Chrome? You device must also have hardware support for h265 decoding. Otherwise it's expected that the browser rejects the offer.

Yes, I've activated chrome using this CL `chrome.exe --enable-features=WebRtcAllowH265Receive --force-fieldtrials=WebRTC-Video-H26xPacketBuffer/Enabled`

I've have nvidia GPU which supports h265 decoding. Does `media_sender` works on your machine?

**Comment by paullouisageneau** [comment]
From the symptom, it really looks like a lack of support on Chrome side. I can't test currently as Chromium hardware acceleration has been broken on Linux with AMD GPU for some time (FYI issue is [here](https://issues.chromium.org/issues/40267998)). I haven't had the time to investigate as I use Firefox. Have you tried using AV1?

**Comment by FreeNachman** [comment]
- Closing this ticket since there is, as of the time of this writing, `h265` support in Chrome Canary.
- The example works as expected, when using the Canary drop
