### ISSUE TITLE
Question about dataChannel:onMessage

### ISSUE THREAD

**Issue by slonv23** [paullouisageneau/libdatachannel#129]
When I set onMessage callback and read incoming data as binary (i.e. vector of bytes) I receive both new data and old data. Is this how it is supposed to be? New data is just appended to some buffer and I receive reference to the same buffer every time.
For example:
```
        dataChannel->onMessage([this](const std::variant<binary, std::string> &message) {
            if (std::holds_alternative<binary>(message)) {
                auto msgData = std::get<binary>(message);
                // msgData  have size of 8192 bytes and contains both old and new message
            }
        });
```
Should I clear this buffer by myself?

**Comment by paullouisageneau** [comment]
You should only receive the new data. How is the data sent on the other side?

**Comment by slonv23** [comment]
This is my method for sending data from client:
```
     /**
     * @param {Buffer|Uint8Array} buffer
     */
    sendMessage(buffer) {
        this.dataChannel.send(buffer.buffer);
    }
```
`this.dataChannel` is RTCDataChannel (https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel)

**Comment by slonv23** [comment]
@paullouisageneau Most likely the problem is with my serialization library. Thank you for clarification.
