### ISSUE TITLE
Receiving onLocalCandidate after onTrack

### ISSUE THREAD

**Issue by singpolyma** [paullouisageneau/libdatachannel#1301]
Sometimes I get `onLocalCandidate` being called after `onTrack` has been called, and at that time if I check the peerconnection state it says Connecting, even though it must be connected in order for there to be a track fully added. Am I understanding the lifecycle wrong?

**Comment by paullouisageneau** [comment]
No, tracks are added during negotiation, before connection. The order of `onLocalCandidate` and `onTrack` is undefined.
