### ISSUE TITLE
copy-paste

### ISSUE THREAD

**Issue by alicera** [paullouisageneau/libdatachannel#136]
https://github.com/paullouisageneau/libdatachannel/tree/master/examples/copy-paste

Redo same procedure for answerer
Redo same procedure for candidates
Wait for "DataChannel open" message
Send message from one peer to another

Could you tell me more detail?
how to do ?
thank you

**Comment by paullouisageneau** [comment]
It means that you need to copy paste the answer description from the answerer to the offerer, then the candidates from the offerer to the answerer, then the candidates from the answerer to the offerer. You should then see the "DataChannel open" message.

**Comment by paullouisageneau** [comment]
Did it answer your question?

**Comment by alicera** [comment]
Thanks for your help . 
I get the "DataChannel open : test" message.
But I dont copy paste the candidates from the offerer to the answerer.
I just do
1. Copy "Local Description" from offerer then Paste copied description
2. copy paste the answer description from the answerer to the offerer
3. the candidates from the answerer to the offerer.

**Comment by paullouisageneau** [comment]
Great!

> But I dont copy paste the candidates from the offerer to the answerer.

Indeed, in the absence of firewalls, it's sufficient for one side to get the candidates.

**Comment by alicera** [comment]
Does the SDP message can be fixed?
If it can,how to do 

thanks

**Comment by paullouisageneau** [comment]
What do you mean by fixed?

**Comment by alicera** [comment]
I open the offer and get a SDP.
I reopen the offer and get another SDP.
could I generate the same SDP for offer?

**Comment by paullouisageneau** [comment]
No SDP descriptions are dynamic and reflect the current setup connection endpoint.

**Comment by alicera** [comment]
"No SDP descriptions are dynamic "

This mean I run the offer everytime, it will generate the same SDP.

**Comment by paullouisageneau** [comment]
That's not possible to generate the same SDP, since things change between creations of peer connections, for instance the candidate obtained via the STUN server will always be different. Also, the generated connection secrets must be different for instance.

**Comment by alicera** [comment]
Thanks for your answer and I have another problem.
which is the sdp message that is necessary ?
I want to reduce some message for sdp.

Example:
origin
"""
v=0
o=- 2653376230 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=mid:data
a=sctp-port:5000
a=max-message-size:262144
a=ice-options:trickle
a=ice-ufrag:JZ
a=ice-pwd:6S6P3RotLGA
a=setup:actpass
a=tls-id:1
a=fingerprint:sha-256 35:21:41:00:6
"""

After reduce
"""
v=0
o=- 2653376230 0 IN IP4 127.0.0.1
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:JZ
a=ice-pwd:6S6P3RotLGA
a=setup:actpass
a=fingerprint:sha-256 35:21:41:00:6
"""

**Comment by paullouisageneau** [comment]
Don't remove the attribute `a=mid` as it is mandatory and it won't connect without it.

You should also keep `a=sctp-port` and `a=max-message-size` to be fully compatible. In particular, omitting the max message size means the other side can set a lower limit.

I think you can safely remove `a=msid-semantic` as it is optional.
