### ISSUE TITLE
client in example

### ISSUE THREAD

**Issue by alicera** [paullouisageneau/libdatachannel#137]
libdatachannel/examples/client/
I run the project and it show the message.
how to do to run it? 

2020-07-31 17:03:00.400 ERROR [3024] [rtc::TcpTransport::runLoop@310] TCP connect: Connection to localhost:8000 failed
WebSocket failed: TCP connection failed
2020-07-31 17:03:00.401 DEBUG [3016] [rtc::TcpTransport::stop@100] Waiting for TCP recv thread

**Comment by paullouisageneau** [comment]
You need to have at least one signaling server running in background (either the [node.js one](https://github.com/paullouisageneau/libdatachannel/tree/master/examples/web), the [python one](https://github.com/paullouisageneau/libdatachannel/tree/master/examples/signaling-server-python) or the [rust one](https://github.com/paullouisageneau/libdatachannel/tree/master/examples/signaling-server-rust)). Then you may run two clients and give the id of the first one to the second one so they can connect.

**Comment by alicera** [comment]
thanks,
So the client only can type the " id " ,other messages cant be type ,right?

**Comment by paullouisageneau** [comment]
Indeed it's not possible by default, however you could modify it to allow typing messages.

**Comment by alicera** [comment]
I have another problem 
" connectivity.cpp "  and  " signaling-server.py " do the same thing? 
![image](https://user-images.githubusercontent.com/59388989/89024225-5763df80-d357-11ea-8c63-30b157785085.png)

connectivity.cpp do the 1~5
 signaling-server.py  do the 1~4         +     client do the 5

**Comment by paullouisageneau** [comment]
> connectivity.cpp do the 1~5
> "signaling-server.py do the 1 ~ 4 " + " client do the 5 "

You are right, `connectivity.cpp` is a connectivity test acting as two clients with a signaling server.

**Comment by alicera** [comment]
I try to run the web with node server.js 
I cant type the "remote ID" or "message" in the interface 
![image](https://user-images.githubusercontent.com/59388989/89249262-5f1bd080-d644-11ea-81e2-ab0d243d001a.png)

**Comment by paullouisageneau** [comment]
The remote ID input is disable because the WebSocket failed to connect to signaling server. Please check the node server is still running and than it didn't encounter any error. You should actually run the example with npm (`npm install` then `npm start`).

**Comment by alicera** [comment]
How to let C++ connect browser without WebSocket
Do you have any idea ?

**Comment by paullouisageneau** [comment]
You can't establish a WebRTC connection without exchanging the descriptions first. It's necessay for firewall and NAT traversal, and for security verifications.

A WebSocket is not required though. You can pass the descriptions through any channel, for instance you could use HTTP polling or server-sent events.

**Comment by alicera** [comment]
The "libdatachannel/examples/client/" pass the descriptions through websocket, right?
"libdatachannel/examples/signaling-server-python/"  and  "libdatachannel/examples/web/" ,too.

Can the "pass the descriptions through any channel"  consider a Signaling Server?

**Comment by paullouisageneau** [comment]
Yes the examples all use WebSocket, except the copy-paste ones which use the user copy-pasting.

Yes whatever method you use you'll need a server, since the browser can only open connections to a server.

**Comment by alicera** [comment]
I want to create a signaling server for c++ and "libdatachannel/examples/web/" , instead of websocket.
Could you recommend me some method for libdatachannel?

**Comment by paullouisageneau** [comment]
I guess HTTP POST requests for client-to-server and server-sent events (or HTTP long poll) for server-to-client should work nearly as well as websockets, you should look into that.

**Comment by alicera** [comment]
Can a signaling server be create by iceServers?
For example
config.iceServers.emplace_back("stun:stun.l.google.com:19302"); // change to your STUN server

**Comment by paullouisageneau** [comment]
No that's not possible as they don't allow relaying information.

**Comment by alicera** [comment]
1. The "libdatachannel/examples/client/" use the WebSocket + ICE(STUN+TURN) to do 5 ?
2. The "copy-pasting" use the ICE(STUN+TURN) to do 5 ?
![image](https://user-images.githubusercontent.com/59388989/89024225-5763df80-d357-11ea-8c63-30b157785085.png)

**Comment by paullouisageneau** [comment]
Yes both do. ICE is always the first part of the datachannel establishment in 5.

**Comment by alicera** [comment]
I  use "config.iceServers.emplace_back("stun.l.google.com:19302");"  in offerer.cpp
and it show the message 
"""
2020-08-06 19:40:56.989 WARN  [952] [rtc::IceTransport::LogCallback@267] juice: agent.c:1007: STUN message send failed, errno=101
"""

**Comment by alicera** [comment]
If using the websocket as the Signaling Server.
Is it possible to connect two different IP (client A  and client B)?

**Comment by paullouisageneau** [comment]
> 2020-08-06 19:40:56.989 WARN [952] [rtc::IceTransport::LogCallback@267] juice: agent.c:1007: STUN message send failed, errno=101

This is just a warning, probably because IPv6 network is not reachable but the STUN server has an IPv6 address. It should still connect fine.

> If using the websocket as the Signaling Server.
> Is it possible to exchange SDP for two different IP (client A and client B)?

What do you mean ?

**Comment by alicera** [comment]
If using the websocket as the Signaling Server.
Is it possible to exchange SDP for two different IP (client A and client B)?
change to 

If using the websocket as the Signaling Server.
Is it possible to exchange SDP for two client and the clients are Public IP

**Comment by paullouisageneau** [comment]
Sure, that's the principle, you need the signaling server to be hosted on a public IP too and both clients should connect to it to exchange descriptions.

**Comment by alicera** [comment]
Thanks For Your Help

**Comment by paullouisageneau** [comment]
You're welcome, I'm closing this if you don't have other issues with the client.

**Comment by alicera** [comment]
"examples/client"  cant offer to "examples/web"
But "examples/web" can offer to "examples/client "

**Comment by paullouisageneau** [comment]
Could you describe the issue please?

**Comment by alicera** [comment]
ok
