### ISSUE TITLE
example/web

### ISSUE THREAD

**Issue by alicera** [paullouisageneau/libdatachannel#139]
Could you tell me the operation between "example/web" and "example/client"?
I only know open  the "example/web" and then open "example/client".
I can send the ID

1.I find the status.
The "id" of Client Wzf7  and the "id" of Client ab12 are different,but the other are same.

Client Wzf7 is  "example/web"
Client ab12 is  "example/client"

2. I use the "example/web" send the offer to  "example/client" and it can create datachannel
but I use the "example/client" send the offer to  "example/web" and it cant create datachannel

Client Wzf7 << {"id":"ab12","type":"offer","description":"v=0\r\no=- 304338286661193 4 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/ webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:8P\r\na=ice-pwd:vGrh\r\na=ice-options:trickle\r\na=fingerprint:sha-256 50:80:C8:6C:45:57:70:8D:69:D9:49:DD:EE:71:57:82\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}

Client ab12 >> {"id":"Wzf7","type":"offer","description":"v=0\r\no=- 304338286661193 4 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/ webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:8P\r\na=ice-pwd:vGrh\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9D:50:80:C8:6C:45:57:70:8D:69:D9:49:DD:EE:71:57:82\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}

**Comment by alicera** [comment]
2. 
I use the "example/web" send the offer to "example/client" and it can create datachannel
but I use the "example/client" send the offer to "example/web" and it cant create datachannel

A: I get it , it seem to be using ws://192.x.x.x, it will not work.
   if using ws://127.0.0.1 , it will work

**Comment by paullouisageneau** [comment]
> A: I get it , it seem to be using ws://192.x.x.x, it will not work.
> if using ws://127.0.0.1 , it will work

Yes this is because by default the server only listens on `127.0.0.1`. You can change the behavior by changing it to `0.0.0.0` so it listens on every interface here: https://github.com/paullouisageneau/libdatachannel/blob/master/examples/web/server.js#L101

**Comment by alicera** [comment]
It was a great help to me
