### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by flaviu22** [paullouisageneau/libdatachannel#166]
Hello. Is there any documentation for how to compile this library for Windows using CMake (GUI) ?

I saw there is a dependencies section, but I guess is not enough. I put in CMake:

![image](https://user-images.githubusercontent.com/37621568/93453295-2bd68d80-f8e2-11ea-9be6-ee902b56706a.png)
or
![image](https://user-images.githubusercontent.com/37621568/93453148-f92c9500-f8e1-11ea-9589-aa4b2a614a40.png)

but I still have errors:

```
CMake Error at E:/cmake-3.18.1-win64-x64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY)
Call Stack (most recent call first):
  E:/cmake-3.18.1-win64-x64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  E:/cmake-3.18.1-win64-x64/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
  CMakeLists.txt:198 (find_package)

```

**Comment by paullouisageneau** [comment]
I looks like CMake is unable to find OpenSSL libraries. Could you try to set `OPENSSL_ROOT_DIR=D:/Project/openssl`?

**Comment by flaviu22** [comment]
I am using CMake with GUI. And I don't have any OPENSSL_ROOT_DIR variable there:

![image](https://user-images.githubusercontent.com/37621568/93485975-54737d00-f90c-11ea-9c83-07df21ad7a71.png)

Are you talking about OPENSSL_INCLUDE_DIR ? If you do, then I have tried this one too:

![image](https://user-images.githubusercontent.com/37621568/93488108-aa492480-f90e-11ea-8090-1afa1070978c.png)

The same result. Of course, I have OpenSSL directory, at the proper location:

![image](https://user-images.githubusercontent.com/37621568/93488432-0744da80-f90f-11ea-9cf3-5495b7a6ea19.png)

**Comment by paullouisageneau** [comment]
No, not `OPENSSL_INCLUDE_DIR`, but `OPENSSL_ROOT_DIR`, just like the error message suggests.

I don't know about that GUI, but couldn't you add a new variable with the "Add Entry" button?

If not, it's also possible to define an environment variable `OPENSSL_ROOT_DIR` set to `D:/Project/openssl`, on Windows you can do so in the "System Properties" window, "Advanced" tab, then "Environment Variables". You might need to either restart the GUI or reboot.

**Comment by flaviu22** [comment]
I've tried to compile libdatachannel with OpenSSL already compiled (binary), but didn't worked. So, I have to compile OpenSSL from scratch. I guess there will be a real adventure :)

**Comment by paullouisageneau** [comment]
Both OpenSSL pre-build binary and OpenSSL built from scratch should work if you set `OPENSSL_ROOT_DIR`.

**Comment by murat-dogan** [comment]
I am also using openssl pre-built binaries without any problem.

**Comment by Nemirtingas** [comment]
Hi, personally, I used vcpkg to build the dependencies and added the paths to libdatachannel's CMake options by pressing the 'Add Entry' button.
Variables name are:
CMAKE_INCLUDE_PATH=<path_to_vcpkg>/installed/x86-windows-static
CMAKE_PREFIX_PATH=<path_to_vcpkg>/installed/x86-windows-static

That way I can have any library I want static or dynamic and/or statically or dynamically linked against CRT.

**Comment by flaviu22** [comment]
I have added OPENSSL_ROOT_DIR variable using CMake GUI, and I addressed a pre-compiled OpenSSL, and seem to compiled fine:

OPENSSL_ROOT_DIR -> D:/Project/libdatachannel/openssl-1.1.0f-vs2017
