### ISSUE TITLE
SctpTransport::SendCallback

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#168]
Hi,
Looks like your SctpTransport::SendCallback in sctptransport.hpp is missing a `void* ulp_info`

**Comment by paullouisageneau** [comment]
Did you update `deps/usrsctp yourself to `master`? The build is supposed to work only with the correct submodules versions in the tree.

You can reset usrsctp at the proper commit with `git submodule update --recursive`.

**Comment by Nemirtingas** [comment]
Ah yes, I did that. Is it preferable to use the version that is pulled by submodule update or I can use the latest master version ?

**Comment by paullouisageneau** [comment]
It's preferable to use the version pulled by submodule update, since the latest master can break the API or introduce incompatibilities (libdatachannel relies on some more or less hacky mitigations to have usrsctp working properly).
