### ISSUE TITLE
How to create a p2p connection if I don't know the end user ?

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#169]
Hi, I'm quite new in the world of WebRTC, how would you implement a p2p serverless application like a Video Conference where there would be no initiator ?
Currently, I tweaked the example signaling server to return the whole list of clients it knows and send it back to every client that asks for it and then the clients will initiate a connection to the other clients. But I encounter warnings like so:
```
2020-09-20 15:42:57.748 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.751 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.753 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.757 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.789 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.793 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.797 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.799 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.802 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.808 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.850 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.856 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.900 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:933: Got STUN error binding response, code=487
2020-09-20 15:42:57.901 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
2020-09-20 15:42:57.944 WARN  [15736] [rtc::IceTransport::LogCallback@268] juice: agent.c:836: ICE role conflict (both controlling)
```

That means I'm doing it wrong, but what is the right way to do it ?

**Comment by paullouisageneau** [comment]
> Hi, I'm quite new in the world of WebRTC, how would you implement a p2p serverless application like a Video Conference where there would be no initiator ?

Well, you can't really go serverless, since you need a server to initiate the connection. WebRTC connections are negociated, so you need some form of pre-existing signaling channel to send an offer description to the remote peer and get a answer description back. It's often a simple signaling server, but it could be users sending the messages via instant message and it would work the same.

> Currently, I tweaked the example signaling server to return the whole list of clients it knows and send it back to every client that asks for it and then the clients will initiate a connection to the other clients. But I encounter warnings like so: [...]
> That means I'm doing it wrong, but what is the right way to do it ?

The warnings you see most probably come from a peer connection going crazy trying to connect to itself.

Sending a list of known clients from the signaling server is a good approach. For each client excluding yourself, you need to send the local offer description generated by each peer connection after creating a data channel, then receive the answer and set it as remote description. You also need each client receiving an offer to create a peer connection, set the remote offer description, and send the local answer description.

**Comment by Nemirtingas** [comment]
Ok, I was already ignoring myself in the client code, but I also filtered the signal server answer so it only returns other peers ids but I still have the warning messages.

**Comment by paullouisageneau** [comment]
Are you sure you don't set multiple local descriptions or multiple remote descriptions on the same peer connection?

**Comment by Nemirtingas** [comment]
I use the example client, I don't really know what I'm doing right now ;). I just added the signalling list thing:
Both clients are calling createPeerConnection when they get the answer of the signaling server.
```
shared_ptr<PeerConnection> createPeerConnection(const Configuration& config, weak_ptr<WebSocket> wws, std::string const& id)
{
	auto pc = make_shared<PeerConnection>(config);

	pc->onStateChange([id](PeerConnection::State state){
		cout << "State: " << state << endl;
		switch (state)
		{
			case PeerConnection::State::Closed:
			case PeerConnection::State::Disconnected:
			case PeerConnection::State::Failed:
				peerConnectionMap.erase(id);
		}
	});

	pc->onGatheringStateChange(
		[](PeerConnection::GatheringState state) { cout << "Gathering State: " << state << endl; });

	pc->onLocalDescription([wws, id](Description description) {
		json message = {
			{"id", id}, {"type", description.typeString()}, {"description", string(description)} };

		if (auto ws = wws.lock())
			ws->send(message.dump());
	});

	pc->onLocalCandidate([wws, id](Candidate candidate) {
		json message = { {"id", id},
						 {"type", "candidate"},
						 {"candidate", string(candidate)},
						 {"mid", candidate.mid()} };

		if (auto ws = wws.lock())
			ws->send(message.dump());
	});

	pc->onDataChannel([id](shared_ptr<DataChannel> dc) {
		cout << "DataChannel from " << id << " received with label \"" << dc->label() << "\""
			<< endl;

		dc->onClosed([id]() { cout << "DataChannel from " << id << " closed" << endl; });

		dc->onMessage([id](const variant<binary, string>& message) {
			if (!holds_alternative<string>(message))
				return;

			cout << "Message from " << id << " received: " << get<string>(message) << endl;
		});

		dc->send("Hello from " + localId);

		dataChannelMap.emplace(id, dc);
	});

	peerConnectionMap.emplace(id, pc);
	return pc;
};
```
```
	ws->onMessage([&](variant<binary, string> data) {
		if (!holds_alternative<string>(data))
			return;

		json message = json::parse(get<string>(data));

		auto it = message.find("id");
		if (it == message.end())
			return;
		string& id = it->get_ref<string&>();

		it = message.find("type");
		if (it == message.end())
			return;
		string& type = it->get_ref<string&>();

		shared_ptr<PeerConnection> pc;
		if (type == "list")
		{
			it = message.find("peer_ids");
			if (it == message.end())
				return;

			for (json const& _peer_id : *it)
			{
				std::string const& peer_id = _peer_id.get_ref<std::string const&>();
				if (peer_id == localId || peerConnectionMap.find(peer_id) != peerConnectionMap.end()) {
					continue;
				}

				cout << "Offering to " + peer_id << endl;
				auto pc = createPeerConnection(config, ws, peer_id);
				auto dc = createDataChannel(pc, peer_id);
			}
		}
		else
		{
			if (auto jt = peerConnectionMap.find(id); jt != peerConnectionMap.end()) {
				pc = jt->second;
			}
			else if (type == "offer") {
				cout << "Answering to " + id << endl;
				pc = createPeerConnection(config, ws, id);
			}
			else {
				return;
			}

			if (type == "offer" || type == "answer") {
				auto& sdp = message["description"].get_ref<string&>();
				pc->setRemoteDescription(Description(sdp, type));
			}
			else if (type == "candidate") {
				auto& sdp = message["candidate"].get_ref<string&>();
				auto& mid = message["mid"].get_ref<string&>();
				pc->addRemoteCandidate(Candidate(sdp, mid));
			}
		}
	});
```

**Comment by paullouisageneau** [comment]
> Both clients are calling createPeerConnection when they get the answer of the signaling server.

Wait, do you mean that both clients actually offer to the other ? Only one must offer, the other must answer.

```
auto dc = createDataChannel(pc, peer_id);
```
On a side node, this will create the data channel and close it immediately since `dc` will be dropped.

**Comment by Nemirtingas** [comment]
Yes, that why I was asking how to actually offer to peer if you don't know em. I've modified my signalling server like so:
1 connects, signalling server saves him in an array
2 connects, signalling server saves him in the array and is now returning peer2 to peer1,
3 connects, signalling server saves hime in the array and is now returning peer2 and peer3 to peer 1 and peer3 to peer 2.
So only the older peers get to know the new peers and only older peers offer to the other.

Would that be sufficient to fix this kind of use case ?

**Comment by paullouisageneau** [comment]
Yes, it would work. Another possibility would be to send the list of other clients (so older ones) only once when a new client connects.

**Comment by Nemirtingas** [comment]
Oh, ok I see. Thanks for the help, I'm starting to understand how it works.
