### ISSUE TITLE
Logging Library

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#18]
I think we need a logging library for debug & error messages.
I used plog(https://github.com/SergiusTheBest/plog) before.
It is header only and simple.
What you think?

**Comment by paullouisageneau** [comment]
I have never used it but it looks good. If you want to integrate it and replace the few writes to `cerr`, you are welcome to do so. Otherwise, I might do the change in the near future.

**Comment by murat-dogan** [comment]
Is it possible to create a folder named like “third party”?
We can place third party libraries and git sub modules in it.
Also Can we move existing git sub module to in it?
If you want I can do it also or you may advice another way for sub modules.

**Comment by paullouisageneau** [comment]
Good point, I created a new directory `deps` for third party dependencies and moved usrsctp in it. You can add plog in there.

**Comment by paullouisageneau** [comment]
@murat-dogan plog added in https://github.com/paullouisageneau/libdatachannel/pull/24
