### ISSUE TITLE
Is there a reason why this isn't a const std::string & ?

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#180]
Hi, is there a reason why in the ranged for its not a const ref ?

https://github.com/paullouisageneau/libdatachannel/blob/14f8858d3da2e92bbaea92969ecb408aba480671/src/candidate.cpp#L52

**Comment by paullouisageneau** [comment]
Indeed, there is no reason, this is definitely an oversight.

**Comment by paullouisageneau** [comment]
Changed in https://github.com/paullouisageneau/libdatachannel/commit/8cab2b9d879f5fbf5a2b44ee578f0b2fdcd4862d
