### ISSUE TITLE
server.js no longer handles remote clients

### ISSUE THREAD

**Issue by ecotarobles** [paullouisageneau/libdatachannel#181]
Commit c0ea85025b1f708127dc6730e5eb8c9e2088ad1e broke this.  I had been using an old version of server.js that I copied to another host back in August.  When I updated everything after my recent commit to specify websocket and stun servers, I discovered this issue.  It's easy enough for me to revert locally but others may be impacted.  Fix is to just revert that commit.

![With-c0ea85025b1f708127dc6730e5eb8c9e2088ad1e](https://user-images.githubusercontent.com/64188994/94132731-61dabb00-fe68-11ea-9530-ebb783fdd1df.jpg)
![Without-c0ea85025b1f708127dc6730e5eb8c9e2088ad1e](https://user-images.githubusercontent.com/64188994/94132733-61dabb00-fe68-11ea-86b6-2a93f601427f.jpg)

**Comment by paullouisageneau** [comment]
It's not really a bug but a default change. The web signaling server is mostly meant to be run locally or behind a reverse proxy, so for the sake of security I think it is better to listen only on localhost by default.

In practice, you can change `127.0.0.1` to `0.0.0.0` in order to get back the previous behavior. I'll add a parameter to switch between the old and the new behavior in the signaling servers examples.

**Comment by ecotarobles** [comment]
Fair enough.  A parameter to specify the IP address would be sufficient and arguably ideal as it would allow for scripted deployments which is what I'm looking at.
FWIW this entire server.js script is arguably peripheral to libdatachannel just as a stun server is.  I have an additional parameter to the C++ client to make the STUN server optional.  If that's something you're interested in I'll put that change up for review.
Thanks.
--Erik Cota-Robles 

    On Thursday, September 24, 2020, 02:51:07 PM GMT+3, Paul-Louis Ageneau <notifications@github.com> wrote:  
 
 


It's not really a bug but a default change. The web signaling server is mostly meant to be run locally or behind a reverse proxy, so for the sake of security I think it is better to listen only on localhost by default.

In practice, you can change 127.0.0.1 to 0.0.0.0 in order to get back the previous behavior. I'll add a parameter to switch between the old and the new behavior in the signaling servers examples.

**Comment by paullouisageneau** [comment]
PR https://github.com/paullouisageneau/libdatachannel/pull/184 adds parameters to set the port and optionally the host to listen on.

Feel free to submit the additional parameter to the C++ client!
