### ISSUE TITLE
[Discussion] vcpkg port

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#183]
Hi,

Can we talk about vcpkg in this issue ?

I am trying to port your libs libjuice and libdatachannel to vcpkg. I have a working set of portfiles that I now use with vcpkg and I'm setting em up for a merge into the main vcpkg branch.
https://github.com/microsoft/vcpkg/pull/13703
https://github.com/microsoft/vcpkg/pull/13704

1st question: Can you add an option to build the tests in the libjuice CMake file ? BUILD_TESTS to enable/disable juice-tests ?

**Comment by paullouisageneau** [comment]
Sure, this PR adds the `NO_TESTS` (to be coherent with libdatachannel) parameter to libjuice: https://github.com/paullouisageneau/libjuice/pull/37

**Comment by Nemirtingas** [comment]
libjuice looks nice with the:
### Dependencies
None!

**Comment by paullouisageneau** [comment]
Yes indeed, that's pretty cool! Thanks for the suggestion.

I don't know if the pun was intended, since you can use libjuice instead of libnice :laughing:

**Comment by Nemirtingas** [comment]
And thats easier to port to vcpkg ;)

**Comment by paullouisageneau** [comment]
OK, here it is: https://github.com/paullouisageneau/libjuice/releases/tag/v0.5.2

**Comment by Nemirtingas** [comment]
Oh, ok thanks. No hurry, the vcpkg team doesn't seem to look at my changes for now.

**Comment by Nemirtingas** [comment]
Hooray, libjuice is now supported in vcpkg.

**Comment by paullouisageneau** [comment]
Yay, great news! Thank you for handling this.

**Comment by Nemirtingas** [comment]
Guess this discussion is over now. libdatachannel and libjuice has been merged to vcpkg.
We just need to keep it up to date.

**Comment by paullouisageneau** [comment]
Congrats, thank you very much for this!
