### ISSUE TITLE
Access Violation in WebSocket::incoming

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#187]
Stack Trace:

https://github.com/paullouisageneau/libdatachannel/blob/e8a6698abdb69aa75554ea618fb60a4a7e2b1b55/src/tcptransport.cpp#L127
https://github.com/paullouisageneau/libdatachannel/blob/e8a6698abdb69aa75554ea618fb60a4a7e2b1b55/src/transport.hpp#L70
https://github.com/paullouisageneau/libdatachannel/blob/e8a6698abdb69aa75554ea618fb60a4a7e2b1b55/src/wstransport.cpp#L134
https://github.com/paullouisageneau/libdatachannel/blob/e8a6698abdb69aa75554ea618fb60a4a7e2b1b55/src/transport.hpp#L70
https://github.com/paullouisageneau/libdatachannel/blob/e8a6698abdb69aa75554ea618fb60a4a7e2b1b55/src/websocket.cpp#L135-L140

In websocket.cpp, message is nullptr

**Comment by Nemirtingas** [comment]
Thanks !

**Comment by paullouisageneau** [comment]
Good catch, I wonder how I missed this one! The null message is actually used as a connection close signal. For instance, `PeerConnection` reacts to it by closing all data channels.

**Comment by Nemirtingas** [comment]
I hope that when vcpkg will merge your libs, you'll get beteter visibility.
