### ISSUE TITLE
Failed to create a PeerConnection after client reconnects.

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#193]
Hi,

Sometimes, when one of my peer reconnects, it succeed on the initiator side but fails on the receiver side.
Here's the verbose logs, I can see a `DTLS handshake failed` right before receiving the `rtc::PeerConnection::State::Failed` in the onStateChange callback.

[initiator.log](https://github.com/paullouisageneau/libdatachannel/files/5288331/initiator.log)
[receiver.log](https://github.com/paullouisageneau/libdatachannel/files/5288332/receiver.log)

**Comment by paullouisageneau** [comment]
What do you mean by "reconnect"? Opening a new peer connection?

**Comment by Nemirtingas** [comment]
Yes, I force close the client and after it has been detected as closed on the receiver I restart the initiator with the same peerid.

**Comment by paullouisageneau** [comment]
OK, thanks for the logs, it appears the OpenSSL handshake loop quits too early in some cases due to a mistake with the incoming queue. It should be fixed by https://github.com/paullouisageneau/libdatachannel/pull/194

**Comment by Nemirtingas** [comment]
xD I feel like I find all weird bugs.

**Comment by paullouisageneau** [comment]
And that's great :grin:

**Comment by Nemirtingas** [comment]
I'm very thankfull, you ice lib and datachannel are easy to setup and build. Libnice needs glib and many more. All WebRTC tutorials links to chrome impl thatvis even worse to build.
My only concern is C++17 requirement.

**Comment by paullouisageneau** [comment]
Thank you, this is precisely the reason I created these libraries in the first place, I got so frustrated setting up the reference WebRTC implementation. C++17 should be supported nearly everywhere nowadays, and if it's still not somewhere it's just a matter of time before it is.
