### ISSUE TITLE
Is rtc::InitLogger mandatory ?

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#195]
Hi, is the initialization  of rtc::InitLogger mandatory ?
If not, then I've got a nullptr.
Stack trace: 
https://github.com/paullouisageneau/libdatachannel/blob/60d09d5c6f3760913fded9828a311fec4ebb7d72/src/peerconnection.cpp#L266
https://github.com/paullouisageneau/libdatachannel/blob/60d09d5c6f3760913fded9828a311fec4ebb7d72/src/peerconnection.cpp#L111
https://github.com/paullouisageneau/libdatachannel/blob/60d09d5c6f3760913fded9828a311fec4ebb7d72/src/peerconnection.cpp#L318
https://github.com/paullouisageneau/libdatachannel/blob/60d09d5c6f3760913fded9828a311fec4ebb7d72/src/icetransport.cpp#L63

**Comment by paullouisageneau** [comment]
Oh yes, you are right, `rtc::InitLogger()` shouldn't be mandatory, just like the other global functions. Fixed  by https://github.com/paullouisageneau/libdatachannel/pull/196.
