### ISSUE TITLE
[Question] Does it worth it to add an option to disable logs entirely ?

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#197]
Hi,

Do you think it worth the hassle to add an option to disable logs, remove the need to plog and making a bit lighter lib ? (Mostly for release builds)

**Comment by paullouisageneau** [comment]
I don't think it would be worth it. Even if it is true that it would make the release build a bit lighter, I don't like like the idea of needing to switch to a debug build to get logs, as it might make troubleshooting and reporting bugs harder.

**Comment by Nemirtingas** [comment]
Ok fair enought I guess.
