### ISSUE TITLE
'JUICE_LOG_LEVEL_NONE': undeclared identifier

### ISSUE THREAD

**Issue by flaviu22** [paullouisageneau/libdatachannel#204]
I updated my local repository and when I compiled again, I got:

`'JUICE_LOG_LEVEL_NONE': undeclared identifier`

Of course, I have done a seek here, on github, but I didn't found any place where this constant is defined. Do I need another stuff here in order to compiled ? By the way, I have successfully compiled few days ago.

**Comment by paullouisageneau** [comment]
It is defined in the submodule libjuice. You need to update the submodules also after the update:
```
$ git submodule update --init --recursive
```
