### ISSUE TITLE
Replacing the last parameter of C callbacks from pointers to indices (the so called user pointers)

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#206]
The C API is designed as it expects access to instances via indices, such as pc and dc. However, the callbacks return the actual pointers of the corresponding instances, not the indices that are used in other functions. This makes finding which instance was the callback function called very difficult.

I propose replacing, for example
typedef void (RTC_API *rtcDescriptionCallbackFunc)(const char *sdp, const char *type, void *ptr);
to
typedef void (RTC_API *rtcDescriptionCallbackFunc)(const char *sdp, const char *type, int pc);

The direct access to instances would be still possible by adding rtcGetUserPointer(int id). 

While I think this won't harm the library, I wanted to check how you think about this before working on its implementation.

**Comment by paullouisageneau** [comment]
I get your point, my only worry here is that it'll break existing wrappers which will need to be updated.

What is your use case exactly? My stance on the user pointer is that it's an opaque type so you can pass whatever you like in it. If you don't need a user structure on your side, couldn't you just pass the indices as user pointer?

**Comment by hanseuljun** [comment]
First, I misunderstood user pointers as somewhat a generalized version of IDs. Thanks for the clarification.

The use case here is a Unity (C#) application with many PeerConnections. Since Unity only allows static methods as callbacks for C code, to avoid having 20 static methods to support 5 PeerConnections, there should be an identifier coming from callback calls.

Definitely I can use void* to contain the IDs as void* is an address, therefore can contain non-negative integers as IDs. But still this involves casting an integer to void* while the integer is not actually an address, which seems dangerous. Another case of sending the addresses of IDs as UserPointers would allow avoid casting a non-address as an address but this would make code written by a language with garbage collection and its own memory model ugly, so I would like to avoid it.

And going one step forward, I would like to propose changing the order of parameters. As changing "void* ptr" to "int pc" implies imitating instance-based callbacks, and since oftentimes people place the parameter to imitate "this" of the OOP languages the first in these cases,
typedef void (RTC_API *rtcDescriptionCallbackFunc)(int pc, const char *sdp, const char *type);
might be more comprehensible.

I think this order thing comes from how people explain and understand the similarity between a.f(b) and g(a, b) when g is the following:
g(A a, B b) { a.f(b) }

**Comment by hanseuljun** [comment]
Oh I just checked datachannel-rs and it seems like having void* as a UserPointer is actually useful for binding with Rust. I guess I should stick to casting non-memory int as if it is a memory address for now...

**Comment by paullouisageneau** [comment]
Actually it can be handy to bind with any other language that supports pointers since you can just pass the address of your wrapper class, removing the need for a map on the wrapper side to retrieve the callbacks. In your case, I'm not familiar enough with C#, but I think this could be done in your wrapper instead of maintaining an instance map.

**Comment by paullouisageneau** [comment]
What could be done is adding the indexes as first parameter to the callbacks, without removing the user pointer at the end. Like this everybody is happy, it's relatively easy to update the existing wrappers, you just need to declare the new first parameter. What do you think about this compromise?

**Comment by hanseuljun** [comment]
I think that would be perfect! Thanks a lot for the idea and I’ll implement
that soon.
