### ISSUE TITLE
Unable to open DataChannel

### ISSUE THREAD

**Issue by sriramsk1999** [paullouisageneau/libdatachannel#211]
Hello,

I'm trying to make a connection from native code to native code, a server running libdatachannel and a client running [flutter-webrtc-demo](https://github.com/flutter-webrtc/flutter-webrtc-demo) using [flutter-webrtc-server](https://github.com/flutter-webrtc/flutter-webrtc-server) as the signaling server.

I'm using a modified version of the provided example in libdatachannel. Please refer to [my commit](https://github.com/sriramsk1999/libdatachannel/commit/5325ee8b322066f43da676aae7deb703bdd2107a) for the changes. The changes are mostly in the formats of the messages exchanged as a different format is expected by flutter-webrtc-server.

When I run the application, SDP messages are offered and answered, ice candidates are sent from both ends and then .... nothing happens. The `dc->OnOpen()` event is never called and the program crashes with `DataChannel transport is not open` when I try to send a message anyway.
 
The logs of the signaling server, the libdatachannel client and the flutter client are [here](https://github.com/sriramsk1999/libdatachannel/commit/5d0097fa05e7d2828e0ef86f0e595d49901fea3c)

My own hunch is that there might be something wrong with the ICE candidates but I'm not knowledgeable enough about them to know for sure. Please let me know if any other information is required. I'm new to WebRTC and any help would be highly appreciated!

**Comment by sriramsk1999** [comment]
Thanks for the quick response. By removing the call to `send()`, the loop would repeat and candidates would be gathered all over again so by waiting I assume you meant increasing the value of the parameter of `this_thread::sleep_for()`. I increased the value to 60 seconds and there wasn't any change, it neither connected nor failed and after the 60 seconds the whole process repeated. 

As for the flutter client, I missed mentioning this in my first message but I used [this blog](https://larrylisky.com/2020/05/22/implementing-flutter-webrtc-client-and-server/) to set it up, and I have [coturn](https://github.com/coturn/coturn) running on a remote server, which serves as both STUN and TURN I believe?  

Your comment about relay candidates made me check everything on the flutter side so I discarded the changes I'd made with the flutter client and started again. The flutter client sends relay ice candidates now but the libdatachannel client does not from what I could see in the logs. 

The updated verbose logs and the changes I've made to the files are [here](https://github.com/sriramsk1999/libdatachannel/commit/1d2de29bb8dafbe07a2c64fc17e6f407fbb51076)

PS - Do let me know if you would prefer another way of showing the logs.

**Comment by paullouisageneau** [comment]
> Thanks for the quick response. By removing the call to `send()`, the loop would repeat and candidates would be gathered all over again so by waiting I assume you meant increasing the value of the parameter of `this_thread::sleep_for()`. I increased the value to 60 seconds and there wasn't any change, it neither connected nor failed and after the 60 seconds the whole process repeated.

Yes, actually you don't need the loop in your case. If it doesn't do anything and just wait it means you didn't pass either the remote description or at least one remote candidate.

In you case, I think it's because you modified how the id are handled and there is a confusion: the offer peer connection is created with `from_id` equal to `localId`, which stores it it the map at `localId`, but the answer comes back it looks into the map at the remote id (`from` in the message), so it's not found and the remote description and candidates are dropped.

> As for the flutter client, I missed mentioning this in my first message but I used [this blog](https://larrylisky.com/2020/05/22/implementing-flutter-webrtc-client-and-server/) to set it up, and I have [coturn](https://github.com/coturn/coturn) running on a remote server, which serves as both STUN and TURN I believe?

Yes coturn can do both but you need to specify two URLs, one for STUN and optionally one for TURN.

> Your comment about relay candidates made me check everything on the flutter side so I discarded the changes I'd made with the flutter client and started again. The flutter client sends relay ice candidates now but the libdatachannel client does not from what I could see in the logs.

For now libdatachannel doesn't support TURN with libjuice ICE backend so it won't generate `relay` candidates. It will still use relay candidates provided by other clients. If you need TURN support you can also switch to the libnice backend instead of libjuice.

**Comment by sriramsk1999** [comment]
> In you case, I think it's because you modified how the id are handled and there is a confusion: the offer peer connection is created with `from_id` equal to `localId`, which stores it it the map at `localId`, but the answer comes back it looks into the map at the remote id (`from` in the message), so it's not found and the remote description and candidates are dropped.

Thanks for the catch! I fixed that and removed the loop too. Running the program now, I can see that the connection fails from the logs. Hope there's enough info in there to find the issue! [Changes and logs](https://github.com/sriramsk1999/libdatachannel/commit/fb320e0fbd9d65a7b66fd287b40f638319541556)

**Comment by paullouisageneau** [comment]
Hum I see you switched to libnice. Here libnice did not manage to find a working network path. It could be caused by a firewall blocking UDP traffic. What is you network setup for this test?

**Comment by sriramsk1999** [comment]
Both clients are running on my local network, while the signaling and coturn server are running on AWS with all traffic allowed. I don't think it is a firewall issue because both flutter<->flutter with their [signaling server](https://github.com/flutter-webrtc/flutter-webrtc-server) and the provided libdatachannel example with the python signaling server work correctly. What other information did you mean by network setup?

**Comment by paullouisageneau** [comment]
Both clients have local addresses on different ranges (192.168.0.110 and 10.0.2.16). Are you sure they are indeed on the same local network?

**Comment by sriramsk1999** [comment]
Ah okay I think I know why that's the case. The flutter client is running on an emulated mobile device which might be the cause of the different range. I will try with an actual phone on the same network and report back.

**Comment by sriramsk1999** [comment]
It worked! :) Looks like there might be a problem with how the emulated IP address is translated. Thank you so much for the help and the quick responses.
