### ISSUE TITLE
PeerConnection does not update Gathering State when not a shared_ptr

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#212]
Hi Paul,
I have a class that has an instance of `rtc::PeerConnection`. When it is initialized as a shared_ptr, `rtc::PeerConnection::gatheringState()` is updated correctly (and the relevant callbacks are made). However, when it is initialized as a unique_ptr, or not a pointer at all, it does not update. Any idea why this is the case?

**Comment by paullouisageneau** [comment]
`PeerConnection` is a `std::enable_shared_from_this` so it must be held using a `shared_ptr`. It's a bit of a limitation that could be solved by wrapping the classes, however it would be quite a big change.

**Comment by stazio** [comment]
:(

**Comment by paullouisageneau** [comment]
@stazio Good news, this is now possible with the refactoring in https://github.com/paullouisageneau/libdatachannel/pull/347
