### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by gerald-dotcom** [paullouisageneau/libdatachannel#214]
Is there any performance improvement of WASM version of this lib compared to plain JavaScript data channel API?

I'm talking about Browser env not NodeJS

**Comment by paullouisageneau** [comment]
The library does not have a WASM version. [datachannel-wasm](https://github.com/paullouisageneau/datachannel-wasm) is a wrapper to expose a compatible API to WASM code in the browser. It allows to write code that can be compiled both for browsers (with the wrapper) and native (with libdatachannel).

**Comment by gerald-dotcom** [comment]
Yeah so what about datachannel-wasm  then?

**Comment by paullouisageneau** [comment]
> datachannel-wasm is a wrapper to expose a compatible API to WASM code in the browser. It allows to write code that can be compiled both for browsers (with the wrapper) and native (with libdatachannel).

datachannel-wasm translates the JavaScript API into the same C++ API as libdatachannel for WASM code running in the browser.

**Comment by gerald-dotcom** [comment]
Why can't you answer a question direct!!

Wasting my time.

**Comment by paullouisageneau** [comment]
Please don't be rude. Since I told you twice datachannel-wasm only wraps the JavaScript API, it should be pretty obvious you won't get any performance improvement.

**Comment by gerald-dotcom** [comment]
https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%F0%9F%8E%89/

**Comment by gerald-dotcom** [comment]
"If you can write your code so that JavaScript is always passing the same types to the same WebAssembly exported function, then your calls are going to be very fast. In fact, these calls are faster than many JavaScript to JavaScript calls."

**Comment by paullouisageneau** [comment]
If you read my messages you would understand that datachannel-wasm actually calls the Javascript API under the hood. You will get roughly the same performance than when you call the Javascript API directly.
