### ISSUE TITLE
SRTP detection

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#217]
Hi,

I was wondering, would you like to add an OPTION for SRTP instead of looking for it ? In case of vcpkg, one could use SRTP for something else than libdatachannel but libdatachannel will link and use it anyway because it doesn't ask for the user if he needs it.

https://github.com/paullouisageneau/libdatachannel/blob/2eb523e2eac2ce646ea66f886925f7516a280add/CMakeLists.txt#L165-L166

**Comment by paullouisageneau** [comment]
I could add an option, however I don't really get the use case for it for now. libdatachannel will link it if it is there but it won't be used if you don't attempt to explicitly negotiate media, so basically it doesn't change anything for the user, the interface stays the same. If you really don't want the library to be linked for some reason, you can still disable it with `-DCMAKE_DISABLE_FIND_PACKAGE_SRTP=1`. Am I missing something?

**Comment by Nemirtingas** [comment]
Its just a though. If it doesn't make sense to add it, then don't.

**Comment by paullouisageneau** [comment]
Thinking about it, it can indeed be useful if your project needs media support, in that case you want libdatachannel to compile with SRTP support or fail. I'll add a `USE_SRTP` flag, if unspecified it'll fall back to autodetection.

**Comment by Nemirtingas** [comment]
Hmm, ok. It would also making libdatachannel not linking against libSRTP if its available but not used.

**Comment by paullouisageneau** [comment]
Yes, it'll allow force enable or force disable basically.

**Comment by Nemirtingas** [comment]
If you add it then thanks. That will simplify the support of vcpkg. I don't know why, but the maintainers want that features you provide need to be handled in the port file. I don't know why, I used the feature to add a dependency on libSRTP if asked by the user.
