### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#223]
I am testing memory usage of the library.
I modified `benchmark.cpp` file like this;
```
#ifdef BENCHMARK_MAIN
int main(int argc, char **argv) {

	try {
		for (int i = 1; i <= 10; i++) {
			cout << "Test #" << i << std::endl;
			size_t goodput = benchmark(30s);
			if (goodput == 0)
				throw runtime_error("No data received");

			if (i < 10) {
				cout << "Waiting 15 sec for next test..." << std::endl;
				this_thread::sleep_for(15s);
			}
		}

		return 0;

	} catch (const std::exception &e) {
		cerr << "Benchmark failed: " << e.what() << endl;
		return -1;
	}
}
#endif
```

Basically I am running benchmark test in a loop to see memory usages.
Here is what I noted;
```
Test#      After Test Memory Usage (KB)
--------     ------------------------------------------
1                19028
2                32900
3                32156
4                48000
5                43900
6                51700 
7                53500
8                62216
9                45860
10               62190
```

It doesn't seem normal.
What you think?

**Comment by paullouisageneau** [comment]
Do you measure the memory usage from the process virtual memory size ? If so it doesn't look weird to me as you have to take into account the dynamic memory allocation layer.

The library and its dependencies will malloc and free an important number of chunks in the heap, however it doesn't mean that the dynamic memory allocation mechanism will free everything at the lower level between tests, as it depends on memory fragmentation for instance.

To precisely keep track of what is actually allocated by the library, you could use valgrind.

**Comment by doganmurat** [comment]
Sorry for late reply.
You are right. 

I checked with valgrind & everything seems ok.

**Comment by murat-dogan** [comment]
Sorry for late reply.
You are right.

I checked with valgrind & everything seems ok.
