### ISSUE TITLE
Allow Renegotiation of Media

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#225]
Hi @paullouisageneau, would it be possible for you to add the ability to do renegotiation's? I can't merge #176 with master because it breaks my (admittedly janky) implementation of renegotiation's for media and I would like for renegotiation's to have first-class support.

**Comment by paullouisageneau** [comment]
Yes it's possible, however it needs some rather extensive modifications to be done properly, like the adding the signaling state, so I hope it won't create to much merging difficulties for you.

**Comment by paullouisageneau** [comment]
Renegociation for data channels and tracks is implemented in https://github.com/paullouisageneau/libdatachannel/pull/226
