### ISSUE TITLE
Standalone C/C++ Signaling SERVER?

### ISSUE THREAD

**Issue by jacobfriedman** [paullouisageneau/libdatachannel#229]
Bonjour Paul,

Am I correct in saying that the only signaling servers are in python/rust/node? That is, there's no barebones c/c++ signaling server? Just wondering as I'm trying to contain the build / export as much as possible and keep it lean.

FYI- I'm on the path towards integrating this library with SWI-Prolog (including the WASM version) and am making some headway. Thank you for the effort and library.

**Comment by paullouisageneau** [comment]
Bonjour !

Indeed, there is no C++ signaling server in the repository. The only reason is that it would require including an external WebSocket server implementation. Extending the ẀebSocket client implementation of the library with server support would also be doable, however it is currently not designed to scale.

> FYI- I'm on the path towards integrating this library with SWI-Prolog (including the WASM version) and am making some headway. Thank you for the effort and library.

That sounds pretty interesting, do you have a particular use case in mind?

**Comment by jacobfriedman** [comment]
Yeah! I'll be working with a paxos library to make a p2p logic engine (at
the moment, for an inventory system). All will be open sourced and
documented.  Down the road a conceptual structure will be implemented. From
there - the sky's the limit...

J

**Comment by gerald-dotcom** [comment]
You can use existing WebSockets libs for C++ for Signaling!!

**Comment by jacobfriedman** [comment]
Good to know! Thank you :)

**Comment by paullouisageneau** [comment]
I'm closing this, please re-open if needed.

**Comment by paullouisageneau** [comment]
I'm adding a WebSocket server in addition to the client, as it doesn't require a lot of additional implementation and I need it for another project. However, as the server re-uses the existing stack, it is thread-based and therefore not designed for any large-scale deployment.
