### ISSUE TITLE
ICE Does not begin to negotiate until the peer offers candidates

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#232]
This regression is new and I am not exactly sure why it is happening. IceTransport won't start doing anything when there are only  `SendOnly` tracks until the receiver offers candidates to the sender.

**Comment by paullouisageneau** [comment]
Are you sure this is new? `IceTransport` needs candidates to start the discovery process, either in the description or trickled afterwards.

**Comment by stazio** [comment]
Up until now I did not need to have the browser provide any candidates (neither in the SDP, nor as trickle candidates).

**Comment by paullouisageneau** [comment]
Oh OK, you mean one side has remote candidates but the other has not. Indeed, it should start.

Hopefully https://github.com/paullouisageneau/libdatachannel/pull/234 solves you issue.

**Comment by paullouisageneau** [comment]
Did you get to test with #234 ?

**Comment by stazio** [comment]
Yep, and it works! Thanks!
