### ISSUE TITLE
Out of band negotiated DataChannels

### ISSUE THREAD

**Issue by dbotha** [paullouisageneau/libdatachannel#233]
Hi Paul-Louis,

Using webrtc in the browser I am able to pass a `negotiated: true` flag to the [RTCPeerConnection.createDataChannel](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel#RTCDataChannelInit_dictionary) function which allows me to explicitly create the desired RTCDataChannel's on both sides. 

Are such out of band negotiated DataChannels supported by _libdatachannel_ or does the answering side always need to listen for channels created by the offerer like so: 

### Only Offerer

```
auto dc = pc->createDataChannel("test");
```

### Only Answerer
```
shared_ptr<rtc::DataChannel> dc;
pc->onDataChannel([](shared_ptr<rtc::DataChannel> incoming) {});
```

Kind regards,

Deon

**Comment by paullouisageneau** [comment]
Hi Deon,

Out-of-band Data Channels are not supported for now but they would be a good enhancement to match the browser API.

**Comment by dbotha** [comment]
Thanks Paul-Louis!

**Comment by paullouisageneau** [comment]
Out-of-band negotiated Data Channels are added to the C++ and C API in  https://github.com/paullouisageneau/libdatachannel/pull/245
