### ISSUE TITLE
What's this used for?

### ISSUE THREAD

**Issue by gerald-dotcom** [paullouisageneau/libdatachannel#243]
On your client example, I see below line

```
shared_ptr<PeerConnection> createPeerConnection(const Configuration &config,
                                                weak_ptr<WebSocket> wws, string id);
```

But it's hard to understand what it does as the PeerConnection class only has `PeerConnection(const Configuration &config)`

`Line 207` seems indicate some sort of function around the smart pointer but not sure if it's possible to do with smart pointers. 

FYI, `using namespace std;` is a bad practice.

**Comment by paullouisageneau** [comment]
This is a function declaration for the utility function `createPeerConnection` defined line 107, allowing to call the function in the following code before its definition. It returns a `shared_ptr<PeerConnection>` but is unrelated to the `PeerConnection` constructor.

> FYI, using namespace std; is a bad practice.

Indeed, that's exactly why it's not used in the library code base, only in the short and self-contained examples. I would suggest that you first finish learning the language before making such rude comments.

**Comment by gerald-dotcom** [comment]
I realized it's an actual function on yesterday. 

Excuse me, It's not appropriate to use namespace std even in small examples. Due to lack of std:: in your examples, it took me a lot of time to build mental model around your examples. 

"first finish learning the language before making such rude comments"

Now that's rude. My issue isn't. I know C++ quite well and likewise many people I too still learning many parts of it but at least I get code standards right without being lazy.

**Comment by paullouisageneau** [comment]
Please keep in mind the code is voluntary work provided free of charge in the hope that it will be useful. You are welcome to open a PR to upgrade parts of it you think are below standard.

**Comment by gerald-dotcom** [comment]
It's not just me, everyone thinks so. You can post this on Stackoverflow's Code Review section and see their feedbacks.

I understand this is voluntary work but most of open source C++ projects I found never had used this kind namespace thing ever in their examples. Voluntary work without quality is bad. 

I can't open PR as my experience with your library is low and if I become more comfortable then you can count me on future for this PR.

**Comment by paullouisageneau** [comment]
https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice

> The problem with putting using namespace in the header files of your classes is that it forces anyone who wants to use your classes (by including your header files) to also be 'using' (i.e. seeing everything in) those other namespaces. However, you may feel free to put a using statement in your (private) *.cpp files.

> Short version: don't use global using declarations or directives in header files. Feel free to use them in implementation files.

> Here's what Herb Sutter and Andrei Alexandrescu have to say about this issue in C++ Coding Standards: "[...] Despite repeated assertions to the contrary, namespace using declarations and directives are not evil and they do not defeat the purpose of namespaces. Rather, they are what make namespaces usable."

Anyway, like I said, contributions are welcome.

**Comment by gerald-dotcom** [comment]
`"you may feel free to put a using statement in your (private) *.cpp files."
`
That's it. Your open source project isn't private rather a public. It hurts readability when you use using statement on a public project.

Like the comments section says, it's akin to goto and evil. 

I can't help but even "Nazis" can find answers that please their mind on the Internet.

**Comment by paullouisageneau** [comment]
Public in the context means not exposed to external code, contrary to code in header files for instance. Other comments are pretty clear about the distinction.

> I can't help but even "Nazis" can find answers that please their mind on the Internet.

Please stop insulting people and stay civil.
