### ISSUE TITLE
How to set maxMessage size?

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#244]
On `sdp` description we have maxMessage option. How to change that?
Should we change it before creating datachannel?

**Comment by paullouisageneau** [comment]
You can't change the local maximum dynamically. It is set at compile time here:
https://github.com/paullouisageneau/libdatachannel/blob/973f58ec8b2c17d51dc56e5c545131896cd04837/include/rtc/include.hpp#L67

You can modify it, however higher values might require increasing SCTP buffer sizes to work correctly: https://github.com/paullouisageneau/libdatachannel/blob/973f58ec8b2c17d51dc56e5c545131896cd04837/src/sctptransport.cpp#L183

**Comment by murat-dogan** [comment]
Thanks

**Comment by juslesan** [comment]
Hi,

I'm posting this here as it seems appropriate. I'm currently in a place where I would need to implement functionality to fragment JSON type messages in the application layer to send large messages. The current max message size 256kb ends up being too low in many cases. Would it be possible to make the values for setting max messages size and sctp buffer size configurable?

Thanks!

**Comment by paullouisageneau** [comment]
@juslesan The current limit is arbitrary and mostly here for compatibility. If retro-compatibility is not an issue, it should be possible to allow large messages while keeping a decent SCTP buffer size, the only drawback being that it will break proper multiplexing if you use multiple data channels: https://blog.mozilla.org/webrtc/large-data-channel-messages/

I have to investigate a bit but support for large messages should require only a few modifications.

**Comment by juslesan** [comment]
Hi, has there been any progress on making the larger messages sizes possible?

**Comment by paullouisageneau** [comment]
It appears it's not doable as I thought with usrsctp. I guess I'll just add a setting in the configuration which will setup the buffer size accordingly.

**Comment by paullouisageneau** [comment]
The PR #386 adds a setting for max message size.

**Comment by juslesan** [comment]
Great, Thanks!
