### ISSUE TITLE
Run this library on arm platform with c++11 compile

### ISSUE THREAD

**Issue by miaovictor** [paullouisageneau/libdatachannel#257]
Hi:

I want run this library on arm platform, but the cross compile tool only support c++11, the libdatachannel is the best choose for me, do you have plan to support c++11?

**Comment by murat-dogan** [comment]
You can compile for ARM by using cross compile tools easily.
No need to change anything on `libdatachannel`.

Just create a cmake toolkit with your arm tools.

**Comment by paullouisageneau** [comment]
Sadly C++17 is necessary, and due to the numerous features of C++17 that are required there is no plan to support C++11.

**Comment by murat-dogan** [comment]
I misunderstood the issue. Sorry @miaovictor .

**Comment by miaovictor** [comment]
> Sadly C++17 is necessary, and due to the numerous features of C++17 that are required there is no plan to support C++11.

ok，thanks

**Comment by Nemirtingas** [comment]
I'm porting this lib to cxx11 thanks to boost: https://github.com/Nemirtingas/libdatachannel/tree/cxx11
I have 1 compile error left: 
```
libdatachannel\src\certificate.cpp(255,38): error C2672: 'rtc::ThreadPool::enqueue' : fonction correspondante surchargée introuvable
libdatachannel\src\certificate.cpp(255,81): error C2893: La spécialisation du modèle de fonction 'std::future<_Select_invoke_traits<std::decay<_Ty>,decay<_ArgTypes>::type...>::type> rtc::ThreadPool::enqueue(F &&,Args &&...)' a échoué
libdatachannel\src\threadpool.hpp(56): message : voir la déclaration de 'rtc::ThreadPool::enqueue'
libdatachannel\src\certificate.cpp(255,81): message : Avec les arguments template suivants :
libdatachannel\src\certificate.cpp(255,81): message : 'F=rtc::certificate_ptr (__cdecl *)(std::string)'
libdatachannel\src\certificate.cpp(255,81): message : 'Args={std::string &}'
```

**Comment by paullouisageneau** [comment]
@Nemirtingas Interesting! I'm a big puzzled by the error, the call seems legit. Did you alter the definition of `invoke_future_t`?

**Comment by Nemirtingas** [comment]
It seems legit to me too. Its the standard definition by MSVC community 2019.
I can't find the error for now.

**Comment by Nemirtingas** [comment]
Here, fixed. It compiles on cxx14. I don't know if it works tho 😆
