### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alicera** [paullouisageneau/libdatachannel#258]
-- Performing Test has_wno_unreachable_code - Success
-- Performing Test has_wstrict_prototypes
-- Performing Test has_wstrict_prototypes - Success
-- Compiler flags (CMAKE_C_FLAGS):  -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Wunreachable-code -Winit-self -Wno-unused-function -Wno-unused-parameter -Wno-unreachable-code -Wstrict-prototypes -Werror
-- Performing Test has_wno_address_of_packed_member
-- Performing Test has_wno_address_of_packed_member - Success
-- Performing Test has_wno_deprecated_declarations
-- Performing Test has_wno_deprecated_declarations - Success
CMake Error at CMakeLists.txt:118 (target_compile_options):
  Cannot specify compile options for target "usrsctp-static" which is not
  built by this project.

CMake Error at CMakeLists.txt:121 (add_library):
  add_library cannot create ALIAS target "Usrsctp::UsrsctpStatic" because
  target "usrsctp-static" does not already exist.

-- Could NOT find SRTP (missing: SRTP_INCLUDE_DIRS SRTP_LIBRARIES HAVE_SRTP_SRTP_H SRTP_VERSION) 
-- LibSRTP NOT found, compiling WITHOUT media transport
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")  
-- Using the single-header code from /tmp/libdatachannel/deps/json/single_include/
-- Configuring incomplete, errors occurred!

**Comment by paullouisageneau** [comment]
Did you update `deps/usrsctp` to a more recent version? The submodule needs to be at the right commit to compile properly. You can update the submodules with:
```
$ git submodule update --recursive
```

**Comment by alicera** [comment]
So if I use v0.9.4, it will fail.

**Comment by paullouisageneau** [comment]
Does it also fail after the submodule update?

**Comment by alicera** [comment]
thanks you,

solved by
https://github.com/paullouisageneau/libdatachannel/issues/258#issuecomment-727818012
