### ISSUE TITLE
SSL certificate file

### ISSUE THREAD

**Issue by alicera** [paullouisageneau/libdatachannel#259]
how to create  SSL certificate file?

**Comment by paullouisageneau** [comment]
What do you mean? The library do not use certificate files.

**Comment by alicera** [comment]
I want to use ssl for the example
https://github.com/paullouisageneau/libdatachannel/blob/0fcafad9c72c71de04ca3dfe7554e4ac8cb4f7a7/examples/signaling-server-python/signaling-server.py#L72

**Comment by paullouisageneau** [comment]
Oh, OK. This is a bit out of scope here, but you have two choices:
- [Generate a self-signed certificate](https://dev.to/techschoolguru/how-to-create-sign-ssl-tls-certificates-2aai). You'll have to manually accept the certificate in browsers, and [disable certificate verification in libdatachannel](https://github.com/paullouisageneau/libdatachannel/blob/0fcafad9c72c71de04ca3dfe7554e4ac8cb4f7a7/test/websocket.cpp#L41). If you need your certificate for a private host (not public facing) you must use this method.
- Obtain a signed certificate from a certificate authority of your choice. You'll need to pay for it, or you can use the [Let's Encrypt framework](https://letsencrypt.org/).

**Comment by paullouisageneau** [comment]
I'm closing this as it is out of the library scope.
