### ISSUE TITLE
Use libdatachannel from another project

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#26]
I am trying to integrate libdatachannel to a project.
My own project is also using cmake.

I added this;
```add_subdirectory(third-party/libdatachannel)```

While compiling I got;
```[build] libdatachannel.so.0.2.1: undefined reference to `pthread_atfork'```

We need to add Thread as an requirement to libdatachannel.

**Comment by paullouisageneau** [comment]
Indeed, the Threads package was missing.

**Comment by murat-dogan** [comment]
Resolved with #27
