### ISSUE TITLE
Renegotiation Causes candidates to be re-added

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#260]
Last one, I think! When you renegotiate the same candidates are duplicated in the SDP. This goes a bit deeper because I am also getting libjuice errors about reaching maximum numbers of candidate pairs.

Thank you for all your hard, and speedy, work!

**Comment by paullouisageneau** [comment]
You get the local description with the `localDescription` getter rather than the callback, right? I seems I forgot to handle that possibility.

**Comment by paullouisageneau** [comment]
Indeed, I forgot to handle candidates that could be re-sent multiple times.

**Comment by stazio** [comment]
This issue has exposed an deadlock. I don't know why or how to reproduce it, but sometimes if I join or leave from a browser too quickly, `agent.c:270` blocks forever.

**Comment by paullouisageneau** [comment]
I'm a bit in the dark here but releasing the remote description lock earlier should fix it (keeping it was really clumsy): https://github.com/paullouisageneau/libdatachannel/pull/263

**Comment by stazio** [comment]
I'm impressed that you think you have a fix for something as vauge as that. I wasn't expecting to have much come out of what is essentially, "sometimes it doesn't work", but I should know better by now. Thank you!

**Comment by paullouisageneau** [comment]
Ha ha well, you told me on what lock it can get stuck, and just near what I modified there is some clumsy code locking that mutex without releasing another one. This looks like an ideal culprit to me!
