### ISSUE TITLE
SRTP Drops first packet if it is a new SSRC

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#286]
This issue is opened in response to #285. There is no guarantee made by libsrtp that the data and size of the media is safe when srtp fails. That means, that process of `srtp_unprotect`, if the error is `srtp_err_status_no_ctx`, add the SSRC and try again is not guaranteed to be safe. Although, the code does not say so for this specific error, the documentation explicity says so for all errors.

**Comment by stazio** [comment]
I think the threading issue might actually be why each stream had to be set individually in SRTP. @paullouisageneau could you open a new PR undoing that and I can test it? I tried to do it myself but couldn't get it to work.

**Comment by paullouisageneau** [comment]
@stazio You mean reverting to the libsrtp settings with the wildcards inbound + outbound, right?

**Comment by stazio** [comment]
Correct.

**Comment by paullouisageneau** [comment]
OK I'll do it!

**Comment by paullouisageneau** [comment]
It's done in https://github.com/paullouisageneau/libdatachannel/issues/286

**Comment by paullouisageneau** [comment]
It's done in https://github.com/paullouisageneau/libdatachannel/pull/290

**Comment by stazio** [comment]
Fixed by #290.
