### ISSUE TITLE
Must be compiled in C++17 or above?

### ISSUE THREAD

**Issue by asbai** [paullouisageneau/libdatachannel#292]
We hope to use this library on an embedded toolchain that only supports C++11. But I see the following code in your example:
```C++
dc->onMessage([](variant<binary, string> message) {
     if (holds_alternative<string>(message)) {
         cout << "Received: "<< get<string>(message) << endl;
     }
});
```
Does this mean that it can only be compiled on the C++17 toolchain?

Thanks :-)

**Comment by asbai** [comment]
Sorry, I did not see that you have pointed this out in the first sentence of README.md.

**Comment by paullouisageneau** [comment]
Indeed, it requires C++17. However, @Nemirtingas attempted to port it to C++14, see https://github.com/paullouisageneau/libdatachannel/issues/257

**Comment by asbai** [comment]
OK, Thanks :-)
