### ISSUE TITLE
Segfault when closing a Track

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#294]
I only managed to see this once before. I sometimes get a segfault right after I close a Track and it happens in `rtc::PeerConnection::getMidFromSssrc` on line 737 on commit 7751a9b inside of the unordered map. `mState` is `Closed` and the logs say that everything has closed. I know this isn't really useful, and I spent a couple minutes looking for it myself, but I don't see a reason why it would segfault where it does.

**Comment by paullouisageneau** [comment]
Good catch: the only place where `getMidFromSsrc()` is `forwardMedia()`, which is erroneously bound with `std::bind` instead of the weak bind trick (since the `PeerConnection` might be destroyed while the transport is still closing).
