### ISSUE TITLE
Too Much Logging

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#296]
When entering failure states, there is too much logging happening and causing a further degredation of the application. Even if ideally the developer was to create a perfect application, the peer, whether malicious or not, can still trigger a lot of logs at reasonable log levels such as WARNING. Ideally, there should be no logging performed on the processing thread.
I was thinking about going through and changing all of logs messages that are present in the real-time paths and making them at least `PLOG_DEBUG`. I wanted to get your opinion first if you had a better solution.

**Comment by paullouisageneau** [comment]
What failure states are you speaking about? I guess you are refering to situations where there is an SRTP issue and each message triggers a warning, right?

I think a good number of them can be changed to PLOG_DEBUG, another possibility for the most critical warnings is to have a local define that would call PLOG_WARNING only for the first call for a given instance, then PLOG_DEBUG (this can be achieved easily with `std::call_once`).

**Comment by stazio** [comment]
I like the way Janus does it where they count the number of errors and report it at an interval.

**Comment by paullouisageneau** [comment]
It sounds good too. How is this achieved, I guess the first line is printed, and the following identical lines are cached for a given duration, right?

**Comment by stazio** [comment]
Just looked at the code: `JANUS_LOG(LOG_ERR, "[%"SCNu64"] Got %d SRTP/SRTCP errors in the last few seconds (last error: %s)\n", handle->handle_id, handle->srtp_errors_count, janus_srtp_error_str(handle->last_srtp_error));`. It's been a while since I used Janus, must have forgotten how those logs look. Apparently when debugging it prints every error.

I'd rather have those print on their own thread. Does libdatachannel have a free thread that this could be used.

**Comment by paullouisageneau** [comment]
That could be good. 

You can delegate a task to libdatachannel's threadpool with `ThreadPool::Instance().enqueue()`, but for now it has no support for scheduling a task at a given time and I think that's what you'd want here.

**Comment by paullouisageneau** [comment]
I quickly added a `schedule()` method in https://github.com/paullouisageneau/libdatachannel/pull/300
