### ISSUE TITLE
Are there are any drawbacks of calling dc->onMessage multiple times?

### ISSUE THREAD

**Issue by jeffRTC** [paullouisageneau/libdatachannel#297]
See this pseudo code and it can have multiple registrations to onMessage callback for same DC

```
while(true) {
     variable response := pull request from somewhere
     variable channel_id := extract Channel ID from response

     DC := lookup map using variable channel_id
     DC->onMessage([] .......
}
```

My heart tells me it can have issues. What do you think?

**Comment by jeffRTC** [comment]
Maybe you can add some sort of internal tracker that prevent multiple onMessage callback registrations same DC?

I really don't have any other way in this situation.

**Comment by paullouisageneau** [comment]
Don't worry, multiple calls to `onMessage` will always replace the existing callback in a thread-safe manner, so you won't have issues. Other callback also behave the same way.

**Comment by jeffRTC** [comment]
Duh

I have a Mutex Lock Guard inside onMessage

As you know, Mutex has to be awaiting till the other local release the Mutex.

If you replace existing callback with another, what happen to the Mutex and the overall I/O happen to be over there?

It seems I am running into deadlock on my side. This crazy thing happen only inside this callback. I assume it because the replacement. 

Yeah Yeah I have scoped it properly in RAII style

**Comment by paullouisageneau** [comment]
A call to `onMessage()` won't interrupt the existing callback if it is running. It will wait for the existing callback to return first, then replace the existing callback with the new one and return. This is thread-safe, but you must still pay attention not to create deadlocks from your own code, for instance you must not lock the same mutex while calling `onMessage()` and in the callback itself.

**Comment by jeffRTC** [comment]
I'm not calling onMessage inside callback itself rather a thread.

I will try to create a minimal example to reprod this

**Comment by paullouisageneau** [comment]
It's still the same principle, you must unlock any mutex you hold before calling `onMessage`.

**Comment by jeffRTC** [comment]
I'm using STD Lock Guard in RAII style so it should be unlocked.

**Comment by jeffRTC** [comment]
I need to find a time to give u example lol

**Comment by paullouisageneau** [comment]
It depends, it's unlocked only if the lock guard is not in the same scope as the `onMessage()`call.

**Comment by jeffRTC** [comment]
```
class TCP
{

public:
    zmq::context_t context;

public:
    std::mutex guard;
    zmq::socket_t socket;
   
..........
..........
}

void worker(TCP &guard, RTCTransport &channels) {
     ..........
     ..........

     dc->onMessage([&](const std::variant<rtc::binary, std::string> &reply) {
                // Scoped
                {
                    std::lock_guard<std::mutex> lock(guard.guard);
                }
     }
}

int main() {
      TCP network;
      RTCTransport RTCInterface;
      
      ............
      ............
      
      std::thread(std::ref(network), std::ref(RTCInterface));

      ..........
}
```

**Comment by paullouisageneau** [comment]
You said that you called `onMessage()` inside the callback, where is it in the code? Is the mutex locked elsewhere, like in `worker()`?

**Comment by jeffRTC** [comment]
I said I called it inside a thread.

**Comment by jeffRTC** [comment]
Of course, In 

```
     ..........
     ..........
```

parts has some extra code that pull messages from ZMQ and if there is message avail, I invoke dc->onMessage

The pulling parts too has a extra Mutex guard (RAII style)

**Comment by jeffRTC** [comment]
I had a chat with ZMQ dev an hour ago, he said that is expected since there is always some thread that is going to block holding the lock waiting for the next message, which will block all other threads that try to send.

**Comment by paullouisageneau** [comment]
OK, then you just have ensure the mutexes are unlocked before calling `onMessage()`. If you can't do it with proper scopes, you might use a `std::unique_lock` and manually unlock it before the call.

**Comment by jeffRTC** [comment]
I am using fake scopes to make sure they are getting unlocked but the problem now is more like backpressure thing. 

Fake scopes means scope with scope.

**Comment by jeffRTC** [comment]
Well, I am going to use conditional variables to solve this. Closing this

**Comment by jeffRTC** [comment]
Removed all Mutexs. Yes, that was the solution.

Socket is thread safe if I pass at thread initialization else I shall use Mutex to guard socket.

**Comment by jeffRTC** [comment]
:D
