### ISSUE TITLE
Video call between native c++ apps

### ISSUE THREAD

**Issue by nihalar** [paullouisageneau/libdatachannel#301]
Hello,

I am creating a video call app in C++ (without any browser involvement). I would like to know if this package can be used for real-time video and audio transmission (video call) between native c++ applications?

Thank You.

**Comment by paullouisageneau** [comment]
It can be used for native to native video call, however you'll need to handle the video encoding and decoding externally.

You should look into `examples/media` to see how the decoding can be achieved and you might need #291 if you want to stream H264 video.

**Comment by nihalar** [comment]
In examples/media/main.cpp (line 76), instead of sending it as a RTP packet to the socket, how would I play the rtp::binary directly as video (using opencv, or any other library)

**Comment by LeoNavel** [comment]
Take a look at *examples/streamer* example. It shows how to send raw h264 NAL units and opus samples. It may help you.

**Comment by paullouisageneau** [comment]
I'm closing this, please reopen if needed.
