### ISSUE TITLE
PeerConnection sometimes fails to establish local connection

### ISSUE THREAD

**Issue by dbotha** [paullouisageneau/libdatachannel#308]
Hi Paul-Louis,

I hope you are well :)

I'm using libdatachannel to facilitate networking in a realtime multiplayer game. When a player hosts a game they run both the client & server code within the same process & thread i.e. the architecture is client-server, the host just happens to be running both the client & server code. In this hosting instance two `rtc::PeerConnection`s are created, one for the _"server side"_ code & one for the _"client side"_ code. I then connect these two local PeerConnections to eachother. Remotely connecting clients only create a single `rtc::PeerConnection` that is connected to the host's _server side_ `rtc::PeerConnection`.

Now I'm occasionally having trouble establishing a connection between the host's two local `rtc::PeerConnection`'s in the same process. I'd say connection establishment fails 5% of the time. As a side note I have a WebAssembly build of the game and I don't experience the same issue. 

I've attached [game.log](https://github.com/paullouisageneau/libdatachannel/files/5855739/game.log) captured during a session that experienced the problem. It's sprinkled with a few of my own log items for my own context so I can help but I can remove these if you like. I've also attached my [stun_server.log](https://github.com/paullouisageneau/libdatachannel/files/5855745/stun_server.log) although it's likely of little use other than for my own context.

Interestingly in the captured logs the _client side_ `rtc::PeerConnection` finds both **host** & **srflx** ice candidates, but the _server side_ only finds  a **host** candidate. Seems a little strange to me. My STUN server also sees much more activity in these 5% failure cases vs the 95% happy path cases. After 10 seconds (at the end of the logs) the game aborts the connection attempt. 

Let me know how I can help?

Kind regards,

Deon

**Comment by paullouisageneau** [comment]
Thanks for reporting the issue!

The symptom is weird, it seems the server-side agent is unable to receive any datagram. This also explains why it only finds a host candidate, since it doesn't receive answers for the server. However, there is no errors at reception...

What OS are you running?

**Comment by dbotha** [comment]
Thanks for taking the time to have a look. It occurs on both MacOS Catalina & Windows 10. 

I'll stick Wireshark inbetween to double check the srflx candidate is arriving for the server-side agent & update with my findings. I'm happy to do my own digging but any chance you could point me in the direction as to where the stun message responses are received/parsed?

**Comment by paullouisageneau** [comment]
Excellent, Wireshark would allow to confirm the response from the STUN server actually arrives.

Everything is received by libjuice here: https://github.com/paullouisageneau/libjuice/blob/64db5b3be66d48af5c6c75eb9ad74f7b30cf8a39/src/agent.c#L650

However, there seems to be no trace of a single datagram received server-side in the log.

**Comment by dbotha** [comment]
Here's an update so far on my findings. I've captured the STUN protocol packets in Wireshark. Unfortunately (although at least I'm not crazy 🤣) they do indeed arrive at my computer for delivery to the game process. Here's an upload of the logs & wireshark capture file:

1. [wireshark_stun_capture.pcapng.zip](https://github.com/paullouisageneau/libdatachannel/files/5866275/wireshark_stun_capture.pcapng.zip)
2. [game.log](https://github.com/paullouisageneau/libdatachannel/files/5866276/game.log)
3. [stun_server.log](https://github.com/paullouisageneau/libdatachannel/files/5866277/stun_server.log)

Here's a screenshot of the Wireshark capture in case you don't want to load the file:

![wireshark_capture](https://user-images.githubusercontent.com/760653/105701586-6ab8c780-5f02-11eb-9eb8-7596f5e33f03.png)

On this occasion the host-side agent discovers both the `host` & `srflx` candidates but the client-side agent only discovers the `host` candidate. This is despite 7 STUN Binding requests being sent to my stun server & responses received (confirmed in both the stun server & wireshark capture logs).  

The `srflx` candidate correctly indicates my public IP of `94.15.18.230`.  I'm assuming the ICMP destination unreachable packets are expected and part of the ICE negotiation process caused by the client-agent failing to connect to the host agent from my local ip `192.168.1.2`to my public ip of `94.15.18.230`.

For reference this screenshot shows the STUN message flow for a successful connection:

![successful_connection_wireshark_capture](https://user-images.githubusercontent.com/760653/105702718-1a426980-5f04-11eb-99af-9a694b99422b.png)

**Comment by paullouisageneau** [comment]
Could you please try with the submodule updated in https://github.com/paullouisageneau/libdatachannel/commit/f5a6342c60e6f0d689e578036e7bc8f35903f132 to see if the issue happens again?

**Comment by dbotha** [comment]
Amazing, thanks for looking. I'll grab the changes and retest. I'll also aim to reproduce on Windows aswell.

**Comment by dbotha** [comment]
Unfortunately I'm still seeing the behaviour on MacOS even with your latest changes. I'm going to try on Windows now.

> For UDP sockets, it means multiple sockets may bind on the same port, which is something we definitely don't want here. 

Thinking about this a bit more, I think it's probably unrelated to this issue as I can see in the wireshark logs above (and my latest tests) that there are two distinct UDP ports being used locally (I'm assuming one for the client-side agent, and one for the server-side agent).

**Comment by dbotha** [comment]
Not sure if it's appropriate (& subject to if you version things consistently) but it would be nifty if the libjuice stun software attribute included the library version number to assist debugging. Save's me tripple checking I'm using the right commits across the board.

**Comment by dbotha** [comment]
Hold fire on investing any more time in this right now as I'm now struggling to reproduce it under my Windows setup. I'm going to get things setup there so that I can use it for my daily development and monitor things over the next few days.

**Comment by dbotha** [comment]
Good news, I can't reproduce this under Windows - not sure why I believed I could before. I'll try get another Mac in the near future and see if it's purely something to do with my local dev environment or affects all MacOS users. For now feel free to close this issue if it's causing clutter and I'll create a follow up once I've had the chance to investigate further.

**Comment by paullouisageneau** [comment]
> Thinking about this a bit more, I think it's probably unrelated to this issue as I can see in the wireshark logs above (and my latest tests) that there are two distinct UDP ports being used locally (I'm assuming one for the client-side agent, and one for the server-side agent).

Yes, but in theory, enabling the flag means the OS could choose an ephemeral port where another program is already listening. So it's still good to have that fixed.

Good news for Windows, keep me posted about the situation on Mac!

**Comment by dbotha** [comment]
Not sure if this if this is related, expected behaviour or a total red herring but I've noticed that when I experience the above issue I'll hit an exception breakpoint due to timeout here after 30 seconds:

https://github.com/paullouisageneau/libdatachannel/blob/986e5f985fe403836f82451ad7afa764d437b551/src/dtlstransport.cpp#L491

After this has happened I can usually connect successfully. Sorry I've still not managed to get my hands on a second Mac to investigate further.

**Comment by dbotha** [comment]
@paullouisageneau I don't see the above behaviour anymore - or at least nowhere near as much as I was before. I've since upgraded my OS and updated all manner of firewall / network utilities so possibly down to something there. I'm going to close this if that's ok with you?

**Comment by paullouisageneau** [comment]
Great, thank you for the update, feel free to reopen if you encounter the issue again.
