### ISSUE TITLE
Fixing the UWP crashes (continuing #216)

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#310]
Finally I had time to come back! So, which seemingly was a crash (see #216) was neither an actual crash or something caused by a missing dll. It was UWP by default expecting all applications to be GUI and complaining about the libdatachannel applications not having an "App" class with methods like OnLaunched, OnSuspending, and OnNavigationFailed in it!

So, the fix is stating the libdatachannel applications are not GUI but console. When running CMake to create a Visual Studio Solution, CMake auto-generates a package.appxManifest file per executable. To claim the executables are console, these appxManifest files need to be manipulated as below:

1. Add two attributes to the <Package> tag
xmlns:desktop4="http://schemas.microsoft.com/appx/manifest/desktop/windows10/4" 
xmlns:iot2="http://schemas.microsoft.com/appx/manifest/iot/windows10/2"

2. Add four attributes to <Application> tags inside the <Applications> tag.
desktop4:Subsystem="console"
desktop4:SupportsMultipleInstances="true"
iot2:Subsystem="console"
iot2:SupportsMultipleInstances="true"

This information comes from this website (https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp) and attached is an appxManifest file modified for datachannel-benchmark provided as an example.
[package.appxManifest.txt](https://github.com/paullouisageneau/libdatachannel/files/5858615/package.appxManifest.txt)

The problem here is that I don't think CMake currently supports adding those attributes by a flag or something. So, to fix this UWP crashing issue, an approach would be adding the above attributes via XML manipulation. While I am not even sure XML manipulation can be done inside a CMake script, I will try it soon...

p.s. One positive thing I have learned is that actually your applications were working fine. The crashes happen after completely running main() and does not cause any actual problems. It was just having an error alerting window, which is terribly unappealing, at the end of execution.

**Comment by paullouisageneau** [comment]
Great to have you back on the UWP quest!

> The problem here is that I don't think CMake currently supports adding those attributes by a flag or something. So, to fix this UWP crashing issue, an approach would be adding the above attributes via XML manipulation. While I am not even sure XML manipulation can be done inside a CMake script, I will try it soon...

You can't do XML manipulation, however you could try using [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html) to do variable substitution on an XML template.

**Comment by hanseuljun** [comment]
Thanks for the suggestion! I'll come back to this hopefully by the end of this week.

**Comment by hanseuljun** [comment]
As the way to support applications in uwp is now known, I will continue this line of work to support the examples... soon...
