### ISSUE TITLE
Init Ice Transport error : stoul

### ISSUE THREAD

**Issue by lukepolo** [paullouisageneau/libdatachannel#321]
We are getting an error when getting an offer from the client: 

```
2021-01-29 14:16:10.564 VERB  [19951] [rtc::PeerConnection::setRemoteDescription@203] Setting remote description: v=0
o=- 815130196651388299 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
a=setup:actpass
a=ice-ufrag:3HYE
a=ice-pwd:JIRCzK+5AlIIwHvudK5rcxbQ
a=ice-options:trickle
a=fingerprint:sha-256 8C:8A:9F:3D:BA:BF:B4:EE:EE:46:57:82:DC:1B:76:2C:EF:89:4B:5E:67:74:F7:FC:D1:62:9F:73:2C:38:BF:FF
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=bundle-only
a=mid:0
a=sendrecv
a=ice-options:trickle
a=sctp-port:5000
a=max-message-size:262144

2021-01-29 14:16:10.564 VERB  [19951] [rtc::PeerConnection::validateRemoteDescription@930] Remote description looks valid
2021-01-29 14:16:10.564 VERB  [19951] [rtc::PeerConnection::initIceTransport@399] Starting ICE transport
2021-01-29 14:16:10.564 DEBUG [19951] [rtc::IceTransport::IceTransport@58] Initializing ICE transport (libjuice)
2021-01-29 14:16:10.564 DEBUG [19951] [rtc::IceTransport::IceTransport@106] Using STUN server "stun:stun1.l.google.com:19302"
2021-01-29 14:16:10.564 ERROR [19951] [rtc::PeerConnection::initIceTransport@455] stoul
```

We are not sure what to make of the error, any ideas ? 

**UPDATE:**
I was able to get the error 

```(node:20346) UnhandledPromiseRejectionWarning: Error: libdatachannel error while adding remote decsription # ICE transport initialization failed```

**Comment by paullouisageneau** [comment]
This is a weird error. I guess this could be an exception thrown by the `std::stoul` function, but I wonder why the runtime would use "stoul" as a message. It's probably the one here: https://github.com/paullouisageneau/libdatachannel/blob/289b71bc8e70ddc4a8b6df274ff610a7da47a720/src/icetransport.cpp#L110

However, the argument would be `"19302"` here, so I wonder why I would fail.

What are the OS and compiler?

**Comment by lukepolo** [comment]
We are using the package `https://github.com/murat-dogan/node-datachannel` , on ubuntu 20.04.  

It could be in that package but it just seems its wrapper. (Its using an older version 0.10.4 as well.

**Comment by paullouisageneau** [comment]
After verification, `std::st*` functions in libstdc++ indeed throw an exception with the name of the function and not the argument. For reference: https://gcc.gnu.org/onlinedocs/gcc-10.2.0/libstdc++/api/a01088_source.html#l00083

Could you try removing the STUN server and see if the same error happens?

@murat-dogan Is this something you have already witnessed?

**Comment by lukepolo** [comment]
removing the stun server does work (of course need the stun but at least I can code around it for now)

**Comment by paullouisageneau** [comment]
OK, I found the issue, your STUN server URL is probably malformed. It is parsed as the hostname being "stun" and the port being "stun1.l.google.com:19302", which results in the port conversion to number failing. Try instead with the STUN server URL `stun1.l.google.com:19302`.

 I'll add checks to make such format errors explicit.

**Comment by murat-dogan** [comment]
I am glad that you found the issue. 
Please inform me if there is something that I can do.

**Comment by paullouisageneau** [comment]
@murat-dogan I think it's good, this will just need an update in the wrapper when I'll tag a new version. Thanks for the work on it!

@lukepolo Please re-open if the issue is not solved for you by replacing the STUN server URL.

**Comment by paullouisageneau** [comment]
@murat-dogan You might want to update libdatachannel to v0.11.1 in node-datachannel to fix this issue.

**Comment by murat-dogan** [comment]
I just released updated version. (v0.0.21)
