### ISSUE TITLE
No video stream (streamer example)

### ISSUE THREAD

**Issue by iaamp** [paullouisageneau/libdatachannel#341]
#### Expected behaviour:
* clicking 'Start'
* no error
* candle video stream

#### Actual behaviour:
* clicking 'Start'
* error:
127.0.0.1:8080 says
"OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='video-stream'.
* no stream at all
* after clicking 'Stop', then 'Start' again: no error, black video stream

#### Context
Ubuntu 20.04 LTS
About Chromium: Version 87.0.4280.141 (Developer Build) built on Debian 10.7, running on Debian bullseye/sid (64-bit)

**Comment by paullouisageneau** [comment]
I'm unable to reproduce with Chromium 88. Is the package chromium-codecs-ffmpeg-extra package (or the chromium-ffmpeg snap) installed?

**Comment by paullouisageneau** [comment]
Please re-open if you still encounter the issue.
