### ISSUE TITLE
Candidate::operator== makes Description::extractCandidates skip some candidates

### ISSUE THREAD

**Issue by ilsalvopss** [paullouisageneau/libdatachannel#348]
In the particular situation in which the Description is representing a peer behind a symmetric NAT I find useful to be able to detect it by configuring more than one STUN and check if more than one candidate has the same IP and varies by port.

`Description::extractCandidates` checks for doubles in the return vector using the `==` overload which relies just on comparing `mFoundation`.

In some cases this leads to the exclusion of some very similar candidates, eg:

Given the following SDP the candidate with port number 14177 is skipped
```
v=0
o=- 4034358774864795185 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 video-stream audio-stream
a=msid-semantic: WMS
m=application 14095 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
b=AS:30
a=candidate:3370501507 1 udp 2113937151 2d03edd6-2490-4322-884a-0286be57e62d.local 64360 typ host generation 0 network-cost 999
a=candidate:842163049 1 udp 1677729535 37.159.*.* 14095 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=candidate:842163049 1 udp 1677729535 37.159.*.* 14177 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=ice-ufrag:q+Na

...
```

**Comment by ilsalvopss** [comment]
My hotfix consists is just comparing other details (idk if this somehow violates specifications):

```
bool Candidate::operator==(const Candidate &other) const {
	return (mFoundation == other.mFoundation &&
	        mService == other.mService &&
	        mNode == other.mNode)
	    ;
}
```

**Comment by paullouisageneau** [comment]
The foundation should allow differentiating candidates, as stated in [RFC 5245 section 4.1.1.3](https://tools.ietf.org/html/rfc5245#section-4.1.1.3):
> Similarly, two candidates MUST have different foundations if their
   types are different, their bases have different IP addresses, the
   STUN or TURN servers used to obtain them have different IP addresses,
   or their transport protocols are different.

In this case, the two STUN servers have different IP addresses, therefore the remote implementation is not following specification when using the same foundation for the two candidates. Which browser is it?

That being said, I think it's harmless to compare the node and service fields too. Could you please open a PR with your fix to make the change?

**Comment by ilsalvopss** [comment]
That SDP was (sadly) produced by iOS Safari (iOS 14.4)
