### ISSUE TITLE
Request to update libdatachannel in libtorrent

### ISSUE THREAD

**Issue by aldenml** [paullouisageneau/libdatachannel#362]
Hi @paullouisageneau, can you submit a PR in `libtorrent` to update to the latest version? This code
https://github.com/paullouisageneau/libdatachannel/blob/fe9a34905b79f7daa0bccc8901c44b7245f09628/src/peerconnection.cpp#L48
does not work in Android :(

Thanks

**Comment by paullouisageneau** [comment]
Hi, this is done in https://github.com/arvidn/libtorrent/pull/6046

**Comment by aldenml** [comment]
Thank you!
