### ISSUE TITLE
addTrack(desc) != addTrack(desc)

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#366]
HI @paullouisageneau. I'm back again!

I have a sanity assertion I am making during renegotiation to affirm that when I update the description for a track (via `addTrack`) I get the same track I had before. I'm upgrading the library as I was running before the `ChesireCat` refactor, and now that assertion is failing because of the re-instantiation of `std::shared_ptr<Track>(trackImpl)`. Is this intended behavior?

**Comment by paullouisageneau** [comment]
Hello,

Yes, it is intended. The refactoring hides implementation and makes all interface classes manipulable without shared_ptrs. I kept them for returned DataChannels and Tracks for compatibility, but it means you could move them away and store them directly.

Now `addTrack()` returns a different interface wrapper instance, but it is still guaranteed to wrap the same implementation, meaning any operation on one or the other has the same effect. It'll basically behave as if it is the same object.
