### ISSUE TITLE
Application SDP difference

### ISSUE THREAD

**Issue by korrix** [paullouisageneau/libdatachannel#376]
I'm having problem establishing session with description containing `application`. Libdatachannel generates:
```
...
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=bundle-only
a=mid:0
a=sendrecv
a=sctp-port:5000
a=max-message-size:262144
...
```

Whereas chrome used as alternative client generates:
```
...
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:Vqsx
a=ice-pwd:REDACTED_PWD
a=ice-options:trickle
a=fingerprint:REDACTED_FINGERPRINT
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
...
```
(I manually redacted sensitive parts).

Negotiating only video without any data channel enabled works correctly:
```
[11196] [rtc::impl::PeerConnection::changeSignalingState@986] Changed signaling state to connecting
[rtc::impl::IceTransport::LogCallback@339] juice: agent.c:787: Changing state to connected
....
```
But adding single line:
```
m_dataChannel = m_peerConnection->createDataChannel("test-channel");
```
Makes it stop on "Changed signaling state to connecting" without any further action. from the juice agent.

Could you provide any hints to resolving this situation? I am quite new to WebRTC and SDP is especially confusing.

**Comment by korrix** [comment]
For some reason even though I am adding video track and creating datachannel before `setLocalDescription` and having library compiled with media support
this: https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L203 if statement not executed. Commenting it allowed to choose `DtlsSrtpTransport` over the `DtlsTransport` and solved my issue

**Comment by paullouisageneau** [comment]
By default the library starts the negotiation automatically, like when you set the `onnegotiationneeded` callback to call `setLocalDescription()` in the JavaScript API.

The behavior can be disabled by setting `disableAutoNegotiation` to `true` in `rtc::Configuration`:
https://github.com/paullouisageneau/libdatachannel/blob/33c7518b17b258a504fbccc5ba614f52db6e0dd4/include/rtc/configuration.hpp#L81

**Comment by paullouisageneau** [comment]
I'm closing this since the issue seems addressed, please reopen if needed.
