### ISSUE TITLE
removing cmake deprecation warning from plog

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#378]
Not something of much importance but when running cmake the below warning appears. It is cmake saying plog has too low minimum version supported (as cmake people are planning to drop support of 2.x).

![image](https://user-images.githubusercontent.com/5001447/112189179-fd9f7680-8bc0-11eb-81b5-90d539ac4a84.png)

As now plog has a higher minimum version (i.e., 3.0), it no longer prints the above warning. So, would you like to update the version of plog being used?

libsrtp is also printing the same warning message, so I may leave the same type of an request for libsrtp later...

**Comment by paullouisageneau** [comment]
Indeed, libdatachannel actually uses a fork of plog with a specific fix I didn't report upstream, I'll update it.
