### ISSUE TITLE
EWOULDBLOCK != EAGAIN

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libdatachannel#38]
```
if (ret >= 0) {
	PLOG_VERBOSE << "SCTP sent size=" << message->size();
	return true;
} else if (errno == EWOULDBLOCK && errno == EAGAIN) {
	PLOG_VERBOSE << "SCTP sending not possible";
	return false;
} else {
	PLOG_ERROR << "SCTP sending failed, errno=" << errno;
	throw std::runtime_error("Sending failed, errno=" + std::to_string(errno));
}	
```
should not it be this instead ?

`if (errno == EWOULDBLOCK || errno == EAGAIN)`

**Comment by paullouisageneau** [comment]
Yes, good catch! It worked by chance on Linux because both are the same :man_facepalming: 
I pushed the fix: https://github.com/paullouisageneau/libdatachannel/commit/cb3bc85474102841c102640968a1fcb161cd2dc7
