### ISSUE TITLE
Little CMake project improvements suggestion.

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#388]
Hi, would you like to add some CMake tweaks to make it easier to port to vcpkg ?
Here is the current patch that needs to be applied to the project to make it work: https://github.com/microsoft/vcpkg/blob/master/ports/libdatachannel/fix-for-vcpkg.patch

Right now, I think those changes might be nice for everyone using CMake and not only vcpkg:
This adds an include interface, when building you can set an absolute path, but when installing, cmake requires it to be relative.
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/libdatachannel/fix-for-vcpkg.patch#L43

This add an export target, so you don't need to search for the library with cmake as its now aware of what include/library you export
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/libdatachannel/fix-for-vcpkg.patch#L81-L85
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/libdatachannel/fix-for-vcpkg.patch#L93-L97

Tho the exported library will be LibDatachannel::datachannel, instead of your current alias LibDatachannel::LibDatachannel., this might be configurable somewhere.

**Comment by paullouisageneau** [comment]
Sure, how does this work with plog through? I see you removed plog as a library to replace it with a manual include directory. Does it mean it must be available as an external library?

**Comment by Nemirtingas** [comment]
Yup, I removed plog and usrsctp as this can be built by vcpkg and I add plog and usrsctp as dependencies, so you don't have to dowload em separatly anymore, they are used if they are already built or built if missing.

**Comment by paullouisageneau** [comment]
> Thats because plog is header only (https://github.com/SergiusTheBest/plog) and doesn't export its configuration to cmake like I did when porting your libs to vcpkg (the export target), and to find it automatically, I needed to tell cmake where to look.

OK, then how would it work with the export target? plog is a public dependency so the headers need to be installed. I guess it would require adding an export target for plog too, right?

**Comment by Nemirtingas** [comment]
Best would be that plog exports its interface library yes, like nlohmann's json did here: https://github.com/nlohmann/json/blob/develop/CMakeLists.txt#L164-L182 but since plog doesn't, I needed to find the include path.

**Comment by paullouisageneau** [comment]
> One could add the export target to plog and send a merge request, that way, all projects that use plog could use the auto conf target instead of looking for it by hand.

Could you please handle it? Then I would update plog and integrate the changes.

**Comment by Nemirtingas** [comment]
> 
> 
> > One could add the export target to plog and send a merge request, that way, all projects that use plog could use the auto conf target instead of looking for it by hand.
> 
> Could you please handle it? Then I would update plog and integrate the changes.

I could, but vcpkg uses https://github.com/SergiusTheBest/plog, not your fork. Also your fork seems dirty: https://github.com/paullouisageneau/plog/blob/master/include/plog/Util.h#L522-L531, do you want me to send a pr on your fork or Sergius' project ?

**Comment by paullouisageneau** [comment]
> I could, but vcpkg uses https://github.com/SergiusTheBest/plog, not your fork. 

Yes, libdatachannel does not use my fork anymore. I should have archived it, actually.

> do you want me to send a pr on your fork or Sergius' project ?

Sergius' project please :smile: 

> Also your fork seems dirty: https://github.com/paullouisageneau/plog/blob/master/include/plog/Util.h#L522-L531

Arf thanks :eyes:

**Comment by Nemirtingas** [comment]
Hmm, I think I can't send this pr, it looks like it has already been sent but Sergius didn't have the time to merge it since 2020. https://github.com/SergiusTheBest/plog/pull/171

**Comment by paullouisageneau** [comment]
Hmm, there is another way: I could make plog a private dependency. The main reason it's public is that there is some implementation in headers (especially RTP stuff).

**Comment by Nemirtingas** [comment]
Did you try https://github.com/gabime/spdlog ?

**Comment by paullouisageneau** [comment]
I moved plog as a private dependency in https://github.com/paullouisageneau/libdatachannel/pull/404, which should solve a lot of issues.

**Comment by paullouisageneau** [comment]
Now the improvements you suggested can be integrated independently of plog: https://github.com/paullouisageneau/libdatachannel/pull/410

**Comment by Nemirtingas** [comment]
Seems to work fine for now. The cmake configuration file is generated properly. One can automatically link libdatachannel through cmake with:
```
find_package(libdatachannel CONFIG REQUIRED)
target_link_libraries(<project> PRIVATE LibDatachannel::datachannel)
```

**Comment by wasphin** [comment]
> Seems to work fine for now. The cmake configuration file is generated properly. One can automatically link libdatachannel through cmake with:
> 
> ```
> find_package(libdatachannel CONFIG REQUIRED)
> target_link_libraries(<project> PRIVATE LibDatachannel::datachannel)
> ```

It doest not work in my case, ``cmake`` generates two files: ``datachannel-export.cmake`` and ``datachannel-export-noconfig.cmake``, and ``find_package`` looks for ``datachannel-config.cmake`` by default.

@Nemirtingas, do you test it? or am I missing something? 

The exported target name in the patch at
 [vcpkg](https://github.com/microsoft/vcpkg/blob/7b1016e10ef0434fe7045d320a9ee05b63e0efe9/ports/libdatachannel/fix-for-vcpkg.patch#L73) is ``datachannel-config`` rather than ``datachannel-export``, which will guide ``cmake`` to generate files
``datachannel-config.cmake`` and ``datachannel-config-noconfig.cmake``, this works for me.

**Comment by Nemirtingas** [comment]
Yes, I tested it, but as I have both in my cmake path, I think it did choose the datachannel-config instead of the datachannel-export.
You're right, it should be datachannel-config.

**Comment by paullouisageneau** [comment]
> I think datachannel-export should be renamed datachannel-config.

Indeed, I think I did the same mistake.

**Comment by paullouisageneau** [comment]
The various enhancements discussed here all landed in version 0.14.0, and I added some more. For instance, I fixed the coupling with libjuice (no more sneaky importation of the private header `socket.h`) and added a CMake flag `USE_SYSTEM_JUICE` to link against an already installed libjuice.

I think it's worth it to update the vcpkg port to 0.14.0 (and the libjuice one to 0.8.2).

**Comment by Nemirtingas** [comment]
Can be cool to update.
I backported (again) libdatachannel v0.14.0 to cxx14 with boost, I also made a fork of vcpkg to make it compile with cxx14 using boost::optional and boost::variant, those 2 libs are header only and don't require too much tweaks.

**Comment by Nemirtingas** [comment]
It seems that libdatachannel has issue when building on arm and uwp: https://github.com/microsoft/vcpkg/pull/19268#issuecomment-890752018

**Comment by paullouisageneau** [comment]
```
4>D:\buildtrees\libdatachannel\src\v0.14.0-ded584d6a1.clean\src\impl\certificate.cpp(205,31): error C3861: 'PEM_read_X509': identifier not found [D:\buildtrees\libdatachannel\x64-uwp-dbg\datachannel.vcxproj]
4>D:\buildtrees\libdatachannel\src\v0.14.0-ded584d6a1.clean\src\impl\certificate.cpp(207,11): error C3536: 'x509': cannot be used before it is initialized [D:\buildtrees\libdatachannel\x64-uwp-dbg\datachannel.vcxproj]
4>D:\buildtrees\libdatachannel\src\v0.14.0-ded584d6a1.clean\src\impl\certificate.cpp(215,6): error C3861: 'PEM_read_PrivateKey': identifier not found [D:\buildtrees\libdatachannel\x64-uwp-dbg\datachannel.vcxproj]
4>D:\buildtrees\libdatachannel\src\v0.14.0-ded584d6a1.clean\src\impl\certificate.cpp(218,11): error C3536: 'pkey': cannot be used before it is initialized [D:\buildtrees\libdatachannel\x64-uwp-dbg\datachannel.vcxproj]
4>D:\buildtrees\libdatachannel\src\v0.14.0-ded584d6a1.clean\src\impl\certificate.cpp(221,31): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rtc::impl::Certificate' [D:\buildtrees\libdatachannel\x64-uwp-dbg\datachannel.vcxproj]
```
I don't think these are linked to the ARM architecture. The cause is the `PEM_read_X509` and `PEM_read_PrivateKey` methods are missing from the OpenSSL, while they should be defined by the header `openssl/pem.h` (which is included in `src/impl/tls.hpp`). OpenSSL might have been built with the flag `OPENSSL_NO_STDIO` for some reason.

Just a note: you should upgrade libjuice directly to 0.8.4.

**Comment by Nemirtingas** [comment]
It seems to be an issue on uwp. I'll update libjuice.

**Comment by paullouisageneau** [comment]
I don't really know why the methods are missing with UWP, but bypassing them is easy, it should compile fine with https://github.com/paullouisageneau/libdatachannel/pull/455.

**Comment by paullouisageneau** [comment]
I merged and released the fix in v0.14.1.

**Comment by Nemirtingas** [comment]
Seems to compile, at least on x64-uwp, lets wait for arm-uwp, but I think it should be ok now, thanks ;).

**Comment by Nemirtingas** [comment]
vcpkg ports updated.

**Comment by paullouisageneau** [comment]
@Nemirtingas Great, thank you!
