### ISSUE TITLE
Not able to create a datachannel with the browser under most circumstances

### ISSUE THREAD

**Issue by eh4** [paullouisageneau/libdatachannel#389]
Hello

I am having significant difficulties in getting this library to work as it's supposed to and I can't figure out what I'm doing wrong.
Hopefully the issue is somewhere in my code - maybe there are some unwritten restrictions on what functions I have to call and in what order that I'm just not following. No errors are returned by the functions I call.

I'm using the C api, no websockets, no STUN servers (communication is on a single computer), and for the most part ICE seems to finish, but the datachannels do not end up working. 

I have logs stored here
[problems.zip](https://github.com/paullouisageneau/libdatachannel/files/6261591/problems.zip)

There are a number of test cases I've tried, but I can't seem to get to the root of the problem - if the issue is my setup, the C api, the datachannel negotiation... it almost makes it worse that there is one case out of 6 that actually works correctly, but then only on Chrome.

I have firefox 87, chrome 89, libdatachannel 0.12 on linux 

log1.txt
Firefox:
Web answer
C offer
C creates DC
-> ICE does not finish (stuck in checking)

log2.txt
Chrome
Web answer, C offer, C creates DC
-> ICE finished, no data channel on Chrome side

log3.txt
Firefox
Web offer, C answer, both create DC
-> ICE finished, ffx data channel stuck in connecting state

log4.txt
Chrome
Web offer, C answer, both create DC
-> message gets through
-> message sent on chrome's DC and arrives on C's DC (!)

log5.txt
Chrome
Web offer, C answer, web creates DC
-> message gets through
-> new DC event on C program
-> Only option that works as intended

log6.txt
Firefox
Web offer, C answer, web creates DC
-> ICE finished, no new DC event on C side, ffx DC stuck in connecting state

Patterns-
No data channel initiated by the C side ever shows up in browser
Firefox did not work correctly at all
Attempt 4 seems to have merged the two datachannels into one, even though they have different labels and all settings were default (which should mean auto negotiation)

**Comment by paullouisageneau** [comment]
Thank you for the detailed report and for submitting code to reproduce the issue.

It looks like the primary issue comes from the lack of either a candidate or gathering callback on libdatachannel side.

On the web client, there is this function:
```JavaScript
function local_gathering(e){
	if(rtc.iceGatheringState == "complete"){
		my_sdp.innerText = rtc.localDescription.sdp;
	}
}
```

So I guess you don't want candidate trickling, and instead you want to wait for candidates to be gathered to send the whole SDP at once. To achieve the same with libdatachannel, you can't call `rtcGetLocalDescription()` immediately. Instead you should do something like:
```C
void RTC_API gathering_state_change_callback(int rtc_id, rtcGatheringState state, void *ptr) {
	if(state == RTC_GATHERING_COMPLETE) {
	   char sdp_out[64 * 1024];
           int sdp_out_len = rtcGetLocalDescription(rtc_id, sdp_out, sizeof(sdp_out));

           [Send the SDP description now]
        }
}

int main(void)
{
        [...]
	int rtc_id = rtcCreatePeerConnection(&empty_config);
	rtcSetGatheringStateChangeCallback(rtc_id, gathering_state_change_callback));

        [Do not call rtcGetLocalDescription() here, gathering is not finished!]
}
```

In addition, don't call `rtcCreateDataChannel()` on both sides without further setup. By default, auto negotiation is enabled so both sides will generate an offer and negotiation won't happen as you expect.

**Comment by eh4** [comment]
Thanks for the reply!

With some changes, it works for 3 of the remaining 4 cases, where only one side creates the datachannel. I'm left with the case of Firefox creating the datachannel, which doesn't work correctly

[loga_firefox.txt](https://github.com/paullouisageneau/libdatachannel/files/6268828/loga_firefox.txt)
[bugs.c.txt](https://github.com/paullouisageneau/libdatachannel/files/6268829/bugs.c.txt)

Firefox offers rtc & creates datachannel, libdatachannel answers, the DC does not work (Firefox says its readystate is still "connecting" and the data channel callback isn't called on the libdatachannel side)

**Comment by paullouisageneau** [comment]
The core issue is that the Peer Connection does not connect. It seems to come from the `ff6115cf-a652-40ef-b811-5cb3c01e58bb.local` remote mDNS host candidates not being resolved. As there is no STUN server, there is no remote candidate passed to libnice. This triggers a libnice-specific issue as libnice does not start connectivity checks without receiving a remote candidate fist (see https://gitlab.freedesktop.org/libnice/libnice/-/issues/69). This should be fixed in upcoming versions of libnice by https://gitlab.freedesktop.org/libnice/libnice/-/merge_requests/182

To quickly fix this issue you may add a STUN server or switch back to the default ICE backend libjuice. Since it works for other tests, could you retry to be sure it's not just mDNS resolution that is unreliable with Firefox or your system?

**Comment by eh4** [comment]
Yes, libnice was the problem - changing to libjuice solved the issue. Thanks!
