### ISSUE TITLE
PLOG logs multiple calls after peerconnection reset

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libdatachannel#39]
Scenario:
I'm creating a peerconnection via shared_ptr
I reset my shared_ptr upon parent object destruction
All destructors are called correctly along the way
I then create another peerconnection
I get 2x logs from this peerconnection
And it keeps going after each destruction/construction of a peerconnection

Example after 2 destructions:
```
2020-03-04 16:30:07.754 INFO  [43988] [rtc::DtlsTransport::runRecvLoop@485] DTLS disconnected
2020-03-04 16:30:07.754 INFO  [43988] [rtc::DtlsTransport::runRecvLoop@485] DTLS disconnected
2020-03-04 16:30:07.754 INFO  [43988] [rtc::DtlsTransport::runRecvLoop@485] DTLS disconnected
```

**Comment by paniksystem** [comment]
Alright i think because i call on my parent contrusctor, what a dumb dumb

`rtcInitLogger(RTC_LOG_INFO);`

**Comment by paniksystem** [comment]
I dont know if this is a desired behavior, so closing for now, feel free to reopen to track if needed

**Comment by paullouisageneau** [comment]
That's a good point, right now if you init the logger multiple times it logs multiple times. It might be a good idea to change that.

**Comment by gamedolphin** [comment]
Yep I can confirm this behavior.
