### ISSUE TITLE
htonll problem

### ISSUE THREAD

**Issue by ZoneLikeWonderland** [paullouisageneau/libdatachannel#391]
Hi, I found current implementation of `htonll` may have problems.

In current `rtp.hpp`, `htonll` is defined as
```c++
#define htonll(x)                                                                                  \
	((uint64_t)htonl(((uint64_t)(x)&0xFFFFFFFF) << 32) | (uint64_t)htonl((uint64_t)(x) >> 32))
```
where `htonl` in `htonl(((uint64_t)(x)&0xFFFFFFFF) << 32)` always reads 0.
I think some parentheses may be placed wrong.

**Comment by paullouisageneau** [comment]
Oops, good catch, thank you. I'm pushing a fix.
