### ISSUE TITLE
[Question] What version scheme do you follow ?

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#397]
What semantic do you follow for your release versions ? vcpkg use some predefinied versions: https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.reference.md

There is a doubt if we should use version or version-semver. 

https://semver.org/#semantic-versioning-specification-semver

What do you think ? Should we use version or version-semver ?

**Comment by paullouisageneau** [comment]
It's semver, even if I use only normal x.y.z version without pre-release tags, at least for now. So `version-semver` looks good!

**Comment by Nemirtingas** [comment]
Thanks !
