### ISSUE TITLE
DataChannel onOpen() callback is not called on the receiving side 

### ISSUE THREAD

**Issue by ptesavol** [paullouisageneau/libdatachannel#403]
I noticed that in libdatachannel the onOpen() callback only gets called on the offering side, and not on
on the receiving side. Apparently the datachannel is already open and ready to be used when the onDataChannel() callback gets called? This is a bit confusing, as in the browsers this is not the case (see https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ondatachannel), and onOpen() gets called at both ends. 

From the user's perspective the current way is a bit inconvenient , as one needs to wait either for onOpen() or on  
onDataChannel() callback before one can start sending data depending on whether one is the offerer or the receiver of the data channel. Additionally, this makes ones code less straightforward to port to browsers and other libraries that follow the standard WebRTC API, as the logic is slightly different.

Would it be possible to change libdatachannel to call onOpen() also in the receiving end?

**Comment by paullouisageneau** [comment]
That's a good point. The `onOpen()` callback is indeed called only when the state changes to open, and it has already changed when the `DataChannel` is passed in the `onDataChannel()` callback. It would be more convenient to have a behavior similar to browsers with onOpen() called symmetrically.
