### ISSUE TITLE
Order of calling createDataChannel() and addTrack() of PeerConnection matters

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#415]
Hi Paul-Louis,

While bumping from version 0.11.10 to 0.12.x, replacing the deprecated addDataChannel() by createDataChannel(), I experienced a tiny thing, not sure whether it is intended behavior, so reporting it here.

What I was doing previously with v0.11.10, which worked:
1. call the first addDataChannel()
2. call the another addDataChannel()
3. call addTrack() for video
4. call addTrack() for audio
5. call setLocalDescription(Type::Offer)

What I first did with v0.12.x, which did not work:
1. call the first createDataChannel()
2. call the another createDataChannel()
3. call addTrack() for video
4. call addTrack() for audio
5. call setLocalDescription(Type::Offer)
* The data channels get opened when the peer connection is connected, but the tracks don't get opened.

What I did with v0.12.x, which worked:
1. call addTrack() for video
2. call addTrack() for audio
3. call the first createDataChannel()
4. call the another createDataChannel()
5. call setLocalDescription(Type::Offer)

In this manner, calling addTrack() before createDataChannel() made a difference!

**Comment by paullouisageneau** [comment]
A bit change in 0.12.x is the introduction of the `disableAutoNegotiation` flag in `rtc::Configuration`. When it is `false` (default), `createDataChannel()` and `setRemoteDescription()` call `setLocalDescription()` internally, when it is `true`, you have to start negotiation yourself by calling `setLocalDescription()`. 

This change allowed to make the API similar to the JavaScript API and to remove the clumsy `addDataChannel()`. You can easily port your code by replacing `addDataChannel()` by `createDataChannel()` and setting `disableAutoNegotiation` to true (don't forget to call `setLocalDescription()` after `setRemoteDescription()` if you don't do it already).

Note the non-working order should actually open the tracks, only it will generate two successive offers, maybe the way you handle signaling doesn't support that.

**Comment by hanseuljun** [comment]
Thanks so much for another super quick and helpful response!!

**Comment by hanseuljun** [comment]
Oh, and I wanted to confirm that this application only sends the initial offer (it is something similar to the copy&paste example of libdatachannel I use for testing) for other people who will read this response in the future. So, it is likely that the problem is due to additional offers begin created but not being sent.
