### ISSUE TITLE
missing hasLocalDescription() definition

### ISSUE THREAD

**Issue by dbotha** [paullouisageneau/libdatachannel#417]
Hi Paul-Louis,

I hope you are well! I've just updated to the latest version of libdatachannel (was using one from back in January) and it seems that the definitions for hasLocalDescription() / hasRemoteDescription() might have disappeared?

https://github.com/paullouisageneau/libdatachannel/blob/ebe64ed8efcaa4580db5e35170848a6b8e6baac0/include/rtc/peerconnection.hpp#L84-L85

The previous version of the library I was using had the implementation as follows:

https://github.com/paullouisageneau/libdatachannel/blob/a7620cca16f1f9c8bf4b61028d72c15909ca3bcc/src/peerconnection.cpp#L115-L123

It's not particularly an issue for me as I can just check if the optional<Description> has a value but you might want to consider removing the declarations in the header or bring back their implementation? Or perhaps I'm just overlooking something 😅 

Cheers,

Deon

**Comment by paullouisageneau** [comment]
Hi Deon,

Good catch, the declarations of `hasLocalDescription()` and `hasRemoteDescription()` should have been removed too. The interface was cleaned up to match the Web API a bit more closely.
