### ISSUE TITLE
Support HoloLens 2？

### ISSUE THREAD

**Issue by zhuisa** [paullouisageneau/libdatachannel#419]
hi! I am very happy to find this C++ WebRTC SDK. Please forgive me for not knowing much about the SDK, so I have a question. Does libdatachannel support audio video communication in HoloLens 2 ？Looking forward your replay.

**Comment by paullouisageneau** [comment]
I don't know specifically about Hololens 2, however libdatachannel itself compiles for Windows and UWP, and @hanseuljun maintains a wrapper for Hololens 1: [hanseuljun/datachannel-unity](https://github.com/hanseuljun/datachannel-unity)

**Comment by hanseuljun** [comment]
In brief, yes libdatachannel supports HoloLens2 (i.e., ARM64 UWP). I am like 99.9% sure that c++ libdatachannel would work, though I am only about 80% sure for the datachannel-unity since I have not tested it with HoloLens2. Sadly, I still don't have access to a HoloLens 2... While not tested with a physical device, datachannel-unity includes dlls for ARM64 and is supposed to work with HoloLens2.

**Comment by zhuisa** [comment]
@hanseuljun @paullouisageneau Thanks yours' detail replay. I am so excited that find the SDK sopport HoloLens. I have other question. Can libdatachannel capture mixed reality photo and video? or，Can I combine libdatachannel and [HolographicMixedRealityCapture](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/HolographicMixedRealityCapture) together to communicate mixed reality video with other people?

**Comment by hanseuljun** [comment]
While it would require nontrivial amount of work to build the application,
yes you can use libdatachannel to stream a video from a headset to another
using libdatachannel. What libdatachannel provides is a way to send bytes
with low-latency, though the capture, compression etc. should be handled by
yourself. Using webrtc datachannels is quite similar to using udp/tcp
sockets.

**Comment by zhuisa** [comment]
Thanks your help. Thanks again! I get good answer. I close the issue.

**Comment by zhuisa** [comment]
@hanseuljun Hi! As there are still some questions, I am sorry to ask you some questions again. I don't know much about Unreal. Can I integrate libDataChannel into Unreal to stream a video, for unreal engine provide some tools,  such as UX Tools. How can I do for it?

**Comment by hanseuljun** [comment]
In case you don't know much about Unreal, I don't think you would be able to go through all steps for using libdatachannel in Unreal for HoloLens2. Also, in case your goal does not include usage of things like TURN, and is more like a prototype, you don't need libdatachannel. I would rather recommend usage of a networking module included in Unreal in your case.
