### ISSUE TITLE
Race condition on libjuice agent destruction

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libdatachannel#43]
Using libjuice and libdatachannel, i'm facing an invalid access to the underlying ice agent when disconnecting and deleting the peerconnection.

I'm destroying the peerconnection to make room for a new one when refreshing the browser (other peer), but doing that, sometimes (due to threads in action?), agent_run triggers the agent_do_destroy before the ~IceTransport destructor. This destructor is then calling agent_destroy on an already freed agent.

If the icetransport destructor is called before the end of agent_run, everything is fine. Am i missing something to properly trigger these in order everytime ?

**Comment by paniksystem** [comment]
Looks like this happens when recvfrom fails inside agent_run, making it exit the loop and destroy the agent

**Comment by paullouisageneau** [comment]
Good catch, it seems that it's not even a race condition, I actually forgot the test when the thread terminates to destroy the agent only if its destruction has been requested. For some reason the connectivity test doesn't crash.

**Comment by paniksystem** [comment]
Maybe you also need to release the agent mutex?

**Comment by paniksystem** [comment]
i ended up doing this to fix it:

```
if (len < 0) {
	JLOG_ERROR("recvfrom failed, errno=%d", sockerrno);
	agent->thread_started = false;
	pthread_mutex_unlock(&agent->mutex);
	agent_change_state(agent, JUICE_STATE_DISCONNECTED);
	return;
	//break;
}
```

**Comment by paullouisageneau** [comment]
> Maybe you also need to release the agent mutex?

Oh, yes indeed. Your solution works except in the edge case where destruction is requested, and at the same moment recvfrom fails.

**Comment by paniksystem** [comment]
Oh i thought it was precisely the case that was fixed by this :D anyway thank you

**Comment by paullouisageneau** [comment]
FYI, I took the opportunity to add a proper thread interruption mechanism to libjuice, which allows to join the thread on destruction: https://github.com/paullouisageneau/libjuice/commit/dd3a5375b5fcc0e6122217dbf22af55bd6910ec3
