### ISSUE TITLE
Include dependencies in releases

### ISSUE THREAD

**Issue by asgeir** [paullouisageneau/libdatachannel#434]
You have a few non-optional dependencies and some optional dependencies. The .tar.gz and .zip files do include the .gitmodules file so that eliminates some of the guesswork, but the refs for the modules are not included so it's somewhat difficult to do a correct build without doing a git checkout.

Do you think you could include the code for all the `deps/` modules in the release archives? If not, then could you at the very least include the non-optional dependencies (plog, usrsctp, and maybe json)?

**Comment by paullouisageneau** [comment]
I merely tag the versions for usage with git, the zip files are an automatic GitHub feature. Sadly, there seems to be no way to configure GitHub to add submodules to release archives. I would need to have my own release system to do so, which might be worth it but will take some time to setup.

You can create a zip with submodules from the git repository yourself with something like:
```
$ git checkout vX.Y.Z
$ git submodule update --init --recursive
$ git archive -o release.zip HEAD
$ git submodule --quiet foreach "cd $toplevel; zip -ru release.zip $sm_path"
```

**Comment by asgeir** [comment]
Should I close the issue or do you think you'll revisit this in the future?

**Comment by paullouisageneau** [comment]
I'm closing it as it seems to be a GitHub limitation. I'll try to setup my own release archives at some point though.
