### ISSUE TITLE
Certificate pinning dTLS

### ISSUE THREAD

**Issue by LeoNavel** [paullouisageneau/libdatachannel#435]
Hi Paul,

we need to allow webrtc connection for trusted clients only. We know their certificate and public key. Is it possible to provide client's certificate (or public key) to libdatachannel for dTLS?

**Comment by paullouisageneau** [comment]
I'm closing this, please reopen if needed.

**Comment by paullouisageneau** [comment]
There is no such mechanism for Websockets at the moment, I opened an issue about it: https://github.com/paullouisageneau/libdatachannel/issues/1249
