### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by sgowen** [paullouisageneau/libdatachannel#44]
https://github.com/chadnickbok/librtcdcpp mentions Android/iOS support explicitly.

I know this project was inspired by librtcdcpp, but is built from scratch.
Any reason why I couldn't use this on Andorid and iOS?

**Comment by paullouisageneau** [comment]
I think it should work fine, however I haven't tested for now.
In particular I don't see any blocking point for compiling it with the Android NDK.

**Comment by sgowen** [comment]
Thank you for your reply. I'll give it a test drive and let you know how it goes.

**Comment by paullouisageneau** [comment]
OK great, keep me informed!

**Comment by paullouisageneau** [comment]
Any news on this? Compilation on Android should be fixed since https://github.com/paullouisageneau/libdatachannel/issues/98

**Comment by sgowen** [comment]
Got pulled in to other projects. Not sure when I will be able to revisit this. Thank you for the update on #98 though!

**Comment by paullouisageneau** [comment]
I'm closing this for now, please re-open if you run into issues.
