### ISSUE TITLE
Force use of relay candidates only

### ISSUE THREAD

**Issue by dbotha** [paullouisageneau/libdatachannel#449]
Hi Paul-Louis,

I might be overlooking things but is it possible to force consideration of relay candidates only - in the browser API you can set the [`RTCConfiguration.iceTransportPolicy = "relay"`](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration/iceTransportPolicy) but the same doesn't appear possible in libdatachannel. Useful for testing my infrastructure setup is working as I hope 😅  

Kind regards,

Deon

**Comment by paullouisageneau** [comment]
A similar setting would indeed be a good enhancement.

For now, you can filter candidates according to `candidate.type()` to forward only the ones with `Type::Relayed`.

**Comment by dbotha** [comment]
Thanks @paullouisageneau - I'll do that, I wasn't sure if just provided the relay candidates would work 👍

**Comment by paullouisageneau** [comment]
I added a `iceTransportPolicy` option to the configuration for consistency with the Web API in https://github.com/paullouisageneau/libdatachannel/pull/452. Under the hood it does the same as filtering the candidates.

**Comment by dbotha** [comment]
Amazing thanks @paullouisageneau
