### ISSUE TITLE
Failed to compile the Android platform dynamic library on macOS

### ISSUE THREAD

**Issue by chenhucxc** [paullouisageneau/libdatachannel#467]
cmake -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
      -DCMAKE_TOOLCHAIN_FILE="${NDK_ROOT}/build/cmake/android.toolchain.cmake" \
      -DANDROID_NDK="${NDK_ROOT}" \
      -DANDROID_NATIVE_API_LEVEL=${API_LEVEL} \
      -DANDROID_ARM_NEON=ON \
      -DANDROID_ABI="$ABI" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=OFF \
      -DANDROID_STL="c++_static" \
      -DUSE_GNUTLS=0 \
      -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl@1.1" \
      -DUSE_NICE=0 \
      ../../
  make -j${N_JOBS}

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.21/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
  deps/libsrtp/CMakeLists.txt:61 (find_package)

**Comment by chenhucxc** [comment]
% which openssl
/usr/local/opt/openssl@1.1/bin/openssl
%openssl version -a
OpenSSL 1.1.1l  24 Aug 2021
built on: Tue Aug 24 13:38:47 2021 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
OPENSSLDIR: "/usr/local/etc/openssl@1.1"
ENGINESDIR: "/usr/local/Cellar/openssl@1.1/1.1.1l/lib/engines-1.1"
Seeding source: os-specific

**Comment by paullouisageneau** [comment]
The issue is that you are trying to make an Android build (probably armv7/armv8) link against a MacOS x86_64 build of OpenSSL.

Instead, you need to retrieve the OpenSSL source and build it for the Android architectures you target.

**Comment by chenhucxc** [comment]
Thank you for your answer. Now I have compiled it successfully
I compiled OpenSSL for Android platform

OPENSSL_SO_DIR="/Users/xxx/build-openssl"

cmake -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
      -DCMAKE_TOOLCHAIN_FILE="${NDK_ROOT}/build/cmake/android.toolchain.cmake" \
      -DANDROID_NDK="${NDK_ROOT}" \
      -DANDROID_NATIVE_API_LEVEL=${API_LEVEL} \
      -DANDROID_ARM_NEON=ON \
      -DANDROID_ABI="$ABI" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=OFF \
      -DANDROID_STL="c++_static" \
      -DOPENSSL_INCLUDE_DIR=${OPENSSL_SO_DIR}/include \
      -DOPENSSL_SSL_LIBRARY="${OPENSSL_SO_DIR}/lib/libssl.so" \
      -DOPENSSL_CRYPTO_LIBRARY="${OPENSSL_SO_DIR}/lib/libcrypto.so" \
      -DUSE_GNUTLS=0 \
      -DUSE_NICE=0 \
      ../../
  make -j${N_JOBS}

  cd ../
