### ISSUE TITLE
My local description information is complete, but the description.value() I get is missing information in ios platform

### ISSUE THREAD

**Issue by qingyangzuijiao** [paullouisageneau/libdatachannel#468]
**1. my localDescription debug content:**

(std::optional<rtc::Description>) $0 =  Has Value=true  {
  Value = {
    mType = Offer
    mRole = ActPass
    mUsername = "rtc"
    mSessionId = "186324525"
    mIceUfrag =  Has Value=true  {
      Value = "u0fB"
    }
    mIcePwd =  Has Value=true  {
      Value = "ncGj4ZKnBMxyd/unJCEcoW"
    }
    mFingerprint =  Has Value=true  {
      Value = "AF:20:13:73:55:F4:76:56:31:E5:47:C9:2D:B6:5E:DA:35:B2:09:D1:81:DE:CF:0E:D5:B8:EA:3C:74:C2:52:1A"
    }
    mEntries = size=0 {}
    mApplication = nullptr {
      __ptr_ = nil
    }
    mCandidates = size=2 {
      [0] = {
        mFoundation = "1"
        mComponent = 1
        mPriority = 2122317823
        mTypeString = "host"
        mTransportString = "UDP"
        mType = Host
        mTransportType = Udp
        mNode = "192.168.13.112"
        mService = "62912"
        mTail = ""
        mMid =  Has Value=true  {
          Value = "0"
        }
        mFamily = Ipv4
        mAddress = "192.168.13.112"
        mPort = 62912
      }
      [1] = {
        mFoundation = "2"
        mComponent = 1
        mPriority = 1686110207
        mTypeString = "srflx"
        mTransportString = "UDP"
        mType = ServerReflexive
        mTransportType = Udp
        mNode = "180.164.177.98"
        mService = "62912"
        mTail = "raddr 0.0.0.0 rport 0"
        mMid =  Has Value=true  {
          Value = "0"
        }
        mFamily = Ipv4
        mAddress = "180.164.177.98"
        mPort = 62912
      }
    }
    mEnded = true
  }
}

**2. my desciption.value() content:**
v=0

o=rtc 3140320631 0 IN IP4 127.0.0.1

s=-

t=0 0

a=group:BUNDLE

a=msid-semantic:WMS *

a=setup:actpass

a=ice-ufrag:ObTt

a=ice-pwd:Ojvlatd6LTHwNJ8PpWz3e5

a=fingerprint:sha-256 3F:A0:31:36:9C:85:75:C7:32:CE:E5:90:AB:E7:80:33:DE:81:94:A4:37:2A:06:D3:D0:8C:74:1C:7E:33:11:7D

**Comment by qingyangzuijiao** [comment]
I have set these contents according to the way of writing datachannel-media main.cpp。
```
    static std::shared_ptr<rtc::PeerConnection> pc_;

- (void)viewDidLoad {
    [super viewDidLoad];
    [self setupChannel];
}

- (void)setupMQTT {
    [[ZMMQTTServices sharedServices] configHttpsHost:@"" mqttHost:@"101.132.24.42" mqttPort:1883];
    [[ZMMQTTServices sharedServices] configMQTTUserName:@"wanghongjiang" password:@"123456"];
    [ZMMQTTServices sharedServices].connected = ^{
        NSString *topic = [NSString stringWithFormat:@"%@%@", TOPIC_ANSWER, testVId];
        [ZMMQTTServices subscribeTopic:topic qos:ZMMQTTQosLevelAtMostOnce];
        pc_->setLocalDescription();
    };

    [ZMMQTTServices sharedServices].receiverHandler = ^(NSDictionary * _Nonnull result) {
        ZMLog(@"===receiverHandler======result:%@", result);
        if ([result[@"type"] isEqualToString:@"answer"]) {
            std::string sdp = [result[@"sdp"] UTF8String];
            std::string type = [result[@"type"] UTF8String];
            rtc::Description answer(sdp, type);
            pc_->setRemoteDescription(answer);
        }
    };
}

/// 发送信息
/// @param dict 信息
- (void)sendOff:(NSDictionary *)dict {
    NSError * error = nil;
    NSData * jsonData = [NSJSONSerialization dataWithJSONObject:dict options:NSJSONWritingPrettyPrinted error:&error];
    NSString * jsonStr = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
    [ZMMQTTServices publishMessage:jsonStr toTopic:[NSString stringWithFormat:@"%@%@", TOPIC_OFFER, testVId]];
}

- (void)setupChannel {
    // 1.Signal a PeerConnection
    // 配置config
    rtc::Configuration config;
    config.iceServers.emplace_back("stun:stun.stunprotocol.org:3478");
    
    // 创建PeerConnection
    auto pc = std::make_shared<rtc::PeerConnection>(config);
    pc_ = pc;
    
    // 2.Observe the PeerConnection state
    pc->onStateChange([](rtc::PeerConnection::State state) {
        std::cout << "State: " << state << std::endl;
    });

    pc->onGatheringStateChange([self, pc](rtc::PeerConnection::GatheringState state) {
        std::cout << "Gathering state: " << state << std::endl;
        std::cout << "Gathering State: " << state << std::endl;
        if (state == rtc::PeerConnection::GatheringState::Complete) {
            auto description = pc->localDescription();
            std::cout << "description:" << description->generateSdp("\r\n") << std::endl;
            NSDictionary *message = @{
                @"type": [NSString stringWithFormat:@"%s", description->typeString().c_str()],
                @"sdp": [NSString stringWithFormat:@"%s", std::string(description->generateSdp("\r\n")).c_str()],
            };
            NSLog(@"message:%@", message.description);
            [self sendOff:message];
        }
    });
    
    //
    rtc::Description::Video media("video", rtc::Description::Direction::RecvOnly);
    media.addH264Codec(96);
    media.setBitrate(
        3000); // Request 3Mbps (Browsers do not encode more than 2.5MBps from a webcam)

    auto track = pc->addTrack(media);

    auto session = std::make_shared<rtc::RtcpReceivingSession>();
    track->setMediaHandler(session);

    track->onMessage([session](rtc::binary message) {
            // This is an RTP packet
//            sendto(sock, reinterpret_cast<const char *>(message.data()), int(message.size()), 0,
//                   reinterpret_cast<const struct sockaddr *>(&addr), sizeof(addr));
        std::cout << "RTP packet:" << message.size() << std::endl;
        },
        nullptr);
    std::string sdp;
    std::cout << "Press any key to exit." << std::endl;
    std::cin >> sdp;

    [self setupMQTT];
}
```

**Comment by qingyangzuijiao** [comment]
Among them, I found through debugging that mEntries.size() is 0, and it seems that mEntries.emplace_back() has not been called

**Comment by paullouisageneau** [comment]
Oh, I see. You need to store pointers to tracks (like pointers to data channels). Here, the track will be destroyed at the end of `setupChannel` when `track`  is released, meaning there is no track left in the PeerConnection when you call `setLocalDescription()`.

**Comment by qingyangzuijiao** [comment]
Thank you very much, it is indeed caused by the release of the track. After storing the track, I can get the correct local description.
