### ISSUE TITLE
Why change export name?

### ISSUE THREAD

**Issue by KangLin** [paullouisageneau/libdatachannel#474]
Changed the export name will change the forward compatibility.

https://github.com/paullouisageneau/libdatachannel/blob/a17eea83ab93991c04568c6e9653dfb9e71f92ed/CMakeLists.txt#L354

**Comment by paullouisageneau** [comment]
I changed the export name because it was inconsistent: local export name was `LibDataChannel::LibDataChannel` while after installing it became `LibDataChannel::datachannel`. It's true that it breaks compatibility, that's why it won't be released in 0.14.x.

**Comment by paullouisageneau** [comment]
Thinking about it, it could be exported as an alias with a manually-generated config file.

**Comment by paullouisageneau** [comment]
I added an alias to allow forward compatibility in #475.

**Comment by paullouisageneau** [comment]
I added an alias for backward compatibility in #475.
