### ISSUE TITLE
Undefined reference when linking

### ISSUE THREAD

**Issue by JanErikFoss** [paullouisageneau/libdatachannel#476]
Hi,

I'm struggling with some linker errors. 

    // root CMakeLists.txt
    
    add_subdirectory(thirdparty/libdatachannel)
    add_subdirectory(thirdparty/libdatachannel/deps/json)

    // CMakeLists.txt of the module where I need libdatachannel
    
    find_package(Threads REQUIRED)
    target_link_libraries(xxxxxx
        PUBLIC
            LibDataChannel::LibDataChannel
            nlohmann_json
            Threads::Threads
    )
    
    
    // module.cpp
    
    #include "rtc/rtc.hpp"
    void test() {
        rtc::Configuration config;
        config.iceServers.emplace_back("stun2.l.google.com:19302");
    }
    

Everything is fine until linking

    [107/107] Linking CXX executable xxxxxx
    FAILED: xxxxxx
    in function `void std::vector<rtc::IceServer, std::allocator<rtc::IceServer> >::_M_realloc_insert<char const (&) [25]>(__gnu_cxx::__normal_iterator<rtc::IceServer*, std::vector<rtc::IceServer, std::allocator<rtc::IceServer> > >, char const (&) [25])':
     /usr/include/c++/9.3.0/ext/new_allocator.h:147: undefined reference to `rtc::IceServer::IceServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
     collect2: error: ld returned 1 exit status
     ninja: build stopped: subcommand failed.
    

Symbols do not seem to be exported

    nm --demangle --dynamic --defined-only --extern-only libdatachannel.so | grep "IceServer"
    // nothing
    
However I can see them if I just do

    nm -C libdatachannel.so | grep "IceServer"
    
    001dc140 b guard variable for rtc::IceServer::IceServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::r
    0004c478 t rtc::IceServer::IceServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    0004c61c t rtc::IceServer::IceServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, rtc::IceServer::RelayType)
    // etc...
    
Anyone have some ideas I could try?

**Comment by JanErikFoss** [comment]
Just tried static linking, which seems to work. Dynamic is required for my use case though.

**Comment by paullouisageneau** [comment]
Thanks for reporting the issue.

> Symbols do not seem to be exported
> 
> ```
> nm --demangle --dynamic --defined-only --extern-only libdatachannel.so | grep "IceServer"
> // nothing
> ```

This is indeed the problem. Since it works with static linking, I guess it has something to do with default symbol visibility. 

Is libdatachannel compiled with specific flags? I'm thinking for instance of `-fvisibility=hidden`, which would result in a similar behavior. Also, do libdatachannel examples link correctly ?

**Comment by JanErikFoss** [comment]
> -fvisibility=hidden

That was it!

Adding the target property _CXX_VISIBILITY_PRESET default_ to the _datachannel_ target solved the issue.
Thank you so much for taking the time to look at this.
