### ISSUE TITLE
Error  running build/examples/streamer

### ISSUE THREAD

**Issue by upanitag** [paullouisageneau/libdatachannel#477]
Hi,
I am getting the following error when running the example in streamer in the browser.

OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='video-stream'.

I am doing the default option; ./streamer

Thanks,
nita

**Comment by upanitag** [comment]
I am using Chromium Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.10 (64-bit)

**Comment by paullouisageneau** [comment]
The video description is probably rejected because your Chromium build lacks h264 video support. Chromium needs to be compiled with the GN options `proprietary_codecs=true ffmpeg_branding=Chrome`.

**Comment by upanitag** [comment]
Okay. Thanks. 

Are these compressed H264 media files ?https://github.com/paullouisageneau/libdatachannel/tree/master/examples/streamer/samples/h264

**Comment by paullouisageneau** [comment]
> Are these compressed H264 media files ?https://github.com/paullouisageneau/libdatachannel/tree/master/examples/streamer/samples/h264

Yes indeed. It would be possible to achieve a similar streaming with VP8, however this would require some work.
