### ISSUE TITLE
Using h.264 video with C API

### ISSUE THREAD

**Issue by eh4** [paullouisageneau/libdatachannel#502]
Hello

I have been trying to use the C API for streaming video (no audio), without much luck. Unfortunately there are a lot of variables here that I could have wrong so it's hard to incrementally troubleshoot.

The documentation shows "int rtcAddTrack(int pc, const char *mediaDescriptionSdp)", but doesn't really elaborate on what is required, other than an "m-line and mid parameter", and I don't have enough familiarity with this system to know what's needed/valid, or if additional parameters are necessary for h.264.

In the header file, there is also rtcAddTrackEx, which seems much easier to follow, but has a number of mystery components as well. Looking at the required items, there are direction and codec, which seem straightforward to use with RTC_DIRECTION_SENDONLY and RTC_CODEC_H264. However, payloadType, ssrc, and mid don't have much explanation with them. I tried to figure it out using Google and looking what Firefox sends when it offers video.
* payloadType, I have read that 96-127 are used for dynamic mapping in h.264 so I set it to 100.
* ssrc just seems to be for keeping track of the connection, so can be any random number you want? This is what I see in Firefox. I chose to use 1. My output SDP is missing a cname which is present in the Firefox SDP and the C++ streamer example. 
* mid also looks to be arbitrary and used as a track identifier (like ssrc). The c++ streamer uses "video-stream" and "audio-stream" while firefox uses "1". I set mine to "test".
* The other two options I left as 0 since they were identified as optional.

Now that the track is set up, I tried to send data using rtcSendMessage but it just hangs for a while and returns -2 or RTC_ERR_FAILURE. The rtcSendMessage explanation doesn't say what format the data is supposed to be in, so for my testing I used a .h264 file recorded from a raspberry pi camera. It starts with 00 00 00 01 and has that sequence between the NAL units. The example h264 files for the streamer seem to be formatted differently.

Next I see there is a rtcSetH264PacketizationHandler function, which looks promising. It also has a list of required settings which I will have to figure out.
* ssrc is set to 1 to match the ssrc above
* cname is set to "testcname"
* payloadType is set to 100 as above
* clockRate is set to 90000
* maxFragmentSize I assume has to do with ethernet packet size so I set this to 1200
* sequenceNumber and timestamp are set to zero

At this point the program gives a core dump and the message "Assertion `naluEndIndex <= message->size()' failed" shows up. This is where I leave off, as I have so many config variables that I just guessed at that it I have no idea what is wrong.

Looking at the C++ streamer example, it seems like there is some custom H.264 parsing needed to split data into NALUs. Is this done instead of using the H264 packetization handler? Or is it done as a pre-processing step before the packetization handler? Do you have to do rtcSendMessage with one NAL at a time only?

**Comment by paullouisageneau** [comment]
Indeed, the media API is not obvious to use and scarcely documented. It's also very low-level, so nothing is automatic.

> The documentation shows "int rtcAddTrack(int pc, const char *mediaDescriptionSdp)", but doesn't really elaborate on what is required, other than an "m-line and mid parameter", and I don't have enough familiarity with this system to know what's needed/valid, or if additional parameters are necessary for h.264.

Basically `rtcAddTrack` is useful when you want to connect an existing encoding pipeline giving you the SDP and outputting RTP packets.

> In the header file, there is also rtcAddTrackEx, which seems much easier to follow, but has a number of mystery components as well. Looking at the required items, there are direction and codec, which seem straightforward to use with RTC_DIRECTION_SENDONLY and RTC_CODEC_H264. However, payloadType, ssrc, and mid don't have much explanation with them. I tried to figure it out using Google and looking what Firefox sends when it offers video.

Yes it's not obvious, the settings must actually match the RTP stream you are going to send for this track, as it also covers the case where you send your own RTP packets directly from the encoding pipeline.

> Now that the track is set up, I tried to send data using rtcSendMessage but it just hangs for a while and returns -2 or RTC_ERR_FAILURE. The rtcSendMessage explanation doesn't say what format the data is supposed to be in, so for my testing I used a .h264 file recorded from a raspberry pi camera. It starts with 00 00 00 01 and has that sequence between the NAL units. The example h264 files for the streamer seem to be formatted differently.

By default, `rtcSendMessage` expects RTP packets for a Track, while you have h264 raw file, which consists in the unpacketized encoded data: it lacks the timestamps and identifiers (SSRC, etc).

> Next I see there is a rtcSetH264PacketizationHandler function, which looks promising. It also has a list of required settings which I will have to figure out.

You guessed right, setting the H264 packetization handler to the track makes it accept h264 samples. They will be processed by the handler into RTP packets.

You settings are correct, but note you have to handle the timestamp yourself with `rtcSetTrackRtpTimestamp`. The timestamp is part of the metadata of the sample, but if you don't have it you may just convert the current time with `rtcTransformSecondsToTimestamp`.

> At this point the program gives a core dump and the message "Assertion `naluEndIndex <= message->size()' failed" shows up.

I think this comes from the fact the NAL unit separator is incorrectly set. It is sadly not exposed on the C API and defaults to 32-bit length between NAL units, while your sample uses the long start sequence 00 00 00 01. I'll add the setting to the C API.

> Looking at the C++ streamer example, it seems like there is some custom H.264 parsing needed to split data into NALUs. Is this done instead of using the H264 packetization handler? Or is it done as a pre-processing step before the packetization handler? Do you have to do rtcSendMessage with one NAL at a time only?

You don't need to split the data into NAL units if your h264 file is a sample, you can send the whole sample directly. The streamer example does it mostly as an optimisation to send keyframes immediately to new clients.

If your h264 is not a sample but a dump of the whole video, then it's trickier as you have to read it to retrieve the sequence of NAL units fro each frame. You also have to know the video frame rate and replay the frames at the correct rate.

**Comment by MagicAtom** [comment]
So could you please tell me the difference between a sample and the whole h264 file, I have little knowledge about sample
