### ISSUE TITLE
How to build static version?

### ISSUE THREAD

**Issue by jeffRTC** [paullouisageneau/libdatachannel#519]
Does `cmake -B build -DUSE_GNUTLS=1 -DUSE_NICE=0` build static version as-well?

Also, I did the make install which printed,

`-- Installing: /usr/local/lib/libdatachannel.so.0.15.5
-- Installing: /usr/local/lib/libdatachannel.so`

I'm not using CMake on my project so I have to link the lib via shell.  A silly mistake but have to live with that now.

**Comment by paullouisageneau** [comment]
The static version corresponds to the CMake target `datachannel-static`, you can build it with `cd build; make datachannel-static` after running `cmake -B build [...]`. Note libdatachannel is under LGPL, so there are [license requirements](https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic) to statically link against it.

**Comment by jeffRTC** [comment]
Okay

**Comment by jeffRTC** [comment]
@paullouisageneau 

I tried  your build commands and `-Llibdatachannel/build -l:libdatachannel-static.a` but it gives me,

```
/usr/bin/ld: libdatachannel/build/libdatachannel-static.a(tlstransport.cpp.o): in function `rtc::impl::TlsTransport::ReadCallback(void*, void*, unsigned long)':
tlstransport.cpp:(.text+0x22e1): undefined reference to `gnutls_transport_set_errno'
/usr/bin/ld: tlstransport.cpp:(.text+0x2305): undefined reference to `gnutls_transport_set_errno'
/usr/bin/ld: tlstransport.cpp:(.text+0x2469): undefined reference to `gnutls_transport_set_errno'
```

**Comment by paullouisageneau** [comment]
You must now link your application itself against gnutls (the dynamic library libdatachannel.so was linked against gnutls). You need to add `-lgnutls` to the linker command.

**Comment by jeffRTC** [comment]
> You must now link your application itself against gnutls (the dynamic library libdatachannel.so was linked against gnutls). You need to add `-lgnutls` to the linker command.

But that makes gnutls non static, no? I want everything to be static. Is it possible to build static version of gnutls?

**Comment by paullouisageneau** [comment]
Sure, you can build gnutls as a static library and link it instead of linking against the dynamic library provided by your OS. If you really want everything to be static, you should also statically link the C and C++ runtime libraries with the flag `-static`.

**Comment by jeffRTC** [comment]
This is how I link the libs,

```
-pthread -lgnutls -lcrypto -lssl \
 -Ilibdatachannel/build/deps/libjuice\
 -Ilibdatachannel/deps/libjuice/include\
 -Ilibdatachannel/deps/libsrtp/include\
 -Ilibdatachannel/deps/usrsctp/usrsctplib\
 -Llibdatachannel/build/deps/usrsctp/usrsctplib -l:libusrsctp.a\
 -Llibdatachannel/build/deps/libsrtp -l:libsrtp2.a\
 -Llibdatachannel/build/deps/libjuice -l:libjuice-static.a\
 -Llibdatachannel/build -l:libdatachannel-static.a
```

Yet I'm still seeing bunch of undefined errors,

```
dtlssrtptransport.cpp:(.text+0x16af): undefined reference to `srtp_unprotect_rtcp'
/usr/bin/ld: sctptransport.cpp:(.text+0xdd1): undefined reference to `usrsctp_setsockopt'
/usr/bin/ld: icetransport.cpp:(.text+0xae0): undefined reference to `juice_create'
```

**Comment by paullouisageneau** [comment]
The order of libraries is important, as the linker will look for unresolved symbols in a library only in libraries that come after. You must set libdatachannel first, followed by its dependencies.

**Comment by jeffRTC** [comment]
It works, I had to link libnettle too.
