### ISSUE TITLE
RtpPacketizationConfig::getTimestampFromSeconds may trigger undefined behavior

### ISSUE THREAD

**Issue by asgeir** [paullouisageneau/libdatachannel#521]
RtpPacketizationConfig::getTimestampFromSeconds converts the result of `seconds * clockRate` to uint32_t but this has undefined behavior if the resulting value exceeds `0xffffffff`.

I got bitten by this when targeting a particular 32-bit ARMv7 where the operation will saturate rather than overflow so all timestamps end up being `0xffffffff`.

**Comment by paullouisageneau** [comment]
Ow, good catch! Overflow when casting a float to an integer indeed causes undefined behavior.

**Comment by paullouisageneau** [comment]
Thanks for reporting, this should be fixed in https://github.com/paullouisageneau/libdatachannel/pull/522
