### ISSUE TITLE
How to stream raw H264 frame

### ISSUE THREAD

**Issue by MagicAtom** [paullouisageneau/libdatachannel#523]
I am a green-hand of webrtc. And I am just trying to use the raw h264 frame instead of samples from file in the streamer example. So which confuses me is, is there any difference between the raw h264 frame and the sample. I know it maybe a naive question. Hope it not bother.

**Comment by MagicAtom** [comment]
I see the issue stated below, which is useful.

**Comment by paullouisageneau** [comment]
> I see the issue stated below, which is useful.

For reference: https://github.com/paullouisageneau/libdatachannel/issues/502

To answer, your question, in the example, the samples correspond to frames. If you have raw h264 frames, you can send the directly with the RTP handler, you just have to handle timestamps yourself.

**Comment by MagicAtom** [comment]
I have read the #325, and I think make the frames to sample is also okay?

**Comment by paullouisageneau** [comment]
Yes, just make sure to set the separator to the right one.

**Comment by MagicAtom** [comment]
Thanks a lot for your helping hand. And my way to solve this problem is, first I encode the opengl buffer to H264 packets within the ffmpeg. And just cast the buffer to sample is okay, no need to glue. I think it's because the ffmpeg automatilly glued the nalunits having the same timestamp. And here's my repo https://github.com/MagicAtom/opengl-webrtc-streamer, thanks a lot for all of your's helping hand.

**Comment by paullouisageneau** [comment]
> And my way to solve this problem is, first I encode the opengl buffer to H264 packets within the ffmpeg. And just cast the buffer to sample is okay, no need to glue. I think it's because the ffmpeg automatilly glued the nalunits having the same timestamp.

Indeed, this is a good solution, ffmpeg will give you the h264 frame with the corresponding NAL units glue togethers with separators, which you can send directly.

> And here's my repo https://github.com/MagicAtom/opengl-webrtc-streamer, thanks a lot for all of your's helping hand.

That's a cool project, I'm glad you got it working!
