### ISSUE TITLE
rtc::impl::Message is private but is still part of the public API

### ISSUE THREAD

**Issue by asgeir** [paullouisageneau/libdatachannel#524]
`rtc::impl::Message` is no longer part of the public API but is still required to implement `rtc::MediaHandler` and its descendants, this makes it somewhat challenging to implement a custom `rtc::MediaHandlerElement` (we are doing so to listen for PLI messages)

**Comment by paullouisageneau** [comment]
Indeed good point, you still need the `Message` for implementing custom elements. I partially reverted the change in https://github.com/paullouisageneau/libdatachannel/pull/525 to move the class back into the public API.
