### ISSUE TITLE
opus decode from chrome browser

### ISSUE THREAD

**Issue by deblauwetom** [paullouisageneau/libdatachannel#526]
Hello,

First, thanks for the great library! I could succesfully stream video and a datachannel to the browser from my embedded device, it's really cool... And now I am trying the other direction, namely from the browser with the microphone to my device. It works to get a stream of encoded packets coming in:
I added this media track:

```
std::shared_ptr<RtcPeerTrack> RtcPeer::createRtcAudioInputTrack(
    const uint8_t payloadType, const std::string cname, const std::function<void()> onOpen, std::function<void(rtc::binary)> onPcmData)
{
    auto audio = rtc::Description::Audio(cname, rtc::Description::Direction::RecvOnly);
    audio.addOpusCodec(payloadType);

    auto track = peerConnection->addTrack(audio);

    auto session = std::make_shared<rtc::RtcpReceivingSession>();
    track->setMediaHandler(session);
    track->onOpen(onOpen);
    track->onMessage(
        [this](rtc::binary opusMessage) {
            // => here I get data
            audioInputDecoder->addEncodedData(opusMessage);
        },
        nullptr);
    return std::make_shared<RtcPeerTrack>(track, nullptr);
}
```

So that gives me data packets, so that is great already. And it looks like the "libopus" decoder that I send the packets to always decodes something, but the resulting decoded pcm information looks and sounds strange. I found out that the libopus decoder always decodes something, no matter what the input data looks like, even random bytes. 

So that is difficult to debug, except writing the pcm values to a wav file, and see if it makes sense. To be sure, I tested my wav writer code by converting the opus sample data files in the streamer example to wav and that played perfect. So I am now suspecting the opus input data I get from the browser via the media reicv track is not really opus data. So I was wondering, is this code correct in assuming I will only receive encoded data in the onMessage function? Or should there be another layer after the RtcpReceivingSession somehow?

Or is there an example I should look into?
Thanks very much!

**Comment by paullouisageneau** [comment]
Hi, your intuition is correct. By default, when not handler is present, tracks send and receive RTP and RTCP datagrams. While the `RtcpReceivingSession` handles RTCP, the messages you receive are still RTP datagrams, so you have to remove the RTP header to feed only the payload to libopus.

To this end, you may use the utility structure `rtc::RTP` from `rtc/rtp.hpp` to parse the header.

**Comment by deblauwetom** [comment]
Hello,

Yes, that was the problem! Thanks for the help.

Now I get indeed correctly decoded opus packets, and I can hear my test audio, which is me saying something my built-in microphone in the Chrome browser.

Nothing to do with libdatachannel, but, the sound quality is really low. I can hear what I say in the microphone, but pretty distorted. I even tried with a simple sine wave and that looks like it somewhat, but bad quality. 
I don't get the quality like in for example the opus packets in the streamer example. These are CBR with 64kb bitrate, and the sound is very clear after decoding them. In the chromium source, I saw the encoder is created for 160kb bitrate, and yet I get worse sounding audio. So it's a mystery to me why.

**Comment by deblauwetom** [comment]
So, funny thing... I said I heard my voice, but it's very bad quality... turns out I only sent a small amount of the payload to the decoder... I did this:

`
auto rtpPacket = (const rtc::RTP*)message.data();
auto rtpPayloadSize = rtpPacket->getSize();
auto bufStart = reinterpret_cast<const std::byte*>(rtpPacket->getBody());
`

But that is totally not correct :) I only got like 12 bytes of the payload, and so the first part of the audio got decoded, and then the opus codec probably inserts something. anyways, this is the correct payload size:

`
auto rtpPayloadSize = message.size() - rtpPacket->getSize();
`

So now I have a high quality audio!

**Comment by paullouisageneau** [comment]
Good news, thanks for the update! Indeed, `getSize()` actually returns the size of the RTP header represented by `rtc::RTP` (as it's variable-length), which can be a bit misleading.

**Comment by zjkhahah** [comment]
After investigation, it was found that the high packet loss rate of UDP was the cause. What caused the high packet loss rate? Was it a bug in the library itself or a configuration error?

<img width="587" alt="Image" src="https://github.com/user-attachments/assets/e0bdea33-d734-4031-a8fd-888308e15a7a" />
