### ISSUE TITLE
Receiving session and multiple ssrc handling

### ISSUE THREAD

**Issue by deblauwetom** [paullouisageneau/libdatachannel#529]
Hello,
I was adding a recv track for audio to a rtc::PeerConnection and that works. But now I noticed that it's possible that a client opens the track multiple times and sends me data but as expected with different SSRC id. So my question is, can I somehow reject such a second session when it opens while there is already a session started? We have the "onOpen" handler of the track, but that does not return a value, so I don't know how I can somehow refuse the new incoming stream? I could filter the incoming packets but also, I don't know for sure the ssrc that will be used for the stream. I could of course remember the ssrc when the first packet arrives and from then on only accept packets with that ssrc until the onClose is called. What is the recommended approach?
Best regards

**Comment by paullouisageneau** [comment]
There is indeed no way to refuse a track in `onOpen()` as the track is already negotiated at that point. You could however close the track immediately, which will effectively filter out the corresponding SSRC.

The proper way to refuse an incoming track is during SDP negotiation. When a new track is added, it triggers an exchange of SDP descriptions via the signaling channel which creates the track on the remote side (contrary to Data Channels which are created in-band after the first SDP exchange). You may for instance modify the offer description containing the new track before calling `setRemoteDescription()`: create an `rtc::Description` from the incoming SDP description, deactivate the corresponding media with `setDirection(rtc::Description::Direction::Inactive)`, then pass the `rtc::Description` to `setRemoteDescription()` as usual.
