### ISSUE TITLE
SctpTransport::connect bind socket & MTU bugs

### ISSUE THREAD

**Issue by twisted89** [paullouisageneau/libdatachannel#534]
Currently the SctpTransport is using what is actually the remote port to bind locally, this should default to DEFAULT_SCTP_PORT if not provided by the user. 

Also, as can be seen commented here https://chromium.googlesource.com/external/webrtc/+/branch-heads/70/media/sctp/sctptransport.cc#631 setting the MTU should be done after connect, not before.

My local fix as reference:

`	

	void SctpTransport::connect() {
	if (!mSock)
		throw std::logic_error("Attempted SCTP connect with closed socket");
	PLOG_DEBUG << "SCTP connecting";
	changeState(State::Connecting);
    struct sockaddr_conn sconn = {};
	sconn.sconn_family = AF_CONN;
    sconn.sconn_port = htons(DEFAULT_SCTP_PORT);
	sconn.sconn_addr = this;
    #ifdef HAVE_SCONN_LEN
	sconn.sconn_len = sizeof(sconn);
    #endif

	if (usrsctp_bind(mSock, reinterpret_cast<struct sockaddr *>(&sconn), sizeof(sconn)))
		throw std::runtime_error("Could not bind usrsctp socket, errno=" + std::to_string(errno));

    sconn.sconn_port = htons(mPort);
	// According to RFC 8841, both endpoints must initiate the SCTP association, in a
	// simultaneous-open manner, irrelevent to the SDP setup role.
	// See https://tools.ietf.org/html/rfc8841#section-9.3
	int ret = usrsctp_connect(mSock, reinterpret_cast<struct sockaddr *>(&sconn), sizeof(sconn));
	if (ret && errno != EINPROGRESS)
        throw std::runtime_error("Connection attempt failed, errno=" + std::to_string(errno));

    // Set the MTU and disable MTU discovery.
    // We can only do this after usrsctp_connect or it has no effect.
        if (usrsctp_setsockopt(mSock, IPPROTO_SCTP, SCTP_PEER_ADDR_PARAMS, &spp, sizeof(spp)))
        throw std::runtime_error("Could not set socket option SCTP_PEER_ADDR_PARAMS, errno=" +
                                 std::to_string(errno));
    }
`

**Comment by paullouisageneau** [comment]
This might not be properly commented in the code, but the SCTP port is actually negotiated with SDP to be the same locally and remotely, as a result there is a unique SCTP port for the connection which is both bound and connected. [RFC 8841](https://datatracker.ietf.org/doc/html/rfc8841#section-9.3) says:
```
both endpoints MUST use the same SCTP port as client port and server port, 
in order to prevent two separate SCTP associations from being established.
```

I think the comment in the WebRTC codebase refers to a limitation in an old version of usrsctp. The MTU issue has been fixed in usrsctp since https://github.com/sctplab/usrsctp/commit/de0630dfeee51edb3a4b6119c9954a89ab87da21, so it should work fine. Doesn't changing `mtu` in `rtc::Configuration` work for you?

**Comment by twisted89** [comment]
Maybe this is a server config problem but I'll try and explain the issue I was encountering trying to connect to a webrtc server -

As a client I generated the SDP using setLocalDescription, this creates a description which explicitly states the SCTP port 

"a=sctp-port:5000"

Send this to the server, get a remote description with the following

"a=sctp-port:22586"

Negotiate ice/stun...

Now when attempting to connect via SCTP libdatachannel tries to send an init with a different port to what was sent in the initial description. This leads the client to abort as the server sends the SCTP init with the wrong dest port (5000 when we're actually using 22586).

Chrome/Firefox connect fine as they default to using 5000 as the local bind port, not the remote port.

**Comment by paullouisageneau** [comment]
Interesting, what is the WebRTC server software? The behavior seems to violate the WebRTC 1.0 spec (relying on RFC 8841), but it might have been acceptable according to older drafts.

**Comment by twisted89** [comment]
Yeah I think you're right, it's a 3rd party server which unfortunately I have no control over so you can close the issue and I'll stick with my local fix for the moment.

**Comment by paullouisageneau** [comment]
I'll look into it, I think it would be better for libdatachannel to handle this gracefully.

**Comment by paullouisageneau** [comment]
Actually, I might have misunderstood what the RFC says, as "client port and server port" may not mean local port and remote port here ("client" and "server" terms only make sense when referring to the underlying DTLS layer). It think it simply means that SCTP has to connect from the port it listens on, and not a new one, which would create a second association (I don't know why anyone would do that though).

I implemented support for different local and remote ports in https://github.com/paullouisageneau/libdatachannel/pull/535, which fixes the case where the remote peer answers with another non-default port. libdatachannel will still choose the same port as the remote peer when answering, so it doesn't break the previous behavior.
