### ISSUE TITLE
Crash on establishing connection (on Windows)

### ISSUE THREAD

**Issue by kuzux** [paullouisageneau/libdatachannel#538]
We're currently trying to build an application thast will send video data over webrtc. The application runs on windows and is built using c# (.net framework). Libdatachannel is used for providing the webrtc communication, a native dll loads libdatachannel, and then the c# side calls the native dll via P/Invoke. The signalling is done via a websocket connection (the websocket server is on the c# side and uses WebSocketSharp).

In our case, the JS "client" initiates the communication by sending an offer message via websocket. That message is then passed to setRemoteDescription. After setRemoteDescription is called, we get a sdp description in onLocalDescription. This is passed to the client over the websocket (as an answer message). The "client" also sends ice candidate messages afterwards, those are passed to addRemoteCandidate. 

The problem we're having is the program (the whole thing, both sides) quits abruptly before a data channel can be established. What we found is that the process  crashes some time after setRemoteDescription is called. The crash has no exception, and happens somewhere within ntdll (there are no libdatachannel code in the stack trace, the full stack trace from the debugger is here - https://imgur.com/0dr0i7N). The crash occurs whether addRemoteCandidate is called afterwards or not. Similarly, sending (or not sending) the sdp from the generated local description does not affect the crash.

The native side of the application is currently modelled after this simple example: https://github.com/paullouisageneau/libdatachannel/blob/master/examples/copy-paste/answerer.cpp

**Comment by paullouisageneau** [comment]
What version of libdatachannel do you run?

The "External code" mentions in the stack trace means the code in question has no debug info. Have you tried compiling libdatachannel in debug mode?

**Comment by kuzux** [comment]
On debug mode, the exception I get is: 
```
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.
```

and the stack trace looks like this - https://imgur.com/LBScsvz

**Comment by paullouisageneau** [comment]
OK, it means the problem is probably caused by mismatched calling conventions during compilation: libdatachannel calls the callbacks with one calling convention, but callbacks use another one in your program. It corrupts the call stack and leads to a crash later.

I think this is a similar issue as https://github.com/paullouisageneau/libdatachannel/pull/203, but for the C++ API: P/invoke in C# always assumes the stdcall convention for callbacks instead of the default cdecl.

If that's indeed the problem, compiling libdatachannel with the flag `/Gz` on Windows to force stdcall should solve it. Note targeting x64 would also work as this problem only happens with legacy x86.

**Comment by kuzux** [comment]
Alright, turns out the problem was not related to libdatachannel after all. It took me quite a while to figure that out. Here are the details so that I won't end up being that guy who just says "ok, fixed it" and ends the discussion.

============
unrelated explanation 

The issue, turns out, was related to interop between .net and native code (the code I've written) - there were a couple of callbacks defined as delegates in c# code that were called by the native code (passed as function pointers). .net runtime, by default, marshals functions with stdcall calling convention. I had explicitly marked the functions I defined on native side with CallingConvention.Cdecl on .net side. However, I forgot to mark the delegates I was passing to native side as cdecl. So, that caused all that headache.

**Comment by paullouisageneau** [comment]
Great! Thank you for taking the time to write the details.
