### ISSUE TITLE
Not working with Qt Creator on Android device

### ISSUE THREAD

**Issue by KuharenkoArtem** [paullouisageneau/libdatachannel#539]
I compiled the library for android armeabi-v7a and wrote a simple example to check the Client. When the program is launched on the phone, it cannot connect to the signaling server with webskets. On the Client function "wsFuture.get();" never called. When program compiled for linux it works fine. 

My repository with code:    https://github.com/KuharenkoArtem/LibdatachannelTest.git

Cmake command for compiling libdatachannel library: 

 cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/sergey/Android/Sdk/ndk/21.3.6528147/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_STL=c++_shared -DANDROID_NATIVE_API_LEVEL=android-26 -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_USE_STATIC_LIBS=1 -DOPENSSL_INCLUDE_DIR=/home/sergey/ThirdParty/openssl_for_ios_and_android/output/android/openssl-armeabi-v7a/include -DOPENSSL_CRYPTO_LIBRARY=/home/sergey/ThirdParty/openssl_for_ios_and_android/output/android/openssl-armeabi-v7a/lib/libcrypto.a -DOPENSSL_SSL_LIBRARY=/home/sergey/ThirdParty/openssl_for_ios_and_android/output/android/openssl-armeabi-v7a/lib/libssl.a

**Comment by paullouisageneau** [comment]
Could you please get the verbose with `rtc::InitLogger(rtc::LogLevel::Verbose, [callback])` and post it here please?

**Comment by KuharenkoArtem** [comment]
> Could you please get the verbose with `rtc::InitLogger(rtc::LogLevel::Verbose, [callback])` and post it here please?

D libWebRtcAndroid2.so: "rtc::Init::doInit@118: Global initialization"
D libWebRtcAndroid2.so: "rtc::impl::WebSocket::WebSocket@46: Creating WebSocket"
D libWebRtcAndroid2.so: "rtc::WebSocket::open@57: Opening WebSocket to URL: wss://ws.ifelse.io:443/5FAN"
D libWebRtcAndroid2.so: "rtc::impl::WebSocket::open@55: Opening WebSocket to URL: wss://ws.ifelse.io:443/5FAN"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::TcpTransport@41: Initializing TCP transport"
D libWebRtcAndroid2.so: "rtc::impl::WebSocket::setTcpTransport@193: Starting TCP transport"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::start@76: Starting TCP recv thread"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::connect@127: Connecting to ws.ifelse.io:443"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::connect@174: Trying address 213.188.199.36:443"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::connect@177: Creating TCP socket"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::connect@238: TCP connection to 213.188.199.36:443 succeeded"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::connect@144: Connected to ws.ifelse.io:443"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::runLoop@318: TCP connected"
D libWebRtcAndroid2.so: "rtc::impl::WebSocket::initTlsTransport@237: Starting TLS transport"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::TlsTransport@300: Initializing TLS transport (OpenSSL)"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::TlsTransport@335: Server Name Indication: ws.ifelse.io"
D libWebRtcAndroid2.so: "rtc::impl::VerifiedTlsTransport::VerifiedTlsTransport@34: Setting up TLS certificate verification"
D libWebRtcAndroid2.so: "rtc::impl::Transport::registerIncoming@58: Registering incoming callback"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::start@377: Starting TLS recv thread"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::send@101: Send size=435"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::incoming@109: Incoming size=1428"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::incoming@419: Incoming size=1428"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::incoming@109: Incoming size=2788"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::incoming@419: Incoming size=2788"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::InfoCallback@491: TLS alert: unknown CA"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::send@101: Send size=7"
D libWebRtcAndroid2.so: "rtc::impl::TlsTransport::runRecvLoop@481: TLS handshake failed"
D libWebRtcAndroid2.so: "rtc::impl::TcpTransport::runLoop@389: TCP disconnected"
D libWebRtcAndroid2.so: "rtc::impl::WebSocket::close@111: Closing WebSocket"
D libWebRtcAndroid2.so: "rtc::impl::WebSocket::closeTransports@372: Closing transports"

**Comment by paullouisageneau** [comment]
The problem seems to be that OpenSSL is compiled with an incorrect directory for root CA certificates (the setting is called `openssldir`). Therefore, it can't verify the certificate from the server as it doesn't know the CA and the TLS connection fails.

You have 3 possibilities:
- Set `disableTlsVerification = true` in `WebSocket::Configuration`. Note this will reduce security as the server certificate will be blindly trusted.
- Set the environment variable `SSL_CERT_DIR` to the proper directory (I think it's `/system/etc/security/cacerts` on Android), which should override the default in OpenSSL.
- Rebuild OpenSSL with the proper directory set as `openssldir`.

**Comment by KuharenkoArtem** [comment]
> You

Thank You very much!
