### ISSUE TITLE
Unable to create video stream

### ISSUE THREAD

**Issue by kuzux** [paullouisageneau/libdatachannel#540]
Hello there, what we're trying to do right now is that we have real-time video (screen recording) data as raw h264 frames. We want to transport this to the client using webrtc. To do that, we're establishing a webrtc connection, using websockets as the signalization channel (using libdatachannel as the webrtc library). We add a h264 track (payload type 102) to the connection. When we get the track open event, we start streaming the h264 frames. 

On the client side; a connection is established and an offer is created. A track is then added on the answerer side (the ontrack event is triggered on javascript). Through the webrtc-internals view (using chrome as the client); we can also see the data streaming from the remote. However, chrome-internals shows no track information and we get no display. 

We're currently guessing that there might be an issue with the sdp answer created by the webrtc library on the answerer side. The sdp generated by libdatachannel (and for reference, the sdp generated by sipsorcery - another webrtc library that we manage to produce a not-very-stable video stream with ) is here: https://gist.github.com/kuzux/1335bbe00c8789be974ab043a6300527

**Comment by paullouisageneau** [comment]
Hi, you said that you add only one h264 track with payload type 102 to the connection, but the libdatachannel description features a lot of other payload types:
```
m=video 9 UDP/TLS/RTP/SAVPF 35 36 37 96 97 98 99 100 101 102 107 108 109 114 115 116 118 119 120 121 122 123 124 125 127
```
This looks weird, how do you set up the track?

**Comment by kuzux** [comment]
Let me directly add the source here
```
globalConn = new rtc::PeerConnection(*globalConf);
rtc::Description::Video media("video");
media.addH264Codec(102);
media.setBitrate(32000);

uint32_t ssrc = 1;
std::string cname = "video-stream";
std::string msid = "stream1";

media.addSSRC(ssrc, cname, msid, cname);
globalTrack = globalConn->addTrack(media);

auto rtpConfig = std::make_shared<rtc::RtpPacketizationConfig>(ssrc, cname, 102, rtc::H264RtpPacketizer::defaultClockRate);
auto packetizer = std::make_shared<rtc::H264RtpPacketizer>(rtc::H264RtpPacketizer::Separator::StartSequence, rtpConfig);
auto h264handler = std::make_shared<rtc::H264PacketizationHandler>(packetizer);
auto srReporter = std::make_shared<rtc::RtcpSrReporter>(rtpConfig);
h264handler->addToChain(srReporter);
globalSender = srReporter;
auto nackResponder = std::make_shared<rtc::RtcpNackResponder>();
h264handler->addToChain(nackResponder);
globalTrack->setMediaHandler(h264handler);
```

It was supposed to be similar to `addVideo ` function in https://github.com/paullouisageneau/libdatachannel/blob/master/examples/streamer/main.cpp#L215
Is there something I'm missing?

**Comment by paullouisageneau** [comment]
This is strange, I wonder were all these codecs come from. Are you sure no track is already present in the original offer?

Note the setup looks weird as you are trying to add tracks in the answer. While it could work, WebRTC negotiation is not designed to work this way: a peer should send a offer each time it adds new tracks. Therefore, here it would be better that either libdatachannel makes the offer or the JavaScript client adds the track as receiving only.

**Comment by kuzux** [comment]
Alright, there were extra tracks present in the offer created by the browser. That turned out to be the main problem. Reversing the offer/answer negotiation (browser just sends an "initiate" message on the socket, libdatachannel creates track & sends an offer, browser receives the offer and sends an answer, libdatachannel starts streaming) solved the issue of no track being visible in webrtc-internals.

Thank you for the great help.
