### ISSUE TITLE
Can't create a DataChannel

### ISSUE THREAD

**Issue by kuzux** [paullouisageneau/libdatachannel#547]
Hello there again, now that I can send the video in a (relatively) stable way, the current issue I'm having is about creating data channels. What I'm doing right now is creating a data channel right after adding the tracks but before sending an offer (similar to how it's done in https://github.com/paullouisageneau/libdatachannel/blob/master/examples/streamer/main.cpp#L319). I also have `disableAutoNegotiation = true` in the settings so that creating a data channel does not automatically start the negotiation process. After doing that; I can see the data channel info in the SDP but neither the `onOpen` callback of the data channel nor the `ondatachannel` callback on the javascript side gets called after establishing the connection.

Here's the offer sdp:
```
v=0 
o=rtc 1499614174 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 video
a=group:LS video
a=msid-semantic:WMS *
a=setup:actpass
a=ice-ufrag:EluZ
a=ice-pwd:PNvoHIr/9LBhDtu+jHBAEO
a=fingerprint:sha-256 D3:AD:3A:6C:E4:B2:E6:09:3A:ED:27:A4:E3:8C:30:C5:C5:05:DA:81:EC:95:B0:DA:C4:1D:80:9B:E6:14:A9:AD
m=application 57346 UDP/DTLS/SCTP webrtc-datachannel 
c=IN IP4 10.21.10.30
a=bundle-only
a=mid:0
a=sendrecv
a=sctp-port:5000
a=max-message-size:262144
a=candidate:1 1 UDP 2122317823 10.21.10.30 57346 typ host
a=candidate:2 1 UDP 1686110207 34.245.221.153 57346 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
m=video 57346 UDP/TLS/RTP/SAVPF 107 123 
c=IN IP4 10.21.10.30
b=AS:32000
a=bundle-only
a=mid:video
a=sendonly
a=ssrc:1 cname:video-stream
a=rtcp-mux
a=rtpmap:107 RTX/90000
a=fmtp:107 apt=123
a=rtpmap:123 H264/90000
a=rtcp-fb:123 nack
a=rtcp-fb:123 goog-remb
a=fmtp:123 profile-level-id=42e01f;packetization-mode=1;level-asymmetry-allowed=1
```

**Comment by paullouisageneau** [comment]
You should check no callback is blocked. To prevent race conditions, the Peer Connection opens Tracks and Data Channels sequentially, so here the simplest explanation is that the `onOpen` callback of the Track does not return, preventing the Data Channel from opening.

If the issue happens while no callback is blocked, could you please post the verbose log?

**Comment by kuzux** [comment]
Just checked that the track onOpen handler does not block. It just creates a new thread for the main capture loop. 

About the verbose log: how do I get it? Is it a config option? Or a switch I need to enable when compiling?

**Comment by paullouisageneau** [comment]
> About the verbose log: how do I get it? Is it a config option? Or a switch I need to enable when compiling?

There is a global function to initialize the log that you should call at the beginning of the program: https://github.com/paullouisageneau/libdatachannel/blob/6e818ebb2517cb693ee4713f40cff9e33717fb84/include/rtc/global.hpp#L42

For instance `rtc::InitLogger(rtc::LogLevel::Verbose)` will output the verbose log to stdout. You can also specify an optional log callback as second parameter.

**Comment by kuzux** [comment]
[webrtc.log](https://github.com/paullouisageneau/libdatachannel/files/7976509/webrtc.log)
Here's the verbose log in its entirety

**Comment by paullouisageneau** [comment]
Everything looks fine, only it seems that there is no DataChannel to open after the PeerConnection is connected. Are you sure the `shared_ptr` to the DataChannel is not dropped before the connection succeeds? The DataChannel would be destroyed and would never open.

Also is the version 0.16.2 or lower? Data Channel and Track destruction was not logged before 0.16.3.

**Comment by kuzux** [comment]
Yep, the problem was exactly the lifetime of the data channel object. I was apparently only assigning it to a local shared_ptr that was being dropped after the function returns.
