### ISSUE TITLE
Set Generic RTP Feedback

### ISSUE THREAD

**Issue by xesdiny** [paullouisageneau/libdatachannel#550]
I found a very strange phenomenon. I used the magic modification `demo/client` as the receiving end to connect to a signaling server and received the video stream of `ue4/pixelstreaming` and forwarded it to rtp to be decoded by `ffmpeg`, and It is found that it is much more ambiguous than the receiving web display provided by the manufacturer. Later, using `wireshark` to capture rtp packets, it was found that after using the modified `demo/client` receiver, `RTPFB (Generic RTP Feedback)` was rarely performed, while the web receiver provided by the manufacturer would perform Feedback in each batch; In the other hand, the phenomenon was found to be After the magic modification, the `packet length` of the `demo/client` captured packets is getting smaller and smaller, and it feels that they are tanslate all non-key frames. Refer to the [rtc4585](https://tools.ietf.org/id/draft-dt-rmcat-feedback-message-04.html) supplementary protocol. I suspect that the sender uses the `Temporal Max Media Bitrate Request` (TMMBR protocol) , but again I'm not sure.
So I'm guessing possible reasons:
1. When I don't know the current default bandwidth, the receiver thinks that it is limited by the current bandwidth, and tells the sender to control the bit rate, and then the video packet content becomes less and less, resulting in blurred video.
2. The client without the magic modification does not have a Feedback mechanism, which leads to the lack of feedback information to the sender for the congestion control algorithm . If there is no feedback, the sender is considered that the current receiving bandwidth is congested, and the content of the video packet at the sender is less and less, and the final video is blurred.

**Comment by paullouisageneau** [comment]
Thank you for reporting but I'd need some context here first, what do you call the "magic modification demo/client"? Also, what is ue4/pixelstreaming?

**Comment by xesdiny** [comment]
> Thank you for reporting but I'd need some context here first, what do you call the "magic modification demo/client"? Also, what is ue4/pixelstreaming?

The `magic modification demo/client` is that I made a receiver according to the `example/client` you provided.

The `ue4/pixelstreaming` is a [plugin](https://github.com/Azure/Unreal-Pixel-Streaming) for Unreal Engine to interact media and control.

**Comment by paullouisageneau** [comment]
> RTPFB (Generic RTP Feedback) was rarely performed, while the web receiver provided by the manufacturer would perform Feedback in each batch

FB is currently not implemented in `RtcpReceivingSession`, so it will only send RR to the sender (primitives like `RtcpFbHeader` are present, but the logic is not here for now).

> When I don't know the current default bandwidth, the receiver thinks that it is limited by the current bandwidth, and tells the sender to control the bit rate, and then the video packet content becomes less and less, resulting in blurred video.

On the receiver side, a specific bitrate may be requested with REMB manually by calling `RtcpReceivingSession::requestBitrate()`. Otherwise, no automatic estimation is done.

> The client without the magic modification does not have a Feedback mechanism, which leads to the lack of feedback information to the sender for the congestion control algorithm . If there is no feedback, the sender is considered that the current receiving bandwidth is congested, and the content of the video packet at the sender is less and less, and the final video is blurred.

Yes, I don't have the details but what could happen is that the sender somehow requires FB messages and RR are not sufficient.

**Comment by paullouisageneau** [comment]
I opened an issue for RTCP-FB messages: https://github.com/paullouisageneau/libdatachannel/issues/551
