### ISSUE TITLE
"BIO_meth_new" NOT DECALRED IN THIS SCOPE when libnice is enabled during compiling in linux (ubuntu 18.04)

### ISSUE THREAD

**Issue by lucpattyn** [paullouisageneau/libdatachannel#552]
/mnt/d/linux/dev/experiments/libdatachannel/src/impl/dtlstransport.cpp:345:16: error: ‘BIO_meth_new’ was not declared in this scope
   BioMethods = BIO_meth_new(BIO_TYPE_BIO, "DTLS writer");
                ^~~~~~~~~~~~
/mnt/d/linux/dev/experiments/libdatachannel/src/impl/dtlstransport.cpp:345:16: note: suggested alternative: ‘g_menu_new’
   BioMethods = BIO_meth_new(BIO_TYPE_BIO, "DTLS writer");
                ^~~~~~~~~~~~
                g_menu_new
/mnt/d/linux/dev/experiments/libdatachannel/src/impl/dtlstransport.cpp:348:3: error: ‘BIO_meth_set_create’ was not declared in this scope
   BIO_meth_set_create(BioMethods, BioMethodNew);

**Comment by paullouisageneau** [comment]
It looks like OpenSSL is a legacy version before 1.1.0. What version is the libssl-dev package?

However, enabling libnice should not change anything about OpenSSL. Do you mean that the error is absent without libnice?

**Comment by paullouisageneau** [comment]
I can't reproduce: [this workflow](https://github.com/paullouisageneau/libdatachannel/actions/runs/1823182097) building with libnice + OpenSSL on Ubuntu 18.04 [works fine](https://github.com/paullouisageneau/libdatachannel/runs/5139159788?check_suite_focus=true).

How do you build?

**Comment by paullouisageneau** [comment]
I can't reproduce: [this workflow](https://github.com/paullouisageneau/libdatachannel/blob/00e1344600724bd9af399abe556ae213ccc26596/.github/workflows/build-nice.yml#L25) building with libnice + OpenSSL on Ubuntu 18.04 [works fine](https://github.com/paullouisageneau/libdatachannel/runs/5139458989?check_suite_focus=true).

How do you build?

Independently from this, there was an issue with the nlohmann/json library used by examples because Ubuntu 18.04 only has gcc7 which does not have full C++17 standard library support. I updated the json submodule from v3.10.4 to v3.10.5 on master, which solves the problem.

**Comment by lucpattyn** [comment]
I was using Windows Powershell for Ubuntu 18.04 - with 
cmake -B build -DUSE_GNUTLS=0 -DUSE_NICE=1  --> Is this setup correct?

I think might be some problem with my setup (on windows powershell). 
Thanks for looking into it.  

As long as works on pure ubuntu 18.04 this can be closed down IMHO.

**Comment by lucpattyn** [comment]
However, there is a problem by passing openssl.
This is ubuntu 20.04 powershell in linux.

Following this workflow:
https://github.com/paullouisageneau/libdatachannel/blob/00e1344600724bd9af399abe556ae213ccc26596/.github/workflows/build-nice.yml#L17
and setting DUSE_GENUTILS=1

![problembypassingopenssl](https://user-images.githubusercontent.com/30570071/153415504-b7dae97f-4583-4fad-aaba-bbc317c56c9e.png)

**Comment by paullouisageneau** [comment]
Oh, I think the issue is that you run `make` in the libdatachannel folder, so it attempts to build using the standalone Makefile, which would require its own flags. To build with the CMake configuration, you need to change to the build directory first:
```
$ cmake -B build -DUSE_GNUTLS=1 -DUSE_NICE=1
$ cd build
$ make
```

**Comment by paullouisageneau** [comment]
> cmake -B build -DUSE_GNUTLS=0 -DUSE_NICE=1

It's correct but a bit weird as libnice depends on GnuTLS, meaning the resulting application will use both OpenSSL and GnuTLS.

**Comment by lucpattyn** [comment]
Closing this because most likely mistake on my side.
