### ISSUE TITLE
Support for SetICEUDPMux, Simplifying libDatachannel deployments to static public routable IP:PORT dst addresses

### ISSUE THREAD

**Issue by jordo** [paullouisageneau/libdatachannel#555]
It has been brought up before (https://github.com/paullouisageneau/libdatachannel/discussions/451) but there seems to be an increasing need of simplifying libdatachannel deployments to public routable infrastructure.  

We also fall under the above use case as well (agones/k8s gameserver deployments on public routable endpoints), where specifically a single IP:PORT pair (or pairings) that can mux udp data_channels would be insanely helpful.  

A followup comment on the SO discussion [here](https://stackoverflow.com/questions/68339856/webrtc-on-kubernetes-cluster/68349888#68349888) I also agree with, in that muxing UDP traffic in a data_channel is preferrable to solutions that add an additional hop and additional infrastructure complexity ( deploying a dedicated turn server per service for relay ).  UDP datachannel multiplexing is available in [go webrtc](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetICEUDPMux) via [pion ICE udp_mux](https://github.com/pion/ice/blob/master/udp_mux.go#L229).

K8's services and infrastructure is just not designed with port ranges in mind.  [This thread](https://github.com/kubernetes/kubernetes/issues/23864) of 5+ years requesting support for these types of services in k8s is most likely not going to change as it doesn't really mesh well with the k8s design philosophy or security model.

There are no options right now to support a simple, clean, webrtc datachannel interface with maybe the exception of something like [webudp](https://github.com/seemk/WebUDP) which implements a very small subset of webrtc datachannel spec.  

With the [agones](https://github.com/googleforgames/agones) project, we get a usable port range of 7000-8000 for gameserver forwarding through iptables into k8s gameserver CRD's.  Each port (or ports) allocated statically per gameserver, which doesn't work if each `peer_connection` in libdatachannel's `rtcCreatePeerConnection` is port exclusive even with limited `portRangeBegin:portRangeEnd`  to a single or couple ports.  (We run out quickly with a single gameserver and say 100 peer connections on each node).

It would be incredibly useful to support something like [this](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetICEUDPMux).

**Comment by paullouisageneau** [comment]
Indeed, allowing to multiplex all Peer Connections on the same UDP port would indeed be pretty useful on server side.

This would need to be implemented in the ICE library [libjuice](https://github.com/paullouisageneau/libjuice), I'm opening an issue there for reference.

**Comment by paullouisageneau** [comment]
I just merged https://github.com/paullouisageneau/libdatachannel/pull/570, the new `enableIceUdpMux` config option allows to enable UDP multiplexing.

**Comment by paullouisageneau** [comment]
I just merged https://github.com/paullouisageneau/libdatachannel/pull/570, the new `enableIceUdpMux` config option allows to enable UDP multiplexing :rocket:
