### ISSUE TITLE
Connecting to web_webrtc takes 3 times the time in stun mode and in turn mode 

### ISSUE THREAD

**Issue by LiuAriel** [paullouisageneau/libdatachannel#559]
Currently using the library to connect to the web side, in the same LAN mode, the stun mode takes hundreds of milliseconds, and in the turn mode of different LANs, the time consumption can be close to 3s. In the same code environment, using libnice, the turn mode takes less time. It is more than 100 milliseconds than the stun mode. Through the current phenomenon, it is suspected that the program has not done a good job in dealing with the interactive process of turn!
look forward to your reply！

**Comment by paullouisageneau** [comment]
Please add more context: How do you use the library? Do you trickle candidates, or do you wait for a complete gathering? What do you call "stun mode" and "turn mode"? Do you mean with STUN/TURN enabled? How many STUN and TURN servers did you set? What exact duration did you measure? What network type are your LANs? Is UDP traffic blocked? Code to reproduce would also be good.

**Comment by LiuAriel** [comment]
@paullouisageneau   Thank you very much for your reply, the content is as follows
1. Operating environment: ARM;
2. Code version: the latest master;
3. Local IP collection: Full mode, it takes less than 100ms to complete the sdp callback;
4. There are stun and turn examples in the test cases in the library. Refer to this writing and turn on stun/turn.
5. There is only one set of coturn servers associated with stun and turn;
6. By printing the log, it takes about 400ms for the entire stun pairing to succeed, and about 2800ms for the entire turn pairing to succeed. Basically, every test is this value;
7. Under the same environmental conditions, it takes about 400ms for the entire stun pairing to succeed, and about 900ms for the entire turn pairing. Basically, every test is this value;
8. For home routers, the specific type has not been tested. In the unsuccessful p2p mode, it is also possible to use relay, and the type does not affect;
9. UDP will not be blocked by filtering, otherwise libnice will not succeed. Make sure that libnice is also enabled UDP, full mode!
10. The libjuice code is initialized as follows:
       `juice_set_log_level(JUICE_LOG_LEVEL_NONE);
	juice_config_t jconfig;
	memset(&jconfig, 0, sizeof(jconfig));
	// STUN server
	jconfig.stun_server_host = "xxx.xxx.x.x";
	jconfig.stun_server_port = 3478;

	// TURN server
	// Please do not use outside of libjuice tests
	juice_turn_server_t turn_server;
	memset(&turn_server, 0, sizeof(turn_server));
	turn_server.host = "xxx.xxx.x.x";
	turn_server.port = 3478;
	turn_server.username = "testuser";
	turn_server.password = "testpw";
	jconfig.turn_servers = &turn_server;
	jconfig.turn_servers_count = 1;
	jconfig.cb_state_changed = StateChangeCallback;
	//jconfig.cb_candidate = CandidateCallback; //full mode sdp ?
	jconfig.cb_gathering_done = GatheringDoneCallback;
	jconfig.cb_recv = RecvCallback;
	jconfig.user_ptr = this;
        juice_create(&jconfig);
        juice_gather_candidates(m_pNiceAgent);`
11. The libjuice code callback code is as follows:

void  StateChangeCallback(juice_agent_t *agent, juice_state_t state, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;
	switch (state) {
	case JUICE_STATE_CONNECTING:
		break;
	case JUICE_STATE_CONNECTED:
	{
	}
		break;
	case JUICE_STATE_COMPLETED:
	{
		
	        pAgent->NewSelectedPairFull(1, 1);
	}
		break;
	case JUICE_STATE_DISCONNECTED:
	case JUICE_STATE_FAILED:
	{
	}	
		break;
	};
}

void WebrtcNiceAgentIce::CandidateCallback(juice_agent_t *agent, const char *sdp, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;
}

void WebrtcNiceAgentIce::GatheringDoneCallback(juice_agent_t *agent, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;

        char sdp_callback[JUICE_MAX_SDP_STRING_LEN];
	juice_get_local_description(pAgent->m_pAgent, sdp_callback, JUICE_MAX_SDP_STRING_LEN);
	XLOG_ERROR("Local description:\n%s\n", sdp_callback);
}

void RecvCallback(juice_agent_t *agent, const char *data, size_t size, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;
	pAgent->NiceRecvData(1, 1, size, (char*)data);
}

void LogCallback(juice_log_level_t level, const char *message)
{

}       void StateChangeCallback(juice_agent_t *agent, juice_state_t state, void *user_ptr)
      {
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;
	switch (state) {
	case JUICE_STATE_CONNECTING:
		break;
	case JUICE_STATE_CONNECTED:
	{
	}
		break;
	case JUICE_STATE_COMPLETED:
	{
		
	        pAgent->NewSelectedPairFull(1, 1);
	}
		break;
	case JUICE_STATE_DISCONNECTED:
	case JUICE_STATE_FAILED:
	{
	}	
		break;
	};
}

void WebrtcNiceAgentIce::CandidateCallback(juice_agent_t *agent, const char *sdp, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;
}

void WebrtcNiceAgentIce::GatheringDoneCallback(juice_agent_t *agent, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;

        char sdp_callback[JUICE_MAX_SDP_STRING_LEN];
	juice_get_local_description(pAgent->m_pAgent, sdp_callback, JUICE_MAX_SDP_STRING_LEN);
}

void RecvCallback(juice_agent_t *agent, const char *data, size_t size, void *user_ptr)
{
	WebrtcAgentIce* pAgent = (WebrtcAgentIce*)user_ptr;
	pAgent->NiceRecvData(1, 1, size, (char*)data);
}

void LogCallback(juice_log_level_t level, const char *message)
{

}

**Comment by LiuAriel** [comment]
In fact, I tested lijuice as long as it did not pass the relay mode, stun between Asia and the Americas, after the connectivity test passed, the time consumption was the same as about 400ms.
Once you go to relay, the time-consuming is very terrible!

**Comment by LiuAriel** [comment]
After packet capture analysis, combined with the code, I found that I made a mistake here.
In the code StateChangeCallback callback function, I put the handler function in JUICE_STATE_COMPLETED, which should actually be in JUICE_STATE_CONNECTED.

**Comment by paullouisageneau** [comment]
Thank you for the details.

I looked at the capture, there are a few issues:

- The capture contains only the traffic of Chrome browser, the traffic between libjuice and the STUN/TURN server is absent.

- You use full SDP gathering mode instead of candidate trickling, while this method causes delays. As you mentioned it may roughly introduce a 100ms delay on both sides, i.e. 200ms, and if one single server is slow to answer it will block the whole connection process for a while.

- You shouldn't set both STUN and TURN server if you set them to the same server. TURN servers actually do STUN automatically, so this will just cost one additional request.

- I don't understand why you mention custom code example for libjuice. Don't you use libdatachannel (I guess you do since you posted here)? Since you connect to Chrome browser, you have to use the whole WebRTC stack, not only ICE.

- You wrote juice takes about 2800ms for TURN pairing to succeed, but in the capture it looks like CONNECTED state was reached in less than 1 second.

- You should actually look at the CONNECTED state instead of COMPLETED to know when a pair is selected. CONNECTED means a pair is selected and is sufficient to send messages to the other peer, COMPLETED only means all alternative pairs have been explored so it won't switch to a better one anymore. libnice is faster to switch to COMPLETED because it uses an ICE method called "aggressive nomination", which was allowed in RFC 5245 but is now disallowed in RFC 8445. libjuice does not use aggressive nomination. Again, it doesn't matter because the CONNECTED state is what is important for connectivity.

**Comment by paullouisageneau** [comment]
> After packet capture analysis, combined with the code, I found that I made a mistake here.
In the code StateChangeCallback callback function, I put the handler function in JUICE_STATE_COMPLETED, which should actually be in JUICE_STATE_CONNECTED.

Sorry, I missed your message. Indeed, I think you found the issue, see the reason for the behavior difference in my previous message.

**Comment by paullouisageneau** [comment]
> Currently, libjuice also supports trickle mode?

Yes it does, with the candidate callback and `juice_add_remote_candidate()`.

**Comment by LiuAriel** [comment]
> > Currently, libjuice also supports trickle mode?
> 
> Yes it does, with the candidate callback and `juice_add_remote_candidate()`.

Thank you so much, you are doing a great job! Helped me a lot. No problem, you can close this issue！
