### ISSUE TITLE
Close callback behaviour

### ISSUE THREAD

**Issue by pimterry** [paullouisageneau/libdatachannel#574]
_Continuing the conversation from https://github.com/murat-dogan/node-datachannel/pull/82#issuecomment-1062944038:_

> The behavior is expected, and is indeed a difference with the WebRTC JavaScript API: libdatachannel guarantees no more callbacks will be called after close() returns, so in particular onClose() won't be called locally after close() (onClose() will of course be called on the remote peer). This allows proper thread synchronization in C++, as you can safely destroy objects on the caller side after calling close().
> 
> In order to prevent data loss in the background or Jest complaining when the program exits, you may call the global cleanup function before exiting. It will block and ensure every channel is properly closed.

This makes sense. In my case, I can't use the global cleanup or Jest's settings. This is a connection shutdown detail that's illustrated by that implementation & test, but the code I care about is a long-running application managing many separate connections & channels.

I do need to clean up everything related to a single connection when the connection closes, but I don't want to do so for _all_ connections.

It's not impossible to do that right now, but it is difficult. The built-in callbacks working differently depending on whether the connection is closed locally or remotely makes the implementation much more complicated - in effect everybody needs to implement their own callbacks that they call manually anywhere that any code might call `peer.close()`, to clean up all resources related to any channel, duplicating the logic of the channel's own close callback, and requiring a tight link between the channel management & peer management code.

It would be much easier to safely handle connection shutdown if there was a single close callback that was always called consistently, regardless of the close reason (as there is on the web).

I understand your point about safe cleanup after `peer.close()` though. Is there any other way to make these callbacks consistent whilst providing that? For example, synchronously calling close callbacks on all channels during `peer.close()`, before that function returns? Alternatively, would it be possible to fire the those callbacks for all channels asynchronously, but add a close callback to the peer itself, and define cleanup as only being safe once that peer callback is called?

Similar logic applies to other callbacks like the connection state change callback: it would be useful to be able to handle peer connection closure the same way for local & remote connections (wait for state to change to 'disconnected') but currently if `peer.close()` is called locally then that callback is never called.

I understand any changes to this would probably be breaking changes for the existing API, so there isn't likely to be a quick & easy fix here, but personally an approach along those lines would make my channel management code significantly cleaner & easier, and give me a lot more confidence that everything is being cleaned up reliably.

**Comment by paullouisageneau** [comment]
I agree with your points. Actually, the `PeerConnection` calls its state change callback with the `Closed` state synchronously when `close()` is called, so I think it would be consistent for `DataChannel` to also call `onClose` synchronously when its own `close()` method is called. This is a breaking change, but I think it could be OK if shipped in a major version.

**Comment by paullouisageneau** [comment]
The change has been merged in https://github.com/paullouisageneau/libdatachannel/pull/576 :rocket: 

It will need a few adaptations in the node-datachannel wrapper as currently the wrapper will cancel scheduled callbacks running after `close()`.

**Comment by pimterry** [comment]
Amazing, thanks for your work on this!
