### ISSUE TITLE
Renegotiation fails with Chrome with "Failed to set SSL role for the transport" when changing offer/answer direction

### ISSUE THREAD

**Issue by pimterry** [paullouisageneau/libdatachannel#584]
I'm not very familiar with some of the details here, so it's quite possible I'm doing something wrong, but I _think_ this is a libdatachannel bug. The flow is:

* Libdatachannel creates offer with one data channel
* Chrome receives offer, returns an answer
* Connection is set up & working happily
* Chrome generates new offer with `{ offerToRecieveAudio: true }` to add an audio channel, to renegotiate the connection
* Libdatachannel receives the offer, returns an answer
* `setRemoteDescription` in Chrome to complete the handshake throws:
  ```
  Failed to set remote answer sdp: Failed to apply the description for m= section with mid='0': Failed to set SSL role for the transport.
  ```

This does not happen if the initial setup is flipped, so that it goes: Chrome offer/libdatachannel answer/Chrome renegotiation offer/Libdatachannel answer. In that case everything works immediately.

This behaviour seems extremely similar to this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1240897. That has the same flow: first a data channel, then a renegotation that flips the direction, then the `Failed to set SSL role for the transport` error.

According to that issue, this is because of the `a=setup:...` attributes are used incorrectly. In the above, the setup attributes are:

* Libdatachannel offer: `a=setup:actpass`
* Chrome answer: `a=setup:active`
* Chrome renegotiation offer: `a=setup:actpass`
* Libdatachannel answer: `a=setup:active`

Judging from that Firefox bug, the final answer in this case should be `a=setup:passive`, because there's already a working connection here already. If I directly modify the SDP with `sdp.replace('setup:active', 'setup:passive')` then the renegotiation seems to run successfully.

I don't have an easy to share repro for this case I'm afraid, but if that would clarify anything let me know and I can try to put something together with node-datachannel. I'm using node-datachannel v0.2.4 and Chrome v99.0.4844.82.

**Comment by paullouisageneau** [comment]
I can confirm this looks like a bug, however I'm unable to reproduce. When I attempt an equivalent scenario, the final answer from libdatachannel has `a=setup:passive`.

Could you please give more information about the setup? Are you sure the second offer is not forwarded to a new Peer Connection by mistake?

**Comment by pimterry** [comment]
Ahhhhh, sorry, you're completely right, and you've just found the bug in my code :smiley:. I was unexpectedly & incorrectly creating a new connection every time. Works fine now that I've fixed that.

Thank you, and sorry for the noise! I'll close this.
