### ISSUE TITLE
CMake Error: override default CMAKE_MODULE_PATH cause root project cannot find custom module

### ISSUE THREAD

**Issue by littlepush** [paullouisageneau/libdatachannel#593]
I was trying to compile `libsrtp` with `boringssl` in my own project.
I create a `FindOpenSSL.cmake` under `<project_root>/cmake/`, but when use cmake to generate the project, I still get the following error:
`
CMake Error at /usr/local/Cellar/cmake/3.22.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.22.3/share/cmake/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
  thirdparty/libdatachannel/deps/libsrtp/CMakeLists.txt:75 (find_package)
`

After a lot of searching, I found the problem finally: 

https://github.com/paullouisageneau/libdatachannel/blob/ca90539f662cbfcb50492924fa6a6979157b84bc/CMakeLists.txt#L30

**this line should be changed to:**

`list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/Modules)`

then everything works perfect.

**Comment by paullouisageneau** [comment]
Thank you for reporting, the line is changed in https://github.com/paullouisageneau/libdatachannel/pull/594.
