### ISSUE TITLE
Building for Android with OpenSSL

### ISSUE THREAD

**Issue by kylegranger** [paullouisageneau/libdatachannel#595]
### Building for Android with OpenSSL

Hi! I'm not quite getting the library to build for Android with OpenSSL.  
I've built it and used it successfully on Linux.  
My Android development system is Win 10. The error I'm getting back from my cmake call is this:

```
CMake Error at CMakeLists.txt:222 (add_library):
Target "datachannel" links to target "OpenSSL::SSL" but the target was not
found. Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing?

CMake Error at CMakeLists.txt:227 (add_library):
  Target "datachannel-static" links to target "OpenSSL::SSL" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

In this scenario, I'm building for the arm64-v8a ABI. The steps are:

1. I have libssl.a and libcrypto.a in .../openssl-arm64-v8a/lib
```
libdatachannel$ ls $OPENSSL_ROOT_DIR/lib -l
total 4564
-rw-r--r-- 1 User 197121 3985694 Jul 26  2021 libcrypto.a
-rw-r--r-- 1 User 197121  681048 Jul 26  2021 libssl.a
```
2. The OpenSSL include folder is here: .../openssl-arm64-v8a/include
3. The command line looks like this:

```
cmake -H. -Bgenerated -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/d/piq/3rdparty/android/openssl-arm64-v8a -DOPENSSL_INCLUDE_DIR=/d/piq/3rdparty/android/openssl-arm64-v8a/include -DOPENSSL_CRYPTO_LIBRARY=/d/piq/3rdparty/android/openssl-arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-29 -DANDROID_NDK=/c/Users/User/AppData/Local/Android/Sdk/ndk/21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=/c/Users/User/AppData/Local/Android/Sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -G Ninja
```

4. OPENSSL_ROOT_DIR points to the directory containing the lib and include folders
   OPENSSL_INCLUDE_DIR points to the include directory itself
   OPENSSL_CRYPTO_LIBRARY points to the lib directory containing libcrypto.a (and libssl.a)
5. The static libraries have been built for the arm64-v8a ABI. The paths are correct, and have also been expored in the bash shell.

Thank you for any ideas!

Kyle

**Comment by littlepush** [comment]
Check this: https://github.com/paullouisageneau/libdatachannel/issues/593
I think the main branch has fixed this issue

**Comment by kylegranger** [comment]
I installed the Android dev tools on Linux (Ubuntu), and I think I fared better.

I still got errors from cmake, but I ignored them and just did the 'make datachannel-static' from within the generated android-build folder.

The generated libraries look raisonable.
```
-rw-rw-r-- 1 z 6788998 Apr 12 19:52 libdatachannel-static.a
-rw-rw-r-- 1 z 169440 Apr 12 19:49 deps/libsrtp/libsrtp2.a
-rw-rw-r-- 1 z 347098 Apr 12 19:48 deps/libjuice/libjuice-static.a
-rw-rw-r-- 1 z 966720 Apr 12 19:49 deps/usrsctp/usrsctplib/libusrsctp.a
```
I'll try linking/running them in a test Android app.  If it works, I'll close this.

BTW, my cmake line is this:
```
cmake -B android-build -DANDROID=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/ader/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DOPENSSL_ROOT_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/lib/libssl.a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-29 -DANDROID_NDK=/home/ader/Android/Sdk/ndk/24.0.8215888 -DOPENSSL_INCLUDE_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/include -DOPENSSL_CRYPTO_LIBRARY=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/lib/libcrypto.a
```
The error returned (which I now ignore) is this:
```

CMake Error at CMakeLists.txt:338 (target_link_libraries):
  Target "datachannel" links to:

    OpenSSL::SSL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at CMakeLists.txt:339 (target_link_libraries):
  Target "datachannel-static" links to:

    OpenSSL::SSL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

**Comment by paullouisageneau** [comment]
I think the issue here might be that your compiled OpenSSL library is static while by default CMake tries to link a dynamic one. You should try to add `-DOPENSSL_USE_STATIC_LIBS=1` to the CMake line.

Also, `OPENSSL_INCLUDE_DIR` and `OPENSSL_CRYPTO_LIBRARY` are internal result variables, you shouldn't need to specify them, only `-DOPENSSL_ROOT_DIR=xxx/openssl-prebuilt/android/arm64-v8a/arm64-v8a` is necessary.

**Comment by kylegranger** [comment]
Merci...I tried your suggestion, and it did not make a difference.  Also, if I don't include `OPENSSL_INCLUDE_DIR`and `OPENSSL_CRYPTO_LIBRARY` defines, I will not get a `Makefile` in the build directory.  And also unfortunately, I need to solve a new problem with the native linking in Studio.

### No additional OpenSSL defines
This version has the OPENSSL_USE_STATIC_LIBS, minus OPENSSL_INCLUDE_DIR & OPENSSL_CRYPTO_LIBRARY
```
cmake -B build -DOPENSSL_USE_STATIC_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/ader/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DOPENSSL_ROOT_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-25 -DANDROID_NDK=/home/ader/Android/Sdk/ndk/24.0.8215888 
```

The error returned is this.  There is no `Makefile `in the build directory
```
CMake Error at /snap/cmake/1082/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /snap/cmake/1082/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /snap/cmake/1082/share/cmake-3.23/Modules/FindOpenSSL.cmake:578 (find_package_handle_standard_args)
  deps/libsrtp/CMakeLists.txt:75 (find_package)
```

### With Additional OpenSSL defines
```
cmake -B build -DOPENSSL_USE_STATIC_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/ader/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DOPENSSL_ROOT_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-25 -DANDROID_NDK=/home/ader/Android/Sdk/ndk/24.0.8215888 -DOPENSSL_INCLUDE_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/include -DOPENSSL_CRYPTO_LIBRARY=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/lib/libcrypto.a 
```

I get same errors as in my original post, but I still also get a `Makefile` generated.  And as before, I can run `make datachannel-static`, and get the four libraries built as before.

### Linker Problem
But I need to solve a new problem.  When I link the libraries with the native code in the project in Android Studio, I'm getting some undefined references to low level arm instructions.  

```
peerconnection.cpp:(.text._ZN3rtc14PeerConnectionD2Ev+0x4c): undefined reference to '__aarch64_ldadd8_relax'
peerconnection.cpp:(.text._ZN3rtc14PeerConnectionD2Ev+0x68): undefined reference to '__aarch64_ldadd8_acq_rel'
```

When I solve that, I'll post everything I know here.  It's probably an NDK issue

**Comment by kylegranger** [comment]
one note regarding the linker problem.  I have gcc and g++ pointing to their Android/clang equivalents.  Cmake kept using gcc & g++ and not the Android cross compilers (I tried versions 9, 10, 11 for gcc/g++).  Only by pointing the symbol links for gcc/g++ via `sudo update-alternatives --config gcc` could I get the Android compilers to be used.  This is (obviously) not a libdatachannel issue.

```
ader@ader-ZBook:~/dev/piq/3rdparty/libdatachannel$ gcc --version
Android (8075178, based on r437112b) clang version 14.0.1 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
ader@ader-ZBook:~/dev/piq/3rdparty/libdatachannel$ g++ --version
Android (8075178, based on r437112b) clang version 14.0.1 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Anyways, I'll let you all know when I get it solved.

**Comment by paullouisageneau** [comment]
> ### No additional OpenSSL defines
> 
> This version has the OPENSSL_USE_STATIC_LIBS, minus OPENSSL_INCLUDE_DIR & OPENSSL_CRYPTO_LIBRARY
> 
> ```
> cmake -B build -DOPENSSL_USE_STATIC_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/ader/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DOPENSSL_ROOT_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-25 -DANDROID_NDK=/home/ader/Android/Sdk/ndk/24.0.8215888 
> ```
> 
> The error returned is this. There is no `Makefile `in the build directory
> 
> ```
> CMake Error at /snap/cmake/1082/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
>   OPENSSL_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /snap/cmake/1082/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   /snap/cmake/1082/share/cmake-3.23/Modules/FindOpenSSL.cmake:578 (find_package_handle_standard_args)
>   deps/libsrtp/CMakeLists.txt:75 (find_package)
> ```

As OpenSSL is mandatory, it is expected that no Makefile is generated if it is not found. This looks OK, I wonder why it doesn't pick up the library. Does setting `OPENSSL_ROOT_DIR` as environment variable instead works by any chance?

> ### With Additional OpenSSL defines
> 
> ```
> cmake -B build -DOPENSSL_USE_STATIC_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/ader/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DOPENSSL_ROOT_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-25 -DANDROID_NDK=/home/ader/Android/Sdk/ndk/24.0.8215888 -DOPENSSL_INCLUDE_DIR=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/include -DOPENSSL_CRYPTO_LIBRARY=/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/lib/libcrypto.a 
> ```
> 
> I get same errors as in my original post, but I still also get a `Makefile` generated. And as before, I can run `make datachannel-static`, and get the four libraries built as before.

This is not a proper way around the error as pre-setting the result variables probably just makes the FindOpenSSL module bypass the search because it looks like it has already been called, however since OpenSSL wasn't actually found and the actual `OpenSSL::SSL` target wasn't actually created you get the new error. 

This result in OpenSSL still not being linked, and you can build datachannel-static only because static libraries are not linked (linking happens only later when linking them into an executable or shared library).

You should look at FindOpenSSL documentation [here](https://cmake.org/cmake/help/latest/module/FindOpenSSL.html).

> one note regarding the linker problem. I have gcc and g++ pointing to their Android/clang equivalents. Cmake kept using gcc & g++ and not the Android cross compilers (I tried versions 9, 10, 11 for gcc/g++). Only by pointing the symbol links for gcc/g++ via `sudo update-alternatives --config gcc` could I get the Android compilers to be used. This is (obviously) not a libdatachannel issue.

OK great!

**Comment by kylegranger** [comment]
>> Does setting OPENSSL_ROOT_DIR as environment variable instead works by any chance?

No.  I set the environment variable (via export, I'm on Ubuntu 20.04), and I get the same results.  Tried both with and without the -DOPENSSL_ROOT_DIR in the cmake command line.  Weird.  
Btw, my project already links to the static libs libopenssl.a and libcrypto.a

Again, to be clear, this openssl root directory contains include and lib folders
```
ader@ader-ZBook:~/dev/piq/3rdparty/libdatachannel$ echo $OPENSSL_ROOT_DIR
/home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a
ader@ader-ZBook:~/dev/piq/3rdparty/libdatachannel$ ls -l $OPENSSL_ROOT_DIR
total 8
drwxrwxr-x 3 ader ader 4096 Jan  4  2021 include
drwxrwxr-x 3 ader ader 4096 Jan  4  2021 lib
```

**Comment by Nemirtingas** [comment]
Isn't OpenSSL::SSL a target that is set by find_package(OpenSSL REQUIRED) ?
The error message seems to be telling that you are trying to link against OpenSSL::SSL, but find_package(OpenSSL REQUIRED) should have already thrown an error about OpenSSL not found.

**Comment by littlepush** [comment]
create a `FindOpenSSL.cmake` under `libdatachannel/cmake/Modules` and put the following content:

```
set(OPENSSL_INCLUDE_DIR @YOUR-OPEN-SSL-ROOT-PATH@/include)

set(OpenSSL_LIBRARIY_SSL @YOUR-OPEN-SSL-ROOT-PATH@/lib/libssl.a)
set(OpenSSL_LIBRARY_CRYPRO @YOUR OPEN SSL ROOT PATH@/lib/libcrypto.a)
set(OpenSSL_LIBRARIES ${OpenSSL_LIBRARIY_SSL} ${OpenSSL_LIBRARY_CRYPRO})

mark_as_advanced(OPENSSL_INCLUDE_DIR)
mark_as_advanced(OpenSSL_LIBRARIES)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args("OpenSSL"
  DEFAULT_MSG
  OPENSSL_INCLUDE_DIR
  OpenSSL_LIBRARIES
)

if(NOT TARGET OpenSSL::Crypto)
  add_library(OpenSSL::Crypto STATIC IMPORTED)
  set_target_properties(OpenSSL::Crypto PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${OpenSSL_INCLUDE_DIR}"
  )
  set_target_properties(OpenSSL::Crypto PROPERTIES
    IMPORTED_LOCATION "${OpenSSL_LIBRARY_CRYPRO}"
  )
endif()

if(NOT TARGET OpenSSL::SSL)
  add_library(OpenSSL::SSL STATIC IMPORTED)
  set_target_properties(OpenSSL::SSL PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES OpenSSL::Crypto
  )
  set_target_properties(OpenSSL::SSL PROPERTIES
    IMPORTED_LOCATION "${OpenSSL_LIBRARIY_SSL}"
  )
endif()

```

**Comment by kylegranger** [comment]
Thank you for the file! That did the trick.  No errors with cmake or make.
I am a bit further with link errors.  96% of them were due to unsupported atomics (because of static build -- some flags differ from shared library builds).  Adding these cmake defines got rid of them.
```
-DCMAKE_CXX_FLAGS="-march=armv8-a -mno-outline-atomics" 
-DCMAKE_C_FLAGS="-march=armv8-a -mno-outline-atomics"
```
It's not yet super isolated.  The -march=armv8-a is probably no necessary because I'm still just building for the arm64-b8a ABI.
The rest of the link errors are most likely NDK version mismatches.

**Comment by littlepush** [comment]
@kylegranger You can use [boringssl](https://github.com/google/boringssl) for Android

**Comment by kylegranger** [comment]
I'm now (enfin) running on Android, and could connect to a signalling server and create a PeerConnection.  I could not solve the linker problems:   many undefined symbols, plus "relocation R_AARCH64_PREL64" errors.  In the end, I just gave up trying to build static, and built libdatachannel.so.  That worked.

[ Probably the reason I was fixated on building a static library was because two years ago, I had to build the chrome webrtc library for Linux/iOS/Android.  As you all know, not fun.  But at the end, I had a 91MB libwebrtc.a ]

Regarding version of NDK:  I'm using 21.4, not the latest 24.0.  When I use the latest, I get this build error, probably due to how our openSSL static libraries were built.  Other will probably not have this problem.
```
ld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
```

Sooooo.... how I built libdatachannel for Android:

1.  Add littlepush's file `FindOpenSSL.cmake` to `/cmake/modules`.  Mine looks like this, for arm64-v8a:
```
# set(OPENSSL_INCLUDE_DIR /home/ader/dev/piq/3rdparty/openssl-prebuilt/android/armeabi-v7a/include)
# set(OpenSSL_LIBRARY_SSL /home/ader/dev/piq/3rdparty/openssl-prebuilt/android/armeabi-v7a/lib/libssl.a)
# set(OpenSSL_LIBRARY_CRYPTO /home/ader/dev/piq/3rdparty/openssl-prebuilt/android/armeabi-v7a/lib/libcrypto.a)

set(OPENSSL_INCLUDE_DIR /home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/include)
set(OpenSSL_LIBRARY_SSL /home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/lib/libssl.a)
set(OpenSSL_LIBRARY_CRYPTO /home/ader/dev/piq/3rdparty/openssl-prebuilt/android/arm64-v8a/lib/libcrypto.a)

set(OpenSSL_LIBRARIES ${OpenSSL_LIBRARY_SSL} ${OpenSSL_LIBRARY_CRYPTO})

mark_as_advanced(OPENSSL_INCLUDE_DIR)
mark_as_advanced(OpenSSL_LIBRARIES)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args("OpenSSL"
  DEFAULT_MSG
  OPENSSL_INCLUDE_DIR
  OpenSSL_LIBRARIES
)

if(NOT TARGET OpenSSL::Crypto)
  add_library(OpenSSL::Crypto STATIC IMPORTED)
  set_target_properties(OpenSSL::Crypto PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${OpenSSL_INCLUDE_DIR}"
  )
  set_target_properties(OpenSSL::Crypto PROPERTIES
    IMPORTED_LOCATION "${OpenSSL_LIBRARY_CRYPTO}"
  )
endif()

if(NOT TARGET OpenSSL::SSL)
  add_library(OpenSSL::SSL STATIC IMPORTED)
  set_target_properties(OpenSSL::SSL PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES OpenSSL::Crypto
  )
  set_target_properties(OpenSSL::SSL PROPERTIES
    IMPORTED_LOCATION "${OpenSSL_LIBRARY_SSL}"
  )
endif()
```
2.  Run this cmake command line, for arm64-v8a.  It works for armeabi-v7a as well, so long as you change the openssl/crypto paths in the above cmake file.
```
cmake -B ./shared -DANDROID=1 -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=23 -DCMAKE_BUILD_TYPE=Release  -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a  -DCMAKE_TOOLCHAIN_FILE=/home/ader/Android/Sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-29 -DANDROID_NDK=/home/ader/Android/Sdk/ndk/21.4.7075529 -DCMAKE_MAKE_PROGRAM=/home/ader/Android/Sdk/cmake/3.18.1/bin/ninja -GNinja
```
3.  Run `ninja`

4.  Gather up the four libs, zip them:
```
mkdir libs
cp libdatachannel.so libs
cp deps/libsrtp/libsrtp2.a libs
cp deps/libjuice/libjuice-static.a libs
cp deps/usrsctp/usrsctplib/libusrsctp.a libs
ls -l libs
zip shared-v7a.zip -r libs

-rwxrwxr-x 1 ader ader 40368784 Apr 14 11:51 libdatachannel.so
-rw-rw-r-- 1 ader ader  1338050 Apr 14 11:51 libjuice-static.a
-rw-rw-r-- 1 ader ader   638680 Apr 14 11:51 libsrtp2.a
-rw-rw-r-- 1 ader ader  4542808 Apr 14 11:51 libusrsctp.a
```
Thanks for the help, and many thanks to Paul for creating this great library.  Chapeau!

**Comment by paullouisageneau** [comment]
Thanks for taking the time to write down the full process. Just a detail: you should only need `libdatachannel.so` in the end, as `libjuice-static.a`, `libsrtp2.a`, and `libusrsctp.a` are already statically linked into the .so library.

> Thanks for the help, and many thanks to Paul for creating this great library. Chapeau!

Thank you very much!

**Comment by kylegranger** [comment]
Ah, cool...one library to rule them all.
[ As for me, this issue could be closed. ]

**Comment by tirthesh007** [comment]
Hi @paullouisageneau ,
I have solved the Open SSL realated error using the steps suggested to write "FindOpenSSL.cmake" inside "/cmake/modules",
and now make file is successfull. 
But now  I am getting errors as below:
``Tirthesh/libdatachannel/libdatachannel# make -j2
Consolidate compiler generated dependencies of target juice-static
Consolidate compiler generated dependencies of target usrsctp
[ 12%] Built target juice-static
[ 12%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o
Consolidate compiler generated dependencies of target srtp2
[ 12%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/srtp/srtp.c.o
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:424:7: error: implicit declaration of function 'getifaddrs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rc = getifaddrs(&ifas);
             ^
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:475:2: error: implicit declaration of function 'freeifaddrs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        freeifaddrs(ifas);
        ^
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:475:2: note: did you mean 'getifaddrs'?
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:424:7: note: 'getifaddrs' declared here
        rc = getifaddrs(&ifas);
             ^
2 errors generated.
deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/build.make:103: recipe for target 'deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o' failed
make[2]: *** [deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o] Error 1
CMakeFiles/Makefile2:458: recipe for target 'deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/all' failed
make[1]: *** [deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o
[ 14%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o
[ 14%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/aes_gcm_ossl.c.o
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/auth.c.o
[ 17%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/auth_test_cases.c.o
[ 17%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/null_auth.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/hmac_ossl.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/alloc.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/crypto_kernel.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/err.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/key.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/math/datatypes.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/replay/rdb.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/replay/rdbx.c.o
[ 23%] Linking C static library libsrtp2.a
[ 23%] Built target srtp2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2``
Can you please help me to solve this errors.

**Comment by kylegranger** [comment]
I solved this my defining `__ANDROID__` in the CMakeFiles.txt at the project root.

Because...in deps/libjuice/src/socket.h, there is this:
```
#ifdef __ANDROID__
#define NO_IFADDRS
#else
#include <ifaddrs.h>
#endif
```

At circa line 29 in CMakeFiles.txt, I added it here:
```
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/Modules)
set(BUILD_SHARED_LIBS OFF) # to force usrsctp to be built static

add_definitions(-D__ANDROID__)
```

I appear to have added it a second time, at around line 204:
```
set(CMAKE_POLICY_DEFAULT_CMP0048 NEW)
add_subdirectory(deps/plog EXCLUDE_FROM_ALL)
add_definitions(-D__ANDROID__)
if(SCTP_DEBUG)
	add_definitions(-DSCTP_DEBUG)
endif()
```

Paul may know of a better way to set the define.  It didn't work for me from the command line (if I remember correctly).

Good luck, I hope this works!

**Comment by paullouisageneau** [comment]
> ```
> deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:424:7: error: implicit declaration of function 'getifaddrs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>        rc = getifaddrs(&ifas);
> ```

It looks like you are trying to build with a minimum Android API level lower than 24 (Android 7 Nougat), whereas usrsctp requires `getifaddrs()`, a function available in the NDK for API level 24 or higher. However, I noticed this part of the SCTP stack is not needed by libdatachannel and may be removed from the build by disabling the usrsctp options `inet` and `inet6`.

Therefore, you need to either increase `minSdkVersion` to 24 or use the patch in https://github.com/paullouisageneau/libdatachannel/pull/630.

> I solved this by defining `__ANDROID__` in the CMakeLists.txt at the project root.
> 
> Because...in deps/libjuice/src/socket.h, there is this:
> 
> ```
> #ifdef __ANDROID__
> #define NO_IFADDRS
> #else
> #include <ifaddrs.h>
> #endif
> ```

I think the issue is different here because libjuice seems to build fine while `getifaddrs()` is missing, meaning `__ANDROID__` is probably defined. Besides, usrsctp does not guard the `getifaddrs()` call with `__ANDROID__`.

> Paul may know of a better way to set the define. It didn't work for me from the command line (if I remember correctly).

That's weird, the define should be set automatically, if it is not then it looks like an issue with the toolchain or compiler.

**Comment by tirthesh007** [comment]
Thanks @paullouisageneau , updating my minSdkVersion to 24, solved my issue. Thanks. Also thanks for reply @kylegranger.
