### ISSUE TITLE
thread synchronization with onMessage

### ISSUE THREAD

**Issue by arvidn** [paullouisageneau/libdatachannel#6]
please excuse my ignorance if I misunderstand something. My understanding is that `mMessageCallback` is called on an internal network thread, and the callback is set from the client thread. Yet, there is no sychronization of this shared variable.

Perhaps more importantly, the call to *set* the `onMessage` callback really must synchronize to ensure that `mMessageCallback` is not clobbered while being executed and additionally, that once [onMessage](https://github.com/paullouisageneau/libdatachannel/blob/61fb38305a7bba8ecf1309e1c54bfd8c69474f77/src/channel.cpp#L31) returns, the previous callback will not be called. i.e. I think you need a mutex around the whole call and the assignment.

Obviously that would mean clients would have to be careful to not update the callback from within the callback itself, as that would be a dead-lock (should be documented).

**Comment by paullouisageneau** [comment]
Your understanding is good, synchronization is indeed missing on callbacks. This should be solved in https://github.com/paullouisageneau/libdatachannel/pull/7 by wrapping each callback with a recursive mutex.
