### ISSUE TITLE
Building with CMake on Windows: does not find NETTLE

### ISSUE THREAD

**Issue by polhaghverdian** [paullouisageneau/libdatachannel#60]
Hi,

Trying to build this on Windows.

Am using OpenSSL. therefore: DUSE_GNUTLS=0

With command:   

> cmake -DUSE_JUICE=1 -DUSE_GNUTLS=0 .. 

I get below Warning. Help please.

` The package name passed to `find_package_handle_standard_args` (NETTLE)
  does not match the name of the calling package (Nettle).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  deps/libjuice/cmake/Modules/FindNettle.cmake:6 (find_package_handle_standard_args)
  deps/libjuice/CMakeLists.txt:63 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.`

**Comment by paniksystem** [comment]
Did you try with only

`cmake -DUSE_JUICE=1`

**Comment by polhaghverdian** [comment]
> 
> 
> Did you try with only
> 
> `cmake -DUSE_JUICE=1`

this worked aswell: "cmake -DUSE_JUICE=1 -DUSE_GNUTLS=0 -DUSE_NETTLE=0 .."

**Comment by paullouisageneau** [comment]
The actual warning about names not matching should be solved by https://github.com/paullouisageneau/libjuice/commit/a0e428ad6c73d6747fba3abf677dec410877216b
