### ISSUE TITLE
No way to have special characters in the TURN server URL username/password in C API

### ISSUE THREAD

**Issue by bigfarts** [paullouisageneau/libdatachannel#611]
`rtcCreatePeerConnection` only takes in `rtcConfiguration` which in turn takes in URLs for `iceServers`, but it's not possible currently to have characters such as `:` or `@` in the username or password of that URL, as they'll get interpreted as delimiters. The credentials from https://subspace.com/ have `:` in the username so it's currently not possible to use them with libdatachannel.

Would it be possible to URL decode the parsed parts of the URL such that `:` and `@` can be safely supplied? Thanks!

**Comment by paullouisageneau** [comment]
Released in v0.17.2
