### ISSUE TITLE
Sending WebSocket ping/pong message with a specific duration

### ISSUE THREAD

**Issue by kaishian** [paullouisageneau/libdatachannel#614]
Can we send WebSocket ping/pong messages of specific "duration"?
Make this "duration" configurable?

**Comment by paullouisageneau** [comment]
Sure, a setting could be added in `rtc::WebSocket::Configuration`.

**Comment by deblauwetom** [comment]
Hi, i would also need this. What do you use for timings normally in the codebase? I would do an attempt at something that closes the connection when the pong is not received for for instance 5 seconds(configurable indeed).

**Comment by deblauwetom** [comment]
maybe also the thing is that the return value is not checked when doing a ping send, so that could already be a quicker fix probably.

**Comment by paullouisageneau** [comment]
Actually, WebSocket background pinging had been mistakenly disabled in the last version, so I re-enabled it in https://github.com/paullouisageneau/libdatachannel/pull/625.

WebSocket pings are triggered by TCP read timeouts in `TcpTransport`, the duration is hardcoded to 10s here: https://github.com/paullouisageneau/libdatachannel/blob/9485fe7dc55a4ffca4aff13c57e1596c3de8e740/src/impl/tcptransport.cpp#L250

> What do you use for timings normally in the codebase? I would do an attempt at something that closes the connection when the pong is not received for for instance 5 seconds(configurable indeed).

Great! The `ThreadPool` singleton has overloads for its `schedule` method to allow running a task at a given time, I guess it can be useful here. However, I think it could be simpler to fail after sending a number of pings without getting a pong.

> maybe also the thing is that the return value is not checked when doing a ping send, so that could already be a quicker fix probably.

Indeed, for now the return value is not checked. The goal was just to send some data to be sure the connection is kept alive (for instance if the system does not send TCP keepalives).

**Comment by paullouisageneau** [comment]
> I gave it a try in #627, but I actually developed it to 0.15.5, and tested there that it worked. It seems the master code is change a little bit, so I did not test with the master code, but it looked straightforward so i think it will work on master too :)

Thank you for the contribution!

**Comment by deblauwetom** [comment]
Should we not close this now?

**Comment by paullouisageneau** [comment]
Yes, thanks
