### ISSUE TITLE
Writing the P2P example in C

### ISSUE THREAD

**Issue by stevedanOgochu** [paullouisageneau/libdatachannel#63]
I am trying to write the p2p example in c but I am having problem on what the parametres type an mid means in this functions 
```
rtcSetRemoteDescription(other->pc, sdp, type);
rtcAddRemoteCandidate(other->pc, cand, mid);
Also do you have a list of more c api like to help me convet the following code
std::optional<std::chrono::milliseconds> rtt = pc->rtt();
if (pc->getSelectedCandidatePair(&local, &remote)) {
    cout << "Local: " << local.address << ":" << local.port << " " << local.type << " " << local.transportType << endl;
    cout << "Remote: " << remote.address << ":" << remote.port << " " << remote.type << " " << remote.transportType << endl;
    cout << "Bytes Sent:" << pc->bytesSent() << " / Bytes Received:" << pc->bytesReceived() << " / Round-Trip Time:";
    if (rtt.has_value())
        cout << rtt.value().count();
    else
        cout << "null";
    cout << " ms";
} else
    cout << "Could not get Candidate Pair Info" << endl;
```

**Comment by paullouisageneau** [comment]
The mid is the media ID, it's the stream ID the candidate corresponds to, and it should travels with it though the signaling channel. The equivalent field in the Javascript API is `sdpMid` and it's mandatory. 

It's mostly here because it is part of WebRTC signaling but actually ignored by libdatachannel. You can safely put an empty string there.

**Comment by stevedanOgochu** [comment]
Thank you for the advise you gave me, it workerd.
Does this api exist in c```


			std::optional<std::chrono::milliseconds> rtt = pc->rtt();
			if (pc->getSelectedCandidatePair(&local, &remote)) {
				cout << "Local: " << local.address << ":" << local.port << " " << local.type << " "
				     << local.transportType << endl;
				cout << "Remote: " << remote.address << ":" << remote.port << " " << remote.type
				     << " " << remote.transportType << endl;
				cout << "Bytes Sent:" << pc->bytesSent()
				     << " / Bytes Received:" << pc->bytesReceived() << " / Round-Trip Time:";
				if (rtt.has_value())
					cout << rtt.value().count();
				else
					cout << "null";
				cout << " ms";
			} 

```

**Comment by paullouisageneau** [comment]
Not exactly, however you can use `rtcGetLocalAddress(int pc, char *buffer, int size)` and 
`rtcGetRemoteAddress(int pc, char *buffer, int size)` to get both addresses.

**Comment by stevedanOgochu** [comment]
I just wrote a version in c, if you want i can post it?, I am fairly new to programming so it might not be perfect

**Comment by paullouisageneau** [comment]
Yes sure, please open a pull request.
For now you can submit it with the copy/paste instead of a signaling. As you might have seen, I opened a pull request to add websocket support, it can be used to send the SDP and candidates to a signaling server.

**Comment by paullouisageneau** [comment]
Done in https://github.com/paullouisageneau/libdatachannel/pull/65
