### ISSUE TITLE
tcp transport runtime errors during websocket connect

### ISSUE THREAD

**Issue by deblauwetom** [paullouisageneau/libdatachannel#643]
Hello,

I am using the websocket library her, and when I do a connect, but that somehow fails due to my wifi being bad for example, then the library throws a runtime error like for example:

Exception of type std::runtime_error
what(): TCP connection to 99.80.51.12:443 failed, errno=101

 3# rtc::impl::TcpTransport::connect(sockaddr const*, unsigned int) in /usr/lib/libdatachannel.so.0.15.5
 4# rtc::impl::TcpTransport::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in /usr/lib/libdatachannel.so.0.15.5
 5# rtc::impl::TcpTransport::runLoop() in /usr/lib/libdatachannel.so.0.15.5
 6# 0x0000007F8327718C in /usr/lib/libstdc++.so.6
 7# 0x0000007F83079088 in /lib/libc.so.6
 8# 0x0000007F830DDF1C in /lib/libc.so.6

Is there a way currently not to throw these errors? I tried to put a try-catch around my websocket connect, but that is a different thread it seems. Am I correct?

**Comment by paullouisageneau** [comment]
The exception is indeed thrown in an internal thread and is part of the normal error handling. It is eventually caught in `runLoop()` which changes the transport state to failed.

Why don't you want to throw the exception? It's merely a symptom of the connection failure, not throwing it won't make the connection succeed. 

If you want to retry the connection on failure, you should reconnect the WebSocket on close. Besides, you should update to the latest version as 0.15.5 is quite old.

**Comment by deblauwetom** [comment]
yes, I was mistaken, it was due to some code I have that catches uncaught exceptions, but clearly, that code is mistaken. Sorry to bother you with it. Closing it, has nothing to do with libdatachannel.
