### ISSUE TITLE
videos start with lags in webRTC android application

### ISSUE THREAD

**Issue by farhadvahdani** [paullouisageneau/libdatachannel#647]
I am using libdatachannel library to stream multiple camera videos.
now I can stream multiple camera videos to a browser through the internet. videos play smoothly. 
We have a webrtc android application working properly, an Embedded board is sending  h264 video at 24 fps; however, the incoming video stream in the android app presents a sort of periodic lag,  videos start with lags and after 4/5 minutes it continues correctly. how can I solve this lag at beginning of my videos?

I guess the incoming video Iframe is too large for the android device to process so it skips some of the Iframes and then continues when the buffer is free again. I'm getting the following output in the logcat (which I've googled but found no answer to my problem) saying ** AndroidVideoDecoder: decode() - key frame required first**

to test my application I have developed another app to act as a video sender. the video plays smoothly.
another test I did was changing the frame rate, it didn`t have any effect.

**Comment by farhadvahdani** [comment]
I tested my Android application with another Android application that played the role of an embedded device and the data was smoothly played and there was no problem

**Comment by paullouisageneau** [comment]
Please describe your setup more precisely: What sender/receiver configuration have you tried and which one experience issues? What networks do the devices use (Wifi, LTE, etc)? How are your sending the streams, do you forward RTP streams or do you packetize with libdatachannel?

The "key frame required first" error probably means the key frame was lost, possibly indicating a network issue with the Android device. You could try lowering the resolution and bitrate to see if it helps. Lowering the keyframe interval might help too.

By the way, this is the same issue with the exact same wording, did you just copy-paste it? https://stackoverflow.com/questions/53965407/key-frame-required-first-error-in-webrtc-android-application-how-to-reduce-fram

**Comment by farhadvahdani** [comment]
hi
My English is not good and I had to copy a bit.
android application:
android 11 - samsung a71
webrtc library : implementation 'org.webrtc:google-webrtc:1.0.28513'
When we use this library, we do not receive an " Android video decoder: key frame required first" error, but the video stream is not received properly at first, and Lee is corrected after a few minutes. (The images are frozen in such a way that we receive 5 frames or less or more every 4 seconds and after a few minutes it is completely correct.)
webrtc library : implementation 'org.webrtc:google-webrtc:1.0.30039' or implementation 'org.webrtc:google-webrtc:1.0.+'
When we use this library, we get an " Android video decoder: key frame required first"  error, but the video stream is not received properly at first, and Lee is corrected after a few minutes. (The images are frozen so that every 4 seconds we receive 5 frames or less or more and the `frames are received green and black` as if they can not receive Iframe and after a few minutes it is completely correct.)
Because my English is not good if you do not understand what I'm saying to send you the video.
Android setting:
```initVideos();
        try {
            getIceServers();
        } catch (JSONException e) {
            e.printStackTrace();
        }
        //Initialize PeerConnectionFactory globals.
        PeerConnectionFactory.InitializationOptions initializationOptions =
                PeerConnectionFactory.InitializationOptions.builder(this)
                        .setEnableInternalTracer(true)
                        //H.264 video provides better picture quality
                        .setFieldTrials("WebRTC-H264HighProfile/Enabled/")
                        .createInitializationOptions();
        PeerConnectionFactory.initialize(initializationOptions);
        //Create a new PeerConnectionFactory instance - using Hardware encoder and decoder.
        PeerConnectionFactory.Options options = new PeerConnectionFactory.Options();

        VideoEncoderFactory defaultVideoEncoderFactory = new DefaultVideoEncoderFactory(rootEglBase.getEglBaseContext(),  /* enableIntelVp8Encoder */true,
                /* enableH264HighProfile */false);
        VideoDecoderFactory defaultVideoDecoderFactory = new DefaultVideoDecoderFactory(rootEglBase.getEglBaseContext());
        defaultVideoDecoderFactory.createDecoder()
        /*VideoEncoderFactory defaultVideoEncoderFactory = new SoftwareVideoEncoderFactory();
        VideoDecoderFactory defaultVideoDecoderFactory = new SoftwareVideoDecoderFactory();*/
        /*options.disableEncryption = true;
        options.disableNetworkMonitor = true;*/

        peerConnectionFactory = PeerConnectionFactory.builder()
                .setOptions(options)
                .setVideoEncoderFactory(defaultVideoEncoderFactory)
                .setVideoDecoderFactory(defaultVideoDecoderFactory)
                .createPeerConnectionFactory();```
```private void createPeerConnection() {

        PeerConnection.RTCConfiguration rtcConfig = new PeerConnection.RTCConfiguration(peerIceServers);
        // TCP candidates are only useful when connecting to a server that supports
        // ICE-TCP.
        rtcConfig.tcpCandidatePolicy = PeerConnection.TcpCandidatePolicy.DISABLED;
        rtcConfig.bundlePolicy = PeerConnection.BundlePolicy.BALANCED;
        rtcConfig.bundlePolicy = PeerConnection.BundlePolicy.MAXBUNDLE;
        rtcConfig.rtcpMuxPolicy = PeerConnection.RtcpMuxPolicy.REQUIRE;
        rtcConfig.continualGatheringPolicy = PeerConnection.ContinualGatheringPolicy.GATHER_CONTINUALLY;
        rtcConfig.enableCpuOveruseDetection = false;
        rtcConfig.sdpSemantics = PeerConnection.SdpSemantics.UNIFIED_PLAN;
        rtcConfig.iceTransportsType = PeerConnection.IceTransportsType.ALL;
        //Use ECDSA encryption.
        rtcConfig.keyType = PeerConnection.KeyType.ECDSA;

        localPeer = peerConnectionFactory.createPeerConnection(rtcConfig, new CustomPeerConnectionObserver() {
            @Override
            public void onIceCandidate(IceCandidate iceCandidate) {
                super.onIceCandidate(iceCandidate);
                onIceCandidateReceived(iceCandidate);
            }

            @Override
            public void onAddStream(MediaStream mediaStream) {
                super.onAddStream(mediaStream);
                gotRemoteStream(mediaStream);
            }
            @Override
            public void onAddTrack(RtpReceiver rtpReceiver, MediaStream[] mediaStreams) {
                super.onAddTrack(rtpReceiver, mediaStreams);
            }

        });
    }```
Embedded device setting:
when the init command is received, board start to send offer
```
printf("===========================line %d ==> receive init\n",_LINE_);
				pthread_mutex_lock(&stream_encoder_mutex );
				rtcConfiguration config1;
				memset(&config1, 0, sizeof(config1));
				config1.mtu = 1472;
				pc = createPeer(&config1 , ws ,id);		
				cJSON *streamOrder_j = cJSON_GetObjectItem(message, "streamOrder");
				int jj = 0;
				streamStatus  stream_status[PRODUCT_TYPE];
				streamQuality stream_quality[PRODUCT_TYPE];		
				for (jj =0 ; jj <PRODUCT_TYPE ; jj++)
				{
					SAMPLE_PRT(" jj =%d \n",jj);
					char string_text[50];
					sprintf(string_text,"cam%d", jj+1 );
					cJSON * camera_j  = cJSON_GetObjectItem(streamOrder_j,  string_text);
					if (camera_j == NULL)continue;
					cJSON * status_j  = cJSON_GetObjectItem(camera_j,  "status");
					cJSON * quality_j  = cJSON_GetObjectItem(camera_j,  "quality");

					stream_status[jj] = !strcmp(status_j->valuestring,"on") ? STREAM_ON : STREAM_OFF ;debug_print
					stream_quality[jj] = !strcmp(quality_j->valuestring,"hd") ? STREAM_HD : STREAM_SD ;debug_print
					SAMPLE_PRT(" jj =%d \n",jj);
					
				}
	
				for (ii = 0 ; ii < PRODUCT_TYPE; ii++ )
				{
				if( stream_status[ii] == STREAM_ON)
				{
					rtcTrackInit  trackinit;
					memset(&trackinit, 0, sizeof(trackinit));
					
					trackinit.direction = RTC_DIRECTION_SENDRECV;
					trackinit.codec = RTC_CODEC_H264;
					trackinit.payloadType = 96;
					trackinit.ssrc =  ii+42;

					trackinit.name= cname[ii];
			
					trackinit.mid= mid[ii];
					trackinit.msid=ssmid[ii];
					trackinit.trackId= cname[ii];
			
					pc->tr[ii] = rtcAddTrackEx(pc->pc, &trackinit);
					
		
		
					rtcPacketizationHandlerInit packetizer_init;
					packetizer_init.ssrc = ii+42;
					packetizer_init.cname = cname;
					packetizer_init.payloadType = 96;
					packetizer_init.clockRate = 90 * 1000;
					packetizer_init.sequenceNumber =0;
					packetizer_init.timestamp = 0;
					packetizer_init.nalSeparator = RTC_NAL_SEPARATOR_LONG_START_SEQUENCE; // NAL unit separator
					packetizer_init.maxFragmentSize = RTC_DEFAULT_MAXIMUM_FRAGMENT_SIZE;// H264
					rtcSetH264PacketizationHandler(pc->tr[ii],&packetizer_init);
					rtcChainRtcpSrReporter(pc->tr[ii]);
					rtcChainRtcpNackResponder(pc->tr[ii],1000);
					rtcSetOpenCallback(pc->tr[ii], trackOpenCallback);
					rtcSetClosedCallback(pc->tr[ii], trackClosedCallback);
					//SAMPLE_PRT("=====> track %d created   \n",ii);
					
				}
			}
			
				rtcSetLocalDescription(pc->pc, NULL);
```
the  createPeer()  function
```
Peer * createPeer( rtcConfiguration * config , int ws , char * ID)
{
	
	Peer *peer = (Peer *)malloc(sizeof(Peer));
	if (!peer)
		return NULL;
	
	memset(peer, 0, sizeof(Peer));
	
	
	peer->iceServers[0] = malloc(100);
	peer->iceServers[1] = malloc(100);
	sprintf(peer->iceServers[0] , "turn:dvr_%s:%s@trn.electropeyk.com:3478",system_setting_network_info.public_token,system_setting_network_info.private_token);
	//sprintf(peer->iceServers[0] , "stun:trn.electropeyk.com:3478",system_setting_network_info.public_token,system_setting_network_info.private_token);
	printf("\nturn:\"%s\"\n ",peer->iceServers[0]);

	config->iceServers =peer->iceServers;
	
	config->iceServersCount = 1;
	
	
	
	peer -> ws = ws ;
	strcpy (peer -> ID , ID );
//	printf ("Peer created  \"%s\"\n",config->iceServers[0]);


	peer->pc = rtcCreatePeerConnection(config);
	rtcSetUserPointer(peer->pc, peer);
	//rtcSetOpenCallback(peer->pc, pcOpenCallback);debug_print
	//rtcSetClosedCallback(peer->pc, pcClosedCallback);//debug_print
	rtcSetStateChangeCallback(peer->pc, stateChangeCallback);
	rtcSetGatheringStateChangeCallback(peer->pc, gatheringStateCallback);	
	rtcSetLocalDescriptionCallback(peer->pc, descriptionCallback);
	rtcSetLocalCandidateCallback(peer->pc, candidateCallback);
	rtcSetDataChannelCallback(peer->pc, dataChannelCallback);
	rtcSetTrackCallback(peer->pc, trackCallback);

	
	connectedPeers[connectedPeerCnt] = peer;
	connectedPeerCnt++;

	return peer;
}
```

**Comment by vahidrezaee** [comment]
I have faced a similar problem.
my problem was video plays smoothly in the Chrome browser, but in firefox browser video doesn't play at all.
after some investigation, I found that my embedded application sent some packets with small sizes of about 8 or 16 bytes.
this packet was rejected by firefox and the key frame was never received by the firefox decoder.

**Comment by farhadvahdani** [comment]
Thank you [vahidrezaee], that was my problem and I solved it.
