### ISSUE TITLE
Differentiated Services field zero

### ISSUE THREAD

**Issue by alexswerner** [paullouisageneau/libdatachannel#654]
Hi,

in the README it states "Differentiated Services QoS ([RFC8837](https://www.rfc-editor.org/rfc/rfc8837.html)) where possible" and I wonder what that means exactly. This came up because I looked at the packages (in tcpdump) and they all have the tos/diffserv set to zero. That is suprising, and I confirmed that setsocketopt(...IP_TOS ...) is called with non-zero dscp values.
Please note, this is in a custom application (using datachannels and tracks) and I have confirmed the behavior with the example code. 

Interestingly this seems to be network dependent. So far whenever i connect between some computers on the LAN, the diffserv field is correctly set. No so far any remote host. Even if when remote host can be reached without NAT traversal or stun/turn. In the log file I can see that the differentiated services field is set.
```
022-06-13 11:45:54.373 VERB  [11595] [rtc::impl::SctpTransport::handleWrite@717] Handle write, len=100
2022-06-13 11:45:54.373 VERB  [11595] [rtc::impl::DtlsTransport::send@476] Send size=100
2022-06-13 11:45:54.373 VERB  [11595] [rtc::impl::IceTransport::send@247] Send size=137
2022-06-13 11:45:54.373 VERB  [11595] [rtc::impl::IceTransport::LogCallback@346] juice: agent.c:406: Setting Differentiated Services field to 0x28
2022-06-13 11:45:54.373 VERB  [11595] [rtc::impl::IceTransport::LogCallback@346] juice: agent.c:413: Sending datagram, size=137
```
I will try and dig deeper, but maybe someone already has an idea.

This is running on Linux kernel 5.16.13 (Ubuntu 18.04) with libdatachannel v0.16 using libjuice v0.9.8. I confirmed that the host in question has no firewall rules rewriting diffserv fields and the packet with the zero-value diffserv fields were captures at the output interface using `tcpdump -i $IFACE -vvv"`.

**Comment by alexswerner** [comment]
One case were this happens is when a dual-stack host is connecting to a IPv4 only host. In that case, libdatachannel or libjuice seems to use setsockopt correctly, but packets have a zero diffserv field. After adding a non-dynamic IPv6 address to the interface, the issue is gone. I can also not reproduce it even when removing the IPv6 address again.

**Comment by paullouisageneau** [comment]
The README says where possible because the feature is not available on some operating systems, in particular on Microsoft Windows.

> One case were this happens is when a dual-stack host is connecting to a IPv4 only host. In that case, libdatachannel or libjuice seems to use setsockopt correctly, but packets have a zero diffserv field. After adding a non-dynamic IPv6 address to the interface, the issue is gone. I can also not reproduce it even when removing the IPv6 address again.

Thank you for investigating, I managed to reproduce the behavior. It appears the kernel (5.18.1 here) does not map the IPv6 traffic class to sent IPv4 traffic on an IPv6+IPv4 socket. This is weird as I didn't notice the problem when testing before. 

I think a decent solution is to always set the IPv4 ToS field too, without checking for errors as it might be illegal on some systems (as there don't seem to be any standard about this). I'll push a fix.

**Comment by alexswerner** [comment]
Excellent! Thanks for the quick fix.
