### ISSUE TITLE
static library

### ISSUE THREAD

**Issue by darrenwinslow** [paullouisageneau/libdatachannel#66]
Can you add an option to build a static library?

**Comment by paullouisageneau** [comment]
A static library is already built by the cmake target `LibDataChannel::LibDataChannelStatic`

**Comment by darrenwinslow** [comment]
These are the targets that have been built, is there something I need to specify for cmake?
[ 51%] Built target usrsctp-static
[ 83%] Built target datachannel
[ 87%] Built target datachannel-answerer
[ 90%] Built target datachannel-offerer
[100%] Built target datachannel-tests

**Comment by murat-dogan** [comment]
`add_library(datachannel-static STATIC EXCLUDE_FROM_ALL ${LIBDATACHANNEL_SOURCES})`

This is the line that builds static lib. It is an excluded target, so build it selecting `datachannel-static` as target

**Comment by paullouisageneau** [comment]
Yes, like @murat-dogan said, if your project uses cmake, use 
```
add_subdirectory(libdatachannel)
target_link_libraries(yourproject LibDataChannel::LibDataChannelStatic)
```
If you just want to build the static lib for some reason, removing `EXCLUDE_FROM_ALL` from the `add_library` line will do the trick.

**Comment by darrenwinslow** [comment]
Using datachannel-static as a make target worked great.  
Thanks.
