### ISSUE TITLE
How to use media-sender example?

### ISSUE THREAD

**Issue by themightyoarfish** [paullouisageneau/libdatachannel#660]
I'm on macOS catalina and have to issues.

I can't copy the entire response from `main.html`'s input field into the program. Somehow the `getline()` call never returns and I cannot press enter either. If I replace the `\r\n` strings in the SDP json by just `\n`, I can paste, and get output like this

```
2022-06-17 19:11:35.163 INFO  [11944829] [rtc::impl::PeerConnection::changeSignalingState@1202] Changed signaling state to stable
2022-06-17 19:11:37.793 WARN  [11945591] [rtc::impl::IceTransport::LogCallback@354] juice: Ignoring candidate with transport TCP
2022-06-17 19:11:37.796 INFO  [11944841] [rtc::impl::IceTransport::LogCallback@354] juice: Changing state to connected
2022-06-17 19:11:37.796 INFO  [11944841] [rtc::impl::PeerConnection::initDtlsTransport@242] This connection requires media support
2022-06-17 19:11:37.796 DEBUG [11944841] [rtc::impl::DtlsTransport::DtlsTransport@389] Initializing DTLS transport (OpenSSL)
2022-06-17 19:11:37.797 DEBUG [11944841] [rtc::impl::DtlsSrtpTransport::DtlsSrtpTransport@67] Initializing DTLS-SRTP transport
2022-06-17 19:11:37.797 DEBUG [11944841] [rtc::impl::DtlsTransport::start@478] Starting DTLS recv thread
2022-06-17 19:11:37.798 INFO  [11944841] [rtc::impl::IceTransport::LogCallback@354] juice: Changing state to completed
2022-06-17 19:11:40.165 WARN  [11945592] [rtc::impl::IceTransport::LogCallback@354] juice: Ignoring candidate with transport TCP
```

When sending video with 

```
gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=480 ! videoconvert ! queue ! x264enc tune=zerolatency bitrate=1000 key-int-max=30 ! video/x-h264, profile=constrained-baseline ! rtph264pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=6000
```

Nothing shows up in the browser though, and no logging gives any indication of  `media-sender` doing anything. 

Am I using this wrong?

**Comment by themightyoarfish** [comment]
Ok in Chromium it works, just not firefox (why?).

But the code always loops because the track is not open: https://github.com/paullouisageneau/libdatachannel/blob/master/examples/media-sender/main.cpp#L96

How do I "open" this "track"?

**Comment by themightyoarfish** [comment]
The console says
```
main.html:35 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. 
```
but nothing else happens.

**Comment by themightyoarfish** [comment]
So it seems that you need to reopen the html file (without cache perhaps) each time you restart the sender.

When using VP9, still the problem of nothing showing up though, does anything have to change besides this?

```
diff --git a/examples/media-sender/main.cpp b/examples/media-sender/main.cpp
index 2907448..a1b52a0 100644
--- a/examples/media-sender/main.cpp
+++ b/examples/media-sender/main.cpp
@@ -74,7 +74,7 @@ int main() {

                const rtc::SSRC ssrc = 42;
                rtc::Description::Video media("video", rtc::Description::Direction::SendOnly);
-               media.addH264Codec(96); // Must match the payload type of the external h264 RTP stream
+               media.addVP9Codec(96); // Must match the payload type of the external h264 RTP stream
                media.addSSRC(ssrc, "video-send");
                auto track = pc->addTrack(media);
```

**Comment by themightyoarfish** [comment]
Huh, actually vp9 video does show up, but it takes quite a while, any idea why?

```
 gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=480 ! videoconvert ! queue ! vp9enc   ! video/x-vp9  ! rtpvp9pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=6000
```

**Comment by themightyoarfish** [comment]
Anyway, it seems that reload without cache fixes my problems, would still like to know why it only works in chrome.

**Comment by paullouisageneau** [comment]
> I can't copy the entire response from main.html's input field into the program. Somehow the getline() call never returns and I cannot press enter either. If I replace the \r\n strings in the SDP json by just \n, I can paste, and get output like this

This is weird since it boils down to pasting a one-line string. The end of lines are escaped here and shouldn't make any difference to the terminal.

> Ok in Chromium it works, just not firefox or safari (why?).

It can't reproduce, the video plays fine on my side with Firefox (Firefox 101.0 64-bit on Linux). What is your setup?

> So it seems that you need to reopen the html file (without cache perhaps) each time you restart the sender.

Yes, the JavaScript receiver is very simple and does not support restarts, so you have to refresh (no need to clear the cache).

> Huh, actually vp9 video does show up, but it takes quite a while, any idea why?
> 
> ```
>  gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=480 ! videoconvert ! queue ! vp9enc   ! video/x-vp9  ! rtpvp9pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=6000
> ```

The reason must be that the key frame interval is too large, as the video will only show up when the decoder gets a key frame. For this reason, the x264 version of pipeline used `key-int-max=30`. For `vp9enc` you should set `keyframe-max-dist=30`.

**Comment by themightyoarfish** [comment]
I agree, the behaviour is so weird that it must be some kind of bug. I disabled plugins and all, but behaviour is consistent across safari and firefox (newest stable versions) and both Catalina and Monterey. I'm not even sure how to debug this. It appears copying works, I can paste the full thing into the FF address bar for instance, but macOS spotlight e.g. rejects the string completely, and I can paste fine into bash, but not into `media-sender`s stdin.

**Comment by themightyoarfish** [comment]
Apparently I am not the only one with this issue: https://github.com/aiortc/aiortc/issues/111
