### ISSUE TITLE
Update vcpkg version 

### ISSUE THREAD

**Issue by crisboarna** [paullouisageneau/libdatachannel#663]
Hi,

I was hoping if it would be possible for you to update the vcpkg entry for your project to latest 0.17.7 as the latest there is 0.17.1 and you have made several important fixes since. Using vcpkg also greatly simplifies the project config for me so I would be really thankful for it!

**Comment by paullouisageneau** [comment]
@Nemirtingas @NancyLi1013 @JonLiu1993 Could one of you bump the version to 0.17.8 on vcpkg please? I think libjuice would also need to be bumped to 1.0.2.

**Comment by JonLiu1993** [comment]
@paullouisageneau, I see @crisboarna has submitted pr #[25522](https://github.com/microsoft/vcpkg/pull/25522) in vcpkg, let's wait for the pr to be merged

**Comment by paullouisageneau** [comment]
Great, thanks!

**Comment by crisboarna** [comment]
Hi, vcpkg has latest `0.17.8` version now available.
Also added `libjuice` `1.0.2`.

**Comment by paullouisageneau** [comment]
@crisboarna Thank you!
