### ISSUE TITLE
Possible data race on websocket when ping is sent creating malformed frames

### ISSUE THREAD

**Issue by peclatj** [paullouisageneau/libdatachannel#664]
Hello, I have encountered a bug, when a ping and a message are sent from a libdatachannel websocket to a websocket server (in JS).
Sometimes, every 10 min. while sending 200 messages per seconds the websocket server says that the frames are malformed and closes the socket.
And indeed I have noticed using tcpdump and prints in the code that two headers are sent followed by two payloads.

It should be:
Ping Header -> Ping Payload -> Message header -> Message Payload

but it is sometimes:
Ping Header -> Message header -> Ping Payload -> Message Payload

Even when I use a more reasonable rate of messages, it still happens at least once per day. It has been the case for a while now, many months but I did not understood the problem back then and just restarted my program automatically.

I'm using the v0.17 branch.

It is not systematic, most pings do not cause the bug, that lead me to think it's a data race issue. However adding a mutex in TcpTransport::trySendMessage does not solve the problem. It helps make the prints more readable however.

I have attached the prints from the codes and tcpdump:
[tcpdumpSimplified.txt](https://github.com/paullouisageneau/libdatachannel/files/9006071/tcpdumpSimplified.txt)
[webSocketLibDataChannel.txt](https://github.com/paullouisageneau/libdatachannel/files/9006072/webSocketLibDataChannel.txt)
[webSocketServer.txt](https://github.com/paullouisageneau/libdatachannel/files/9006073/webSocketServer.txt)

The frames that start with:
- 0x81 are message headers
- 0x88 are close header
- 0x89 are ping header
- 0x8a are pong header
- the rest are payloads

I hope it can help finding the bug.
Thank you.

**Comment by paullouisageneau** [comment]
Thank you for reporting the issue, I'll push a fix when a moment.

**Comment by paullouisageneau** [comment]
Fix released in v0.17.8
