### ISSUE TITLE
Segmentation Fault DtlsTransport

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#67]
I am testing like that;
* Create peer connection
* Connect (signaling etc...)
* Check connection is successful
* Delete peer object
* Start again

I got error on this line;
https://github.com/paullouisageneau/libdatachannel/blob/8530b20dbea34d27e52ae1e8a4aeda0d51c11725/src/dtlstransport.cpp#L395

**Comment by paullouisageneau** [comment]
You mean that you delete the peer connection then create a new one to start again?

**Comment by murat-dogan** [comment]
Yes

**Comment by paullouisageneau** [comment]
I'm trying to run the connectivity test in a loop but I don't reproduce the crash for now. Is there something I'm missing?

**Comment by murat-dogan** [comment]
I think this is also related to issue #68 .
