### ISSUE TITLE
Problems encountered when using the streamer in the example

### ISSUE THREAD

**Issue by sym19991125** [paullouisageneau/libdatachannel#684]
Hello guys. When we use the streamer in the example, it can be used normally when the video sender and receiver are in the same local area network, but when the video sender and receiver are in different local area networks, ice candidate checking will always be displayed, and video transmission cannot be performed. What is the reason for this?

**Comment by paullouisageneau** [comment]
Did you enable "Use STUN server" on the receiver page?

**Comment by sym19991125** [comment]
> 

Yes, it has been selected, but it doesn't work. I also want to ask where is the candidate information exchanged during the connection establishment process?

**Comment by paullouisageneau** [comment]
What is your network setup? If both peers are IPv4-only and behind carrier-grade NATs it's expected that ICE can't open a peer-to-peer connection (in that case you'd need to add a TURN server).

You can see the exchanged descriptions with candidate information in the signaling server output. You can also see the candidates listed on the page `about:webrtc` in Firefox or `about:webrtc-internals` in Chrome.

**Comment by sym19991125** [comment]
network setup is IPv6.
Does this receiver page refer to an html page or a command line terminal?

**Comment by ZL97** [comment]
Here are our candidate images. The first and second images show stuN server unchecked, and the third and fourth images show STUN server unchecked
![27531658311534_ pic](https://user-images.githubusercontent.com/42026987/179957863-66d82a4b-21ea-4966-a90f-6b84cb0606ae.jpg)
![27551658311547_ pic](https://user-images.githubusercontent.com/42026987/179957875-cb362c86-8dfb-4c91-bcd3-65bf40c7cec3.jpg)
Here are the ones that use STUN
![27571658311571_ pic](https://user-images.githubusercontent.com/42026987/179957932-a697db0c-a37f-449b-a208-e8e5ad065f0e.jpg)
![27581658311579_ pic](https://user-images.githubusercontent.com/42026987/179957942-2743954d-0a49-4db1-9971-e7560445bc70.jpg)
The following is the state display under different Lans
![27591658311602_ pic](https://user-images.githubusercontent.com/42026987/179958089-58455994-8eae-4bcf-931b-53b863c30310.jpg)

We ran pythonSingleServer on a macbook using Intranet penetration, ran the Streamer project on a Linux host, and connected the Streamer to pythonSingleServer on a macbook. Then WE opened the HTML web page on the macbook. Above is the background of our project. Please take a look at the problem. Thank you.

**Comment by paullouisageneau** [comment]
When STUN is enabled, there is no `srflx` in the browser answer, only two host candidates, meaning the STUN server is not reachable on the browser side. There is also no IPv6 candidate on the browser side so IPv6 is probably not available.

The default STUN server might be blocked in your country (typically if you are located in China). You should try another one: https://github.com/paullouisageneau/libdatachannel/blob/d0e201ab776dba1b90e7b0a8f237083219c12798/examples/streamer/client.js#L33

However, the connection should still be possible in this scenario as the browser should still be able to reach the application on its srflx candidate, provided that it has UDP connectivity and that the application is not behind a carrier-grade NAT. Therefore, it's also possible that the browser side does not have proper UDP connectivity, which also explains why it can't reach the STUN server.

**Comment by ZL97** [comment]
Thank you for your reply. Yes I am in China, I am on the Android end use webrtc official library, using stun:stun.l.google.com: 19302 can be normal visit, but in the same under the network environment, The above problem of peerConnetcion cannot be established on Linux and HTML. To test whether it was a STUN server, I replaced the STUN server and tested that it was available, but that didn't work.
If stuN is the problem, why is there no communication between different Lans when stuN server is not selected?
![28431658397184_ pic](https://user-images.githubusercontent.com/42026987/180186241-404545c0-c3c2-4b92-8820-17155c95825e.jpg)

**Comment by ZL97** [comment]
I ran another test and found that the STUN server returned this erro
![28771658398085_ pic](https://user-images.githubusercontent.com/42026987/180188990-35392ec1-9ae7-46ad-b9c8-bcb7fadb3a3a.jpg)
r

**Comment by ZL97** [comment]
I ran two more tests and found that the STUN server returned this error, but the second time I could see SRFLX
![28771658398085_ pic](https://user-images.githubusercontent.com/42026987/180189654-a064fff8-80b9-4e7f-8e9e-a598a858811f.jpg)
![28851658398248_ pic](https://user-images.githubusercontent.com/42026987/180189671-819accc7-e35f-4ac0-a61b-840942218d9e.jpg)

**Comment by ZL97** [comment]
I ran two more tests and found that the STUN server returned this error, but the second time I could see SRFLX
![28771658398085_ pic](https://user-images.githubusercontent.com/42026987/180189761-a0fd4e18-4a93-44b9-ba8b-1692a61b8a49.jpg)
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/42026987/180189781-36c2ec73-c7a1-4119-a2a2-47678914fece.png">

**Comment by paullouisageneau** [comment]
Your tests show that the STUN servers you tried can't be reliably reached. You probably should use one located inside China, possibly your own one. Anyway, that's unrelated to libdatachannel as the issue happens with the official browser WebRTC stack.

>  If stuN is the problem, why is there no communication between different Lans when stuN server is not selected?

A STUN server is necessary to communicate between two different LANs separated by NATs, it won't work without one.

**Comment by ZL97** [comment]
Ok thank you, I changed a domestic STUN server can work normally
