### ISSUE TITLE
RFC8824 in the README links to RFC8827

### ISSUE THREAD

**Issue by JRF63** [paullouisageneau/libdatachannel#689]
[At this part](https://github.com/paullouisageneau/libdatachannel/blob/9aa6d48f2f9ad8c08ba38111e6ee3603d8a5c613/README.md?plain=1#L151).

I'm assuming both of those are supposed to be RFC8827? 8824 doesn't seem to be related to WebRTC.

**Comment by paullouisageneau** [comment]
Thanks for reporting, fixed by 14c83d81996ba20407b81c0c3a8b25f8e90ecdde
