### ISSUE TITLE
Allow a peerconnection to offer localhost identities.

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#708]
Hi, I wanted to create a loopback only peerconnection to connect with myself, but it seems like that the library doesn't generate candidate/offer with 127.0.0.1/::1 as ip. I workaround this by using [rtc::Configuration::bindAddress](https://github.com/paullouisageneau/libdatachannel/blob/master/include/rtc/configuration.hpp#L80), thankfully I used libjuice so I could bind on loopback, then libdatachannel started to generate loopback candidates/offers.
Is it the way to go or is there a better way ? I'm using libdatachannel v0.17.1

**Comment by paullouisageneau** [comment]
Hi, this is the proper way. There is also the compile-time flag `JUICE_ENABLE_LOCALHOST_ADDRESS` to make libjuice always gather candidates for the loopback interface. I don't think this is possible with libnice.

However, note that gathering ICE candidates for the loopback interface is forbidden by the specification, so this is non-standard and might cause issues with some other implementations.

**Comment by Nemirtingas** [comment]
Ok, I use this because some users have no interfaces other than loopback. (Using a VM). So my best bet would be to just drop the loopback peerconnection and emulate that behavior myself ?
