### ISSUE TITLE
HelloVerifyRequest as per rfc6347

### ISSUE THREAD

**Issue by rajukasaramoni** [paullouisageneau/libdatachannel#711]
Hello, In the DTLS handshake server is not asking for HelloVerifyRequest upon receiving ClientHello. how to enable this option so that DTLS server will ask for Client to send ClientHello with Cookie.

**Comment by paullouisageneau** [comment]
This should not be useful with WebRTC as the ICE layer provides the same protection against DDoS attacks, and it adds a useless round trip to the connection establishment process.

Anyway, it would require modifications to the `DtlsTransport` class, for GnuTLS see the example [here](https://github.com/gnutls/gnutls/blob/bc7f67c46736486426ba1bd22a52a67bd58beee5/tests/mini-dtls-hello-verify.c#L179) and for OpenSSL you need to use [SSL_CTX_set_cookie_generate_cb and SSL_CTX_set_cookie_verify_cb](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_cookie_verify_cb.html).

**Comment by rajukasaramoni** [comment]
Thank you so much for quick response Paul-Louis. this helped me.
