### ISSUE TITLE
How to disable openssl/GnuTLS functionality from libdatachannel

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libdatachannel#713]
Hi, I am trying to disable openssl/GnuTLS functionality from libdatachannel. Can someone help with information.

**Comment by paullouisageneau** [comment]
Duplicate of https://github.com/paullouisageneau/libdatachannel/issues/399

**Comment by paullouisageneau** [comment]
There is no option to disable the security layer, however you may find some information in https://github.com/paullouisageneau/libdatachannel/issues/399
