### ISSUE TITLE
SCTP: SHUTDOWN_COMPLETE message is not being sent

### ISSUE THREAD

**Issue by rajukasaramoni** [paullouisageneau/libdatachannel#715]
Hello Paul-Louis, We are calling dc->close() followed by pc->close() functions on both local and remote objects but only SCTP shutdown and shutdown_ack being exchanged. anything else needs to be called to have graceful shutdown to complete?

**Comment by paullouisageneau** [comment]
Currently connection teardown is immediate so when the SHUTDOWN_ACK comes back the lower DTLS layer will be shut down already. The reason for this incorrect implementation is that browsers do not implement the shutdown procedure properly either.

**Comment by rajukasaramoni** [comment]
Thank you Paul-Louis.
