### ISSUE TITLE
Please recommend a thread model

### ISSUE THREAD

**Issue by trump-7575** [paullouisageneau/libdatachannel#716]
This question is about where rtc::PeerConnection should  be created and where the sdp and ice candidates are fed.

The example libdatachannel/examples/client/main.cpp  shows all is done at websocket's routine. Does it mean
that    rtc::PeerConnection  has its own worker thread and signaling thread ?

My application needs the datachannels to send large amount of data reliably and as soon as possible.
( Of course , congestion algorithm should be implemented at application sides ) Thus I had to think of the modelling issue.

However , I didnot find any issues about the model. Nor the readme.md mentions it. Does it mean putting all 
  rtc::PeerConnection  and  rtc::DataChannel  related tasks at the websocket's routine is O.K. ?

**Comment by paullouisageneau** [comment]
libdatachannel has its own worker threads from an internal threadpool which are used to trigger its callbacks, therefore you need to ensure proper synchronization on your side.

Classes are reentrant and should be thread-safe, meaning you can call the object methods from your own thread or directly from the thread of a callback, either from the same object or another.

You can create the objects where you want provided you take care of lifetimes, especially of what is captured in callback functions.

**Comment by ClosetMonkey** [comment]
It there more detail possible of how threads are used? For example does IO use a thead pool or just one thread separate from the main thread. If a pool is there any way to set thread count? If libdatachannel automatically sets thread count does it create one thread per processor? Thank you

**Comment by ClosetMonkey** [comment]
Looking through the source it looks like the thread pool size has a cap at THREADPOOL_SIZE = 4. Is this correct? I'm looking here https://github.com/paullouisageneau/libdatachannel/blob/d9a9a4dcfb7445ed4f305c9aba889a162a4bad30/src/impl/internals.hpp#L56 and here https://github.com/paullouisageneau/libdatachannel/blob/796c336087ceae1d65efbda38fcd0cb735043ffa/src/impl/init.cpp#L128

**Comment by paullouisageneau** [comment]
There is a dedicated thread to poll sockets the underlying library libjuice, and libdatachannel has another dedicated thread to poll sockets for WebSockets. The library usrsctp also runs a couple threads under the hood. 

Currently each peer connection performs DTLS decryption in a dedicated thread, however it will be moved to the thread pool in a future version. 

Other tasks, in particular calling the user callbacks, are delegated to the thread pool which indeed spawns 4 threads by default.

**Comment by paullouisageneau** [comment]
There is a dedicated thread to poll sockets in the underlying library libjuice, and libdatachannel has another dedicated thread to poll sockets for WebSockets. The library usrsctp also runs a couple threads under the hood. 

Currently each peer connection performs DTLS decryption in a dedicated thread, however it will be moved to the thread pool in a future version. 

Other tasks, in particular calling the user callbacks, are delegated to the thread pool which indeed spawns 4 threads by default.

**Comment by ClosetMonkey** [comment]
Thank you

**Comment by paullouisageneau** [comment]
> Currently each peer connection performs DTLS decryption in a dedicated thread, however it will be moved to the thread pool in a future version.

FYI this is done in https://github.com/paullouisageneau/libdatachannel/pull/807, after this change new connections don't involve new threads anymore.

**Comment by paullouisageneau** [comment]
> Currently each peer connection performs DTLS decryption in a dedicated thread, however it will be moved to the thread pool in a future version.

The change is done in https://github.com/paullouisageneau/libdatachannel/pull/807, after this change new connections don't involve new threads anymore.
