### ISSUE TITLE
Bug: On windows, WSAStartup must be called externally before using WebSocketServer

### ISSUE THREAD

**Issue by Dakror** [paullouisageneau/libdatachannel#718]
WebSocketServer constructs a TcpServer in the constructor, which then proceeds to call the  PollInterrupter constructor, which tries to use getaddrinfo. 

Init::doInit will be called only ater down the line when the members of the WSS get initialized.

**Comment by paullouisageneau** [comment]
Indeed, `mInitToken` is declared after `tcpServer` in `WebSocketServer`, which cause the initialization to happen too late, causing the issue on WIndows.
