### ISSUE TITLE
How to send and receieve binary data

### ISSUE THREAD

**Issue by stevedanOgochu** [paullouisageneau/libdatachannel#72]
Please, how can I send binary data of type void * instead of char, is it possible to do so with this library?

**Comment by paullouisageneau** [comment]
Sure, you can simply cast your `void*` pointer into `char*`, and pass the data size as usual:
```
rtcSendMessage(dc, (char*)myVoidPointer, mySizeInBytes);
```

**Comment by stevedanOgochu** [comment]
Perfect, it perfectly, Are they any examples using the new WebSocket API you just created.

**Comment by paullouisageneau** [comment]
Not for now, but I plan to push one soon. In the C API, the functions to send and receive on WebSockets are actually the same as DataChannels, only creation and deletion are done with `rtcCreateWebSocket(url)` and  `rtcDeleteWebsocket(ws)`.
