### ISSUE TITLE
Wrong rtcSendMessage documentation

### ISSUE THREAD

**Issue by llenck** [paullouisageneau/libdatachannel#722]
`pages/content/pages/reference.md:445` states about the return value of `rtcSendMessage`:

> Return value: `RTC_ERR_SUCCESS` or a negative error code

However, if you look at `src/capi.cpp:686`, the return value on success seems to not be `RTC_ERR_SUCCESS`, but the input length.

I'm opening an issue and not a PR because I don't know which behaviour is intended, but either way, it should be a trivial fix.

**Comment by paullouisageneau** [comment]
Good catch, the documentation is actually right, it should simply return success or error otherwise it would hint that it can send partial messages.
