### ISSUE TITLE
Re-licensing under MPL 2.0

### ISSUE THREAD

**Issue by paullouisageneau** [paullouisageneau/libdatachannel#728]
After different discussions (in particular in https://github.com/paullouisageneau/libdatachannel/issues/557), there seems to be a common blocking point with the difficulty to bundle the library into closed-source apps due to the LGPL license, even the impossibility to do so for apps in Apple's App store.

**Therefore, I'd like to re-license libdatachannel under [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/).**

The MPL 2.0 is also a weak copyleft license like the LGPL and is compatible with the GPL. Basically, modifications must still be redistributed under the same license, but the license applies on file level which allows combining the code with code under any other license. In particular, it would allow static linking the library with closed-source applications without restrictions (see more information in the [MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)). It should not change anything for current libdatachannel users.

A preliminary requirement is also re-licensing the dependency libjuice under MPL 2.0: https://github.com/paullouisageneau/libjuice/issues/183

@LeoNavel @murat-dogan @hanseuljun @industriousonesoft @stevedanomodolor @ecotarobles @laramackey @SE2Dev @asgeir @DavidEichmann @willm @nicochatzi @hhgyu @cheungxiongwei @aaronalbers @bigfarts @Faless You have made non-trivial contributions to the library, tests, or example code. Thank you again! Could you please confirm here whether you agree with the re-licensing under MPL 2.0?

**Comment by murat-dogan** [comment]
I will follow your decision.

I guess no need to change `node-datachannel` license, right?

**Comment by paullouisageneau** [comment]
@murat-dogan Thank you. You don't need to change the license, but it could be good to make usage easier. Currently node-datachannel has the same limitations, for instance you can't easily bundle it in a closed-source electron app.

**Comment by stevedanomodolor** [comment]
> After different discussions (in particular in #557), there seems to be a common blocking point with the difficulty to bundle the library into closed-source apps due to the LGPL license, even the impossibility to do so for apps in Apple's App store.
> 
> **Therefore, I'd like to re-license libdatachannel under [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/).**
> 
> The MPL 2.0 is also a weak copyleft license like the LGPL and is compatible with the GPL. Basically, modifications must still be redistributed under the same license, but the license applies on file level which allows combining the code with code under any other license. In particular, it would allow static linking the library with closed-source applications without restrictions (see more information in the [MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)). It should not change anything for current libdatachannel users.
> 
> A preliminary requirement is also re-licensing the dependency libjuice under MPL 2.0: [paullouisageneau/libjuice#183](https://github.com/paullouisageneau/libjuice/issues/183)
> 
> @LeoNavel @murat-dogan @hanseuljun @industriousonesoft @stevedanomodolor @ecotarobles @laramackey @SE2Dev @asgeir @DavidEichmann @willm @nicochatzi @hhgyu @cheungxiongwei @aaronalbers @bigfarts @Faless You have made non-trivial contributions to the library, tests, or example code. Thank you again! Could you please confirm here whether you agree with the re-licensing under MPL 2.0?

For me no problem

**Comment by ecotarobles** [comment]
For me no problem either.  But adding MPL as an alternate or dual license as was done with https://github.com/radekp/linux-2.6/blob/master/drivers/char/random.c would also be fine.
--Erik Cota-Robles
    On Friday, October 7, 2022 at 01:15:25 PM GMT+3, Stevedan Ogochukwu Omodolor ***@***.***> wrote:  
 
 



After different discussions (in particular in #557), there seems to be a common blocking point with the difficulty to bundle the library into closed-source apps due to the LGPL license, even the impossibility to do so for apps in Apple's App store.

Therefore, I'd like to re-license libdatachannel under MPL 2.0.

The MPL 2.0 is also a weak copyleft license like the LGPL and is compatible with the GPL. Basically, modifications must still be redistributed under the same license, but the license applies on file level which allows combining the code with code under any other license. In particular, it would allow static linking the library with closed-source applications without restrictions (see more information in the MPL 2.0 FAQ). It should not change anything for current libdatachannel users.

A preliminary requirement is also re-licensing the dependency libjuice under MPL 2.0: paullouisageneau/libjuice#183

@LeoNavel @murat-dogan @hanseuljun @industriousonesoft @stevedanomodolor @ecotarobles @laramackey @SE2Dev @asgeir @DavidEichmann @willm @nicochatzi @hhgyu @cheungxiongwei @aaronalbers @bigfarts @Faless You have made non-trivial contributions to the library, tests, or example code. Thank you again! Could you please confirm here whether you agree with the re-licensing under MPL 2.0?


For me no problem

**Comment by Faless** [comment]
I agree with the re-licensing under MPL 2.0.
Thanks again for your amazing work  maintaining this library.

**Comment by hanseuljun** [comment]
Moving to MPL 2.0 makes a lot of sense and I have no problems with it!

**Comment by willm** [comment]
No objections either, thanks for taking this project forward.

**Comment by LeoNavel** [comment]
No problem 🙂Thanks for your amazing work!

**Comment by asgeir** [comment]
I approve re-licensing under MPL 2.0

**Comment by paullouisageneau** [comment]
Thank you all!

@ecotarobles As I understand, dual-licensing would make sense with MPL 1 (for instance libnice is licensed under LGPL 2.1 only or MPL 1.1), but it should not be necessary with MPL 2.0 without the option "Incompatible With Secondary Licenses" that won't be chosen here (see [here](https://www.mozilla.org/en-US/MPL/2.0/FAQ/#mpl-and-lgpl) for more information).

**Comment by paullouisageneau** [comment]
@industriousonesoft @laramackey @SE2Dev @DavidEichmann @hhgyu @cheungxiongwei @aaronalbers Could you please confirm here whether you agree?

**Comment by SE2Dev** [comment]
I have no objections to switching to a more accessible license.

I believe this should resolve some of the issues regarding static linking w/ custom Rust bindings, correct? Particularly because libdatachannel, itself, would be unmodified in situations like that. Would [libjuice](https://github.com/paullouisageneau/libjuice) need to be relicensed as well?

**Comment by paullouisageneau** [comment]
@SE2Dev Thank you! You are correct, it would solve issues with static linking the unmodified library in all situations, including when using bindings. The plqn is to re-license libjuice as well, see https://github.com/paullouisageneau/libjuice/issues/183.

**Comment by DavidEichmann** [comment]
I have a shallow understanding of the differences, but as far as I can see the MLP 2.0 license is copyleft and specifically allows the library to be distributed with other larger bodies of work i.e. anyone is allowed to use this library in a project and distribute it statically linked to libdatachannel. That aspect sounds good to me. I have no objections.

**Comment by rokups** [comment]
- [x] @LeoNavel - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1272322653)
- [x] @murat-dogan - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1271342112)
- [x] @hanseuljun - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1272021313)
- [ ] @industriousonesoft
- [x] @stevedanomodolor - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1271402729)
- [x] @ecotarobles - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1271424216)
- [x] @laramackey - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1278942610)
- [x] @SE2Dev - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1277773057)
- [x] @asgeir - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1273667567)
- [x] @DavidEichmann - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1290358265)
- [x] @willm - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1272101690)
- [x] @nicochatzi - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1274314932)
- [ ] @hhgyu
- [ ] @cheungxiongwei
- [ ] @aaronalbers
- [x] @bigfarts - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1271821622)
- [x] @Faless - [link](https://github.com/paullouisageneau/libdatachannel/issues/728#issuecomment-1271483101)

I allowed myself to compile a list of contributor confirmations, to better track who is yet to respond. Feel free to copy it to the first post.

Also, @industriousonesoft, @hhgyu, @cheungxiongwei, @aaronalbers - we would love to hear from you.

**Comment by hhgyu** [comment]
No objection.

**Comment by aaronalbers** [comment]
No objection.

**Comment by JonasVautherin** [comment]
Fine for me!

**Comment by paullouisageneau** [comment]
@industriousonesoft @cheungxiongwei It would be really helpful to have answers from you!

**Comment by ecotarobles** [comment]
I believe I already told you but it's fine with me and with Oy Gamecluster, Ltd.
--Erik Cota-Robles, +358 41 748 5774  USA (Google Voice) +1 503 808 0042 

    On Thursday, November 10, 2022 at 01:50:26 PM GMT+2, Paul-Louis Ageneau ***@***.***> wrote:  
 
 


@industriousonesoft @cheungxiongwei It would be really helpful to have answers from you!

**Comment by paullouisageneau** [comment]
@ecotarobles Yes thank you, I was only pinging the last two persons.

**Comment by cheungxiongwei** [comment]
I approve re-licensing under MPL 2.0

**Comment by paullouisageneau** [comment]
As it has been two months and all my attempts to reach out went unanswered, I took the liberty to remove non-trivial code merges from @industriousonesoft to unblock the license change.

I opened https://github.com/paullouisageneau/libdatachannel/pull/769 to change the license across the codebase.

**Comment by rokups** [comment]
Thank you very much for all the hard work! Game developers are silently celebrating the fact that now it is much easier to bring their multiplayer games to the web :rocket:

**Comment by paullouisageneau** [comment]
Thanks! I'm glad to announce that libdatachannel is licensed under MPL 2.0 starting from version 0.18.0 which I have just released.

**Comment by paullouisageneau** [comment]
@murat-dogan @lerouxrgd You may be interested in re-licensing the wrappers as it would facilitate usage in ecosystems revolving around more permissive licenses.
