### ISSUE TITLE
`track.isOpen()` is `false` in the track.onOpen() callback

### ISSUE THREAD

**Issue by JonasVautherin** [paullouisageneau/libdatachannel#730]
Note: I had asked on [StackOverflow](https://stackoverflow.com/questions/74211320/webrtc-track-onopen-is-called-but-track-is-not-open), but I was told to ask here instead.

Using libdatachannel, I establish a `PeerConnection` between two partners using some out-of-band signaling. I can create `DataChannel`s and send data between them successfully (with `peer_connection->createDataChannel()`).

But I am struggling to do the same with a video track. Here is what I do:

* I create a track from one partner:

```c++
rtc::Description::Video media("myvideo", rtc::Description::Direction::RecvOnly);
media.addH264Codec(96);
media.setBitrate(3000);

auto track = peer_connection->addTrack(media);
peer_connection->setLocalDescription();
```

Note how I call `setLocalDescription()` after `addTrack`, so that libdatachannel will negotiate the track and I don't need to send an SDP out of band (at least that's my understanding).

* From the other partner, I check the `onTrack()` callback:

```c++
peer_connection->onTrack([this](const std::shared_ptr<rtc::Track>& track) {
    track->onClosed([]() {
        std::cout << "onClosed" << std::endl;
    });
    track->onOpen([]() {
        std::cout << "onOpen" << std::endl;

        if (track->isOpen()) {
            std::cout << "track is open" << std::endl;
        } else {
            std::cout << "track is not open" << std::endl;
        }
    });
}
```

What I observe is that `onTrack` is called, and the `track` has the `mid` I set from the sending side ("myvideo"). But right in the `onOpen()` callback, the call to `track->isOpen()` says that "track is __not__ open".

If I try to use the track later (with e.g. `track->send()`), if fails with a SIGABRT:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Track is closed
Signal: SIGABRT (Aborted)
```

So somehow it feels like my track was never properly open in the first place. Though I would expect `track->onOpen()` to be called... when the track is open.

Am I missing something?

**Comment by Nemirtingas** [comment]
This issue looks like this one: #596

**Comment by JonasVautherin** [comment]
Hmm interesting. Though I am using v0.17.10, which should have the fix, shouldn't it? :thinking:

**Comment by JonasVautherin** [comment]
Tracking a bit what's happening when I call `isOpen()`. The test [here](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/track.cpp#L102):

```cpp
return !mIsClosed && mDtlsSrtpTransport.lock();
```

Return false because `mDtlsSrtpTransport == nullptr`. However, I see that it is set before, i.e. `[Track::open()](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/track.cpp#L119) is called, with `transport == nullptr`:

```cpp
void Track::open(shared_ptr<DtlsSrtpTransport> transport) {
	{
		std::lock_guard lock(mMutex);
		mDtlsSrtpTransport = transport;
	}

	if (!mIsClosed)
		triggerOpen();
}
```

I don't know yet who is calling `Track::open`, but it feels like it should not be called with a `nullptr` transport as an argument, right?

**Comment by Nemirtingas** [comment]
I believe its this function: https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L756-L766

**Comment by JonasVautherin** [comment]
Yes that's where I am now:

```cpp
void PeerConnection::openTracks() {

// HERE mDtlsTransport is NOT nullptr

#if RTC_ENABLE_MEDIA
	if (auto transport = std::atomic_load(&mDtlsTransport)) {
// HERE transport is nullptr
		auto srtpTransport = std::dynamic_pointer_cast<DtlsSrtpTransport>(transport);
		iterateTracks([&](shared_ptr<Track> track) {
			if (!track->isOpen())
				track->open(srtpTransport);
		});
	}
#endif
}
```

Trying to understand why `transport` is null given that `mDtlsTransport` is not

**Comment by Nemirtingas** [comment]
std::dynamic_pointer_cast triies to get a DtlsSrtpTransport shared pointer. If it returns null, that means that the mDtlsTransport object was not created as a DtlsSrtpTransport but at a DtlsTransport I guess.

**Comment by JonasVautherin** [comment]
Yes I can confirm that it goes [here](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L257):

```cpp
		if (!transport) {
			// DTLS only
			transport = std::make_shared<DtlsTransport>(lower, certificate, config.mtu,
			                                            verifierCallback, dtlsStateChangeCallback);
		}
```

**Comment by JonasVautherin** [comment]
Interestingly, it does not go [here](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L247) at all, but I am not getting any PLOG output (I added an `std::cout` for debugging).

That's a bit weird :thinking:

**Comment by Nemirtingas** [comment]
So, if there is an error on user side, the Track::onOpen is called but with an invalid track type, I think this should throw an exception or maybe an error somewhere instead of silently failing without notification, what do you think @paullouisageneau  ?

**Comment by paullouisageneau** [comment]
There is currently a limitation for tracks creation: the SRTP transport is created only if a track is present in the first description exchange, meaning tracks created with additional description exchanges on a datachannel-only connection won't work. The reason for this is to prevent allocating useless resources in case the user only opens datachannels. 

It seems this scenario results in a silent error while it should indeed throw an exception at some point to inform the user rather than happily creating the track without a functional transport.

For now, the way around it is to negotiate the track while opening the PeerConnection, so the track is present in the first offer.

**Comment by JonasVautherin** [comment]
Do I understand correctly that this is a limitation of `libdatachannel` (not WebRTC)? I really think that I want to dynamically create tracks :innocent:.

Would it make sense to add an option to do this optimization when creating the `PeerConnection`? I.e. by default it would create the SRTP transport, but one could enable this optimization if necessary (or the other way round: one could disable the optimization).

Does that seem feasible? I could try to have a look and see if I can contribute that, if it seems interesting to you. Would be nice if you could give me 1-2 pointers as to where to start looking in the codebase :blush:.

**Comment by Nemirtingas** [comment]
Hi, to me, if you can modify libdatachannel's source, the best way would be to add a parameter here:
https://github.com/paullouisageneau/libdatachannel/blob/master/include/rtc/configuration.hpp#L76-L98

Add something like `bool forceTrackAllocation;` then when creating your PeerConnection, set the forceTrackAllocation to true.
Then here: https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/peerconnection.cpp#L242
Change the condition to:
```
if (config.forceTrackAllocation || auto local = localDescription(); local && local->hasAudioOrVideo()) {
```

**Comment by JonasVautherin** [comment]
That's better, now the track is open! But I wonder if that's enough, because the SSRCs and the `rtc::Description::Direction` I set from the `addTrack` side don't get propagated to the `onTrack` side.

I create the track with:

```cpp
    rtc::Description::Video media("myvideo", rtc::Description::Direction::SendRecv);
    media.addH264Codec(96);
    media.addSSRC(24, "some-name");
    media.setBitrate(3000);

    pc->addTrack(media);
```

And in the other side, in the `onOpen()` callback of the track appearing in `onTrack()`, I try to print:

* `track->mid()` -> this is propagated, it is "myvideo"
* `track->description().getSSRCs().size()` -> this is `0`, so my SSRC is not propagated
* `track->direction()` -> here it is not super consistent:
    * If I set `RecvOnly` above, it is propagated as `RecvOnly` (I would expect `SendOnly` on the other side?)
    * If I set `SendOnly`, it is propagated as `RecvOnly`
    * If I set `SendRecv`, it is propagated as `SendRecv`

Is that all expected?

**Comment by paullouisageneau** [comment]
> Would it make sense to add an option to do this optimization when creating the `PeerConnection`? I.e. by default it would create the SRTP transport, but one could enable this optimization if necessary (or the other way round: one could disable the optimization).
> 
> Does that seem feasible? I could try to have a look and see if I can contribute that, if it seems interesting to you. Would be nice if you could give me 1-2 pointers as to where to start looking in the codebase :blush:.

It sounds good! You could add a boolean setting in `rtc::Configuration` (called for instance `disableMedia`) and make it have a behavior similar to `RTC_ENABLE_MEDIA == 0`, but at runtime. 

> `track->description().getSSRCs().size()` -> this is `0`, so my SSRC is not propagated

This is expected as `track->description()` is actually the **local** media description, which advertises only the SSRCs **sent** in the track, so you won't retrieve the remote SSRCs there as they are the SSRCs sent remotely and received locally. The received media packets should still be forwarded to the corresponding track according to the remote SSRCs.

> If I set `RecvOnly` above, it is propagated as `RecvOnly` (I would expect `SendOnly` on the other side?)

It should definitely show `SendOnly` on the remote side, the logic to do so is in [Description::Media::reciprocate()](https://github.com/paullouisageneau/libdatachannel/blob/f5961525d16f11579debe02ffec25136b7b18198/src/description.cpp#L864). If you can reproduce the behavior, it might be a bug.

> Because what I am observing now is that from the side that received the track (`onTrack`), I can now send data, and it is received (it reaches [this point](https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/dtlssrtptransport.cpp#L194) on the receiving side), but it never triggers the `track->onMessage()` callback of the track created with `addTrack` above. Not sure if it would need e.g. the SSRC or something for that?

Have you checks the payload type and SSRC in the RTP packets you send in the track? They should match the media description specified at track creation (i.e. payload type 96 and SSRC 24 in your case). FYI forwarding packets into tracks according to SSRC is done in [PeerConnection::forwardMedia()](https://github.com/paullouisageneau/libdatachannel/blob/ab48ee0d79aa6ccbb103da8b640df80ccf4daa8a/src/impl/peerconnection.cpp#L533).

**Comment by JonasVautherin** [comment]
> It should definitely show SendOnly on the remote side, the logic to do so is in [Description::Media::reciprocate()](https://github.com/paullouisageneau/libdatachannel/blob/f5961525d16f11579debe02ffec25136b7b18198/src/description.cpp#L864). If you can reproduce the behavior, it might be a bug.

It was my mistake, I messed up when debugging :see_no_evil:. I suggest adding an `operator<<` for `rtc::Description::Direction`, so that I won't make that mistake again :grin:: https://github.com/paullouisageneau/libdatachannel/pull/734

Now moving on to checking the SSRCs with Wireshark :+1:

**Comment by JonasVautherin** [comment]
> Have you checks the payload type and SSRC in the RTP packets you send in the track? They should match the media description specified at track creation (i.e. payload type 96 and SSRC 24 in your case).

Type is 96 indeed (`Payload type: DynamicRTP-Type-96 (96)`), but SSRC is completely off :sweat_smile:. It changes for every run, but it's a number like `2645045414` instead of `24`. It actually works if I:

1. Run the server
2. Run the client (which runs `addTrack()`, setting `RecvOnly` and SSRC=24, after which the server starts sending)
3. Stop the client, and recompile it with the SSRC sent by the server (e.g. `2645045414`)
4. Run the client

So somehow my SSRC does not propagate correctly, it seems. But I'm not sure yet what I am doing wrong for that :thinking:.

**Comment by JonasVautherin** [comment]
Same thing happens if I invert the sender, i.e. if the one calling `addTrack()` is also the one calling `track->send()`...

**Comment by paullouisageneau** [comment]
> Also what surprises me is that when I check in [`PeerConnection::incomingTrack`](https://github.com/paullouisageneau/libdatachannel/blob/ab48ee0d79aa6ccbb103da8b640df80ccf4daa8a/src/impl/peerconnection.cpp#L725), the `description.getSSRCs().size()` is always `0`... I would expect my `24` to arrive there, right? :thinking:

No, since the SSRC in the local SDP description correspond is **sent** on the local side. On the remote side, this SSRC will be received, so it doesn't appear in the description.

You must not set the SSRC on the receiver side, only on the sender side. Therefore, it is easier to call `addTrack()` on the sender side (most of the time the sender knows what it wants to send). You can also call `addTrack()` on the receiver side, but then you need to add the SSRC in the `incomingTrack` callback on the sender side, either with `setDescription` or by re-adding a track with the same mid.

There are multiple ways to set matching SSRCs between the source and track depending of your use case:
- Start the video pipeline, get the SSRC, add the track with the SSRC
- Choose a SSRC, set the video pipeline to use it, add the track with the SSRC
- Choose a SSRC, add the track with the SSRC, then edit RTP packets for the video pipeline so they have the right SSRC (see the media sender example)

**Comment by JonasVautherin** [comment]
> You can also call addTrack() on the receiver side, but then you need to add the SSRC in the incomingTrack callback on the sender side, either with setDescription or by re-adding a track with the same mid.

Hmm I haven't managed to make this work, but I guess I can live without it.

> Choose a SSRC, add the track with the SSRC, then edit RTP packets from the video pipeline so they have the right SSRC (see the media sender example)

This one works! I had not realized that the RTP packets needed to be edited manually.

One last question: is this (those different ways of setting the SSRC) part of the WebRTC specs, or is it rather how libdatachannel does it? Couldn't we theoretically have the SSRC be negotiated at the same time as e.g. the direction? So that one could call `addTrack()`, receive it with `onTrack()` on the other side, and it would "just work" without having to do anything on top (like re-adding a track or changing all the RTP packets before sending them).

**Comment by paullouisageneau** [comment]
> Hmm I haven't managed to make this work, but I guess I can live without it.

Oh sorry, I'm taking my desires for realities here, it's actually something a planned to change before releasing 0.18 and I kind of forgot. Currently you need to re-add the track and renegotiate, which is a mistake. It's fixed in https://github.com/paullouisageneau/libdatachannel/pull/737

> One last question: is this (those different ways of setting the SSRC) part of the WebRTC specs, or is it rather how libdatachannel does it? Couldn't we theoretically have the SSRC be negotiated at the same time as e.g. the direction? So that one could call addTrack(), receive it with onTrack() on the other side, and it would "just work" without having to do anything on top (like re-adding a track or changing all the RTP packets before sending them).

It's part of the specs, and since libdatachannel is low-level it doesn't abstract the media streams for the user, which would allow to set the SSRCs on sender-side automatically. 

WebRTC relies on SDP offer/answer negotiation for RTP, which mandates to advertise only the sent SSRCs in the media description. The reasoning is that the SSRC is source-specific and each side is responsible for its own sources. As [RFC 5576](https://datatracker.ietf.org/doc/html/rfc5576#section-8) describes it:
```
8. Usage With the Offer/Answer Model

When used with the SDP Offer/Answer Model [RFC3264], SDP source-
specific attributes describe only the sources that each party is
willing to send [...] 
The SSRC IDs for sources described by an SDP answer MUST be distinct
from the SSRC IDs for sources of that media stream in the offer.
```

**Comment by JonasVautherin** [comment]
Got it, thanks a lot for all the insights! :pray:
