### ISSUE TITLE
Is it possible to depacketize the RTP packets?

### ISSUE THREAD

**Issue by martinhqualabs** [paullouisageneau/libdatachannel#731]
The receiver side of my application gets RTP packets on the track->onMessage callback, but I need to depacketize them, is it possible using libdatachannel? If so, how?

**Comment by paullouisageneau** [comment]
The library currently lacks depacketizers (see https://github.com/paullouisageneau/libdatachannel/issues/676). 

However, you can do it manually with the helper struct `RtpHeader` in [rtc/rtp.hpp](https://github.com/paullouisageneau/libdatachannel/blob/99be4b7451fc68a9d52dc307b766c503fb153f8f/include/rtc/rtp.hpp#L54): you can get the sequence, timestamp, and other header information, then the codec-specific data will be from `getBody()` to the end of the buffer.
