### ISSUE TITLE
Congestion control / TWCC problem

### ISSUE THREAD

**Issue by kuzux** [paullouisageneau/libdatachannel#732]
We've been using webRTC via libdatachannel for a while without major issues now. Something we want to. also implement (hoping that it will improve connection stability) is congestion control. There are 2 main ways of implementing it
* Receiver-side (REMB)
* Sender-side (TWCC)

REMB is considered the "older" of these 2 methods (and probably affected by the fact that we can't get receiver reports #565). So the main effort is on TWCC. Here's what I did for trying this out:
1. Remove the transport-cc check in `Description::Media::generateSdpLines`
    The check had been there for quite a while (at least since the commit be7a6324dda0fdf0bc3f241f1a6ba7b1b108aa8a) and I couldn't determine why it was added in the first place
2. Add a transport-cc line to the video description
3. Add an extmap line to the same description
```
rtc::Description::Video media("video");
media.addRtxCodec(107, 123, 90000);
// ...
media.rtpMap(123)->addFeedback("transport-cc");
media.addExtMap(rtc::Description::Entry::ExtMap("http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"));
```

After doing only the first 2 of these changes, I simply get no transport-cc messages as defined in the draft rfc. After doing the third change as well, the sender process simply crashes (even before establishing a connection) every time on startup. It is probably related to the reason the check in `Description::Media::generateSdpLines` was added in the first place. I wonder why this kind of thing happens, and why the check for transport-cc was added in the first place.

**Comment by paullouisageneau** [comment]
You approach looks correct, I'm not totally sure what the check was for. 

What do you mean exactly by "the sender process simply crashes"? What is your setup here?

**Comment by paullouisageneau** [comment]
Your approach looks correct, I'm not totally sure what the check was for. 

What do you mean exactly by "the sender process simply crashes"? What is your setup here?

**Comment by kuzux** [comment]
The setup is 
* I'm on a windows server 2022 machine
* running a .net application (framework version v4.6.1, 32-bit application) which calls a native dll that uses libdatachannel (version 0.17.11, only difference from the release is the twcc check is commented out, using a 32-bit build of the library)
* a service starts & restarts the said application when it exits
* when twcc is enabled, that application simply restarts (without printing an error message) even before a webrtc connection can be established

**Comment by kuzux** [comment]
When debug logs are enabled; here are the only log lines we get from libdatachannel

```
rtc::impl::Init::doInit@120: Global initialization
rtc::impl::PollService::runLoop@167: Poll service started
rtc::impl::Certificate::Generate@223: Generating certificate (OpenSSL)
```

After that, the webrtc connection is simply closed.

**Comment by kuzux** [comment]
Found something relevant:

In/around `PollService::runLoop` https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/pollservice.cpp#L184

We have a code block like
```
PLOG_VERBOSE << "Entering poll";
timeout = -1;

ret = ::poll(pfds.data(), static_cast<nfds_t>(pfds.size()), timeout);
PLOG_VERBOSE << "Exiting poll";
```

The "entering poll" line is printed out. The "exiting poll" line should be printed out whether the call to `poll()` succeeds or not. But it does not. 

My current guess is that since we're on windows, the `poll()` functionality is provided by openssl (or some other external library), which causes a crash under certain circumstances.

**Comment by paullouisageneau** [comment]
> Found something relevant:
> 
> In/around `PollService::runLoop` https://github.com/paullouisageneau/libdatachannel/blob/master/src/impl/pollservice.cpp#L184
> 
> We have a code block like
> 
> ```
> PLOG_VERBOSE << "Entering poll";
> timeout = -1;
> 
> ret = ::poll(pfds.data(), static_cast<nfds_t>(pfds.size()), timeout);
> PLOG_VERBOSE << "Exiting poll";
> ```
> 
> The "entering poll" line is printed out when. verbose logging is enabled. The "exiting poll" line should be printed out whether the call to `poll()` succeeds or not. But it does not.
> 
> My current guess is that since we're on windows, the `poll()` functionality is provided by openssl (or some other external library), which causes a crash under certain circumstances.

It is actually unrelated to OpenSSL. `poll()` is a standard POSIX system call, on Windows libdatachannel has compile-time defines to use [WSAPoll](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll) instead.

However, I don't think it crashes there. The most probable explanation is that it crashes in another thread while the `PollService` is just waiting inside `poll()`.

> Now the question is; why does only enabling twcc trigger this behavior?

My guess something goes wrong during the creation of the `rtc::Description::Video` description. Are exceptions properly caught? Your example looks like it misses a call like `addH264Codec(123)` to set the codec, are you sure payload type 123 exists in the RTP map?

**Comment by kuzux** [comment]
In the code, it does have a call to addH264Codec(123)

```
media.addH264Codec(123, "level-asymmetry-allowed=1;profile-level-id=42e01f;packetization-mode=1");
```

**Comment by paullouisageneau** [comment]
Good, but for the symptoms it still looks like the crash happens when creating the description. Do you catch exceptions happening there?

It could be because the `ExtMap` constructor normally takes an SDP `extmap` description with the format `id[/direction] URL` (It might actually be good to add another one with typed parameters to call from application code), therefore you should call it with `ExtMap("1 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01")`.

**Comment by kuzux** [comment]
Apparently I was getting an "Invalid Description" error in that line. That happens when the ext map description string does not contain a space. (While parsing, the part after the space is parsed as a URL). 

In this case;
```
media.addExtMap(rtc::Description::Entry::ExtMap("http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"));
``

The description does not contain a space. Now, how should the extMapLines be added? Because, it looks like the extmap line in SDP should look something like
```
na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
```

I thought the first part was supposed to be generated by libdatachannel?

**Comment by kuzux** [comment]
Changing it to 
```
media.addExtMap(rtc::Description::Entry::ExtMap("1 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"));
```

seems to throw no exception, now the only thing is that I get no twcc messages as defined in https://datatracker.ietf.org/doc/html/draft-holmer-rmcat-transport-wide-cc-extensions-01 :) (That is probably an unrelated problem to the above discussion though)

(neither while using Firefox nor Google Chrome)

**Comment by paullouisageneau** [comment]
Great! I would have thought the corresponding RTCP packets would arrive into the track if there is no media handler intercepting them, however I might be wrong and they might be dropped somewhere. The interception API is indeed the way to go here!

**Comment by feixintianxia** [comment]
It is February 2025 now. I would like to ask if the GCC algorithm has been implemented? Thanks

**Comment by paullouisageneau** [comment]
@kuzux @ognkrmms Any news?

**Comment by ognkrmms** [comment]
Hello Paul,

I am sorry for the late response. 

We have a working implementation of GCC [here](https://github.com/vagonhq/libdatachannel/tree/twcc-v0.21.2) if anyone wants to check out. We would like to contribute our implementation. The whole thing would be a very big PR so instead I propose dividing it to 2 PRs. The first one will be about adding necessary TWCC packet extension and its machinery. The second PR will introduce the GCC algorithm. I can arrange the first PR right away but the second PR might take a little bit more time as I might need to refactor and polish a little bit.

Is this reasonable for you?

**Comment by paullouisageneau** [comment]
@ognkrmms It sounds like a good plan, thank you the constribution. I'm looking forward to reviewing your PRs!

**Comment by FomoGoMan** [comment]
This TWCC/GCC issue is exactly why we ended up working on the usrsctp side. The bottleneck in libdatachannel's throughput under poor network conditions is largely in usrsctp's congestion control - the default SCTP congestion handling doesn't adapt well to WebRTC's UDP-like requirements. Our fork replaces usrsctp with BBRv3 support enabled by default, which directly addresses the stability and throughput degradation you were seeing. It's a different layer than TWCC negotiation, but the underlying congestion control improvement helps significantly when TWCC feedback is available. Fork: https://github.com/FomoGoMan/libdatachannel - usrsctp PR with BBRv3: github.com/sctplab/usrsctp/pull/748
