### ISSUE TITLE
The localdescription cannot be obtained

### ISSUE THREAD

**Issue by Fung-blog** [paullouisageneau/libdatachannel#738]
I used 
```
pc->setLocalDescription()；
auto description = pc->localDescription();
string sdp = string(description.value());
```
sdp has no value. An error message shows` bad optional access`

**Comment by paullouisageneau** [comment]
This is expected, as like with the WebRTC API in browsers, description generation is asynchronous. `localDescription` returns an `std::optional` that contains the description only if available at the time and you must check it has a value before accessing it.

You need to get the local description in the `onLocalDescription` callback:
```
pc->onLocalDescription([](rtc::Description description) {
    // Send the description to the remote peer
});
pc->setLocalDescription();
```
If you want the full description with all local candidates, you may instead call `localDescription()` in `onGatheringStateChange` when `state == rtc::PeerConnection::GatheringState::Complete`.

**Comment by Fung-blog** [comment]
When I do the following work
```
auto peer_connection = make_shared<PeerConnection>(config);
peer_connection->onLocalDescription([](rtc::Description description) {std::cout << "get my localdescription"<< std::endl;});
peer_connection->setLocalDescription();
```
This function `onLocalDescription` doesn't work, I can't get this output of `get my localdescription`

**Comment by paullouisageneau** [comment]
You need something to be negotiated like a data channel or track. Calling `createDataChannel()` is sufficient and will implicitly set the local description:
```
auto peer_connection = make_shared<PeerConnection>(config);
peer_connection->onLocalDescription([](rtc::Description description) {std::cout << "get my localdescription"<< std::endl;});
auto data_channel = peer_connection->createDataChannel("mydatachannel");
```

**Comment by paullouisageneau** [comment]
I'm closing this as it doesn't look like an issue with the library.
