### ISSUE TITLE
DataChannel has no transport

### ISSUE THREAD

**Issue by stevedanOgochu** [paullouisageneau/libdatachannel#74]
Is there a reason why this error is appearing, all the independence were installed.

   2020-05-17 11:40:00.727 ERROR [65349] [rtcSendMessage@362] DataChannel has no transport

   2020-05-17 11:40:00.727 DEBUG [65642] [rtc::IceTransport::stop@457] Stopping ICE thread

**Comment by paullouisageneau** [comment]
This very probably means that you tried to send a message on a DataChannel whose PeerConnection has been closed or destroyed (so the transport does not exists anymore).

**Comment by stevedanOgochu** [comment]
How can I include the libdatachannel library to my cmake if i didnot
install it in systems directory. How do i include the "include" files and
the .so file?
Thank you very much
