### ISSUE TITLE
Hello, if I want to adjust the sending bit rate, is there a corresponding interface?

### ISSUE THREAD

**Issue by ZL97** [paullouisageneau/libdatachannel#743]
Hello, if I want to adjust the sending bit rate, is there a corresponding interface?
Can you adjust the sending bit rate by yourself in the sample program streamer? Looking forward to your reply, thank you

**Comment by paullouisageneau** [comment]
libdatachannel handles only network connectivity, media must be encoded externally, and the bitrate has to be set on the encoder. The streamer example relies on pre-encoded samples, therefore you can't change the bitrate on the fly.

**Comment by ZL97** [comment]
allright,thank you.
