### ISSUE TITLE
macos arm

### ISSUE THREAD

**Issue by ClosetMonkey** [paullouisageneau/libdatachannel#745]

**Comment by ClosetMonkey** [comment]
woops was trying to search guess I'm tired

**Comment by ClosetMonkey** [comment]
I guess while I'm here, are people having any issues compiling on non-intel macs?

**Comment by dtzxporter** [comment]
It compiles fine on M1.

**Comment by paullouisageneau** [comment]
I'm closing this as there doesn't seem to be a specific issue with macOS ARM.
