### ISSUE TITLE
Problem with building tests on Linux

### ISSUE THREAD

**Issue by sol-prog** [paullouisageneau/libdatachannel#758]
There seems to be a problem with the way the Makefile is generated - I tested on Linux (Ubuntu 22.04). The libraries are correctly built, but when the test are built the OpenSSL library is not linked to the resulting executable which generates a few screens of missing symbols. E.g:

```
...
g++ -pthread -o tests test/benchmark.o test/capi_connectivity.o test/capi_track.o test/capi_websocketserver.o test/connectivity.o test/main.o test/negotiated.o test/track.o test/turn_connectivity.o test/websocket.o test/websocketserver.o  libdatachannel.a libusrsctp.a libjuice.a libsrtp2.a 
/usr/bin/ld: libdatachannel.a(tls.o): in function `rtc::openssl::init()':
tls.cpp:(.text+0x148): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: tls.cpp:(.text+0x154): undefined reference to `OPENSSL_init_crypto'
/usr/bin/ld: libdatachannel.a(tls.o): in function `rtc::openssl::error_string[abi:cxx11](unsigned long)':
tls.cpp:(.text+0x1b3): undefined reference to `ERR_error_string_n'
/usr/bin/ld: libdatachannel.a(tls.o): in function `rtc::openssl::check(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
tls.cpp:(.text+0x25a): undefined reference to `ERR_get_error'
...

```

This is a curious bug because the OpenSSL headers and libraries are correctly detected when running cmake.

I can build the tests if I manually add the OpenSSL libraries (I suspect there is something missing from CMakeLists.txt for building the tests):

```
g++ -pthread -o tests test/benchmark.o test/capi_connectivity.o test/capi_track.o test/capi_websocketserver.o test/connectivity.o test/main.o test/negotiated.o test/track.o test/turn_connectivity.o test/websocket.o test/websocketserver.o  libdatachannel.a libusrsctp.a libjuice.a libsrtp2.a -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto
```

**Comment by paullouisageneau** [comment]
It looks like you are using the standalone `Makefile` at the root of the project. To use the one generate by CMake, you have to change directories to the build directory first.

However, the standalone Makefile should indeed issue a command containing the proper system libraries. It relies on pkg-config for that. Does `pkg-config --libs openssl` successfully print `-lssl -lcrypto` on your system?

**Comment by sol-prog** [comment]
Thanks, you were right obviously, I skipped over the step of running make inside the build directory. Everything builds perfectly now and the tests run successfully.

(Yes about pkg-config it correctly prints -lssl and -lcrypto.)
