### ISSUE TITLE
Streamer crashes with compile option "MTD"

### ISSUE THREAD

**Issue by lyd405121** [paullouisageneau/libdatachannel#775]
## Background
I am writing a cloud rendering software protype.
This repository helps a lot, and I have done :
- the server side : C++ with offscreen render and hardware encodering, streaming
- the client side : C++ and web, including depakcet and decode

https://user-images.githubusercontent.com/16344694/210030100-70df6f2d-e81c-4223-bc62-0266e696bc64.mp4

## Question
But, I still get two questions:
-  I tested all the compile option MT MTD MD MDD, and found only MTD will crash which is the same with original streamer example 
-  The latency is still about 200ms，which is impossible for cloud-game,though I have done many optimization. Recently, I investigate http/3 and quic based on udp, will that be much better than webrtc which based on tcp

**Comment by paullouisageneau** [comment]
Nice project, would you mind sharing some more technical details (for instance what are the renderer and the encoder)?

>     * I tested all the compile option MT MTD MD MDD, and found only MTD will crash which is the same with original streamer example

There is a [bug in Microsoft Visual C++](https://developercommunity.visualstudio.com/t/race-condition-on-g-tss-mutex-with-static-crt/672664). Basically, using `thread_local` C++ feature and statically linking the runtime (with MTD) will result in a crash if a thread is started during init. For some reason Microsoft seems unwilling or unable to fix it.

A workaround could be to modify the streamer example to start the dispatch queue later when `main()` is called.

>     * The latency is still about 200ms，which is impossible for cloud-game,though I have done many optimization.

This is quite high but some context would be necessary. What latency do you measure exactly? What is the base network latency? How do you stream the video?

> Recently, I investigate http/3 and quic based on udp, will that be much better than webrtc which based on tcp

This is incorrect, WebRTC is over UDP. The video streams used by WebRTC are based on RTP and that's basically the best you can do for real time traffic.

**Comment by lyd405121** [comment]
- Thanks, learned a lot, I know nothing about network stuff

## The renderer and encoder
- This demo is simply using d3d11 and [nvidia encoder](https://github.com/NVIDIA/video-sdk-samples)
- The main goal is to build an open source project called [cloud-imgui](https://github.com/ocornut/imgui)
- Nowadays, imgui plays an important role in computer graphics, I think it's worth while. 

## Depacket
- I found there is no C++ client for recieve rtp pakect and play it
- So I search some multimeida technology blogs and implement  that
- The key for Depacket is 
![depacket](https://user-images.githubusercontent.com/16344694/210295364-eda98114-0778-47fa-977e-63fbcc66a970.png)

- Mind the start code
- And I frame, P frame , we should keep the header, like 133,129, maybe your encoder has B frame,should do more work
- While middle RTP packet header, we should remove it before putting a whole frame into ffmepg decoder
- That's all the secret here
