### ISSUE TITLE
why add infomation to fmtps but not to rtcpFbs while add feedback config?

### ISSUE THREAD

**Issue by JIAQIA** [paullouisageneau/libdatachannel#783]
in file: src/description.cpp
```
void Description::Media::RtpMap::addFeedback(string fb) {
	if (std::find(rtcpFbs.begin(), rtcpFbs.end(), fb) == rtcpFbs.end())
		fmtps.emplace_back(std::move(fb));
}
```
function addFeedback add string fb to fmtps finally.  Why not add fb to rtcpFbs??

In my case, generate answer while SDP Exchange doesn't generate "a=rtcp-fb" info. I don't know if it's designed like this on purpose, or it's a bug

**Comment by paullouisageneau** [comment]
This was a bug fixed in https://github.com/paullouisageneau/libdatachannel/pull/754, addFeedback() is now fixed starting from v0.17.12.
