### ISSUE TITLE
Incorrect signalingState in onLocalDescription

### ISSUE THREAD

**Issue by toschlog** [paullouisageneau/libdatachannel#787]
I'm currently using 0.16.4 so it's possible that this issue has already been resolved.  I didn't see anything in the forum, however, so I'm noting it here just in case.

After establishing a my signaling connection, I call `setLocalDescription` and then handle the `onLocalDescription` event.  Everything works fine most of the time, but occasionally I find that the `peerConnection->signalingState` is still `Stable` in onLocalDescription; I'm expecting it to be `HaveLocalOffer`.

My code decides whether to send an offer or an answer like this:

```
peer->onLocalDescription(
  [client](Description description) {
    auto type = (client->peer->signalingState() == PeerConnection::SignalingState::HaveLocalOffer) ? "offer" : "answer";
```

But because `signalingState == Stable`, it's sending an answer instead of an offer.  I've worked around the issue like this:

```
peer->onLocalDescription(
  [client](Description description) {
    auto type = (client->peer->signalingState() == PeerConnection::SignalingState::HaveRemoteOffer) ? "answer" : "offer";
```

As I said, perhaps this issue has already been resolved.  I'll hopefully have time soon to update to the latest libdatachannel code.

**Comment by toschlog** [comment]
I've been looking at this more and it definitely seems like a timing issue.  I call `setLocalDescription`, then `onLocalDescription` is called with `signalingState == Stable`, and then very quickly afterwards `signalingState` changes to `HaveLocalOffer`.

My work-around wasn't good enough because sometimes when `signalingState` is `Stable` I need to send an offer, and sometimes I need to send an answer.  So now instead of looking at `signalingState` I'm keeping my own state value.  When I call `setLocalDescription()` I set `sendType = "offer"` and when I call `setRemoteDescription()` I set `sendType = "answer"`.  Then in onLocalDescription I use the value of `sendType`.

**Comment by paullouisageneau** [comment]
The behavior is expected currently as callbacks fire asynchronously and the local description is set before changing the signaling state (it would be quite incoherent to change state to `HaveLocalOffer` before the local offer is actually set). Therefore, you can't rely on the signaling state from the local description callback as it is changed while the callback runs.

You should actually use `description.type()` to know if the description is an offer or an answer as it's already decided:
```cpp
peer->onLocalDescription([](Description description) {
    auto type = description.type() == Description::Type::Offer ? "offer" : "answer";
    [...]
}
```
Even better, you could use the shortcut `description.typeString()` and the corresponding constructor on the other side so you don't have to worry about enums:
```cpp
peer->onLocalDescription([](Description description) {
    auto type = description.typeString(); // "offer" or "answer"
    auto sdp = std::string(description)
    [...]
}
```
```cpp
peer->setRemoteDescription(Description(sdp, type));
```

**Comment by toschlog** [comment]
Perfect.  Thanks for explaining that.
