### ISSUE TITLE
Cryptographic backend for mbedTLS 

### ISSUE THREAD

**Issue by fire** [paullouisageneau/libdatachannel#792]
We want to integrate libdatachannel into Godot Engine to provide an integrated experience without an external shared library. https://github.com/godotengine/webrtc-native. One of the issues was that libdatachannel requires openssl. 

We propose that mbedTLS be an option.

**Comment by paullouisageneau** [comment]
An mbedTLS backend could indeed be a worthy addition. Is GnuTLS not an option?

**Comment by paullouisageneau** [comment]
Great news, qn mbedTLS backend would indeed be a worthy addition. Is GnuTLS not an option?

**Comment by fire** [comment]
Is gnutls mit licensed? Godot Engine is mit licensed.

**Comment by jordo** [comment]
> We want to integrate libdatachannel into Godot Engine to provide an integrated experience without an external shared library. https://github.com/godotengine/webrtc-native.

This would be really great!

**Comment by Sean-Der** [comment]
Hi @fire have you started work on this at all?

If not I am going to open a PR/start working on it this week. thanks!

**Comment by fire** [comment]
Not started at all. I really appreciate your help!

**Comment by Sean-Der** [comment]
Hey everyone! I have a PR [here](https://github.com/paullouisageneau/libdatachannel/pull/822)

I would say should be done ~week

**Comment by Sean-Der** [comment]
@fire this has been merged! Would you mind trying it out :)

If you encounter any bugs I would love to fix them

**Comment by paullouisageneau** [comment]
Thank you again for the much appreciated contribution @Sean-Der ! 

I'm closing this as it is completed, please open a new issue for any encountered bug.
