### ISSUE TITLE
MediaHandler of PeerConnection is never called

### ISSUE THREAD

**Issue by ognkrmms** [paullouisageneau/libdatachannel#801]
Hi,

I have a class called CCResponder derived from MediaHandler. This class is supposed to take care of receiver reports. In the streamer example, I added the following line in the createPeerConnection function:
```
pc->setMediaHandler(std::make_shared<CCResponder>());
```
On the master branch, There is no problem in the commit f9fc064 but starting from the commit 0b98d7a, `CCResponder ::incoming` is never called. I saw this behavior on both Windows and Linux machines. I can confirm there are receiver reports via Wireshark.

Any guidance is appreciated.

**Comment by paullouisageneau** [comment]
Indeed, #765 introduced a regression by breaking SRTCP profile setting on `master` branch.

This should be fixed by https://github.com/paullouisageneau/libdatachannel/pull/802.
