### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by JelleBakker** [paullouisageneau/libdatachannel#814]
Hi,

Would it be possible to get the _"overrides a destructor but is not marked 'override"_ warnings fixed?

`include/rtc/track.hpp:28:2: warning: '~Track' overrides a destructor but is not marked 'override' [-Winconsistent-missing-destructor-override]`

Thanks,
Jelle

**Comment by paullouisageneau** [comment]
Sure, to fix it, all overriding functions should be marked `override`, which is a good practice. What compiler shows the warning?

**Comment by ShufflePerson** [comment]
_Real men turn off warnings, their warnings after all eh!_

**Comment by JelleBakker** [comment]
I'm using AppleClang 14.0.0.14000029 compiler with these settings:

```
-Wall -Wshadow-all -Wshorten-64-to-32 -Wstrict-aliasing
-Wuninitialized -Wunused-parameter -Wconversion -Wsign-compare
-Wint-conversion -Wconditional-uninitialized -Wconstant-conversion
-Wsign-conversion -Wbool-conversion -Wextra-semi -Wunreachable-code
-Wcast-align -Wshift-sign-overflow -Wmissing-prototypes
-Wnullable-to-nonnull-conversion -Wno-ignored-qualifiers -Wswitch-enum
-Wpedantic -Wdeprecated -Wzero-as-null-pointer-constant -Wunused-private-field
-Woverloaded-virtual -Wreorder -Winconsistent-missing-destructor-override
-Wunguarded-availability -Wunguarded-availability-new
```
