### ISSUE TITLE
WebSocket Crash

### ISSUE THREAD

**Issue by web2098** [paullouisageneau/libdatachannel#816]
Hi @paullouisageneau,

When testing using websocket with a lost connection, I encountered a crash via a mutex throwing an exception during dtor.

Here is the stack I found:
![image](https://user-images.githubusercontent.com/7141138/222561482-4dd42e27-3ed4-4e2d-9081-045317d5d3de.png)

From what I can tell it starts with this code
_**TcpTransport::process ~440**_
``` 
PLOG_INFO << "TCP disconnected";
PollService::Instance().remove(mSock);
changeState(State::Disconnected);
recv(nullptr);
```

Which changes the state, calling the synchronized_callback object which locks its internal mutex.

The code then calls the lambda for the in the websocket:
_**websocket::setTcpTransport ~231**_
```
auto shared_this = weak_this.lock();
...

case State::Disconnected:
  remoteClose();
  break;
```

I am not really sure what happens here. Either the websocket is deleted at the end of the lambda, or during the remote close the code transport object is deleted. Either way once the transport object is deleted, that is the same instance that is at the start of the stack. During destruction of the transport its synchronized_callback is destroyed which still has the mutex locked.

![image](https://user-images.githubusercontent.com/7141138/222561420-fd215cda-b356-440d-8ed9-6b8831bb52de.png)

**Comment by paullouisageneau** [comment]
Thank you for reporting! The issue seems to be that the `TcpTransport` is not held while `process` is called. A simple fix could be to make `TcpTransport` derive from `std::enable_shared_from_this<TcpTransport>` and locking a shared ptr to self in the process callback.
