### ISSUE TITLE
Accumulating threads

### ISSUE THREAD

**Issue by toschlog** [paullouisageneau/libdatachannel#817]
I'm using libdatachannel on a server where people are frequently connecting and disconnecting.  It's working fine, but I'm seeing the number of threads go up.  A new connections generally creates two threads, and those threads go away when the user disconnects.  But sometimes a new user results in a bigger jump in the thread count, and those threads aren't going away.

In a simple test case with a few users, I'm seeing (numUsers * 2 + 10) threads.  But after running for a couple hours I'm now seeing 18 connected users and 70 threads.

Any idea what's going on here?  Or tips for tracking this down?  I'll be adding additional logging to get more info, but any suggestions would be greatly appreciated.

**Comment by toschlog** [comment]
It looks like, of course, that this was my fault.  I needed to be closing the PeerConnection on receiving a value of `Failed` in `onStateChange`.

**Comment by paullouisageneau** [comment]
It's great you found the issue. 

FYI, while a new thread is spawned for each new peer connection until v0.18 included, everything has now been moved to the thread pool so new connections no longer spawn threads. The change is currently on `master` branch and will be shipped in the next version.
