### ISSUE TITLE
SSL local private key check failed

### ISSUE THREAD

**Issue by rvkennedy** [paullouisageneau/libdatachannel#824]
I have a confusing error that's occurring in my own code, but not in the examples.
In line 433 of dtlstransport.cpp, the SSL_CTX_check_private_key(mCtx) returns false, and produces the error:
`[rtc::openssl::check@100] SSL local private key check failed: error:00000000:lib(0):func(0):reason(0)`
This is with default configuration, the same as far as I can tell as the datachannel-client example, except I do my own signaling on UDP instead of using WebSockets.
I think this is possibly preventing my connection from changing from the "connecting" to the "connected" state and allowing data to be sent.
Any advice would be appreciated.

**Comment by paullouisageneau** [comment]
This is a sanity check which verifies that the locally-generated certificate and private key match (i.e. the certificate is signed with the private key). I wouldn't expect it to fail except if something is badly wrong with OpenSSL certificate generation. What OpenSSL version do you use?

**Comment by rvkennedy** [comment]
Thanks very much for your response. I have been linking with OpenSSL 1.1.0 - perhaps this is too old?

**Comment by rvkennedy** [comment]
Thanks, I can confirm that the problem doesn't occur with a build of OpenSSL 3.0.8.
