### ISSUE TITLE
`rtcGetPreviousTrackSenderReportTimestamp` was renamed to `rtcGetLastTrackSenderReportTimestamp` in header only 

### ISSUE THREAD

**Issue by Sean-Der** [paullouisageneau/libdatachannel#844]
In commit d263b4b5b7e34cd8a012fc5bb3817fda593d6d69 the function was renamed, but I believe the C code wasn't updated

**Comment by paullouisageneau** [comment]
Good catch, fixed in https://github.com/paullouisageneau/libdatachannel/pull/847.
