### ISSUE TITLE
Thread names

### ISSUE THREAD

**Issue by ktsaou** [paullouisageneau/libdatachannel#852]
It would be very nice to name the threads spawn by libdatachannel and its dependencies.

I see in the code base of `usrsctp` that its threads are named `SCTP iterator` and `SCTP timer` (search for `sctp_userspace_set_threadname`).

It would be quite helpful for all threads spawn by `libdatachannel` to be named.

Now, they inherit the name of the thread they are started from, which is very misleading when debugging of viewing the application threads using `htop` or other tools.

**Comment by ktsaou** [comment]
Naming is quite simple. `usrsctp` uses this:

```c
void
sctp_userspace_set_threadname(const char *name)
{
#if defined(__APPLE__)
	pthread_setname_np(name);
#endif
#if defined(__linux__)
	prctl(PR_SET_NAME, name);
#endif
#if defined(__FreeBSD__)
	pthread_set_name_np(pthread_self(), name);
#endif
}
```

At netdata we use this:

```c
static void thread_set_name_np(NETDATA_THREAD *nt) {

    if (nt->tag) {
        int ret = 0;

        char threadname[NETDATA_THREAD_NAME_MAX+1];
        strncpyz(threadname, nt->tag, NETDATA_THREAD_NAME_MAX);

#if defined(__FreeBSD__)
        pthread_set_name_np(pthread_self(), threadname);
#elif defined(__APPLE__)
        ret = pthread_setname_np(threadname);
#else
        ret = pthread_setname_np(pthread_self(), threadname);
#endif

        if (ret != 0)
            error("cannot set pthread name of %d to %s. ErrCode: %d", gettid(), threadname, ret);
        else
            info("set name of thread %d to %s", gettid(), threadname);

    }
}
```

**Comment by paullouisageneau** [comment]
Yes it would indeed be handy when debugging. Ideally it should be done in libjuice too.
