### ISSUE TITLE
Question: rtcSetMessageCallback() vs rtcSetAvailableCallback()

### ISSUE THREAD

**Issue by ktsaou** [paullouisageneau/libdatachannel#854]
In Netdata we are experimenting for using WebRTC for browser to Netdata agent communication. This is a request - response communication, much like the web. So, the browser and the agent establish a peer connection and then the browser opens a data channel, makes a request and receives the response on the same data channel.

We need requests to be per data channel, mainly to allow the browser to cancel a request by shutting down the data channel the response would come, signalling the agent to discard the request mid-flight.

There are cases that the agent needs some time to process the requests it receives. This time can vary from less than a millisecond to several seconds, depending on the request.

The questions I have are the following:

1. You offer 2 method for receiving messages: `rtcSetMessageCallback()` and `rtcSetAvailableCallback()`. I understand the first is for synchronously handling the messages, while running at a libdatachannel worker thread. The later seems to be ideal for asynchronous communication, in which case the application may have its own mechanics for processing received messages.

2. Is the execution time of these callbacks important for libdatachannel? Is there anything locked while these callbacks are executing that probably prevents new data channels from being created on the same peer connection, other messages on different data channels of the same peer connection being handled, etc? So, is the application supposed to minimize the time spent in these callbacks?

3. Is there a way for the application to control how many libdatachannel workers are spawn?

**Comment by paullouisageneau** [comment]
> * You offer 2 method for receiving messages: `rtcSetMessageCallback()` and `rtcSetAvailableCallback()`. I understand the first is for synchronously handling the messages, while running at a libdatachannel worker thread. The later seems to be ideal for asynchronous communication, in which case the application may have its own mechanics for processing received messages.

You are right, the second one is better for situations where the application has its own event loop, as you may post a task to the event loop on `rtcSetAvailableCallback()` and call `rtcReceiveMessage()` from it.

> * Is the execution time of these callbacks important for libdatachannel? Is there anything locked while these callbacks are executing that probably prevents new data channels from being created on the same peer connection, other messages on different data channels of the same peer connection being handled, etc? So, is the application supposed to minimize the time spent in these callbacks?

While there is no hard requierement on execution time, blocking the callback has indeed undesirable side effects, as it prevents you from receiving data over the same SCTP connection, therefore you won't receive events or messages for data channels over the same peer connection while the callback is blocked, including the close event for the blocked data channel.

In your case, you should definitely post a task to your own worker when receiving a message.

> * Is there a way for the application to control how many libdatachannel workers are spawn?

The application can't control the number of workers, but the minimum can be changed here: https://github.com/paullouisageneau/libdatachannel/blob/45e7f44765e130f51d753de3c24bc395ee5b40f0/src/impl/internals.hpp#L46

However this won't allow you to process messages from the same peer connection asynchronously. For this you need you own worker.

**Comment by ktsaou** [comment]
Thank you! This information is very helpful!
