### ISSUE TITLE
How can I attach a socket to an already running server

### ISSUE THREAD

**Issue by drizzle042** [paullouisageneau/libdatachannel#860]
I’m wondering if this feature is available. We have a server up and running but we need WebSocket support. We need to use the library but attach the WebSocket to our server which is already running.

**Comment by paullouisageneau** [comment]
You can't "attach" to an existing HTTP server but you can make the server forward the WebSocket requests as a reverse proxy. The configuration depends on the server so it is out of libdatachannel's scope. For instance [here are instructions for nginx](https://www.nginx.com/blog/websocket-nginx/).
