### ISSUE TITLE
"Failed to gather local ICE candidates"

### ISSUE THREAD

**Issue by toschlog** [paullouisageneau/libdatachannel#861]
What could cause a "Failed to gather local ICE candidates" error?  My app (a voice relay server) ran fine for days and then crashed with this error.

I actually had two servers running and they both crashed with the same error within about 30 minutes of each other.   The two servers were handling about the same amount of traffic, so if, for example, the cash happened on the 32768th connection that would have occurred around the same time on the two machines.  (I mention that number because the lifetime number of connections to the signaling sockets was somewhere around 35-40K.  Given that not every socket connection results in trying to establish a PeerConnection it's possible that the lifetime number of PCs was around 32767.  So maybe a signed 16-bit counter that overflowed?)

Or maybe it's just a memory leak in my app and both clients ran out of system memory around the same time.  I'll look into this.

**Comment by toschlog** [comment]
I found a memory leak so I'm pretty sure that was the problem.  Sorry for the false alarm.

**Comment by paullouisageneau** [comment]
The error is probably happening because no UDP port is available so the socket of the new connection can't be bound to a port locally. A leak could indeed explain it as leaking peer connections wouldn't free UDP ports.

**Comment by toschlog** [comment]
I'm continuing to scour my code for leaks.  Does libdatachannel have anything that might help?

I'm using `ss -s` to look for extra ports left open and I'm not seeing any.  

I'm allocating PeerConnections with `make_unique<PeerConnection>(config);` and I'm confirming that the object that holds the `unique_ptr` is getting destroyed.

**Comment by toschlog** [comment]
I found these in the logs after my latest crash:
```1682308073136: RTC: rtc::impl::IceTransport::LogCallback@362: juice: udp.c:74: UDP socket creation for IPv6 family failed, errno=24
1682308073136: RTC: rtc::impl::IceTransport::LogCallback@362: juice: udp.c:74: UDP socket creation for IPv4 family failed, errno=24
1682308073136: RTC: rtc::impl::IceTransport::LogCallback@362: juice: udp.c:82: UDP socket creation failed: no suitable address family
1682308073136: RTC: rtc::impl::IceTransport::LogCallback@362: juice: conn_poll.c:332: UDP socket creation failed
1682308073136: RTC: rtc::impl::IceTransport::LogCallback@362: juice: agent.c:210: Connection creation for agent failed
```

That looks like support for the idea of no UDP ports available.  Is there anything I should look at other than freeing PeerConnections?

**Comment by toschlog** [comment]
As usual, I am dumb.  The version I was testing still had address sanitization on, which was eating all the memory.  I'm testing now with a clean version.

**Comment by paullouisageneau** [comment]
Actually, the socket creation fails with EMFILE (errno 24), it means that you reached the maximum number of open file descriptors for the process. The limit is probably 32K on your system, you should be able to change it in `/etc/security/limits.conf`.

However, 32K is a lot of peer connections and you are going to run out of UDP ports quickly, so rather than increasing the limit, I would recommend enabling ICE UDP mux mode with `rtc::Configuration::enableIceUdpMux` to make all peer connections share a single socket.
