### ISSUE TITLE
WebSocket onClosed not called when the internet cuts on streamer

### ISSUE THREAD

**Issue by braoutch** [paullouisageneau/libdatachannel#863]
Hello and thank you for this great, great, great library.

I'm using something close from your examples, and I noticed that the callback of
`ws->onClosed(std::function<void()> callback)`
is not called with reliability when the network gets down. However, it does get called instantly if I shut down my signaling/stun/turn servers.

`ws->onOpen(std::function<void()> callback)` is called allright, and the connection works before the cut. After the cut, the lack of detection of this disconnection prevent me to go on with a reconnection process. Am I missing something ?

Antoine

**Comment by paullouisageneau** [comment]
When the network or the remote host get down, the only way to detect disconnection is a timeout. As TCP timeout entirely depends on the OS configuration, you can make libdatachannel time out faster with `maxOutstandingPings` and `pingInterval` settings in `WebSocket::Configuration`. The WebSocket will close after the specified number of unanswered pings.

**Comment by braoutch** [comment]
Sorry I did not noticed these, I was on 17.x. Great addition to the library. I confirm it works as expected, it calls `onError()`.

Shall I close the issue ?

**Comment by paullouisageneau** [comment]
Perfect, I'm closing the issue.
