### ISSUE TITLE
Socket stuck in CLOSE_WAIT state

### ISSUE THREAD

**Issue by aleksey-salow** [paullouisageneau/libdatachannel#864]
**How to reproduce**: Start a WebSocket server, "telnet" to port, and disconnect. 
**Expected behavior**: The socket is closed, onClose event handler is called.
**Observed behavior**: The socket is stuck in the CLOSE_WAIT state. From the `netstat`:
`TCP    [::1]:25670            [::1]:51535            CLOSE_WAIT`

A quick look under a debugger shows that `WSAPoll` returns `POLLHUP` in the `revents` field, which is not processed by the `PollService::process` method. This issue only occurs on the Windows system. I ran tests on the Linux system, and everything worked as expected.

**Comment by paullouisageneau** [comment]
It seems `WSAPolll` does not set `POLLIN` when the socket is closed, while this is standard behavior for POSIX systems.
