### ISSUE TITLE
WebSocket stuck in Connecting state when garbage is received

### ISSUE THREAD

**Issue by aleksey-salow** [paullouisageneau/libdatachannel#865]
**How to reproduce**: Start a non-TLS WebSocket server. Connect to port via `telnet`, send some garbage. Or, try to establish a `wss` connection from the browser, in most cases, the issue will be reproduced.
**Observed behavior**: Nothing happens
**Expected behavior**: Connection is terminated, and onError or onClose event handlers are called.

I looked into sources, the `parseHttpLines` function expects the `\r\n\r\n` sequence. However, with garbage on input, it always returns 0 and stops further request validation. I don't know the best solution, but checking the first 4 bytes of the `buffer` (expected to be a "GET " string) before calling the `parseHttpLines` function allows close the connection and doesn't make the client to wait for a response.

https://github.com/paullouisageneau/libdatachannel/blob/c0f4203c02d5746cbaaaab4fd6f5b90431def38d/src/impl/wshandshake.cpp#L136-L138

**Comment by paullouisageneau** [comment]
> I don't know the best solution, but checking the first 4 bytes of the buffer (expected to be a "GET " string) before calling the parseHttpLines function allows close the connection and doesn't make the client to wait for a response.

This mitigates the issue but does not totally fix it, for instance it still exists if the client sends "GET " then garbage. I think the proper fix here would be a timeout for reading the request.

**Comment by aleksey-salow** [comment]
I agree that a timeout is the right solution for this case. But adding a quick check for "GET " is useful from the UX side. If a user makes a mistake and uses an incorrect protocol, he will be notified immediately without waiting for a timeout.

**Comment by paullouisageneau** [comment]
I added a check in https://github.com/paullouisageneau/libdatachannel/pull/876 and a configurable timeout in https://github.com/paullouisageneau/libdatachannel/pull/881.
