### ISSUE TITLE
answering offerToReceiveVideo offer

### ISSUE THREAD

**Issue by fusionfoxy** [paullouisageneau/libdatachannel#873]
I have a webbrowser trying to show a video feed from a libdatachannel application. In Javascript I can create an offer with the option `offerToReceiveVideo` like this:

```
const offer = await myPeerConnection.createOffer({ offerToReceiveVideo: true});
```
When I handle this offer in libdatachannel, it does not seem to add the `ssrc` media attribute to the answer. The WebRTC connection is connected, and the video data can be transferred over the network, but the feed does not show in the browser. 

If I simply ignore the offer from the browser and creates my own offer in libdatachannel,  the browser returns an answer it works fine.

I looked through the streamer example and discovered that this is essentially how that example works, in that the browser sends a request making the streamer create an offer the browser then answers. 

Is it simply a known limitation of libdatachannel that it cannot properly answer `offerToReceiveVideo`-offers or am I missing something?

**Comment by paullouisageneau** [comment]
> When I handle this offer in libdatachannel, it does not seem to add the `ssrc` media attribute to the answer. The WebRTC connection is connected, and the video data can be transferred over the network, but the feed does not show in the browser.

You need to add the SSRC just like when you create an offer: when you get the track in `onTrack`, get the description with `description()`, edit it by adding the SSRC of the sent stream, and set the new description with `setDescription()` or `addTrack()`.

Note that you must also pick the payload type corresponding to the codec you want to send among the multiple ones the browser offered to receive. You can iterate payload types in the offer with `Description:payloadTypes()` and `Description::rtpMap(pt)`, then you need to use this pt for the sent stream. If the codec is not there you have to handle the track negotiation failure. You may clean up the other payload types with `removeRtpMap(pt)` but it shouldn't be necessary.

Generating the offer from the libdatachannel side is more straightforward as you probably have already decided what format you are going to send, so you can just create an offer reflecting it and let the browser check it can decode it.

**Comment by fusionfoxy** [comment]
Thanks for the clarification, this fixed my issue!

Just to clarify my solution in case others have the same issue:

When I get the `HaveRemoteOffer` event, I call `pc_->setLocalDescription()` on the peerConnection which triggers the `onTrack` event.
I get the `Description::Media` object from the `Track` provided in the event, using `auto media = track->description()`. I then check the `Media` contains the right payload type with the `media.rtpMap(pt)`.
If it does, I add the ssrc to the `Media` using `media.addSSRC()`

Finally, i add a track to the peerConnection using the `Media` with `pc_->addTrack(media)`.

It all now works as expected, so I am closing the issue.
