### ISSUE TITLE
Fail to build with MinGW

### ISSUE THREAD

**Issue by jacobszpz** [paullouisageneau/libdatachannel#884]
C:\Users\User\Downloads\Code\build>C:\MinGW\bin\mingw32-make.exe
[  5%] Building C object _deps/libdatachannel-build/deps/libjuice/CMakeFiles/juice-static.dir/src/addr.c.obj
C:\Users\User\Downloads\Code\build\_deps\libdatachannel-src\deps\libjuice\src\addr.c: In function 'addr_resolve':
C:\Users\User\Downloads\Code\build\_deps\libdatachannel-src\deps\libjuice\src\addr.c:261:19: error: 'AI_ADDRCONFIG' undeclared (first use in this function)
  261 |  hints.ai_flags = AI_ADDRCONFIG;
      |                   ^~~~~~~~~~~~~
C:\Users\User\Downloads\Code\build\_deps\libdatachannel-src\deps\libjuice\src\addr.c:261:19: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\User\Downloads\Code\build\_deps\libdatachannel-src\deps\libjuice\src\addr.c: In function 'addr_is_numeric_hostname':
C:\Users\User\Downloads\Code\build\_deps\libdatachannel-src\deps\libjuice\src\addr.c:290:34: error: 'AI_NUMERICSERV' undeclared (first use in this function); did you mean 'NI_NUMERICSERV'?
  290 |  hints.ai_flags = AI_NUMERICHOST|AI_NUMERICSERV;
      |                                  ^~~~~~~~~~~~~~
      |                                  NI_NUMERICSERV
_deps\libdatachannel-build\deps\libjuice\CMakeFiles\juice-static.dir\build.make:75: recipe for target '_deps/libdatachannel-build/deps/libjuice/CMakeFiles/juice-static.dir/src/addr.c.obj' failed
mingw32-make[2]: *** [_deps/libdatachannel-build/deps/libjuice/CMakeFiles/juice-static.dir/src/addr.c.obj] Error 1
CMakeFiles\Makefile2:12572: recipe for target '_deps/libdatachannel-build/deps/libjuice/CMakeFiles/juice-static.dir/all' failed
mingw32-make[1]: *** [_deps/libdatachannel-build/deps/libjuice/CMakeFiles/juice-static.dir/all] Error 2
Makefile:154: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
/

**Comment by paullouisageneau** [comment]
What version of Mingw and what version of Microsoft Windows are you using?

**Comment by jacobszpz** [comment]
The latest version from this url:

https://osdn.net/projects/mingw/


Windows 11 latest build

**Comment by paullouisageneau** [comment]
The original MinGW project has been outdated/abandoned for years, basically it exposes only APIs available since Windows XP and has not support for 64 bits. While I think the code could be adapted to make it compile anyway, you really should use [mingw-w64](https://www.mingw-w64.org/) instead.

**Comment by jacobszpz** [comment]
My apologies, I am new to MinGW and was not sure of the legitimacy of other download sources. Thank you for your prompt response. I have been using libdatachannel and it is genuinely great!
