### ISSUE TITLE
Application crashes while transferring data through DataChannel

### ISSUE THREAD

**Issue by kaishian** [paullouisageneau/libdatachannel#890]
Both version 0.18.2 and 0.18.4 will cause the application to crash when transmits data over DataChannel.
The backtrace of the crash stack looks like this:

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/8162cc24-e11b-447c-b194-b0a503a16c3f)

Any advice will be appreciated.

**Comment by paullouisageneau** [comment]
Does it happen with GnuTLS or OpenSSL? Could you please get the backtrace with a debug build (i.e. with `-DCMAKE_BUILD_TYPE=Debug`)?

**Comment by kaishian** [comment]
Same reproduce step, different call-stack of crashing

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/dc4bd58f-3a13-4c99-8d0f-cc4264b41dd2)

**Comment by kaishian** [comment]
> Does it happen with GnuTLS or OpenSSL? Could you please get the backtrace with a debug build (i.e. with `-DCMAKE_BUILD_TYPE=Debug`)?

This is my build flag:
cmake -DUSE_GNUTLS=OFF -DUSE_NICE=OFF -DUSE_SYSTEM_SRTP=OFF -DNO_EXAMPLES=ON -DNO_TESTS=ON

Sure, I will collect the call-stack with debug version then. Thanks for helping

**Comment by kaishian** [comment]
This call-stack was collected from debug build of libdatachannel-0.18.4

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/27f3695a-58dc-4186-a0c5-917e75c1477d)

**Comment by kaishian** [comment]
I just enabled debug logs, hope this helps:

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/4025c2d8-d076-4083-b56a-31350cab3ad2)

**Comment by paullouisageneau** [comment]
The segfault is caused by a null message somehow retrieved from the incoming queue: https://github.com/paullouisageneau/libdatachannel/blob/287dd2afe6ab8816b9ed7e53f25128ed651c7b11/src/impl/dtlstransport.cpp#L548

 However, only non-null message pointers are pushed in the queue, so I must be missing something: https://github.com/paullouisageneau/libdatachannel/blob/287dd2afe6ab8816b9ed7e53f25128ed651c7b11/src/impl/dtlstransport.cpp#L501

 Do you do something specific to trigger the crash?

**Comment by kaishian** [comment]
> The segfault is caused by a null message somehow retrieved from the incoming queue:
> 
> https://github.com/paullouisageneau/libdatachannel/blob/287dd2afe6ab8816b9ed7e53f25128ed651c7b11/src/impl/dtlstransport.cpp#L548
> 
> However, only non-null message pointers are pushed in the queue, so I must be missing something:
> 
> https://github.com/paullouisageneau/libdatachannel/blob/287dd2afe6ab8816b9ed7e53f25128ed651c7b11/src/impl/dtlstransport.cpp#L501
> 
> Do you do something specific to trigger the crash?

I didn't find a specific step to make the app crash, it just happens sporadically and often.
This is another debug log message that might help, the library returns some openssl related error messages before the app crashes.

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/a6e17e48-ba12-461e-a8a7-38766e73e63e)

**Comment by kaishian** [comment]
using binary = std::vector<byte>;
using message_ptr = shared_ptr<Message>;

struct RTC_CPP_EXPORT Message : binary {
};

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/46c3e69d-b86d-4703-96fb-bf96f89ac9b4)

Is there a case where an "empty" message object is pushed into the DtlsTransport's mIncomingQueue?

**Comment by kaishian** [comment]
Here's another call stack of the app crashing.
The root cause looks like it was caused by an empty "Message".

![image](https://github.com/paullouisageneau/libdatachannel/assets/22209240/c82b868b-b745-4e98-b21c-6d12cba5059c)

**Comment by paullouisageneau** [comment]
> Is there a case where an "empty" message object is pushed into the DtlsTransport's mIncomingQueue?

No, that's why it's puzzling.

> Here's another call stack of the app crashing.
> The root cause looks like it was caused by an empty "Message".

Even with a null pointer in the queue the program should not crash when deleting it. There is clearly a case of memory corruption here, and the null pointer might just be a symptom.

Is the compiler gcc? What version do you use? By any chance, do you have a minimal example allowing to reproduce the crash?

**Comment by kaishian** [comment]
> > Is there a case where an "empty" message object is pushed into the DtlsTransport's mIncomingQueue?
> 
> No, that's why it's puzzling.
> 
> > Here's another call stack of the app crashing.
> > The root cause looks like it was caused by an empty "Message".
> 
> Even with a null pointer in the queue the program should not crash when deleting it. There is clearly a case of memory corruption here, and the null pointer might just be a symptom.
> 
> Is the compiler gcc? What version do you use? By any chance, do you have a minimal example allowing to reproduce the crash?

I am using gcc 9.4.0 (c++-17)
We can't narrow it down to small reproducible steps right now.
We tried both versions 0.18.4 and 0.17.12, both died in the same place.
Network bandwidth was good enough for our application, 15-20Mbps uplink and 5-10Mbps used by the application.

Is there any OS/system log or setting I should check in advance?

**Comment by paullouisageneau** [comment]
Could you please send the verbose log from libdatachannel until the crash?

**Comment by kaishian** [comment]
> Could you please send the verbose log from libdatachannel until the crash?

This is a detailed log (verbose) from application launch to crash.
[ldc.log](https://github.com/paullouisageneau/libdatachannel/files/11527602/ldc.log)

**Comment by kaishian** [comment]
After upgrading to v0.18.5, the crash problem no longer exists.
