### ISSUE TITLE
Simulcast Sender

### ISSUE THREAD

**Issue by Sean-Der** [paullouisageneau/libdatachannel#891]
Hey @paullouisageneau 

I would like to add the ability to send Simulcast from libdatachannel. Would you accept this feature? Happy to type up justifications if you aren't sure if it is worth it yet. Do you have any opinions on API? I see these options.

### Add a new constructor to `Media`
Users could construct multiple `Media`s with different RIDs. Then would call `Send` as usual.

```
rtc::Description::Video highQuality("video", rtc::Description::Direction::SendOnly, "h");
rtc::Description::Video mediumQuality("video", rtc::Description::Direction::SendOnly, "m");
rtc::Description::Video lowQuality("video", rtc::Description::Direction::SendOnly, "l");

auto highQualityTrack = pc->addTrack(highQuality);
highQualityTrack->send(buffer, len);
```

### Express multiple RIDs on one Track or Media
```
rtc::Description::Video video("video", rtc::Description::Direction::SendOnly);

auto highRid = video->addRid("h");
auto mediumRid = video->addRid("m");
auto lowRid = video->addRid("l");

auto videoTrack = pc->addTrack(video);
videoTrack->send(buffer, len, highRid);
```

**Comment by paullouisageneau** [comment]
It looks good! Feel free to open a PR with the changes to `rtc::Description::Video`, I'd be happy to review it.

You might want to add a new function to the C API, for instance `rtcAddTrackRid(int tr, const char *rid)`, since WHIP in OBS relies on the C API.

**Comment by Sean-Der** [comment]
@paullouisageneau 

Unfortunately the new API doesn't work for non-packetized media :/ 

If I only have access to one track handle how do I set MID/RID on it? If I packetize myself I am able to send media though.

Would you suggest that I do packetization myself and not use libdatachannel's here?

**Comment by paullouisageneau** [comment]
Ah yes, the packetizer is independent and you must fill the `RtpPacketizationConfig` and update it. I think you'd need to add something similar to video orientation for both rid and mid, and update the rid before sending: 
https://github.com/paullouisageneau/libdatachannel/blob/1ead0ce3040fb2c08fba3919bb503e6ee78b025d/include/rtc/rtppacketizationconfig.hpp#L54

This current design is not great and comes from when the packetizer was contributed. I think it should be more integrated to the track object: it should read media settings from the description and per-frame metadata should come with the frame, possibly with a dedicated send method. It's something I'd need to work on.

**Comment by Sean-Der** [comment]
@paullouisageneau Unfortunately I don't believe that will work :/

You get one Packetizer per track track. I want to set a different RID/MID depending on what frame of H264 I am pushing. I see some ways forward. Which do you prefer?

* Go back to old design of unique Tracks (but belong to same MID)
* Allow multiple Packetizers per Track
* Add new APIs that allow caller to specify RID/MID per Send
* ?

**Comment by paullouisageneau** [comment]
Currently a different timestamp must be set for each frame in the packetization config. In OBS you call the C API so it's done for you by `rtcSetTrackRtpTimestamp()`:
https://github.com/paullouisageneau/libdatachannel/blob/1ead0ce3040fb2c08fba3919bb503e6ee78b025d/src/capi.cpp#L1263

So you could indeed create a new send function in the C API for tracks only which accepts frame info like RID and set it in the packetization config before sending (you can also add the timestamp in there). It could be called `rtcSendFrame` for instance.

**Comment by Sean-Der** [comment]
Oh that sounds great! So to match current API could I have

* `setTrackRIDHeader`

**Comment by paullouisageneau** [comment]
You mean adding `rtcSetTrackRtpRidHeader()` and `rtcSetTrackRtpMidHeader()` to the C API, on the model of `rtcSetTrackRtpTimestamp()`? That can work too, but I thought a new send function would be simpler.

**Comment by Sean-Der** [comment]
I am happy with anything! What C/C++ API would you prefer? Will implement tonight

**Comment by paullouisageneau** [comment]
My preference goes to `rtcSendFrame(int tr, const char *data, int size, const rtcFrameInfo *info)`, as I think it's more straightforward to use than multiple functions to set the state before sending. Thank you for your work on this!

**Comment by pkviet** [comment]
We plan to switch back to c++ api since we can now build win DLLs on msvc. The cross compiled ones forced us to switch to c api because of mangling issues, but we don't have to stay with the c api any more.

**Comment by paullouisageneau** [comment]
@pkviet OK sure, keep me updated.
