### ISSUE TITLE
Support AV1

### ISSUE THREAD

**Issue by hassan379** [paullouisageneau/libdatachannel#905]
thank you for this nice library 
is there any plan to support AV1 codec ?
thx in advance

**Comment by paullouisageneau** [comment]
I haven't looked into it for now but that would be nice.

**Comment by DatCaptainHorse** [comment]
I support this, [I tried my hand at adding support sometime ago](https://github.com/DatCaptainHorse/libdatachannel/tree/av1), but it's very much not working 😓 (furthest I got was getting Chrome to recognize incoming AV1 RTP stream)

**Comment by hassan379** [comment]
> I support this, [I tried my hand at adding support sometime ago](https://github.com/DatCaptainHorse/libdatachannel/tree/av1), but it's very much not working 😓 (furthest I got was getting Chrome to recognize incoming AV1 RTP stream)

Hi
I tried ur code but Chrom didtn't recognize any incoming AV1 RTP stream
![image](https://github.com/paullouisageneau/libdatachannel/assets/12671422/e5af4cf9-1211-40a4-97ce-b43b281cd379)
can u please tell me how you tested it ?
best regards

**Comment by DatCaptainHorse** [comment]
> Hi I tried ur code but Chrome didtn't recognize the received packets as AV1 RTP packets

Ah, I had changed something in the code before committing which stopped Chrome from recognizing the stream as AV1, I'll poke at it in a bit as I got nothing else to do, see if I can get it back to how it was.

I just build the libdatachannel library and put it straight into modified OBS-Studio to use, not the best way to test probably.

**Comment by DatCaptainHorse** [comment]
@hassan379 

[Here's the new commit](https://github.com/DatCaptainHorse/libdatachannel/commit/a4a85e8e0a90ff64f29d5290b0c0ed116c7c6d6b), I removed bunch of stuff that didn't seem to matter for now and Chrome recognizes the stream now, doesn't display anything but I guess it's step forward?

**Comment by DatCaptainHorse** [comment]
Can be closed as PR #936 was merged, thank you Sean and Paul-Louis 🙏
