### ISSUE TITLE
Add new Track for established connection

### ISSUE THREAD

**Issue by hassan379** [paullouisageneau/libdatachannel#933]
Hi
I wonder if libdatachannel can add a new track for established connection
I tried to add new track, recall setLocalDescription and send the new created SDP offer to edge browser 
but onStateChange was fired 2 times with state closed and disconnected
are my steps correct ? or should i reestablish a new connection?
Best regards

**Comment by paullouisageneau** [comment]
The process is correct but you also need to forward the answer like you would for the initial negotiation. I'd need more information like exchanged descriptions and logs to know what happens exactly.

Note libdatachannel only has partial renegotiation support so it's better to offer always on the same side to guarantee it works.

**Comment by hassan379** [comment]
@paullouisageneau Thank you for ur answer
sorry it was my mistake I was re establiching a new Connection on the client side when the new created sdp offer is received by the browser
it works now
thank you again for ur help
