### ISSUE TITLE
Problems with Windows

### ISSUE THREAD

**Issue by Laky-64** [paullouisageneau/libdatachannel#934]
When i try to compile and then just open my executable happens this on windows:

Process finished with exit code -1073741515 (0xC0000135)

My code:
```cpp
#include "rtc/rtc.hpp"

int main() {
    auto pc = make_shared<PeerConnection>();
    return 0;
}
```

**Comment by paullouisageneau** [comment]
The error means a DLL is missing, check libdatachannel.dll is present in the same folder as the executable.
