### ISSUE TITLE
No way to synchronize answer media mid with incoming remote media mid

### ISSUE THREAD

**Issue by zucher** [paullouisageneau/libdatachannel#937]
Seems retrieving the mid for a media type is not possible to use media in addTrack with an equivalent mid as the one received without parsing manually again the incoming SDP.

https://github.com/paullouisageneau/libdatachannel/blob/cde1fbc675beea0769266b5ab2a67f0b83520c54/src/impl/peerconnection.cpp#L856

Force to response with the same one.

**Comment by paullouisageneau** [comment]
You should receive the incoming track with the `onTrack` callback. You can then get the mid and update the description from the callback.

**Comment by zucher** [comment]
on but during sdp negociation I have also to initiate some media too, and mid is not known in that case.

**Comment by paullouisageneau** [comment]
What do you mean? You can't add new media in an answer.

**Comment by zucher** [comment]
On offer reception from remote party we need to prepare the answer, for this it's required to define local track on peer connection before setting the localdescription

The several addtrack needs mid in line with the index/name used by remote party

**Comment by paullouisageneau** [comment]
You need to update tracks in the `onTrack` callback, any change you make to the track description in the callback will be applied to the local description. You can use either `setDescription()` or `addTrack()` to update the description.

**Comment by zucher** [comment]
Thank you I have to try your proposition.

**Comment by zucher** [comment]
It's fine working, thank you for your help
