### ISSUE TITLE
Is PCM16L supported in this library?

### ISSUE THREAD

**Issue by Laky-64** [paullouisageneau/libdatachannel#939]
Now I really don't know what I'm doing wrong. Still, there's no audio on telegram, I followed the streamer's example, convinced it was the exact implementation of [wrtc](https://github.com/node-webrtc/node-webrtc) but it doesn't seem to work, and if you're wondering I'm migrating from NodeJS to C++ due to the need to create a library.

It may be the wrong codec. Since nodejs side, I use pcm16le while here apparently it's the opus codec

# Code

### New Code
https://github.com/pytgcalls/ntgcalls/tree/master/src

### NodeJS Code (Old Code)
https://github.com/pytgcalls/pytgcalls/tree/d76b6488d8c9752b1e715bd9c6cbff8a6f1e08fc/src

# Stream Sending

### The sending part NodeJS
https://github.com/pytgcalls/pytgcalls/blob/master/src/stream.ts#L322-L329

### The sending part C++
https://github.com/pytgcalls/ntgcalls/blob/master/src/webrtc/MediaStreamTrack.cpp#L85-L102

_If you need any more details, I'm here, just ask me_

**Comment by Laky-64** [comment]
Migrating to https://github.com/paullouisageneau/libdatachannel/issues/941

**Comment by paullouisageneau** [comment]
It would be weird that Telegram doesn't support Opus and requires PCM, as [Opus support is mandatory for WebRTC endpoints](https://www.rfc-editor.org/rfc/rfc7874.html#section-3) while streaming uncompressed audio is very uncommon nowadays.

I see that you parse and regenerate SDP descriptions with a lot of hardcoded values, are you sure everything is right? In particular payload type doesn't seem to be sent to the remote peer, how is it supposed to work?

**Comment by Laky-64** [comment]
Hi @paullouisageneau, thanks for the support you are providing me, I hope to be able to successfully migrate to your library, however it is also the version in Node.js hardcodavo everything, since telegram does not give the Sdp, but only some important values.

As for the codec, I saw around in the client also telegram itself that sends the audio in PCM16L, but they have a web version of telegram (with group call), but I don't know how the audio is sent, however I'm afraid to hardcode only in your library, being that I don't know if it needs to be set in certain ways, since the current hardcore is made for the lib in node, I'm waiting for its news

**Comment by paullouisageneau** [comment]
> As for the codec, I saw around in the client also telegram itself that sends the audio in PCM16L, but they have a web version of telegram (with group call), but I don't know how the audio is sent

Audio is never sent as PCM, the codec is always Opus. The difference is that libwebrtc handles encoding internally so the input is PCM, while libdatachannel requires the input to already by encoded by the user. In both cases audio is sent encoded as Opus.
