### ISSUE TITLE
Datachannel speed is too slow in ubuntu. But windows is good. why?

### ISSUE THREAD

**Issue by JoonikChoi** [paullouisageneau/libdatachannel#940]
Hi, I'm using the library you created well and appreciate it so much.

I have a question because there was an issue recently.

In my c++ program Using this library, I byteize the 8-bit cv matrix getting from the webcam and deliver it to other peers over the data channel. Mat bytelength is about 200,000 and is sent every 20 ms. (Actually, I send it by dividing it by 50,000 segments within 20ms.)

When I build and run the above program using msvc in windows, it works really great. There is no problem with the sender and the receiver. It actually sends every 20ms and receives data well without delay.

But, when I build and run the program using g++ on linux (ubuntu), it occured issue.

The sender is doing well (at least, on the console, sending well)
The recipient receives data every 10 to 20 'seconds', as if it had virtually stopped.

I was wondering if the Linux device specification was a problem, so I tried Linux devices with graphics cards, but it's the same. I tested the internet speed, but it doesn't seem to be a problem.

In the end, my conclusion seems to be an issue depending on the difference in OS environment.
Does this library differ depending on the OS environment? Or could the usage be a little different?

(Note: The sending and receiving devices are different devices. However, if a Linux device sends and receives from that device, the issue does not occur. Occurs when the sending-side&receiving-side devices are different. Of course, if the Windows device is the sender, the issue does not occur in any case.)

Please help me :(

**Comment by paullouisageneau** [comment]
There should be no fundamental difference from one OS to the other.

> (Note: The sending and receiving devices are different devices. However, if a Linux device sends and receives from that device, the issue does not occur. Occurs when the sending-side&receiving-side devices are different. Of course, if the Windows device is the sender, the issue does not occur in any case.)

Could you please clarify, do you mean that the issue happens only when sending from a device to another across a network, and not from a device to itself?

What is the network between the devices?
This is quite demanding as 200KB every 20ms would require a capacity over 100Mbps, most residential connections don't have such an upload capacity. Even a non-optimal WiFi network might struggle with this.

Have you checked `DataChannel::bufferedAmount()`? If it is non-zero, it means you are sending too fast and data is queued as a result.

**Comment by JoonikChoi** [comment]
Thank you very much for your quick reply. I will check tomorrow about 'DataChannel::bufferedAmount()' you mentioned and reply to you. (I'm on vacation until today.)

Here is table about this issue
I have 4 devices that windows A, windows B, linux A, linux B .

**Sender(c++ program)               Receiver(web browser)                Result                     Network**
        windows A                                 windows A                              good         same area LAN(same WiFi)
        windows A                                 windows B                              good                          ''
        windows A                                   linux A                                   good                          ''
        linux A                                          linux A                                   good                          ''
        linux A                                linux B, windows A,B                        bad                          ''
        linux B                                          linux B                                   good                          ''
        linux B                                linux A, windows A,B                        bad                          ''

The program you receive first is a web page (browser). There is no problem when the device runs the program, sends it, accesses the web page, and receives it. However, if another device tries to access the web page and receive it, an issue arises (even though it is the same Wi-Fi)

The network has the same LAN(Wi-Fi) environment for all devices, and when tested for speed with that WiFi, the download speed is 200 Mbps and the upload speed is 120-150 Mbps.

I've been thinking a lot about this issue all day.

First of all, even if it's not every 20 ms, if you send data every 1 second or every 5 seconds, the same issue occurs. Therefore, my conclusion is that the network situation is not the cause.

I don't think this wonderful library is the cause of the issue at all. 
I think the reason is that the default buffer value of UDP packet is low in the kernel parameter value of Ubuntu. Therefore, I will modify the kernel parameter(UDP) values.

I'm currently on vacation, so I can't test it right away, but I think I'll be able to go to work in 12 hours. I'll try it first.

Thank you again for your reply and wish me luck.

**Comment by paullouisageneau** [comment]
> I think the reason is that the default buffer value of UDP packet is low in the kernel parameter value of Ubuntu. Therefore, I will modify the kernel parameter(UDP) values.

I think the maximum UDP buffer size could indeed be too small to sustain outgoing traffic bursts at that sending rate. You could try increasing the maximum socket write buffer size:
```
$ sudo sysctl -w net.core.wmem_max=1048576
```

**Comment by paullouisageneau** [comment]
> I think the reason is that the default buffer value of UDP packet is low in the kernel parameter value of Ubuntu. Therefore, I will modify the kernel parameter(UDP) values.

The maximum UDP buffer size could indeed be too small to sustain outgoing traffic bursts at that sending rate. You could try increasing the maximum socket write buffer size:
```
$ sudo sysctl -w net.core.wmem_max=1048576
```

**Comment by JoonikChoi** [comment]
I modified the udp buffer value. But it didn't work. my kernel value is as follows.
![image](https://github.com/paullouisageneau/libdatachannel/assets/99402563/d210d0e1-3da0-4c2e-b621-eda0a0536e43)


As you said, I checked the bufferedAmount value after datachannel.send(). It is as follows.
![image](https://github.com/paullouisageneau/libdatachannel/assets/99402563/639990af-b821-4e4d-8904-f5e3970d6b7c)

(I'm sorry that the font size is small.)

Even if the interval time is set sufficiently (10 seconds), the bufferedAmount value always increases eventually.
**When I run this program in Windows, the bufferedAmount value is always zeroed.**

In this situation, I don't know what factors affect the bufferedAmount value.
Do you have any idea what the issue is?

**Comment by paullouisageneau** [comment]
> Even if the interval time is set sufficiently (10 seconds), the bufferedAmount value always increases eventually.

The sending period by itself does not really matter, but the rate does. How much data do you send every 10 seconds? Have you tried sending less data on each period?

> However, when I connect it by wire LAN, it feels a little better. The bufferedAmount value is zero and occasionally increases. However, after a little time (3-4 seconds), the value returns to 0. (Improved, but still frustrating compared to the windows case)

When you say wired, do you mean it's wired all the way to the other machine, or is the other machine still on WiFi? This is expected behavior if you send at a continuous rate but such a rate can't be achieved at some point due to some temporary disruption.

> I thought it was due to the network's throughput, so I tested udp with iperf3.
> ![image](https://user-images.githubusercontent.com/99402563/258782431-1c126263-515b-4a70-8f8d-b2d5e7f0aec0.png)
> From the above results, the network does not look slow.

With 127.0.0.1, you are testing the host to itself, meaning packets never go through the network. You are basically measuring the speed at which the OS can copy data between processes, that's why you get extremely high throughputs. You should test from Linux A to Linux B, for instance.

> In this situation, I don't know what factors affect the bufferedAmount value.

The buffered amount only reflects the amount of data that couldn't be sent for now.

Also, the bottleneck could be encryption on the Linux device at such a rate. The Nvidia Jetson Orin Nano board has an ARM CPU which is probably slower than the Windows machine for single-core processing. What is the CPU usage on the sender machine when you send? Did you compile libdatachannel in release mode?

**Comment by JoonikChoi** [comment]
> The sending period by itself does not really matter, but the rate does. How much data do you send every 10 seconds? Have you tried sending less data on each period?
Sent 0.2mb every 10 seconds.

I will attach the answer to this below. The following is about my current issue.
![image](https://github.com/paullouisageneau/libdatachannel/assets/99402563/b17d0d28-b9bd-4f1f-97e3-2d7306e484ea)


> With 127.0.0.1, you are testing the host to itself, meaning packets never go through the network. You are basically measuring the speed at which the OS can copy data between processes, that's why you get extremely high throughputs. I should test from Linux A to Linux B, for instance.
As you advised, I tested iperf3 on two devices. The result is too long, so I'll show it to you as a my notion link.
https://beaded-jumbo-a58.notion.site/iperf3-Test-Result-2768c8679d844af58c47b5111ec85785?pvs=4
Ubuntu devices often experience zero transfer values. But I don't know if this will help solve the problem. I'm confused about what analysis to do.

> Also, the bottleneck could be encryption on the Linux device at such a rate. The Nvidia Jetson Orin Nano board has an ARM CPU which is probably slower than the Windows machine for single-core processing. What is the CPU usage on the sender machine when you send? Did you compile libdatachannel in release mode?
As you said, it can be seen as a issue due to the performance of ARM cpu, so I tested it with a good enough hardware desktop. I did the build this library according to your guidance. 
```
$ cmake -B build -DUSE_GNUTLS=0 -DUSE_NICE=0 -DCMAKE_BUILD_TYPE=Release
$ cd build
$ make -j2
```

I was completely confused. I don't know why the issue occurs when the OS is different with the same device.
I found a stackoverflow post saying that the program performance may be different because gnu and msvc have different memory management.
https://stackoverflow.com/questions/70693970/why-do-i-get-different-results-from-c-code-running-in-gcc-and-visual-studio-runn

But I'm not a c/c++ expert, so I don't know what to do.
It seems to be dependent on the operating system and compiler, not the issue of the library... It's already outside your scope of responsibility, but please help if possible.

https://github.com/JoonikChoi/zedApp
This is github from my project. A brief description is provided in the readme.
(It's hard for anyone other than me to run because I use sdk from stereo camera companies.)


(Note : I currently sent a string of one line every 20ms. The dump string I sent is as follows.
**"quternion row:3.2421, pitch:2.1412, yaw: -1.2324, t: 5.432"**
This string is sent every 20 ms, but sometimes the receiver does not receive data for 1-2 seconds.  After 1-2 seconds, Receive it normally again. In this case, the bufferedAmount value did not appear to increase. (always 0))

**Comment by paullouisageneau** [comment]
> As you advised, I tested iperf3 on two devices. The result is too long, so I'll show it to you as a my notion link.
> https://beaded-jumbo-a58.notion.site/iperf3-Test-Result-2768c8679d844af58c47b5111ec85785?pvs=4
> Ubuntu devices often experience zero transfer values. But I don't know if this will help solve the problem. I'm confused about what analysis to do.

Both UDP tests shows a very bad network, so I'm not sure the command is correct. Anyway, the main issue here is indeed that the Linux device is unable to send during a few seconds at regular intervals, which can only be caused by the WiFi link, possibly a driver issue. This is quite bad, I think there is no need to investigate performance tuning before this is solved.

> (Note : I currently sent a string of one line every 20ms. The dump string I sent is as follows.
"quternion row:3.2421, pitch:2.1412, yaw: -1.2324, t: 5.432"
This string is sent every 20 ms, but sometimes the receiver does not receive data for 1-2 seconds. After 1-2 seconds, Receive it normally again. In this case, the bufferedAmount value did not appear to increase (always 0) . Anyway, what I'm saying is that the size of the data is not the cause of the issue.)

A lot of short messages like this can fit in the underlying SCTP send buffer without filling it so you won't see the buffered amount increase until after some time. But if the network link stops transmitting for a while, the data will always arrive later at the receiver, there is no way around it.

As a side note, you should consider sending compressed messages, for instance by shortening the text labels, or by encoding the values as binary.

**Comment by FomoGoMan** [comment]
If you ever revisit the throughput issues on Linux, even after fixing the driver, our fork with BBRv3 congestion control in usrsctp showed significant improvement on Linux systems with WiFi. The default SCTP congestion control in usrsctp doesn't handle WiFi latency spikes and variable bandwidth well. BBRv3 adapts much better to these conditions: https://github.com/FomoGoMan/libdatachannel - usrsctp PR: github.com/sctplab/usrsctp/pull/748
