### ISSUE TITLE
Rtp Extension Header serialization is incorrect.

### ISSUE THREAD

**Issue by SetoKaiba** [paullouisageneau/libdatachannel#942]
https://github.com/Sean-Der/obs-studio/pull/2
I try to use Sean-Der's Simulcast PR of OBS. And I found that it can't be compatible with other SFUs with simulcast support.

After I have a deep dive in it, I found that the Rtp Extension Header serialization is incorrect.
![image](https://github.com/paullouisageneau/libdatachannel/assets/159540/b31ca30e-5f1c-4c36-9bcd-c0c771c9215c)
https://datatracker.ietf.org/doc/html/rfc5285#page-5
![image](https://github.com/paullouisageneau/libdatachannel/assets/159540/3f4fbbed-216f-4004-80f7-dbdb0d6d1c21)

https://github.com/paullouisageneau/libdatachannel/blob/059d06ed0277512ef88bd97abe4354369aab6b4a/src/rtp.cpp#L66-L69
https://github.com/paullouisageneau/libdatachannel/blob/059d06ed0277512ef88bd97abe4354369aab6b4a/src/rtp.cpp#L115
This is incorrect. 
![image](https://github.com/paullouisageneau/libdatachannel/assets/159540/a2d4f4d8-fb80-4d40-bc0f-671d868dc27f)
For example, if all the extension header is with only one byte data, the size of each extension header element is two bytes sized.
The size should be 8 bytes sized excluding the sizeof(RtpExtensionHeader). But your method is 3 * 4 = 12.

But the RtpExtensionHeader is cast by pointer for serialization. So I can't simply add a property to storage the size of extension header. I don't know how to fix it.

**Comment by SetoKaiba** [comment]
> Sorry, I don't get what the issue is here, could you please elaborate?
> 
> According to [RFC 5285](https://datatracker.ietf.org/doc/html/rfc5285#section-4.1):
> 
> ```
> A sequence of extension elements, possibly with padding, forms the
> header extension defined in the RTP specification. There are as many
> extension elements as fit into the length as indicated in the RTP
> header extension length. Since this length is signaled in full 32-
> bit words, padding bytes are used to pad to a 32-bit boundary.
> ```
> 
> So the length field of the header extension contains the length of the extension payload in 32-bit words, hence the length in bytes is the value multiplied by 4.

Hi. What I understand is that what is expressed here is that the elements of the extension header are stored in multiple 32-bit words. So its byte length is a multiple of 4. Take the following as an example, this extension header has 3 elements, each element data is 1 byte in length. Then each element occupies 2 bytes, and since it is stored in 32-bit words, it will eventually occupy 8 bytes. But according to your calculation method, the number of elements in the extension header is 3, then 3*4 gives a byte length of 12. But actually, its byte length is 8. The length of each extension header element is determined according to the last four bits of its first byte, and each element is variable in length. Therefore, the byte length cannot be obtained by the number of elements * 4.
![image](https://github.com/paullouisageneau/libdatachannel/assets/159540/75c42f83-9b16-47d2-9c9d-7a07e0361d22)

**Comment by paullouisageneau** [comment]
The length field should contain the length of the extension header in 32-bit words, not the number of elements. In this example, length should be 2, then `RtpExtensionHeader::getSize()` will indeed return 2*4=8, and `RtpHeader::getExtensionHeaderSize()` will return 8+4=12.

Have you observed this example with length=3 on the wire? If so, it looks like a bug.

**Comment by SetoKaiba** [comment]
> The length field should contain the length of the extension header in 32-bit words, not the number of elements. In this example, length should be 2, then `RtpExtensionHeader::getSize()` will indeed return 2*4=8, and `RtpHeader::getExtensionHeaderSize()` will return 8+4=12.
> 
> Have you observed this example with length=3 on the wire? If so, it looks like a bug.

```
The 4-bit length is the number minus one of data bytes of this header
   extension element following the one-byte header.  Therefore, the
   value zero in this field indicates that one byte of data follows, and
   a value of 15 (the maximum) indicates element data of 16 bytes.
   (This permits carriage of 16-byte values, which is a common length of
   labels and identifiers, while losing the possibility of zero-length
   values -- which would often be padded anyway.)
```
As you can see there, it indicates that the value can be as maximum as 15. Then the data is 16 bytes lengthed. The design of this is the header element size is variable length. 
What if I only contain one element. And the element data length is 16 bytes. According to your calculation, the size become 1 * 4 = 4. But the size should be 20.
![image](https://github.com/paullouisageneau/libdatachannel/assets/159540/5f613d1f-307b-40ca-a08d-3144cac6fb46)

**Comment by SetoKaiba** [comment]
> The length field should contain the length of the extension header in 32-bit words, not the number of elements. In this example, length should be 2, then `RtpExtensionHeader::getSize()` will indeed return 2*4=8, and `RtpHeader::getExtensionHeaderSize()` will return 8+4=12.
> 
> Have you observed this example with length=3 on the wire? If so, it looks like a bug.

OK. I see. It's the length of 32-bit words, not the count of the elements.
