### ISSUE TITLE
Problem in building on macOS

### ISSUE THREAD

**Issue by DrakF12** [paullouisageneau/libdatachannel#945]
Hi:
When I did “make -j2” to build libdatachannel, I got 

> [  3%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/addr.c.o
[  3%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_asconf.c.o
[  3%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/agent.c.o
[  3%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_auth.c.o
/Users/jinghai/Desktop/NEW-OBS/libdatechannel/libdatachannel/deps/libjuice/src/agent.c:118:26: warning: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Wdeprecated-pragma]
        agent->selected_entry = ATOMIC_VAR_INIT(NULL);
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include/stdatomic.h:51:41: note: macro marked 'deprecated' here
#pragma clang deprecated(ATOMIC_VAR_INIT)
                                        ^
1 warning generated.
[  3%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o
[  3%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/crc32.c.o
[  5%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/const_time.c.o
[  6%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_callout.c.o
[  6%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/conn.c.o
[  6%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_cc_functions.c.o
[  6%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/conn_poll.c.o
[  8%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/conn_thread.c.o
[  8%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_crc32.c.o
[  8%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/conn_mux.c.o
[ 10%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_indata.c.o
[ 10%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/base64.c.o
/Users/jinghai/Desktop/NEW-OBS/libdatechannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_indata.c:3323:6: error: variable 'tot_retrans' set but not used [-Werror,-Wunused-but-set-variable]
        int tot_retrans = 0;
            ^
1 error generated.
make[2]: *** [deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_indata.c.o] Error 1
make[1]: *** [deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/hash.c.o
[ 12%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/hmac.c.o
[ 12%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/ice.c.o
[ 13%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/juice.c.o
[ 13%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/log.c.o
[ 13%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/random.c.o
/Users/jinghai/Desktop/NEW-OBS/libdatechannel/libdatachannel/deps/libjuice/src/log.c:36:46: warning: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Wdeprecated-pragma]
static atomic(juice_log_level_t) log_level = ATOMIC_VAR_INIT(JUICE_LOG_LEVEL_WARN);
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include/stdatomic.h:51:41: note: macro marked 'deprecated' here
#pragma clang deprecated(ATOMIC_VAR_INIT)
                                        ^
1 warning generated.
[ 15%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/server.c.o
[ 15%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/stun.c.o
[ 15%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/turn.c.o
[ 17%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/timestamp.c.o
[ 17%] Building C object deps/libjuice/CMakeFiles/juice-static.dir/src/udp.c.o
[ 18%] Linking C static library libjuice-static.a
[ 18%] Built target juice-static
make: *** [all] Error 2

How to fix it?

**Comment by paullouisageneau** [comment]
This is the same issue as https://github.com/murat-dogan/node-datachannel/issues/174#issuecomment-1672357619

You need to either add the CXX flag `-Wno-unused-but-set-variable` or simply update the usrsctp submodule.

**Comment by paullouisageneau** [comment]
I updated usrsctp in https://github.com/paullouisageneau/libdatachannel/pull/946, so the issue should be fixed on master branch after updating the submodules.
