### ISSUE TITLE
Some questions about the time it takes to execute rtcSendMessage

### ISSUE THREAD

**Issue by hqs1** [paullouisageneau/libdatachannel#951]
Hi, when I use  `rtcSendMessage` in C API to send audio and video, I find that if I execute `rtcSendMessage`after traversing the user's audio and video Track ID, the audio and video delay will become more and more serious with the increasing number of users. Debugging code finds that `rtcSendMessage`seems to be a time-consuming operation. So the question is, does  `rtcSendMessage`push the data into the buffer or send it directly to the network?

Thanks.

**Comment by paullouisageneau** [comment]
There is no buffer for tracks so `rtcSendMessage` synchronously encrypts and immediately sends the data. Sending itself is non-blocking, but encryption can take a signifiant time at high bitrate depending on the CPU.

**Comment by hqs1** [comment]
Thank you for your answer, the current test does tell you that high bit rate will lead to increased encryption time.
