### ISSUE TITLE
SCTP Invalid notification length

### ISSUE THREAD

**Issue by X-Kent** [paullouisageneau/libdatachannel#96]
Hello.

I am getting a weird behavior when sending data bidirectionally on a connection.
I use libjuice and openssl compiling with clang on 64 bit linux.
Let's assume I create and connect 2 rtcdatachannels c1 and c2 to each other.

If c1 is only sending messages to c2 - everything works fine and c2 receives the sent messages from c1 as expected.

If c1 **and** c2 send messages to each other, it works for (randomly) about 20-30 messages and then when for ex. c1 sends 50k bytes message, c2 will receive a message with less than 50k bytes.
I as well see the following when logger is set to debug:
WARN  [5730] [rtc::SctpTransport::processNotification@576] Invalid notification length
each time it happens.
The connection can continue and I will again receive a number of messages that are OK but then (randomly after 10-15 messages) it will happen again. The message gets truncated or something. Although I checked the first bytes of the truncated message and they do not correspond to the first bytes of the sent message.

I tried using only single datachannel and using it to both send/recv AND tried opening two datachannels (single RTC connection with two data channels) so one is used to send and one is used to receive. Still the problem remains.

I can provide logs but when I set log level to DEBUG this is the only useful line if I set it to VERBOSE I get about 20-30mb log file before the problem happens.

Can someone point me where should I dig ? I tried updating usrsctp & libjuice to latest versions from master and it doesn't seem to help. Did anyone had this kind of a problem ?

Update:
It seems the truncation only happens for big messages.
Message size 100k -> truncated message that I receive is 33644 bytes
Message size 70k -> truncated message that I receive is 3644 bytes
Message size 60k -> no truncation, everything works fine (at least for about 10 minutes sending/receiving full speed)
So the problem is somewhere at 66356 which is very close to 2^16... Is there any unsigned short that can overflow ?

**Comment by paullouisageneau** [comment]
Thanks for reporting the issue. Given the symptoms you describe, it seems to me the behavior you observe here is that when the message is long enough the first roughly 2^16 bytes of the message might be marked as a SCTP notification, therefore triggering the length sanity check discarding it, in which case you receive only what's left.

It's probably an issue with how usrsctp API is handled (it's a bit tricky to use correctly). The option `SCTP_FRAGMENT_INTERLEAVE` is set to 0 which should prevent messages being interleaved with event notifications (as stated in (RFC6458)[https://tools.ietf.org/html/rfc6458#page-75]), but that behavior might change for messages bigger than 2^16.

The involved code is here: https://github.com/paullouisageneau/libdatachannel/blob/3d7764c1e966a74287a44525d90efd67cb700cf9/src/sctptransport.cpp#L460

**Comment by paullouisageneau** [comment]
Could you please check if separated SCTP notifications and messages on branch [usrsctp-fix-notifications](https://github.com/paullouisageneau/libdatachannel/tree/usrsctp-fix-notifications) prevents the issue?

**Comment by X-Kent** [comment]
Hello.
It seems the problem is fixed in the branch you linked.
I was unable to reproduce the issue after about 10k of 200kbytes messages.

**Comment by paullouisageneau** [comment]
Excellent, I'll merge the fix.
