### ISSUE TITLE
in iOS no frames are decoded

### ISSUE THREAD

**Issue by nola-a** [paullouisageneau/libdatachannel#979]
Hello,

My streamer (based on streamer example) uses libdatachannel 0.19.1.
It works on Linux, Windows, Macos, Android with Google Chrome, Safari, Brave but does not work in iOS
The logging below shows that even if the frames are coming no one is decoded. 
I know libdatachannel is a network library, but I wonder if anyone has the same problem.

 Thank you A.

```
LibWebRTCMediaEndpoint::OnStatsDelivered(24DB77BE8001485C) 
Object
bytesReceived: 1943805
codecId: "RTCCodec_RTCTransport_video-stream_1_Recv_102_level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"
decoderImplementation: "RemoteVideoToolBox"
firCount: 0
framesAssembledFromMultiplePackets: 0
framesDecoded: 0
framesDropped: 46
framesReceived: 1000
headerBytesReceived: 38568
id: "RTCInboundRTPVideoStream_1"
jitter: 0.009
jitterBufferDelay: 0
jitterBufferEmittedCount: 0
keyFramesDecoded: 19
kind: "video"
lastPacketReceivedTimestamp: 1694700682718
mediaType: "video"
mid: "video-stream"
minPlayoutDelay: 0
nackCount: 0
packetsLost: 0
packetsReceived: 3214
pliCount: 213
ssrc: 1
timestamp: 1694700682727077
totalAssemblyTime: 0
totalDecodeTime: 0
totalInterFrameDelay: 0
totalProcessingDelay: 0
totalSquaredInterFrameDelay: 0
trackId: "DEPRECATED_RTCMediaStreamTrack_receiver_4"
trackIdentifier: "video-stream"
transportId: "RTCTransport_video-stream_1"
type: "inbound-rtp"
```

**Comment by hassan379** [comment]
It works for me using safari on IPhone XS and IPad (IOS 14.5.1).
I send VP8 and H264 encoded frames by software and hardware encoders

**Comment by nola-a** [comment]
in iOS 16.6 it doesn't work. I am using h264 frames coming from /dev/video0 (v4l2)

**Comment by nola-a** [comment]
I am going to close this issue; it was a bug in my code where corrupted frames were delivered.

The takeaways are that some browsers comply more with specs than others.

Thanks,
A.
