### ISSUE TITLE
De-packetization API

### ISSUE THREAD

**Issue by Sean-Der** [paullouisageneau/libdatachannel#986]
I am trying to add a WHEP Source to OBS. To do that I need full H264 buffers (not just fragments)

Would you be open to something that would cache/de-jitter RTP packets and then emit full media frames? 

What would be the idiomatic/preferred API?

**Comment by paullouisageneau** [comment]
This would be great! I think it should be a media handler implementing a jitter buffer.

FYI I'm still working on refactoring the media handler API, which would allow to chain multiple ones more easily (for instance a generic jitter buffer and an h264 depacketizer).

Related to https://github.com/paullouisageneau/libdatachannel/issues/676

**Comment by Sean-Der** [comment]
Closing as dupe of #676
