### ISSUE TITLE
The LICENSE files in the "client/client" and "client/benchmark" directories appear to be GPL v2

### ISSUE THREAD

**Issue by chobie** [paullouisageneau/libdatachannel#998]
Hi. I am currently playing around with creating bindings for libdatachannel. 

I noticed while looking at the example files that the LICENSE files in the "client/client" and "client/benchmark" directories seem to be GPL v2. However, in the source code, it's mentioned as MPL v2.

Is this as expected?
https://github.com/paullouisageneau/libdatachannel/blob/master/examples/client-benchmark/LICENSE
https://github.com/paullouisageneau/libdatachannel/blob/master/examples/client-benchmark/main.cpp

https://github.com/paullouisageneau/libdatachannel/blob/master/examples/client/LICENSE
https://github.com/paullouisageneau/libdatachannel/blob/master/examples/client/main.cpp

Furthermore, in other examples where there is a LICENSE file, it seems to have been changed to MPL.

Thanks

**Comment by paullouisageneau** [comment]
This is an oversight, the GPL license files are leftovers from before the transition to MPL2.
